Repository servo/servo, pull requests merged in 2018-04, with the labels that each got.

#20495 Move `text-emphasis-position` outside of mako
  components/style/properties/longhand/inherited_text.mako.rs
  components/style/values/computed/mod.rs
  components/style/values/computed/text.rs
  components/style/values/specified/mod.rs
  components/style/values/specified/text.rs
Labels: S-awaiting-merge

#20499 style: Implement percentages for 'column-gap'.
  components/layout/multicol.rs
  components/style/properties/gecko.mako.rs
  components/style/properties/longhand/column.mako.rs
  components/style/values/computed/length.rs
  components/style/values/specified/length.rs
Labels: S-awaiting-merge

#20391 Measure cache memory usage
  Cargo.lock
  components/malloc_size_of/Cargo.toml
  components/malloc_size_of/lib.rs
  components/net/Cargo.toml
  components/net/http_cache.rs
  components/net/lib.rs
  components/net/resource_thread.rs
  components/net/tests/resource_thread.rs
  components/net_traits/Cargo.toml
  components/net_traits/lib.rs
  components/net_traits/response.rs
  components/profile_traits/mem.rs
  components/servo/lib.rs
Labels: S-awaiting-merge

#20504 Hide non-Servo heap measurement.
  components/malloc_size_of/Cargo.toml
  components/malloc_size_of/lib.rs
Labels: S-awaiting-merge

#20481 style: Derive a debug impl instead of implementing by hand.
  components/style/values/generics/image.rs
Labels: S-awaiting-merge

#20501 style: Use a more consistent style for parsing functions.
  components/style/properties/longhand/svg.mako.rs
  components/style/properties/shorthand/background.mako.rs
  components/style/properties/shorthand/border.mako.rs
  components/style/properties/shorthand/box.mako.rs
  components/style/properties/shorthand/column.mako.rs
  components/style/properties/shorthand/font.mako.rs
  components/style/properties/shorthand/inherited_svg.mako.rs
  components/style/properties/shorthand/inherited_text.mako.rs
  components/style/properties/shorthand/list.mako.rs
  components/style/properties/shorthand/mask.mako.rs
  components/style/properties/shorthand/outline.mako.rs
  components/style/properties/shorthand/position.mako.rs
  components/style/properties/shorthand/text.mako.rs
  components/style/values/specified/length.rs
Labels: S-awaiting-merge

#20508 Convert StylePrefs to StaticPrefs.
  components/style/font_face.rs
  components/style/gecko/data.rs
  components/style/gecko/generated/structs.rs
  components/style/gecko/media_queries.rs
  components/style/gecko/selector_parser.rs
  components/style/stylesheets/document_rule.rs
  components/style/values/specified/grid.rs
  components/style/values/specified/svg.rs
  components/style/values/specified/transform.rs
Labels: S-awaiting-merge

#20517 Fix the env_logger update
  components/servo/lib.rs
Labels: S-awaiting-merge

#20488 Add build-geckolib checkbox to pull request template
  PULL_REQUEST_TEMPLATE.md
Labels: S-awaiting-merge

#20482 Implement a URL-generic type for ListStyleImage
  components/layout/construct.rs
  components/style/gecko/conversions.rs
  components/style/properties/gecko.mako.rs
  components/style/properties/helpers/animated_properties.mako.rs
  components/style/properties/longhand/box.mako.rs
  components/style/properties/longhand/inherited_svg.mako.rs
  components/style/properties/longhand/list.mako.rs
  components/style/properties/shorthand/inherited_svg.mako.rs
  components/style/properties/shorthand/list.mako.rs
  components/style/values/animated/mod.rs
  components/style/values/computed/basic_shape.rs
  components/style/values/computed/image.rs
  components/style/values/computed/length.rs
  components/style/values/computed/list.rs
  components/style/values/computed/mod.rs
  components/style/values/computed/svg.rs
  components/style/values/computed/url.rs
  components/style/values/generics/mod.rs
  components/style/values/generics/url.rs
  components/style/values/specified/list.rs
  components/style/values/specified/mod.rs
  components/style/values/specified/svg.rs
  components/style/values/specified/url.rs
  tests/unit/style/properties/serialization.rs
  tests/wpt/mozilla/meta/css/get-computed-style-for-url.html.ini
  tests/wpt/mozilla/tests/css/get-computed-style-for-url.html
Labels: S-awaiting-merge

#20519 Use Servo data to back @font-face rule in Gecko
  components/style/font_face.rs
  components/style/gecko/arc_types.rs
  components/style/gecko/generated/bindings.rs
  components/style/gecko/generated/structs.rs
  components/style/gecko/rules.rs
  components/style/gecko_bindings/sugar/refptr.rs
  components/style/stylesheets/font_face_rule.rs
  components/style/stylesheets/mod.rs
  components/style/stylist.rs
  ports/geckolib/glue.rs
Labels: S-awaiting-merge

#20507 New Session History
  Cargo.lock
  components/constellation/Cargo.toml
  components/constellation/browsingcontext.rs
  components/constellation/constellation.rs
  components/constellation/lib.rs
  components/constellation/pipeline.rs
  components/constellation/session_history.rs
  tests/wpt/mozilla/meta/MANIFEST.json
  tests/wpt/mozilla/tests/mozilla/servo-max-session-history.html
Labels: S-awaiting-merge

#20582 Have CSSOM append rather than replace slot in declaration block
  components/style/properties/declaration_block.rs
Labels: S-awaiting-merge

#20583 selectors: Don't serialize :nth-child(-n) as -1n.
  components/selectors/parser.rs
  tests/wpt/metadata/css/selectors/anplusb-selector-parsing.html.ini
Labels: S-awaiting-merge

#20586 style: Respect the -moz- gradient pref again.
  components/style/values/specified/image.rs
Labels: S-awaiting-merge

#20575 Use correct filler y value when animating with an implied-y translate()s
  components/style/properties/helpers/animated_properties.mako.rs
Labels: S-awaiting-merge

#20597 style: Implement the non-functional :host selector.
  components/selectors/builder.rs
  components/selectors/context.rs
  components/selectors/matching.rs
  components/selectors/parser.rs
  components/style/data.rs
  components/style/dom.rs
  components/style/dom_apis.rs
  components/style/gecko/selector_parser.rs
  components/style/invalidation/element/state_and_attributes.rs
  components/style/servo/selector_parser.rs
  components/style/sharing/mod.rs
  components/style/stylist.rs
  ports/geckolib/glue.rs
Labels: S-awaiting-merge

#20606 style: Implement the functional :host(..) selector.
  components/selectors/builder.rs
  components/selectors/matching.rs
  components/selectors/parser.rs
  components/style/dom.rs
  components/style/invalidation/element/invalidation_map.rs
  components/style/invalidation/element/invalidator.rs
  components/style/selector_map.rs
  components/style/stylist.rs
Labels: S-awaiting-merge

#20610 style: Simplify border-image-repeat serialization.
  components/style/values/computed/border.rs
  components/style/values/specified/border.rs
Labels: S-awaiting-merge

#20613 Backed out changeset d186bcce1235 for failing on layout/style/test/test_shorthand_property_getters.html on a CLOSED TREE
  components/style/values/computed/border.rs
  components/style/values/specified/border.rs
Labels: S-awaiting-merge

#20614 Use the incumbent global as the source of x-origin postMessage
  components/script/dom/dissimilaroriginwindow.rs
Labels: A-content/script, S-awaiting-merge

#20616 style: Simplify border-image-repeat serialization.
  components/style/values/computed/border.rs
  components/style/values/specified/border.rs
Labels: S-awaiting-merge

#20619 Have nscssproperty a method of data instances
  components/style/properties/data.py
  components/style/properties/helpers.mako.rs
  components/style/properties/helpers/animated_properties.mako.rs
  components/style/properties/properties.mako.rs
Labels: S-awaiting-merge

#20626 added spec comments for progressive web metrics
  components/metrics/lib.rs
Labels: S-tests-failed

#20627 style: Let overflow parse two values.
  components/style/properties/shorthand/box.mako.rs
  tests/unit/style/properties/serialization.rs
  tests/wpt/metadata/css/cssom/index-002.html.ini
Labels: S-awaiting-merge

#20639 style: Sync changes from mozilla-central.
  ports/geckolib/glue.rs
Labels: S-awaiting-merge

#20641 Fork the jemallocator crate, fix for nightly-2018-04-15
  Cargo.lock
  components/allocator/Cargo.toml
  components/allocator/lib.rs
  rust-toolchain
Labels: S-awaiting-merge

#20638 Implement History State
  components/atoms/static_atoms.txt
  components/constellation/constellation.rs
  components/constellation/pipeline.rs
  components/constellation/session_history.rs
  components/msg/constellation_msg.rs
  components/net/http_loader.rs
  components/net/resource_thread.rs
  components/net_traits/lib.rs
  components/script/dom/bindings/trace.rs
  components/script/dom/history.rs
  components/script/dom/popstateevent.rs
  components/script/script_thread.rs
  components/script_traits/lib.rs
  components/script_traits/script_msg.rs
  tests/wpt/metadata/html/browsers/browsing-the-web/history-traversal/popstate_event.html.ini
  tests/wpt/metadata/html/browsers/browsing-the-web/navigating-across-documents/javascript-url-abort/javascript-url-abort-return-value-undefined.tentative.html.ini
  tests/wpt/metadata/html/browsers/history/the-history-interface/001.html.ini
  tests/wpt/metadata/html/browsers/history/the-history-interface/002.html.ini
  tests/wpt/metadata/html/browsers/history/the-history-interface/004.html.ini
  tests/wpt/metadata/html/browsers/history/the-history-interface/005.html.ini
  tests/wpt/metadata/html/browsers/history/the-history-interface/007.html.ini
  tests/wpt/metadata/html/browsers/history/the-history-interface/008.html.ini
  tests/wpt/metadata/html/browsers/history/the-history-interface/009.html.ini
  tests/wpt/metadata/html/browsers/history/the-history-interface/010.html.ini
  tests/wpt/metadata/html/browsers/history/the-history-interface/011.html.ini
  tests/wpt/metadata/html/browsers/history/the-history-interface/012.html.ini
  tests/wpt/metadata/html/browsers/history/the-history-interface/combination_history_002.html.ini
  tests/wpt/metadata/html/browsers/history/the-history-interface/combination_history_003.html.ini
  tests/wpt/metadata/html/browsers/history/the-history-interface/combination_history_004.html.ini
  tests/wpt/metadata/html/browsers/history/the-history-interface/combination_history_005.html.ini
  tests/wpt/metadata/html/browsers/history/the-history-interface/combination_history_006.html.ini
  tests/wpt/metadata/html/browsers/history/the-history-interface/combination_history_007.html.ini
  tests/wpt/metadata/html/browsers/history/the-history-interface/history_back.html.ini
  tests/wpt/metadata/html/browsers/history/the-history-interface/history_back_1.html.ini
  tests/wpt/metadata/html/browsers/history/the-history-interface/history_forward.html.ini
  tests/wpt/metadata/html/browsers/history/the-history-interface/history_forward_1.html.ini
  tests/wpt/metadata/html/browsers/history/the-history-interface/history_go_minus.html.ini
  tests/wpt/metadata/html/browsers/history/the-history-interface/history_go_no_argument.html.ini
  tests/wpt/metadata/html/browsers/history/the-history-interface/history_go_plus.html.ini
  tests/wpt/metadata/html/browsers/history/the-history-interface/history_go_to_uri.html.ini
  tests/wpt/metadata/html/browsers/history/the-history-interface/history_go_undefined.html.ini
  tests/wpt/metadata/html/browsers/history/the-history-interface/history_go_zero.html.ini
  tests/wpt/metadata/html/browsers/history/the-history-interface/history_properties_only_fully_active.html.ini
  tests/wpt/metadata/html/browsers/history/the-history-interface/history_pushstate_err.html.ini
  tests/wpt/metadata/html/browsers/history/the-history-interface/history_replacestate_err.html.ini
  tests/wpt/metadata/html/browsers/history/the-history-interface/traverse_the_history_1.html.ini
  tests/wpt/metadata/html/browsers/history/the-history-interface/traverse_the_history_2.html.ini
  tests/wpt/metadata/html/browsers/history/the-history-interface/traverse_the_history_3.html.ini
  tests/wpt/metadata/html/browsers/history/the-history-interface/traverse_the_history_4.html.ini
  tests/wpt/metadata/html/browsers/history/the-history-interface/traverse_the_history_5.html.ini
  tests/wpt/metadata/html/browsers/history/the-history-interface/traverse_the_history_unload_1.html.ini
  tests/wpt/metadata/html/browsers/history/the-history-interface/traverse_the_history_write_after_load_1.html.ini
  tests/wpt/metadata/html/browsers/history/the-history-interface/traverse_the_history_write_after_load_2.html.ini
  tests/wpt/metadata/html/browsers/history/the-history-interface/traverse_the_history_write_onload_1.html.ini
  tests/wpt/metadata/html/browsers/history/the-history-interface/traverse_the_history_write_onload_2.html.ini
Labels: S-tests-failed

#20646 Some drive-by error condition fix for gl.drawElements
  components/script/dom/webglrenderingcontext.rs
Labels: S-awaiting-merge

#20647 style: Sync changes from mozilla-central.
  components/style/properties/data.py
  components/style/properties/longhand/box.mako.rs
  components/style/properties/longhand/column.mako.rs
  components/style/properties/longhand/font.mako.rs
  components/style/properties/longhand/position.mako.rs
  components/style/properties/shorthand/border.mako.rs
  components/style/properties/shorthand/box.mako.rs
Labels: S-awaiting-merge

#20656 Fix error name in comment for try_match_ident_ignore_ascii_case
  components/style/macros.rs
Labels: S-awaiting-merge

#20648 Implement gl.getParameter(gl.ALIASED_LINE_WIDTH_RANGE)
  Cargo.lock
  components/canvas/Cargo.toml
  components/canvas/webgl_thread.rs
  components/canvas_traits/webgl.rs
  components/compositing/Cargo.toml
  components/script/Cargo.toml
  components/script/dom/webglrenderingcontext.rs
  components/servo/Cargo.toml
  ports/servo/Cargo.toml
  tests/wpt/mozilla/meta/webgl/conformance-1.0.3/conformance/more/conformance/quickCheckAPI-L_S.html.ini
Labels: S-awaiting-merge

#20662 Update to smallbitvec 2.1
  Cargo.lock
  components/malloc_size_of/Cargo.toml
  components/script/dom/cssstyledeclaration.rs
  components/style/Cargo.toml
  components/style/properties/declaration_block.rs
Labels: S-awaiting-merge

#20453 History: update document URL on pushState/replaceState
  components/script/dom/history.rs
  tests/wpt/metadata/html/browsers/history/the-history-interface/008.html.ini
  tests/wpt/metadata/html/browsers/history/the-history-interface/009.html.ini
  tests/wpt/metadata/html/browsers/history/the-history-interface/010.html.ini
  tests/wpt/metadata/html/browsers/history/the-history-interface/011.html.ini
  tests/wpt/metadata/html/browsers/history/the-history-interface/012.html.ini
  tests/wpt/metadata/html/browsers/history/the-history-interface/history_pushstate_err.html.ini
  tests/wpt/metadata/html/browsers/history/the-history-interface/history_replacestate_err.html.ini
  tests/wpt/metadata/html/browsers/history/the-location-interface/location_hash.html.ini
  tests/wpt/metadata/html/browsers/history/the-location-interface/location_search.html.ini
  tests/wpt/metadata/html/semantics/forms/attributes-common-to-form-controls/formAction_document_address.html.ini
Labels: S-tests-failed

#20661 Remove insaccessible history states
  components/constellation/constellation.rs
  components/net/resource_thread.rs
  components/net_traits/lib.rs
  components/script/dom/history.rs
  components/script/script_thread.rs
  components/script_traits/lib.rs
Labels: S-awaiting-merge

#20666 Fix building servo_url by itself
  components/url/Cargo.toml
Labels: S-awaiting-merge

#20676 Notify the embedder when it should display or hide an IME
  components/compositing/compositor_thread.rs
  components/constellation/constellation.rs
  components/msg/constellation_msg.rs
  components/script/dom/document.rs
  components/script/dom/element.rs
  components/script/dom/htmlinputelement.rs
  components/script_traits/script_msg.rs
  ports/servo/browser.rs
Labels: S-awaiting-merge

#20687 fix(browser): do not omit unexpected keyevent
  ports/servo/browser.rs
Labels: S-tests-failed

#20695 Revert "Don't clean nightlies on Mac builds"
  etc/ci/buildbot_steps.yml
Labels: S-tests-failed

#20691 Update Webrender to last version
  Cargo.lock
  components/layout/display_list/webrender_helpers.rs
  tests/wpt/metadata/css/css-backgrounds/background-repeat/background-repeat-round-roundup.xht.ini
  tests/wpt/metadata/css/css-backgrounds/background-repeat/background-repeat-round.xht.ini
  tests/wpt/metadata/css/css-backgrounds/background-size-025.html.ini
  tests/wpt/metadata/css/css-backgrounds/background-size-027.html.ini
  tests/wpt/metadata/css/css-backgrounds/background-size/background-size-contain.xht.ini
  tests/wpt/metadata/css/css-backgrounds/background-size/background-size-cover.xht.ini
Labels: S-tests-failed

#20533 Delegate resource reading to embedder
  Cargo.lock
  components/bluetooth_traits/Cargo.toml
  components/bluetooth_traits/blocklist.rs
  components/bluetooth_traits/lib.rs
  components/config/Cargo.toml
  components/config/lib.rs
  components/config/opts.rs
  components/config/prefs.rs
  components/config/resource_files.rs
  components/config/tests/opts.rs
  components/config/tests/prefs.rs
  components/constellation/Cargo.toml
  components/constellation/lib.rs
  components/constellation/sandboxing.rs
  components/embedder_traits/Cargo.toml
  components/embedder_traits/lib.rs
  components/embedder_traits/resources.rs
  components/layout_thread/Cargo.toml
  components/layout_thread/lib.rs
  components/net/Cargo.toml
  components/net/chrome_loader.rs
  components/net/connector.rs
  components/net/hsts.rs
  components/net/image_cache.rs
  components/net/lib.rs
  components/net/resource_thread.rs
  components/net/tests/chrome_loader.rs
  components/net/tests/cookie.rs
  components/net/tests/fetch.rs
  components/net/tests/hsts.rs
  components/net/tests/http_loader.rs
  components/net/tests/main.rs
  components/net_traits/Cargo.toml
  components/net_traits/lib.rs
  components/net_traits/pub_domains.rs
  components/net_traits/tests/pub_domains.rs
  components/script/Cargo.toml
  components/script/dom/servoparser/mod.rs
  components/script/dom/userscripts.rs
  components/script/lib.rs
  components/servo/Cargo.toml
  components/servo/lib.rs
  ports/servo/Cargo.toml
  ports/servo/main.rs
  ports/servo/resources.rs
  resources/badcert.html
  resources/failure.html
  resources/itried.jpg
  support/android/apk/app/src/main/java/com/mozilla/servo/MainActivity.java
  tests/unit/style/Cargo.toml
  tests/unit/style/lib.rs
  tests/unit/style/stylesheets.rs
Labels: S-awaiting-merge

#20448 NCSU Project - Random web content generator
  .gitignore
  etc/servo_automation_screenshot.py
  etc/start_servo.py
Labels: S-awaiting-merge

#20719 Fix pull request template
  PULL_REQUEST_TEMPLATE.md
Labels: S-awaiting-merge
