Repository servo/servo, pull requests merged in 2018-05, with the labels that each got.

#20728 Update WPT syncing metadata.
  tests/wpt/metadata/mozilla-sync
Labels: S-awaiting-merge

#20689 MutationObserver api: Implement takeRecords() and characterData mutations
  components/script/dom/attr.rs
  components/script/dom/characterdata.rs
  components/script/dom/element.rs
  components/script/dom/mutationobserver.rs
  components/script/dom/mutationrecord.rs
  components/script/dom/webidls/MutationObserver.webidl
  tests/wpt/metadata/dom/nodes/MutationObserver-attributes.html.ini
  tests/wpt/metadata/dom/nodes/MutationObserver-characterData.html.ini
  tests/wpt/metadata/dom/nodes/MutationObserver-takeRecords.html.ini
Labels: S-awaiting-merge

#20743 Remove useless message
  components/constellation/constellation.rs
  components/script_traits/script_msg.rs
Labels: S-awaiting-merge

#20738 Adjust WPT manifest update python path to unbreak automated sync.
  tests/wpt/update/__init__.py
Labels: S-awaiting-merge

#20732 Update to gleam 0.5
  Cargo.lock
  components/canvas/Cargo.toml
  components/canvas/webgl_thread.rs
  components/canvas_traits/Cargo.toml
  components/canvas_traits/lib.rs
  components/canvas_traits/webgl.rs
  components/compositing/Cargo.toml
  components/compositing/compositor.rs
  components/layout/display_list/background.rs
  components/layout/display_list/items.rs
  components/layout/display_list/webrender_helpers.rs
  components/malloc_size_of/lib.rs
  components/script/Cargo.toml
  components/script/dom/webglprogram.rs
  components/script/dom/webglrenderingcontext.rs
  components/script/dom/webglshader.rs
  components/servo/Cargo.toml
  ports/servo/Cargo.toml
Labels: S-awaiting-merge

#20753 Build note for Ubuntu 16.04
  README.md
Labels: S-awaiting-merge

#20750 fix(capture_webrender): try fallback capture dir
  components/compositing/compositor.rs
Labels: S-awaiting-merge

#20782 Don't suppress errors when executing mach bootstrap processes.
  python/mach_bootstrap.py
Labels: S-awaiting-merge

#20766 Generate a frame when a transaction scrolls
  components/compositing/compositor.rs
Labels: S-awaiting-merge

#20790 Install rustup in TaskCluster builds
  etc/ci/taskcluster-test.sh
Labels: S-tests-failed

#20776 Replace a boxed iterator with impl Trait
  components/net/cookie_storage.rs
Labels: S-awaiting-merge, S-blocked-on-closed-tree

#20820 Revert "Upgrade to rustc 1.27.0-nightly (8a37c75a3 2018-05-02)"
  components/allocator/lib.rs
  components/dom_struct/lib.rs
  components/gfx/lib.rs
  components/script_plugins/unrooted_must_root.rs
  components/script_plugins/utils.rs
  rust-toolchain
Labels: S-awaiting-merge

#20718 Automatically provide a resource reader for tests
  Cargo.lock
  components/bluetooth_traits/Cargo.toml
  components/config/Cargo.toml
  components/config/tests/opts.rs
  components/config/tests/prefs.rs
  components/constellation/Cargo.toml
  components/embedder_traits/Cargo.toml
  components/embedder_traits/resources.rs
  components/layout_thread/Cargo.toml
  components/net/Cargo.toml
  components/net/tests/cookie.rs
  components/net/tests/fetch.rs
  components/net/tests/http_loader.rs
  components/net_traits/Cargo.toml
  components/net_traits/tests/pub_domains.rs
  components/script/Cargo.toml
  components/servo/Cargo.toml
  tests/unit/style/Cargo.toml
  tests/unit/style/lib.rs
  tests/unit/style/stylesheets.rs
Labels: S-awaiting-merge

#20740 Implement MutationObserver.disconnect()
  components/script/dom/mutationobserver.rs
  components/script/dom/node.rs
  components/script/dom/webidls/MutationObserver.webidl
  tests/wpt/metadata/dom/nodes/Element-classlist.html.ini
  tests/wpt/metadata/dom/nodes/MutationObserver-disconnect.html.ini
  tests/wpt/metadata/dom/nodes/MutationObserver-document.html.ini
  tests/wpt/metadata/dom/nodes/MutationObserver-takeRecords.html.ini
Labels: S-awaiting-merge

#20754 Webgl fixes
  components/script/dom/webglrenderingcontext.rs
  tests/wpt/mozilla/meta/webgl/conformance-1.0.3/conformance/state/gl-get-calls.html.ini
Labels: S-awaiting-merge

#20674 Issue #20556: Implement proper checks in WebGLRenderingContext's bindBuffer()
  components/script/dom/webglbuffer.rs
  tests/wpt/mozilla/meta/MANIFEST.json
  tests/wpt/mozilla/tests/mozilla/webgl/bindBuffer.html
Labels: S-awaiting-merge

#20777 Cleanup constellation debug messages
  components/constellation/constellation.rs
  components/script_traits/lib.rs
  components/script_traits/script_msg.rs
Labels: S-awaiting-merge

#20769 use dedicated TaskCluster workertype
  .taskcluster.yml
Labels: S-tests-failed

#20669 Issue #20623: Check the input to WebGLRenderingContext's clear().
  components/script/dom/webglrenderingcontext.rs
  tests/wpt/mozilla/meta/MANIFEST.json
  tests/wpt/mozilla/tests/mozilla/webgl/clear.html
Labels: S-awaiting-merge

#20843 style: Fix font-stretch animation.
  components/style/values/computed/font.rs
Labels: S-awaiting-merge

#20771 Implement most of the unsupported parameters in gl.getParameter()
  components/canvas/webgl_thread.rs
  components/canvas_traits/webgl.rs
  components/script/dom/webglrenderingcontext.rs
  tests/wpt/mozilla/meta/webgl/conformance-1.0.3/conformance/glsl/misc/shader-uniform-packing-restrictions.html.ini
  tests/wpt/mozilla/meta/webgl/conformance-1.0.3/conformance/glsl/misc/shader-varying-packing-restrictions.html.ini
  tests/wpt/mozilla/meta/webgl/conformance-1.0.3/conformance/glsl/variables/glsl-built-ins.html.ini
Labels: S-awaiting-merge

#20649 Dedupe syn, quote and unicode-xid
  Cargo.lock
  servo-tidy.toml
Labels: S-awaiting-merge

#20749 Basic pinch zoom handling
  components/compositing/compositor.rs
Labels: S-awaiting-merge

#20860 Revert "Dedupe syn, quote and unicode-xid"
  Cargo.lock
  servo-tidy.toml
Labels: S-awaiting-merge

#20857 Use std::simd instead of the simd crate
  Cargo.lock
  components/gfx/Cargo.toml
  components/gfx/lib.rs
  components/gfx/text/glyph.rs
  python/tidy/servo_tidy/licenseck.py
Labels: S-awaiting-merge

#20864 remove misleading spec url
  components/script/dom/node.rs
Labels: S-awaiting-merge

#20868 fix logic in overflow_direction, also add a FIXME
  components/layout/query.rs
Labels: S-tests-failed

#20877 Be less judgemental when tearing down WebGL rendering contexts
  components/script/dom/webglrenderingcontext.rs
Labels: S-tests-failed

#20882 Upgrade to rustc 1.28.0-nightly (524ad9b9e 2018-05-29)
  components/allocator/lib.rs
  components/dom_struct/lib.rs
  components/gfx/lib.rs
  components/nonzero/Cargo.toml
  components/nonzero/lib.rs
  components/script_plugins/lib.rs
  components/script_plugins/unrooted_must_root.rs
  components/script_plugins/utils.rs
  components/servo/Cargo.toml
  rust-toolchain
Labels: S-awaiting-merge

#20879 Update type of custom element constructor
  components/script/dom/customelementregistry.rs
  components/script/dom/webidls/CustomElementRegistry.webidl
Labels: S-awaiting-merge

#20793 Get the mozjs crate to work with the mozjs_sys which uses bindgen
  Cargo.lock
  appveyor.yml
  components/malloc_size_of/Cargo.toml
  components/script/Cargo.toml
  components/script/dom/bindings/codegen/CodegenRust.py
  components/script/dom/bindings/reflector.rs
  components/script/dom/bindings/trace.rs
  components/script/dom/customelementregistry.rs
  components/script/dom/history.rs
  components/script/dom/promise.rs
  components/script/timers.rs
  python/servo/command_base.py
  python/servo/packages.py
Labels: A-content/script, S-awaiting-merge, S-blocked-on-external

#20878 Improve debugging output for WebGL errors.
  components/canvas/webgl_thread.rs
  components/canvas_traits/webgl.rs
  components/canvas_traits/webgl_channel/mod.rs
Labels: S-tests-failed

#20884 Don't forward GL parameter gets for constant limits.
  Cargo.lock
  components/canvas/Cargo.toml
  components/canvas_traits/Cargo.toml
  components/canvas_traits/webgl.rs
  components/script/Cargo.toml
  components/script/dom/webglrenderingcontext.rs
Labels: S-tests-failed
