Repository servo/servo, pull requests merged in 2018-12, with the labels that each got.

#22332 Remove unused recycle argument from Document::unload
  components/script/dom/document.rs
  components/script/dom/window.rs
  components/script/script_thread.rs
Labels: S-awaiting-merge

#22335 Change ML search engine to duckduckgo
  ports/libmlservo/src/lib.rs
Labels: P-magic leap, S-awaiting-merge

#22340 Don't filter the bodies of cross-origin cached responses
  components/net/fetch/methods.rs
Labels: S-tests-failed

#22338 Update rust-webvr
  Cargo.lock
Labels: S-awaiting-merge

#22349 Android_logger update
  Cargo.lock
  ports/libsimpleservo/Cargo.toml
Labels: S-awaiting-merge

#22357 Sync WPT with upstream (03-12-2018)
  tests/wpt/metadata/FileAPI/url/url-in-tags-revoke.window.js.ini
  tests/wpt/metadata/css/css-transitions/transitions-animatable-properties-01.html.ini
  tests/wpt/metadata/encoding/single-byte-decoder.html.ini
  tests/wpt/metadata/html/semantics/embedded-content/the-img-element/environment-changes/viewport-change.html.ini
  tests/wpt/metadata/html/webappapis/dynamic-markup-insertion/opening-the-input-stream/aborted-parser.window.js.ini
  tests/wpt/metadata/performance-timeline/webtiming-resolution.any.js.ini
  tests/wpt/metadata/quirks/unitless-length/limited-quirks.html.ini
  tests/wpt/metadata/quirks/unitless-length/no-quirks.html.ini
  tests/wpt/metadata/workers/semantics/multiple-workers/005.html.ini
  tests/wpt/web-platform-tests/.taskcluster.yml
  tests/wpt/web-platform-tests/audio-output/idlharness.https.window.js
  tests/wpt/web-platform-tests/audio-output/idlharness.window.js
  tests/wpt/web-platform-tests/background-fetch/fetch.https.window.js
  tests/wpt/web-platform-tests/css/css-multicol/balance-table-with-fractional-height-row.html
  tests/wpt/web-platform-tests/interfaces/DOM-Parsing.idl
  tests/wpt/web-platform-tests/interfaces/input-events.idl
  tests/wpt/web-platform-tests/service-workers/service-worker/ServiceWorkerGlobalScope/postmessage.https.html
  tests/wpt/web-platform-tests/service-workers/service-worker/ServiceWorkerGlobalScope/unregister.https.html
  tests/wpt/web-platform-tests/service-workers/service-worker/ServiceWorkerGlobalScope/update.https.html
  tests/wpt/web-platform-tests/service-workers/service-worker/about-blank-replacement.https.html
  tests/wpt/web-platform-tests/service-workers/service-worker/activate-event-after-install-state-change.https.html
  tests/wpt/web-platform-tests/service-workers/service-worker/claim-fetch.https.html
  tests/wpt/web-platform-tests/service-workers/service-worker/claim-not-using-registration.https.html
  tests/wpt/web-platform-tests/service-workers/service-worker/claim-shared-worker-fetch.https.html
  tests/wpt/web-platform-tests/service-workers/service-worker/claim-using-registration.https.html
  tests/wpt/web-platform-tests/service-workers/service-worker/clients-matchall-client-types.https.html
  tests/wpt/web-platform-tests/service-workers/service-worker/clients-matchall-order.https.html
  tests/wpt/web-platform-tests/service-workers/service-worker/controller-on-reload.https.html
  tests/wpt/web-platform-tests/service-workers/service-worker/fetch-csp.https.html
  tests/wpt/web-platform-tests/service-workers/service-worker/fetch-event-after-navigation-within-page.https.html
  tests/wpt/web-platform-tests/service-workers/service-worker/fetch-event-async-respond-with.https.html
  tests/wpt/web-platform-tests/service-workers/service-worker/fetch-event-network-error.https.html
  tests/wpt/web-platform-tests/service-workers/service-worker/fetch-event-respond-with-argument.https.html
  tests/wpt/web-platform-tests/service-workers/service-worker/fetch-event-respond-with-stops-propagation.https.html
  tests/wpt/web-platform-tests/service-workers/service-worker/fetch-event-throws-after-respond-with.https.html
  tests/wpt/web-platform-tests/service-workers/service-worker/fetch-request-redirect.https.html
  tests/wpt/web-platform-tests/service-workers/service-worker/multiple-update.https.html
  tests/wpt/web-platform-tests/service-workers/service-worker/performance-timeline.https.html
  tests/wpt/web-platform-tests/service-workers/service-worker/register-default-scope.https.html
  tests/wpt/web-platform-tests/service-workers/service-worker/register-wait-forever-in-install-worker.https.html
  tests/wpt/web-platform-tests/service-workers/service-worker/serviceworker-message-event-historical.https.html
  tests/wpt/web-platform-tests/service-workers/service-worker/shared-worker-controlled.https.html
  tests/wpt/web-platform-tests/service-workers/service-worker/skip-waiting-installed.https.html
  tests/wpt/web-platform-tests/service-workers/service-worker/skip-waiting.https.html
  tests/wpt/web-platform-tests/service-workers/service-worker/update-after-oneday.https.html
  tests/wpt/web-platform-tests/service-workers/service-worker/update-bytecheck.https.html
  tests/wpt/web-platform-tests/service-workers/service-worker/windowclient-navigate.https.html
  tests/wpt/web-platform-tests/service-workers/service-worker/worker-interception.https.html
  tests/wpt/web-platform-tests/tools/ci/start.sh
  tests/wpt/web-platform-tests/tools/docker/start.sh
  tests/wpt/web-platform-tests/tools/wptserve/wptserve/request.py
  tests/wpt/web-platform-tests/web-animations/animation-model/animation-types/property-list.js
  tests/wpt/web-platform-tests/webxr/xrFrame_lifetime.https.html
Labels: S-awaiting-merge

#22362 Use Utf8LossyDecoder instead of IncompleteUtf8
  components/script/dom/bindings/trace.rs
  components/script/dom/servoparser/mod.rs
Labels: S-tests-failed

#22377 Update servo-media. Fixes discarded frames during player setup
  Cargo.lock
Labels: S-awaiting-merge

#22382 Bug 1509027 - Use more restricted scope for Treeherder routes
  etc/taskcluster/decision_task.py
  etc/taskcluster/decisionlib.py
Labels: S-awaiting-merge

#22386 Use the base Ubuntu distro instead of LinuxMint in './mach bootstrap'
  python/servo/bootstrap.py
Labels: S-awaiting-merge

#22390 Fixup the issue related with an incorrect distro version string handling
  python/servo/bootstrap.py
Labels: S-awaiting-merge

#22391 Minor pull request template cleanup
  PULL_REQUEST_TEMPLATE.md
Labels: S-awaiting-merge

#22218 Implement NavigationPreloadManager for ServiceWorker
  components/script/dom/mod.rs
  components/script/dom/navigationpreloadmanager.rs
  components/script/dom/serviceworkerregistration.rs
  components/script/dom/webidls/NavigationPreloadManager.webidl
  components/script/dom/webidls/ServiceWorkerRegistration.webidl
Labels: S-awaiting-merge

#22389 Cancel animations that affect nodes that do not participate in layout.
  components/layout/animation.rs
  components/layout_thread/lib.rs
  components/msg/constellation_msg.rs
  components/script/dom/webidls/Window.webidl
  components/script/dom/window.rs
  components/script_layout_interface/message.rs
  tests/wpt/mozilla/meta/MANIFEST.json
  tests/wpt/mozilla/meta/mozilla/animation-removed-node.html.ini
  tests/wpt/mozilla/tests/mozilla/animation-removed-node.html
Labels: S-awaiting-merge

#22408 Add info about building on Linux Mint to README.md
  README.md
Labels: S-awaiting-merge

#22414 Remove redundant `.clone()`s
  components/constellation/constellation.rs
  components/constellation/network_listener.rs
  components/constellation/pipeline.rs
  components/devtools/actors/inspector.rs
  components/devtools/actors/network_event.rs
  components/devtools/lib.rs
  components/gfx/font_cache_thread.rs
  components/gfx/font_context.rs
  components/gfx/platform/freetype/font.rs
  components/layout/block.rs
  components/layout/display_list/builder.rs
  components/layout/inline.rs
  components/net/fetch/methods.rs
  components/net/filemanager_thread.rs
  components/net/http_cache.rs
  components/net/http_loader.rs
  components/net/websocket_loader.rs
  components/style/stylist.rs
  components/webvr/webvr_thread.rs
Labels: S-awaiting-merge

#22426 Taskcluster: start a decision task for all try-* branches
  .taskcluster.yml
Labels: S-awaiting-merge

#22324 Implementing HTMLMediaElement.volume attribute
  Cargo.lock
  components/atoms/static_atoms.txt
  components/script/dom/htmlmediaelement.rs
  components/script/dom/webidls/HTMLMediaElement.webidl
  tests/wpt/metadata/html/dom/interfaces.https.html.ini
  tests/wpt/metadata/html/semantics/embedded-content/media-elements/audio_volume_check.html.ini
  tests/wpt/metadata/html/semantics/embedded-content/media-elements/event_volumechange.html.ini
  tests/wpt/metadata/html/semantics/embedded-content/media-elements/playing-the-media-resource/pause-remove-from-document.html.ini
  tests/wpt/metadata/html/semantics/embedded-content/media-elements/video_volume_check.html.ini
  tests/wpt/metadata/html/semantics/embedded-content/media-elements/volume_nonfinite.html.ini
Labels: S-awaiting-merge

#22433 Improve implementation of media resource fetch algorithm
  components/script/dom/htmlmediaelement.rs
  tests/wpt/metadata/html/semantics/embedded-content/media-elements/loading-the-media-resource/load-events-networkState.html.ini
  tests/wpt/metadata/html/semantics/embedded-content/media-elements/loading-the-media-resource/resource-selection-invoke-insert-into-iframe.html.ini
  tests/wpt/metadata/html/semantics/embedded-content/media-elements/loading-the-media-resource/resource-selection-invoke-pause-networkState.html.ini
  tests/wpt/metadata/html/semantics/embedded-content/media-elements/loading-the-media-resource/resource-selection-invoke-remove-from-document-networkState.html.ini
Labels: S-awaiting-merge

#22436 Also run Taskcluster tasks when pushing to `master`
  .taskcluster.yml
Labels: S-awaiting-merge

#22450 One Treeherder page for all try-related branches
  etc/taskcluster/decision_task.py
Labels: S-awaiting-merge

#22446 Disable emulator testing in try-wpt-android and try-android too
  etc/taskcluster/decision_task.py
Labels: S-awaiting-merge

#22448 Delete space after [package] for code format
  components/servo/Cargo.toml
Labels: S-awaiting-merge

#22437 Rust's code of conduct link was changed
  CONTRIBUTING.md
Labels: S-awaiting-merge

#22439 Fix all clippy warnings in style_derive
  components/style_derive/cg.rs
  components/style_derive/parse.rs
  components/style_derive/specified_value_info.rs
  components/style_derive/to_animated_zero.rs
Labels: S-tests-failed

#22447 Add another layer of rAF to avoid intermittent failures.
  tests/wpt/mozilla/meta/MANIFEST.json
  tests/wpt/mozilla/tests/mozilla/animation-removed-node.html
Labels: S-awaiting-merge

#22479 Sync WPT with upstream (16-12-2018)
  tests/wpt/metadata/encoding/single-byte-decoder.html.ini
  tests/wpt/metadata/html/browsers/history/the-history-interface/traverse_the_history_4.html.ini
  tests/wpt/metadata/html/browsers/history/the-history-interface/traverse_the_history_5.html.ini
  tests/wpt/metadata/html/semantics/embedded-content/the-img-element/non-active-document.html.ini
  tests/wpt/metadata/html/semantics/forms/the-button-element/button-validation.html.ini
  tests/wpt/metadata/quirks/unitless-length/no-quirks.html.ini
  tests/wpt/metadata/webaudio/the-audio-api/the-analysernode-interface/realtimeanalyser-fft-scaling.html.ini
  tests/wpt/mozilla/meta/css/transition_calc_implicit.html.ini
  tests/wpt/mozilla/meta/mozilla/animation-removed-node.html.ini
  tests/wpt/web-platform-tests/css/css-align/default-alignment/shorthand-serialization-001.html
  tests/wpt/web-platform-tests/css/css-backgrounds/background-gradient-subpixel-fills-area.html
  tests/wpt/web-platform-tests/css/css-backgrounds/reference/background-gradient-subpixel-fills-area-ref.html
  tests/wpt/web-platform-tests/html/semantics/forms/the-button-element/button-validation.html
  tests/wpt/web-platform-tests/webrtc-quic/RTCQuicStream-helper.js
  tests/wpt/web-platform-tests/webrtc-quic/RTCQuicStream.https.html
Labels: S-awaiting-merge

#22474 Unregister components while exiting
  components/background_hang_monitor/background_hang_monitor.rs
  components/background_hang_monitor/tests/hang_monitor_tests.rs
  components/layout_thread/lib.rs
  components/msg/constellation_msg.rs
  components/script/script_thread.rs
Labels: S-awaiting-merge

#22243 Cleanup of default ciphersuite list
  components/net/connector.rs
Labels: S-awaiting-merge

#22451 Avoid sending idle message more than once after a reflow is complete
  components/script/dom/window.rs
Labels: S-awaiting-merge

#22100 Implement AddEventListenerOptions: once
  components/script/dom/event.rs
  components/script/dom/eventtarget.rs
  components/script/dom/mediaquerylist.rs
  components/script/dom/webidls/EventTarget.webidl
  tests/wpt/metadata/dom/events/AddEventListenerOptions-once.html.ini
Labels: S-awaiting-merge

#22387 ./mach run -n on mac os.
  python/servo/command_base.py
Labels: S-awaiting-merge

#22465 Update userscripts Option
  etc/ci/performance/runner.py
Labels: S-awaiting-merge

#22533 Remove `foreign` service-workers mode
  components/net/http_loader.rs
  components/net_traits/request.rs
  components/script/fetch.rs
Labels: S-awaiting-merge

#22456 Update src/href attributes to be a USVString
  components/script/dom/bindings/str.rs
  components/script/dom/element.rs
  components/script/dom/htmliframeelement.rs
  components/script/dom/htmlimageelement.rs
  components/script/dom/htmlinputelement.rs
  components/script/dom/htmllinkelement.rs
  components/script/dom/htmlmediaelement.rs
  components/script/dom/htmlscriptelement.rs
  components/script/dom/macros.rs
  components/script/dom/servoparser/mod.rs
  components/script/dom/webidls/HTMLIFrameElement.webidl
  components/script/dom/webidls/HTMLImageElement.webidl
  components/script/dom/webidls/HTMLInputElement.webidl
  components/script/dom/webidls/HTMLLinkElement.webidl
  components/script/dom/webidls/HTMLMediaElement.webidl
  components/script/dom/webidls/HTMLScriptElement.webidl
Labels: S-awaiting-merge

#22458 Fixed bug in textinput::adjust_vertical concerning selection_origin
  components/script/textinput.rs
  tests/unit/script/textinput.rs
Labels: S-awaiting-merge

#22490 #22484 small cleanup
  components/script/dom/htmlimageelement.rs
Labels: S-awaiting-merge

#22534 Update owning_ref to 0.4
  Cargo.lock
  components/style/Cargo.toml
Labels: S-tests-failed

#22487 style: Make Servo use a single thread-pool for layout-related tasks per process.
  components/constellation/pipeline.rs
  components/layout_thread/lib.rs
  components/layout_traits/lib.rs
  components/script/dom/htmliframeelement.rs
  components/script/dom/windowproxy.rs
  components/script/script_thread.rs
  components/script_layout_interface/message.rs
  components/script_traits/lib.rs
  components/style/Cargo.toml
  components/style/gecko/mod.rs
  components/style/global_style_data.rs
  components/style/lib.rs
Labels: S-awaiting-merge

#22538 Update ServiceWorkerContainer Webidl
  components/script/dom/webidls/ServiceWorkerContainer.webidl
Labels: S-awaiting-merge

#22540 Update ServiceWorker webidl
  components/script/dom/webidls/ServiceWorker.webidl
Labels: S-awaiting-merge

#22546 Update servo-tidy.toml
  servo-tidy.toml
Labels: S-awaiting-merge

#22547 Implement URL's toJSON()
  components/script/dom/url.rs
  components/script/dom/webidls/URL.webidl
  tests/wpt/metadata/url/idlharness.any.js.ini
  tests/wpt/metadata/url/url-tojson.any.js.ini
  tests/wpt/metadata/url/url-tojson.html.ini
Labels: S-awaiting-merge

#22552 Sync WPT with upstream (24-12-2018)
  tests/wpt/metadata/html/browsers/history/the-history-interface/traverse_the_history_1.html.ini
  tests/wpt/metadata/html/browsers/history/the-history-interface/traverse_the_history_3.html.ini
  tests/wpt/metadata/html/browsers/history/the-history-interface/traverse_the_history_5.html.ini
  tests/wpt/metadata/html/semantics/embedded-content/media-elements/event_timeupdate_noautoplay.html.ini
  tests/wpt/metadata/html/semantics/embedded-content/the-img-element/404-response-with-actual-image-data.html.ini
  tests/wpt/metadata/html/semantics/embedded-content/the-img-element/environment-changes/viewport-change.html.ini
  tests/wpt/metadata/html/semantics/interactive-elements/the-details-element/toggleEvent.html.ini
  tests/wpt/metadata/html/webappapis/dynamic-markup-insertion/document-write/iframe_005.html.ini
  tests/wpt/metadata/performance-timeline/webtiming-resolution.any.js.ini
  tests/wpt/metadata/resource-timing/buffer-full-set-to-current-buffer.html.ini
  tests/wpt/web-platform-tests/html/semantics/embedded-content/the-img-element/404-response-with-actual-image-data.html
  tests/wpt/web-platform-tests/html/semantics/embedded-content/the-img-element/404-response-with-actual-image-data.py
Labels: S-tests-failed

#22549 Make create-wpt mach command use new manifest update implementation
  python/servo/testing_commands.py
Labels: S-awaiting-merge

#22428 Split simpleservo into 3 crates for rust, c and jni apis
  Cargo.lock
  Cargo.toml
  ports/libsimpleservo/api/Cargo.toml
  ports/libsimpleservo/api/build.rs
  ports/libsimpleservo/api/src/gl_glue.rs
  ports/libsimpleservo/api/src/lib.rs
  ports/libsimpleservo/capi/Cargo.toml
  ports/libsimpleservo/capi/src/lib.rs
  ports/libsimpleservo/jniapi/Cargo.toml
  ports/libsimpleservo/jniapi/build.rs
  ports/libsimpleservo/jniapi/src/lib.rs
  ports/libsimpleservo/src/lib.rs
  python/servo/command_base.py
Labels: S-awaiting-merge

#22569 Add missing build dependencies for openSUSE
  README.md
Labels: S-awaiting-merge

#22577 Publish selectors 0.21.0 on crates.io
  Cargo.lock
  components/selectors/Cargo.toml
Labels: S-tests-failed
