Repository servo/servo, pull requests merged in 2018-07, with the labels that each got.

#21105 Assert that DOM structs have the correct first field
  Cargo.lock
  components/dom_struct/Cargo.toml
  components/dom_struct/lib.rs
  components/script/dom/bindings/codegen/CodegenRust.py
  components/script/dom/bindings/inheritance.rs
  components/script/dom/filereadersync.rs
Labels: S-awaiting-merge

#21125 Update README for Android
  README.md
Labels: S-awaiting-merge

#21131 Make (dictionary)::empty() safe
  components/script/dom/bindings/codegen/CodegenRust.py
  components/script/dom/bindings/iterable.rs
Labels: S-awaiting-merge

#21089 Upgrade to rustc 1.29.0-nightly (e06c87544 2018-07-06)
  components/script_plugins/unrooted_must_root.rs
  components/script_plugins/utils.rs
  rust-toolchain
Labels: S-tests-failed

#21135 Update regex to 1.0
  Cargo.lock
  components/bluetooth_traits/Cargo.toml
  components/profile/Cargo.toml
  components/script/Cargo.toml
  components/style/Cargo.toml
  components/webdriver_server/Cargo.toml
Labels: S-awaiting-merge

#21148 Run WPT sync on a machine with a case-sensitive filesystem.
  etc/ci/buildbot_steps.yml
Labels: S-awaiting-merge

#21120 Exposing HTMLSourceElement IDL attributes
  components/script/dom/htmlsourceelement.rs
  components/script/dom/webidls/HTMLSourceElement.webidl
Labels: S-awaiting-merge

#21139 style: Move `float` CSS property outside mako
  components/style/properties/longhands/box.mako.rs
  components/style/values/computed/box.rs
  components/style/values/computed/mod.rs
  components/style/values/specified/box.rs
  components/style/values/specified/mod.rs
Labels: S-awaiting-merge

#21126 Introduce "per task source" cancellation
  Cargo.lock
  components/script/Cargo.toml
  components/script/dom/eventsource.rs
  components/script/dom/filereader.rs
  components/script/dom/globalscope.rs
  components/script/dom/htmlimageelement.rs
  components/script/dom/htmlmediaelement.rs
  components/script/dom/htmlscriptelement.rs
  components/script/dom/websocket.rs
  components/script/dom/window.rs
  components/script/dom/xmlhttprequest.rs
  components/script/fetch.rs
  components/script/layout_image.rs
  components/script/lib.rs
  components/script/stylesheet_loader.rs
  components/script/task_source/dom_manipulation.rs
  components/script/task_source/file_reading.rs
  components/script/task_source/mod.rs
  components/script/task_source/networking.rs
  components/script/task_source/performance_timeline.rs
  components/script/task_source/user_interaction.rs
Labels: S-awaiting-merge

#21156 style: Move `clear` CSS property outside mako
  components/style/properties/longhands/box.mako.rs
  components/style/values/computed/box.rs
  components/style/values/computed/mod.rs
  components/style/values/specified/box.rs
  components/style/values/specified/mod.rs
Labels: S-tests-failed

#20543 build(mach): locate vs via vswhere on win32
  mach
  mach.bat
Labels: S-awaiting-merge

#21162 Add a no-op 'android-x86' set of Buildbot steps
  etc/ci/buildbot_steps.yml
Labels: S-tests-failed

#21159 Add doc comments to specified `float` and `clear` CSS properties
  components/style/values/specified/box.rs
Labels: S-awaiting-merge

#21167 Avoid virtualenv conflicts when running nightly jobs
  etc/ci/performance/test_perf.sh
Labels: S-tests-failed

#21170 Use remote-event task source in EventSource
  components/script/dom/eventsource.rs
  components/script/dom/globalscope.rs
  components/script/dom/window.rs
  components/script/dom/workerglobalscope.rs
  components/script/script_thread.rs
  components/script/task_source/mod.rs
  components/script/task_source/remote_event.rs
Labels: S-awaiting-merge

#21183 Android: run ./mach package implicitly after ./mach build
  etc/ci/buildbot_steps.yml
  python/servo/build_commands.py
Labels: S-awaiting-merge

#21187 Make fetch() API use same-origin credentials by default
  components/script/dom/request.rs
  tests/wpt/metadata/fetch/api/request/request-init-003.sub.html.ini
  tests/wpt/metadata/fetch/api/request/request-structure.html.ini
Labels: S-awaiting-merge

#21190 Fix hittesting on HiDPI screens
  ports/servo/glutin_app/window.rs
Labels: S-tests-failed

#21196 Update euclid to 0.18
  Cargo.lock
  components/canvas/Cargo.toml
  components/canvas/canvas_data.rs
  components/canvas_traits/Cargo.toml
  components/compositing/Cargo.toml
  components/compositing/compositor.rs
  components/config/Cargo.toml
  components/constellation/Cargo.toml
  components/geometry/Cargo.toml
  components/gfx/Cargo.toml
  components/layout/Cargo.toml
  components/layout/display_list/builder.rs
  components/layout/sequential.rs
  components/layout_thread/Cargo.toml
  components/malloc_size_of/Cargo.toml
  components/script/Cargo.toml
  components/script_layout_interface/Cargo.toml
  components/script_traits/Cargo.toml
  components/servo/Cargo.toml
  components/style/Cargo.toml
  components/style/values/generics/transform.rs
  components/style_traits/Cargo.toml
  components/webdriver_server/Cargo.toml
  components/webvr/Cargo.toml
  ports/servo/Cargo.toml
  tests/unit/script/Cargo.toml
  tests/unit/style/Cargo.toml
Labels: S-tests-failed

#21185 Stop using Salt-installed Android SDK on CI
  etc/ci/buildbot_steps.yml
Labels: S-awaiting-merge

#21203 Disable tests for unsupported JS modules
  tests/wpt/include.ini
Labels: S-awaiting-merge

#21181 Implement update source set & select image source
  components/script/dom/bindings/trace.rs
  components/script/dom/htmlimageelement.rs
  components/style/values/specified/source_size_list.rs
  tests/wpt/metadata/html/semantics/embedded-content/the-img-element/adoption.html.ini
  tests/wpt/metadata/html/semantics/embedded-content/the-img-element/update-the-image-data/fail-to-resolve.html.ini
  tests/wpt/metadata/html/semantics/embedded-content/the-img-element/update-the-source-set.html.ini
Labels: S-awaiting-merge

#21207 Some WebGL drive-by fixes
  components/script/dom/webglprogram.rs
  components/script/dom/webglrenderingcontext.rs
  components/script/dom/webgluniformlocation.rs
  tests/wpt/mozilla/meta/webgl/conformance-1.0.3/conformance/uniforms/uniform-location.html.ini
Labels: S-tests-failed

#21209 Resume WPT syncing on mac builders.
  etc/ci/buildbot_steps.yml
Labels: S-awaiting-merge

#21216 Update parking_lot to 0.6
  Cargo.lock
  components/layout/Cargo.toml
  components/layout_thread/Cargo.toml
  components/script/Cargo.toml
  components/style/Cargo.toml
  components/style/shared_lock.rs
  tests/unit/style/Cargo.toml
Labels: S-tests-failed

#21215 Implement step 5 of select_image_source
  components/script/dom/htmlimageelement.rs
Labels: S-awaiting-merge

#21048 Track hash changes in session history
  components/constellation/constellation.rs
  components/constellation/session_history.rs
  components/script/dom/history.rs
  components/script/dom/window.rs
  components/script_traits/script_msg.rs
  tests/wpt/metadata/css/cssom-view/scroll-behavior-smooth.html.ini
  tests/wpt/metadata/encoding/single-byte-decoder.html.ini
  tests/wpt/metadata/fetch/api/request/request-keepalive-quota.html.ini
  tests/wpt/metadata/html/browsers/browsing-the-web/history-traversal/hashchange_event.html.ini
  tests/wpt/metadata/html/browsers/browsing-the-web/scroll-to-fragid/004.html.ini
  tests/wpt/metadata/html/browsers/browsing-the-web/scroll-to-fragid/005.html.ini
  tests/wpt/metadata/html/browsers/browsing-the-web/scroll-to-fragid/006.html.ini
  tests/wpt/metadata/html/browsers/browsing-the-web/scroll-to-fragid/007.html.ini
  tests/wpt/metadata/html/browsers/history/the-history-interface/004.html.ini
  tests/wpt/metadata/html/semantics/document-metadata/the-meta-element/pragma-directives/attr-meta-http-equiv-refresh/parsing.html.ini
  tests/wpt/metadata/websockets/binary/001.html.ini
  tests/wpt/metadata/websockets/binary/002.html.ini
  tests/wpt/metadata/websockets/binary/004.html.ini
  tests/wpt/metadata/websockets/binary/005.html.ini
  tests/wpt/metadata/websockets/interfaces/WebSocket/bufferedAmount/bufferedAmount-arraybuffer.html.ini
  tests/wpt/metadata/websockets/interfaces/WebSocket/bufferedAmount/bufferedAmount-blob.html.ini
  tests/wpt/metadata/xhr/sync-no-timeout.any.js.ini
Labels: S-tests-failed

#21228 Update sync commit.
  tests/wpt/metadata/mozilla-sync
Labels: S-awaiting-merge

#21229 Merge run_wpt.py into run.py
  python/servo/testing_commands.py
  tests/wpt/README.md
  tests/wpt/run.py
  tests/wpt/run_wpt.py
Labels: S-tests-failed

#21225 Rustfmt the constellation
  components/constellation/browsingcontext.rs
  components/constellation/constellation.rs
  components/constellation/event_loop.rs
  components/constellation/lib.rs
  components/constellation/network_listener.rs
  components/constellation/pipeline.rs
  components/constellation/sandboxing.rs
  components/constellation/session_history.rs
  components/constellation/timer_scheduler.rs
Labels: S-tests-failed

#21219 Complete remaining algo update_the_image_data
  components/script/dom/htmlimageelement.rs
Labels: S-awaiting-merge

#21244 Adjust import path for WPT tests to accommodate upstream.
  tests/wpt/run.py
Labels: S-tests-failed

#21246 Cache which capabilities are enabled in the context (fixes #20534)
  components/canvas/webgl_thread.rs
  components/canvas_traits/webgl.rs
  components/script/dom/webglrenderingcontext.rs
Labels: S-awaiting-merge

#21232 Enable MutationObserver by default.
  resources/prefs.json
  tests/wpt/metadata/css/cssom/css-style-attr-decl-block.html.ini
  tests/wpt/metadata/css/cssom/cssstyledeclaration-mutationrecord-001.html.ini
  tests/wpt/metadata/css/cssom/cssstyledeclaration-mutationrecord-002.html.ini
  tests/wpt/metadata/css/cssom/cssstyledeclaration-mutationrecord-003.html.ini
  tests/wpt/metadata/css/cssom/cssstyledeclaration-mutationrecord-004.html.ini
  tests/wpt/metadata/custom-elements/microtasks-and-constructors.html.ini
  tests/wpt/metadata/html/webappapis/scripting/event-loops/task_microtask_ordering.html.ini
  tests/wpt/metadata/html/webappapis/scripting/processing-model-2/unhandled-promise-rejections/promise-rejection-events.html.ini
  tests/wpt/mozilla/meta/MANIFEST.json
  tests/wpt/mozilla/tests/mozilla/interfaces.html
Labels: S-tests-failed

#21275 Use local android toolchain for dynamic symbol check.
  etc/ci/check_dynamic_symbols.py
Labels: S-awaiting-merge

#21272 Use the packed_simd crate instead of std::simd
  Cargo.lock
  components/gfx/Cargo.toml
  components/gfx/lib.rs
  components/gfx/text/glyph.rs
Labels: S-tests-failed

#21281 Fix copy paste typo
  components/servo/lib.rs
Labels: S-tests-failed

#21250 Refactor winit key handling
  components/servo/lib.rs
  ports/servo/browser.rs
  ports/servo/glutin_app/keyutils.rs
  ports/servo/glutin_app/window.rs
Labels: S-blocked-on-external, S-tests-failed

#21286 Avoid frequent disk space errors on cross builders.
  etc/ci/buildbot_steps.yml
Labels: S-awaiting-merge
