Repository servo/servo, pull requests merged in 2018-03, with the labels that each got.

#20154 Update WR (ipc deadlock workaround, clipped-filter fix).
  Cargo.lock
Labels: S-awaiting-merge

#20156 euclid update
  Cargo.lock
Labels: S-awaiting-merge

#20153 Update glutin, skia, and azure.
  Cargo.lock
  ports/servo/Cargo.toml
Labels: S-awaiting-merge

#20150 Remove text-is-significant param from Gecko_IsSignificantChild
  components/style/gecko/generated/bindings.rs
  components/style/gecko/wrapper.rs
Labels: S-awaiting-merge

#20167 Backed out changeset 39a71f4c9d94 for build bustages at make[4]: *** [force-cargo-library-build] Error 101 on a CLOSED TREE
  Cargo.lock
  components/style/Cargo.toml
  components/style/build_gecko.rs
Labels: S-awaiting-merge

#20170 Reland #20160 since it just needed a revendor that didn't happen automatically.
  Cargo.lock
  components/style/Cargo.toml
  components/style/build_gecko.rs
Labels: S-awaiting-merge

#20166 Update WR (async scene building fix)
  Cargo.lock
Labels: S-awaiting-merge

#20168 Improve disk usage of doc builds.
  etc/ci/upload_docs.sh
Labels: S-awaiting-merge

#20175 #20174 removed the option and unwrap
  components/config/basedir.rs
  components/config/prefs.rs
  components/config/tests/prefs.rs
  ports/servo/main.rs
Labels: S-awaiting-merge

#20177 removed default_data_dir() and default_cache_dir()
  components/config/basedir.rs
Labels: S-awaiting-merge

#20186 style: Fix text-emphasis-style conversion.
  components/style/properties/gecko.mako.rs
Labels: S-awaiting-merge

#20183 Unconditionally derive ToComputedValue as Clone for non-generic types
  components/style/values/computed/mod.rs
  components/style_derive/to_computed_value.rs
Labels: S-awaiting-merge

#20190 style: Don't guard the context opacity keywords with the svg in opentype pref.
  components/style/values/specified/svg.rs
Labels: S-awaiting-merge

#20189 Never store a squared root in SquaredDistance
  components/style/properties/helpers/animated_properties.mako.rs
  components/style/values/animated/color.rs
  components/style/values/distance.rs
  components/style_derive/compute_squared_distance.rs
Labels: S-tests-failed

#20192 Derive ToCss for DeclaredValue
  components/style/properties/properties.mako.rs
Labels: S-awaiting-merge

#20193 style: Remove more rustc_has_pr45225 stuff.
  ports/geckolib/tests/build.rs
  ports/geckolib/tests/size_of.rs
Labels: S-awaiting-merge

#20194 style: remove unused AsciiExt imports.
  components/style/attr.rs
  components/style/counter_style/mod.rs
  components/style/custom_properties.rs
  components/style/gecko/generated/pseudo_element_definition.rs
  components/style/gecko/pseudo_element_definition.mako.rs
  components/style/gecko_string_cache/mod.rs
  components/style/str.rs
  components/style/stylesheets/supports_rule.rs
  components/style/stylesheets/viewport_rule.rs
  components/style/values/mod.rs
  components/style/values/specified/align.rs
  components/style/values/specified/angle.rs
  components/style/values/specified/calc.rs
  components/style/values/specified/color.rs
  components/style/values/specified/font.rs
  components/style/values/specified/grid.rs
  components/style/values/specified/length.rs
  components/style/values/specified/mod.rs
  components/style/values/specified/percentage.rs
  components/style/values/specified/text.rs
  components/style/values/specified/time.rs
Labels: S-awaiting-merge

#20195 Remove FreeGLUT
  .travis.yml
  README.md
Labels: S-awaiting-merge

#20198 Use darling::util::Override in #[derive(ToCss)]
  components/style_derive/to_css.rs
Labels: S-awaiting-merge

#20199 Remove metadeps from the dependency tree
  Cargo.lock
Labels: S-awaiting-merge

#20203 Revert "Auto merge of #20201 - Eijebong:bump, r=nox"
  Cargo.lock
  components/style/Cargo.toml
Labels: S-awaiting-merge

#20202 Update devices and fork blurmac
  Cargo.lock
Labels: S-awaiting-merge

#20206 Ensure default paths are set when updating WPT metadata.
  tests/wpt/update/updatecommandline.py
Labels: S-awaiting-merge

#20209 Fix exception when updating WPT metadata.
  tests/wpt/update/updatecommandline.py
Labels: S-awaiting-merge

#20210 style: Add a comment about the weird setup for justify-items.
  components/style/values/computed/align.rs
Labels: S-awaiting-merge

#20144 Add WebGL function glGetTexParameter
  components/canvas/webgl_thread.rs
  components/canvas_traits/webgl.rs
  components/script/dom/webgl2renderingcontext.rs
  components/script/dom/webglrenderingcontext.rs
  components/script/dom/webidls/WebGLRenderingContext.webidl
  tests/wpt/mozilla/meta/webgl/conformance-1.0.3/conformance/context/methods.html.ini
  tests/wpt/mozilla/meta/webgl/conformance-1.0.3/conformance/extensions/ext-texture-filter-anisotropic.html.ini
  tests/wpt/mozilla/meta/webgl/conformance-1.0.3/conformance/state/gl-enum-tests.html.ini
  tests/wpt/mozilla/meta/webgl/conformance-1.0.3/conformance/textures/gl-get-tex-parameter.html.ini
  tests/wpt/mozilla/meta/webgl/conformance-1.0.3/conformance/textures/tex-input-validation.html.ini
  tests/wpt/mozilla/meta/webgl/conformance-2.0.0/conformance2/context/methods-2.html.ini
Labels: S-awaiting-merge

#20212 Regenerate all WebIDLs when one of them changes
  components/script/CMakeLists.txt
Labels: S-awaiting-merge

#20213 Add the option in servo-tidy to not check for alphabetical ordering.
  python/tidy/servo_tidy/tidy.py
  servo-tidy.toml
Labels: S-awaiting-merge

#20214 Stop using LocalClip::RoundedRect
  components/layout/block.rs
  components/layout/display_list/builder.rs
Labels: S-awaiting-merge

#20222 Do not disable thread pool in the parent process
  components/style/gecko/generated/bindings.rs
  components/style/gecko/global_style_data.rs
Labels: S-awaiting-merge

#19947 Add a --nightly | -n flag to mach run commands for linux
  python/servo/command_base.py
  python/servo/post_build_commands.py
Labels: S-awaiting-merge

#20226 Update WR (nVidia/ANGLE workaround, vertex shader optimizations).
  Cargo.lock
Labels: S-awaiting-merge

#20229 style: Separate the XBL and shadow dom styling bits.
  components/layout_thread/dom_wrapper.rs
  components/style/data.rs
  components/style/dom.rs
  components/style/gecko/wrapper.rs
  components/style/invalidation/element/state_and_attributes.rs
  components/style/stylesheet_set.rs
  components/style/stylist.rs
Labels: S-awaiting-merge

#20232 Update mozjs_sys
  Cargo.lock
Labels: S-awaiting-merge

#20240 style: Fix special color keywords.
  components/style/properties/longhand/color.mako.rs
  components/style/values/specified/color.rs
Labels: S-awaiting-merge

#20241 style: Make getting the XBL binding faster.
  components/style/gecko/wrapper.rs
Labels: S-awaiting-merge

#20245 Disable logging in bindgen to reduce code size
  Cargo.lock
  components/style/Cargo.toml
  ports/geckolib/tests/Cargo.toml
  servo-tidy.toml
Labels: S-awaiting-merge

#20247 Stop unconditionally collecting traversal statistics in nightly builds
  components/style/driver.rs
Labels: S-awaiting-merge

#20250 style: Reorder style sharing checks so that cheaper and broader ones are earlier.
  components/style/sharing/mod.rs
Labels: S-awaiting-merge

#20249 Add mesa-libGLU-devel dependency to README.md
  README.md
Labels: S-awaiting-merge

#20248 style: Change the order we match selectors on invalidation to match normal order.
  components/selectors/matching.rs
Labels: S-awaiting-merge

#20251 Chart memory reports over time
  components/profile/mem.rs
  etc/memory_chart.html
  etc/memory_reports_over_time.py
Labels: S-awaiting-merge

#20255 style: Fix serialization of place-items.
  components/style/properties/shorthand/position.mako.rs
Labels: S-awaiting-merge

#20262 constellation: Make setting up the WebGL state fallible.
  components/canvas/gl_context.rs
  components/constellation/constellation.rs
  components/constellation/pipeline.rs
  components/script/dom/webglrenderingcontext.rs
  components/script/dom/window.rs
  components/script/script_thread.rs
  components/script_traits/lib.rs
  components/servo/lib.rs
Labels: S-awaiting-merge

#20185 Make KeyframesPercentage::parse faster
  components/style/stylesheets/keyframes_rule.rs
Labels: S-awaiting-merge

#20274 style: Make the generated bindings really be formatted.
  components/style/build_gecko.rs
Labels: S-awaiting-merge

#20216 Switch from servo/angle to the mozangle crate
  Cargo.lock
  components/script/Cargo.toml
  components/script/dom/webglprogram.rs
  components/script/dom/webglshader.rs
  components/script/lib.rs
Labels: S-awaiting-merge

#20276 Update WR (various small optimizations and driver fixes).
  Cargo.lock
  tests/wpt/mozilla/meta/css/text_shadow_blur_a.html.ini
Labels: S-awaiting-merge

#20273 Unbreak the docs build.
  etc/ci/upload_docs.sh
Labels: S-tests-failed

#20283 style: Fix a typo in Integer struct docs
  components/style/values/specified/mod.rs
Labels: S-tests-failed

#20282 style: Fix some dead links in style.md
  docs/components/style.md
Labels: S-awaiting-merge

#20288 Update libloading to 0.5
  Cargo.lock
  components/style/Cargo.toml
Labels: S-awaiting-merge

#20290 build(cmake): detect python binary for specified version
  components/script/CMakeLists.txt
Labels: S-tests-failed

#20293 Sync WPT with upstream (13-03-2018)
  tests/wpt/metadata/2dcontext/imagebitmap/createImageBitmap-drawImage.html.ini
  tests/wpt/metadata/css/CSS2/floats-clear/clear-on-child-with-margins.html.ini
  tests/wpt/metadata/css/css-values/vh_not_refreshing_on_chrome.html.ini
  tests/wpt/metadata/css/cssom/inline-style-001.html.ini
  tests/wpt/metadata/css/cssom/medialist-interfaces-001.html.ini
  tests/wpt/metadata/css/cssom/style-sheet-interfaces-001.html.ini
  tests/wpt/metadata/encoding/idlharness.html.ini
  tests/wpt/mozilla/meta/css/iframe/hide_after_load.html.ini
  tests/wpt/mozilla/meta/webgl/conformance-1.0.3/conformance/canvas/rapid-resizing.html.ini
  tests/wpt/mozilla/meta/webgl/conformance-1.0.3/conformance/glsl/misc/shader-with-non-reserved-words.html.ini
  tests/wpt/web-platform-tests/.gitignore
  tests/wpt/web-platform-tests/client-hints/accept_ch.https.html
  tests/wpt/web-platform-tests/client-hints/accept_ch.https.html.headers
  tests/wpt/web-platform-tests/client-hints/echo_device_memory_header_received.py
  tests/wpt/web-platform-tests/css/CSS2/floats-clear/clear-on-child-with-margins.html
  tests/wpt/web-platform-tests/css/CSS2/floats-clear/clear-on-parent-and-child.html
  tests/wpt/web-platform-tests/css/CSS2/floats-clear/clear-on-parent-with-margins-no-clearance.html
  tests/wpt/web-platform-tests/css/CSS2/floats-clear/clear-on-parent-with-margins.html
  tests/wpt/web-platform-tests/css/CSS2/floats-clear/clear-on-parent.html
  tests/wpt/web-platform-tests/css/css-typed-om/stylevalue-subclasses/numeric-objects/cssUnitValue.tentative.html
  tests/wpt/web-platform-tests/css/css-typed-om/the-stylepropertymap/properties/scroll-padding.html
  tests/wpt/web-platform-tests/css/cssom/inline-style-001.html
  tests/wpt/web-platform-tests/css/cssom/medialist-interfaces-001.html
  tests/wpt/web-platform-tests/css/cssom/medialist-interfaces-002.html
  tests/wpt/web-platform-tests/css/cssom/medialist-interfaces-004.html
  tests/wpt/web-platform-tests/css/cssom/style-sheet-interfaces-001.html
  tests/wpt/web-platform-tests/encoding/idlharness.html
  tests/wpt/web-platform-tests/fetch/api/redirect/redirect-location.js
  tests/wpt/web-platform-tests/interfaces/encoding.idl
  tests/wpt/web-platform-tests/interfaces/magnetometer.idl
  tests/wpt/web-platform-tests/interfaces/orientation-sensor.idl
  tests/wpt/web-platform-tests/payment-request/payment-request-abort-method-manual.https.html
  tests/wpt/web-platform-tests/payment-request/payment-request-abort-method.https.html
  tests/wpt/web-platform-tests/payment-request/payment-request-canmakepayment-method-manual.https.html
  tests/wpt/web-platform-tests/payment-request/payment-request-canmakepayment-method.https.html
  tests/wpt/web-platform-tests/testharness_runner.html
  tests/wpt/web-platform-tests/tools/.coveragerc
  tests/wpt/web-platform-tests/tools/.gitignore
  tests/wpt/web-platform-tests/tools/lint/lint.py
  tests/wpt/web-platform-tests/tools/third_party/funcsigs/.coveragerc
  tests/wpt/web-platform-tests/tools/third_party/pytest/.coveragerc
  tests/wpt/web-platform-tests/tools/wptserve/.coveragerc
  tests/wpt/web-platform-tests/web-animations/timing-model/animations/setting-the-current-time-of-an-animation.html
Labels: S-awaiting-merge

#20294 Update WR (port blurs and blits to brush_image).
  Cargo.lock
Labels: S-awaiting-merge

#20243 style: add infrastructure to match the :host selector.
  components/layout_thread/dom_wrapper.rs
  components/script/dom/element.rs
  components/selectors/matching.rs
  components/selectors/parser.rs
  components/selectors/tree.rs
  components/style/gecko/selector_parser.rs
  components/style/gecko/wrapper.rs
  components/style/invalidation/element/element_wrapper.rs
  components/style/servo/selector_parser.rs
Labels: S-awaiting-merge

#20224 Fix counter() and counters() serialization.
  components/style/values/specified/counters.rs
  tests/wpt/metadata/css/cssom/serialize-values.html.ini
Labels: S-tests-failed

#20300 Update gleam to 0.4.24
  Cargo.lock
Labels: S-awaiting-merge

#20305 Don't access the reflector when dropping a Promise (fixes #18651)
  components/script/dom/promise.rs
Labels: S-awaiting-merge

#20291 Update the in-tree status of WPT syncing.
  tests/wpt/metadata/mozilla-sync
Labels: S-awaiting-merge

#20303 refactor(window): reference winit where applicable
  Cargo.lock
  ports/servo/Cargo.toml
  ports/servo/glutin_app/window.rs
  ports/servo/main.rs
Labels: S-awaiting-merge

#20309 Update mozangle to 0.1.6.
  Cargo.lock
Labels: S-tests-failed

#20310 Update the MULTIPROCESS static when changing default options
  components/config/opts.rs
Labels: S-awaiting-merge

#20122 Windows support for the --nightly | -n flag to mach run commands.
  python/servo/command_base.py
Labels: S-awaiting-merge

#20312 Avoid using WPT test runner to update the test manifest.
  etc/ci/manifest_changed.sh
  python/servo/testing_commands.py
  tests/wpt/manifestupdate.py
Labels: S-awaiting-merge

#20321 Remove update-manifest argument that is no longer valid.
  etc/ci/update-wpt-checkout
Labels: S-awaiting-merge

#20333 Use upstream mozjs 0.3
  Cargo.lock
  Cargo.toml
Labels: S-awaiting-merge

#20334 Update WR (radial gradient optimizations).
  Cargo.lock
Labels: S-awaiting-merge

#20304 CounterBound::Integer made to store an Integer
  components/style/counter_style/mod.rs
  components/style/gecko/rules.rs
Labels: S-awaiting-merge

#20339 style: Remove unsound Atom From implementations.
  components/style/gecko/conversions.rs
  components/style/gecko/media_queries.rs
  components/style/gecko/values.rs
  components/style/gecko_string_cache/mod.rs
  components/style/properties/gecko.mako.rs
  components/style/stylist.rs
  ports/geckolib/glue.rs
Labels: S-awaiting-merge

#20340 style: Better Shadow DOM assertions.
  components/style/gecko/wrapper.rs
  components/style/stylesheet_set.rs
Labels: S-awaiting-merge

#20259 Support memory report logs with interleaved non-report output
  etc/memory_reports_over_time.py
Labels: S-awaiting-merge

#20341 Update WR revision.
  Cargo.lock
Labels: S-awaiting-merge

#20351 Add Servo_Property_IsShorthand to geckolib/glue.rs
  components/style/properties/properties.mako.rs
  ports/geckolib/glue.rs
Labels: S-awaiting-merge

#20328 Re-expose webrender debugger feature in components/servo
  Cargo.lock
  components/debugger/Cargo.toml
  components/servo/Cargo.toml
Labels: S-awaiting-merge

#20369 Move WebGL validation
  components/canvas/webgl_thread.rs
  components/canvas_traits/webgl.rs
  components/script/dom/webglrenderingcontext.rs
Labels: S-tests-failed

#20374 Fix mouse click
  ports/servo/glutin_app/window.rs
Labels: S-awaiting-merge

#20298 Bump servo-websocket to 0.21
  Cargo.lock
  components/net/Cargo.toml
  components/net/websocket_loader.rs
Labels: S-awaiting-merge

#20371 Bump ipc-channel and bincode
  Cargo.lock
  components/bluetooth/Cargo.toml
  components/bluetooth_traits/Cargo.toml
  components/canvas/Cargo.toml
  components/canvas_traits/Cargo.toml
  components/compositing/Cargo.toml
  components/constellation/Cargo.toml
  components/devtools/Cargo.toml
  components/devtools_traits/Cargo.toml
  components/gfx/Cargo.toml
  components/hashglobe/Cargo.toml
  components/layout/Cargo.toml
  components/layout_thread/Cargo.toml
  components/layout_traits/Cargo.toml
  components/metrics/Cargo.toml
  components/net/Cargo.toml
  components/net_traits/Cargo.toml
  components/profile/Cargo.toml
  components/profile_traits/Cargo.toml
  components/rand/Cargo.toml
  components/rand/lib.rs
  components/script/Cargo.toml
  components/script/dom/worklet.rs
  components/script_layout_interface/Cargo.toml
  components/script_traits/Cargo.toml
  components/servo/Cargo.toml
  components/url/Cargo.toml
  components/url/origin.rs
  components/webdriver_server/Cargo.toml
  components/webvr/Cargo.toml
  components/webvr_traits/Cargo.toml
  servo-tidy.toml
  tests/unit/metrics/Cargo.toml
  tests/unit/profile/Cargo.toml
Labels: S-awaiting-merge

#20376 Remove our dependency on the gcc crate
  Cargo.lock
  support/rust-task_info/Cargo.toml
  support/rust-task_info/build.rs
Labels: S-awaiting-merge

#20370 Blobs support typed arrays now
  components/script/dom/blob.rs
  components/script/dom/file.rs
  components/script/dom/webidls/Blob.webidl
  tests/wpt/metadata/FileAPI/blob/Blob-constructor.html.ini
  tests/wpt/metadata/FileAPI/blob/Blob-slice.html.ini
  tests/wpt/metadata/FileAPI/file/File-constructor.html.ini
  tests/wpt/metadata/FileAPI/reading-data-section/Determining-Encoding.html.ini
Labels: S-awaiting-merge

#20378 Bump parking_lot to 0.5
  Cargo.lock
  components/layout/Cargo.toml
  components/layout_thread/Cargo.toml
  components/script/Cargo.toml
  components/style/Cargo.toml
  ports/geckolib/Cargo.toml
  tests/unit/style/Cargo.toml
Labels: S-awaiting-merge

#20368 refactor(counter_style): parse int via parse_non_negative
  components/style/counter_style/mod.rs
  components/style/gecko/rules.rs
Labels: S-tests-failed

#20327 fix(keyevent): do not emit default ignorable codepoint
  ports/servo/glutin_app/window.rs
Labels: S-awaiting-merge

#20132 Profiler for blocked IpcReceiver::recv()
  Cargo.lock
  components/profile/time.rs
  components/profile_traits/Cargo.toml
  components/profile_traits/ipc.rs
  components/profile_traits/lib.rs
  components/profile_traits/time.rs
  components/script/dom/blob.rs
  components/script/dom/bluetooth.rs
  components/script/dom/bluetoothdevice.rs
  components/script/dom/canvasrenderingcontext2d.rs
  components/script/dom/document.rs
  components/script/dom/history.rs
  components/script/dom/htmlcanvaselement.rs
  components/script/dom/htmliframeelement.rs
  components/script/dom/htmlinputelement.rs
  components/script/dom/paintworkletglobalscope.rs
  components/script/dom/screen.rs
  components/script/dom/storage.rs
  components/script/dom/testrunner.rs
  components/script/dom/url.rs
  components/script/dom/vr.rs
  components/script/dom/vrdisplay.rs
  components/script/dom/websocket.rs
  components/script/dom/window.rs
  tests/unit/profile/Cargo.toml
  tests/unit/profile/lib.rs
  tests/unit/profile/time.rs
Labels: S-awaiting-merge, This Week In Servo (TWiS)

#20389 getRandomValues uses ArrayBufferView now
  components/script/dom/crypto.rs
  components/script/dom/webidls/Crypto.webidl
Labels: S-awaiting-merge

#20390 Don't OOM when laying out basic web pages on Android
  components/layout/inline.rs
Labels: S-awaiting-merge

#20395 Update WR (accelerated webgl fix on mac, line decoration optimizations).
  Cargo.lock
  components/canvas/canvas_paint_thread.rs
  components/canvas/webgl_thread.rs
  components/config/opts.rs
  components/net/image_cache.rs
  components/servo/lib.rs
Labels: S-awaiting-merge

#20407 Rename Gecko string DataFlags::SHARED to REFCOUNTED
  support/gecko/nsstring/src/lib.rs
Labels: S-awaiting-merge

#20404 GamepadButtonList::sync_from_vr should use more iterators #20392
  components/script/dom/gamepadbuttonlist.rs
Labels: S-awaiting-merge

#20405 Add constructors for typed arrays in DOMMatrix and DOMMatrixReadOnly
  components/script/dom/dommatrix.rs
  components/script/dom/dommatrixreadonly.rs
  components/script/dom/webidls/DOMMatrix.webidl
  components/script/dom/webidls/DOMMatrixReadOnly.webidl
  tests/wpt/metadata/css/geometry/DOMMatrix-newobject.html.ini
  tests/wpt/metadata/css/geometry/interfaces.html.ini
  tests/wpt/metadata/css/geometry/interfaces.worker.js.ini
Labels: S-awaiting-merge

#20414 Implement gl.getParameter(gl.ALIASED_POINT_SIZE_RANGE)
  Cargo.lock
  components/canvas/Cargo.toml
  components/canvas/webgl_thread.rs
  components/canvas_traits/webgl.rs
  components/compositing/Cargo.toml
  components/script/Cargo.toml
  components/script/dom/webglrenderingcontext.rs
  components/servo/Cargo.toml
  ports/servo/Cargo.toml
  tests/wpt/mozilla/meta/webgl/conformance-1.0.3/conformance/glsl/variables/gl-pointcoord.html.ini
  tests/wpt/mozilla/meta/webgl/conformance-1.0.3/conformance/rendering/point-size.html.ini
  tests/wpt/mozilla/meta/webgl/conformance-1.0.3/conformance/rendering/point-with-gl-pointcoord-in-fragment-shader.html.ini
  tests/wpt/mozilla/meta/webgl/conformance-2.0.0/conformance2/rendering/clipping-wide-points.html.ini
Labels: S-awaiting-merge

#20413 TextDecoder's Decode now receives a BufferSource as input
  components/script/dom/textdecoder.rs
  components/script/dom/webidls/TextDecoder.webidl
  tests/wpt/metadata/encoding/api-basics.html.ini
Labels: S-awaiting-merge

#20419 Update mozjs.
  Cargo.lock
  components/script/dom/dommatrix.rs
  components/script/dom/dommatrixreadonly.rs
  components/script/dom/textdecoder.rs
  components/script/dom/webglrenderingcontext.rs
Labels: S-awaiting-merge

#20426 Websockets send typed arrays now
  components/script/dom/webidls/WebSocket.webidl
  components/script/dom/websocket.rs
  tests/wpt/metadata/websockets/Secure-Send-binary-arraybufferview-float32.htm.ini
  tests/wpt/metadata/websockets/Send-binary-65K-arraybuffer.htm.ini
  tests/wpt/metadata/websockets/Send-binary-arraybuffer.htm.ini
  tests/wpt/metadata/websockets/Send-binary-arraybufferview-int16-offset.htm.ini
  tests/wpt/metadata/websockets/Send-binary-arraybufferview-int8.htm.ini
  tests/wpt/metadata/websockets/binary/001.html.ini
  tests/wpt/metadata/websockets/binary/002.html.ini
  tests/wpt/metadata/websockets/binary/004.html.ini
  tests/wpt/metadata/websockets/binary/005.html.ini
  tests/wpt/metadata/websockets/interfaces/WebSocket/bufferedAmount/bufferedAmount-arraybuffer.html.ini
  tests/wpt/metadata/websockets/interfaces/WebSocket/bufferedAmount/bufferedAmount-blob.html.ini
Labels: S-awaiting-merge

#20402 Dedupe lazy_static
  Cargo.lock
  components/net/connector.rs
  servo-tidy.toml
Labels: S-awaiting-merge

#20433 Statically allocate static atoms.
  components/style/gecko/generated/structs.rs
  components/style/gecko_string_cache/mod.rs
Labels: S-tests-failed

#20432 Sync WPT with upstream (25-03-2018)
  tests/wpt/metadata/css/css-values/vh_not_refreshing_on_chrome.html.ini
  tests/wpt/metadata/css/geometry/interfaces.html.ini
  tests/wpt/metadata/css/geometry/interfaces.worker.js.ini
  tests/wpt/metadata/fetch/api/basic/text-utf8.html.ini
  tests/wpt/metadata/fetch/api/request/request-structure.html.ini
  tests/wpt/metadata/fetch/api/response/response-stream-disturbed-5.html.ini
  tests/wpt/metadata/fetch/data-urls/base64.any.js.ini
  tests/wpt/metadata/fetch/data-urls/processing.any.js.ini
  tests/wpt/metadata/websockets/binary/001.html.ini
  tests/wpt/metadata/websockets/binary/002.html.ini
  tests/wpt/metadata/websockets/binary/004.html.ini
  tests/wpt/metadata/websockets/binary/005.html.ini
  tests/wpt/metadata/websockets/interfaces/WebSocket/bufferedAmount/bufferedAmount-arraybuffer.html.ini
  tests/wpt/metadata/websockets/interfaces/WebSocket/bufferedAmount/bufferedAmount-blob.html.ini
  tests/wpt/mozilla/meta/MANIFEST.json
  tests/wpt/mozilla/meta/webgl/conformance-1.0.3/conformance/canvas/rapid-resizing.html.ini
  tests/wpt/mozilla/meta/webgl/conformance-1.0.3/conformance/glsl/misc/shader-with-non-reserved-words.html.ini
  tests/wpt/mozilla/meta/webgl/conformance-1.0.3/conformance/ogles/GL/asin/asin_001_to_006.html.ini
  tests/wpt/mozilla/meta/webgl/conformance-1.0.3/conformance/ogles/GL/log/log_001_to_008.html.ini
  tests/wpt/mozilla/meta/webgl/conformance-1.0.3/conformance/ogles/GL/log2/log2_001_to_008.html.ini
Labels: S-awaiting-merge

#20439 refactor(websocket): do not borrow sender anymore
  components/script/dom/websocket.rs
Labels: S-awaiting-merge

#20423 Use ByteBuf for the canvas messages
  Cargo.lock
  components/canvas/Cargo.toml
  components/canvas/canvas_paint_thread.rs
  components/canvas/lib.rs
  components/canvas/webgl_thread.rs
  components/canvas_traits/Cargo.toml
  components/canvas_traits/canvas.rs
  components/canvas_traits/lib.rs
  components/canvas_traits/webgl.rs
  components/malloc_size_of/Cargo.toml
  components/malloc_size_of/lib.rs
  components/script/Cargo.toml
  components/script/dom/canvasrenderingcontext2d.rs
  components/script/dom/htmlcanvaselement.rs
  components/script/dom/vrdisplay.rs
  components/script/dom/webglbuffer.rs
  components/script/dom/webglrenderingcontext.rs
  components/script/lib.rs
  components/webvr/webvr_thread.rs
Labels: S-awaiting-merge

#20449 Update WR (box shadow crash fix, clip task bug fix).
  Cargo.lock
Labels: S-awaiting-merge

#20444 Add comment for overflow-{x,y} applying to ::placeholder
  components/style/properties/longhand/box.mako.rs
Labels: S-awaiting-merge

#20451 Change "OS X" to "macOS" in Readme and docs
  README.md
  docs/HACKING_QUICKSTART.md
  docs/STYLE_GUIDE.md
Labels: S-awaiting-merge

#19550 Issue #15723: Skip git ignored files in update-manifest.
  tests/wpt/mozilla/.gitignore
Labels: S-tests-failed

#20430 Pass new method in CollectServoSizes to get size of ObjectPrivateVisitor
  Cargo.lock
  components/malloc_size_of/Cargo.toml
  components/script/Cargo.toml
  components/script/lib.rs
  components/script/mem.rs
  components/script/script_runtime.rs
  components/script/script_thread.rs
Labels: S-awaiting-merge, This Week In Servo (TWiS)

#20460 Remove StyleBackendType uses
  components/style/gecko/wrapper.rs
Labels: S-awaiting-merge

#20465 Bump env_logger to 0.5 and log to 0.4 in every servo crate
  Cargo.lock
  components/canvas/Cargo.toml
  components/compositing/Cargo.toml
  components/config/Cargo.toml
  components/constellation/Cargo.toml
  components/constellation/constellation.rs
  components/debugger/Cargo.toml
  components/devtools/Cargo.toml
  components/gfx/Cargo.toml
  components/layout/Cargo.toml
  components/layout_thread/Cargo.toml
  components/metrics/Cargo.toml
  components/net/Cargo.toml
  components/net/http_loader.rs
  components/net_traits/Cargo.toml
  components/profile/Cargo.toml
  components/profile_traits/Cargo.toml
  components/rand/Cargo.toml
  components/remutex/Cargo.toml
  components/script/Cargo.toml
  components/script_layout_interface/Cargo.toml
  components/script_layout_interface/reporter.rs
  components/selectors/Cargo.toml
  components/servo/Cargo.toml
  components/servo/lib.rs
  components/style/Cargo.toml
  components/style/error_reporting.rs
  components/style/style_resolver.rs
  components/webdriver_server/Cargo.toml
  components/webvr/Cargo.toml
  ports/geckolib/Cargo.toml
  ports/geckolib/glue.rs
  ports/geckolib/tests/Cargo.toml
  ports/servo/Cargo.toml
Labels: S-awaiting-merge

#20246 Use higher level handles from JS bindings
  Cargo.lock
  Cargo.toml
  components/domobject_derive/lib.rs
  components/malloc_size_of/Cargo.toml
  components/script/Cargo.toml
  components/script/body.rs
  components/script/devtools.rs
  components/script/dom/bindings/callback.rs
  components/script/dom/bindings/codegen/CodegenRust.py
  components/script/dom/bindings/constant.rs
  components/script/dom/bindings/conversions.rs
  components/script/dom/bindings/error.rs
  components/script/dom/bindings/guard.rs
  components/script/dom/bindings/htmlconstructor.rs
  components/script/dom/bindings/interface.rs
  components/script/dom/bindings/iterable.rs
  components/script/dom/bindings/mozmap.rs
  components/script/dom/bindings/namespace.rs
  components/script/dom/bindings/proxyhandler.rs
  components/script/dom/bindings/reflector.rs
  components/script/dom/bindings/structuredclone.rs
  components/script/dom/bindings/trace.rs
  components/script/dom/bindings/utils.rs
  components/script/dom/customelementregistry.rs
  components/script/dom/customevent.rs
  components/script/dom/dedicatedworkerglobalscope.rs
  components/script/dom/dissimilaroriginwindow.rs
  components/script/dom/errorevent.rs
  components/script/dom/eventtarget.rs
  components/script/dom/extendableevent.rs
  components/script/dom/extendablemessageevent.rs
  components/script/dom/globalscope.rs
  components/script/dom/history.rs
  components/script/dom/htmlcanvaselement.rs
  components/script/dom/messageevent.rs
  components/script/dom/paintworkletglobalscope.rs
  components/script/dom/popstateevent.rs
  components/script/dom/promise.rs
  components/script/dom/promisenativehandler.rs
  components/script/dom/serviceworker.rs
  components/script/dom/testbinding.rs
  components/script/dom/window.rs
  components/script/dom/windowproxy.rs
  components/script/dom/worker.rs
  components/script/dom/workerglobalscope.rs
  components/script/dom/xmlhttprequest.rs
  components/script/timers.rs
  components/script/webdriver_handlers.rs
Labels: S-awaiting-merge, S-fails-tidy

#20468 Fix style/build_gecko.rs for log 0.4 on a CLOSED TREE
  components/style/build_gecko.rs
Labels: S-awaiting-merge

#20479 style: Add a fast path to each_anonymous_content_child.
  components/style/gecko/wrapper.rs
Labels: S-awaiting-merge

#20483 Cleanup ports/servo to only rely on libservo
  Cargo.lock
  ports/servo/Cargo.toml
  ports/servo/browser.rs
  ports/servo/glutin_app/keyutils.rs
  ports/servo/glutin_app/mod.rs
  ports/servo/glutin_app/window.rs
  ports/servo/main.rs
Labels: S-tests-failed
