Repository servo/servo, pull requests merged in 2018-11, with the labels that each got.

#22066 Magic Leap URL bar
  ports/libmlservo/src/lib.rs
  support/magicleap/Servo2D/code/inc/Servo2D.h
  support/magicleap/Servo2D/code/src/Servo2D.cpp
Labels: S-awaiting-merge

#22060 Add a build switch to disable the native bluetooth backend.
  components/bluetooth/Cargo.toml
  components/servo/Cargo.toml
  ports/servo/Cargo.toml
  python/servo/build_commands.py
Labels: S-awaiting-merge

#21914 Use pixels::get_rect in CanvasData::draw_image
  components/canvas/canvas_data.rs
Labels: S-awaiting-merge

#22076 Support scrolling in Magic Leap Servo
  ports/libmlservo/src/lib.rs
  support/magicleap/Servo2D/code/inc/Servo2D.h
  support/magicleap/Servo2D/code/src/Servo2D.cpp
Labels: P-magic leap, S-awaiting-merge

#22084 Handle default empty sequence values
  components/script/dom/bindings/codegen/CodegenRust.py
  components/script/dom/testbinding.rs
  components/script/dom/webidls/TestBinding.webidl
Labels: S-awaiting-merge

#22107 Update to new ServiceWorker spec link
  components/script/dom/serviceworkerglobalscope.rs
Labels: S-awaiting-merge

#22109 Sync WPT with upstream (04-11-2018)
  tests/wpt/metadata/css/compositing/mix-blend-mode/mix-blend-mode-animation.html.ini
  tests/wpt/metadata/css/css-transitions/transitions-animatable-properties-01.html.ini
  tests/wpt/metadata/html/browsers/browsing-the-web/navigating-across-documents/006.html.ini
  tests/wpt/metadata/html/browsers/history/the-history-interface/traverse_the_history_1.html.ini
  tests/wpt/metadata/html/browsers/history/the-history-interface/traverse_the_history_5.html.ini
  tests/wpt/metadata/html/browsers/history/the-location-interface/location-protocol-setter-non-broken.html.ini
  tests/wpt/metadata/html/semantics/embedded-content/the-img-element/non-active-document.html.ini
  tests/wpt/metadata/html/semantics/interactive-elements/the-details-element/toggleEvent.html.ini
  tests/wpt/metadata/performance-timeline/webtiming-resolution.any.js.ini
  tests/wpt/metadata/quirks/unitless-length/no-quirks.html.ini
  tests/wpt/metadata/url/urlencoded-parser.any.js.ini
  tests/wpt/metadata/webaudio/the-audio-api/the-analysernode-interface/realtimeanalyser-fft-scaling.html.ini
  tests/wpt/mozilla/meta/mozilla/paint_timing.html.ini
  tests/wpt/web-platform-tests/css/css-position/inheritance.html
  tests/wpt/web-platform-tests/mediacapture-record/MediaRecorder-error.html
  tests/wpt/web-platform-tests/webrtc-identity/RTCPeerConnection-constructor.html
  tests/wpt/web-platform-tests/webrtc/RTCPeerConnection-addTrack.https.html
  tests/wpt/web-platform-tests/webrtc/RTCPeerConnection-constructor.html
  tests/wpt/web-platform-tests/webrtc/RTCPeerConnection-createAnswer.html
  tests/wpt/web-platform-tests/webrtc/RTCPeerConnection-createOffer-offerToReceive.html
  tests/wpt/web-platform-tests/webrtc/RTCPeerConnection-createOffer.html
  tests/wpt/web-platform-tests/webrtc/RTCPeerConnection-helper.js
  tests/wpt/web-platform-tests/webrtc/RTCPeerConnection-setLocalDescription-answer.html
  tests/wpt/web-platform-tests/webrtc/RTCPeerConnection-setLocalDescription-offer.html
  tests/wpt/web-platform-tests/webrtc/RTCPeerConnection-setLocalDescription-pranswer.html
  tests/wpt/web-platform-tests/webrtc/RTCPeerConnection-setLocalDescription.html
  tests/wpt/web-platform-tests/webrtc/RTCPeerConnection-setRemoteDescription-answer.html
  tests/wpt/web-platform-tests/webrtc/RTCPeerConnection-setRemoteDescription-pranswer.html
  tests/wpt/web-platform-tests/webrtc/RTCPeerConnection-setRemoteDescription-rollback.html
  tests/wpt/web-platform-tests/webrtc/RTCPeerConnection-setRemoteDescription.html
  tests/wpt/web-platform-tests/webrtc/RTCRtpReceiver-getParameters.html
  tests/wpt/web-platform-tests/webrtc/RTCRtpReceiver-getStats.https.html
  tests/wpt/web-platform-tests/webrtc/RTCRtpSender-getStats.https.html
  tests/wpt/web-platform-tests/webrtc/RTCRtpTransceiver.https.html
  tests/wpt/web-platform-tests/webrtc/RTCSctpTransport-constructor.html
  tests/wpt/web-platform-tests/webrtc/RTCSctpTransport-maxMessageSize.html
  tests/wpt/web-platform-tests/webrtc/getstats.html
  tests/wpt/web-platform-tests/webrtc/legacy/README.txt
  tests/wpt/web-platform-tests/webrtc/legacy/RTCPeerConnection-createOffer-offerToReceive.html
  tests/wpt/web-platform-tests/webrtc/legacy/RTCRtpTransceiver-with-OfferToReceive-options.https.html
  tests/wpt/web-platform-tests/webrtc/legacy/onaddstream.https.html
  tests/wpt/web-platform-tests/webrtc/no-media-call.html
  tests/wpt/web-platform-tests/webrtc/protocol/jsep-initial-offer.https.html
  tests/wpt/web-platform-tests/webrtc/protocol/video-codecs.https.html
Labels: S-awaiting-merge

#22097 Unused scroll
  components/compositing/compositor.rs
Labels: S-awaiting-merge

#22051 Update Constellation to track each browser's focused browsing context
  components/constellation/constellation.rs
Labels: S-awaiting-merge

#22116 Update gleam.
  Cargo.lock
Labels: S-awaiting-merge

#22103 Use a BTreeMap to store formdata
  components/malloc_size_of/lib.rs
  components/script/dom/formdata.rs
  tests/wpt/metadata/url/urlencoded-parser.any.js.ini
Labels: S-awaiting-merge

#22112 Implement WEBGL_color_buffer_float and EXT_color_buffer_half_float
  components/script/dom/webgl_extensions/ext/extcolorbufferhalffloat.rs
  components/script/dom/webgl_extensions/ext/mod.rs
  components/script/dom/webgl_extensions/ext/oestexturefloat.rs
  components/script/dom/webgl_extensions/ext/oestexturehalffloat.rs
  components/script/dom/webgl_extensions/ext/webglcolorbufferfloat.rs
  components/script/dom/webgl_extensions/extensions.rs
  components/script/dom/webglrenderbuffer.rs
  components/script/dom/webglrenderingcontext.rs
  components/script/dom/webidls/EXTColorBufferHalfFloat.webidl
  components/script/dom/webidls/WEBGLColorBufferFloat.webidl
  tests/wpt/webgl/meta/conformance/extensions/oes-texture-float.html.ini
  tests/wpt/webgl/meta/conformance/extensions/oes-texture-half-float.html.ini
Labels: S-awaiting-merge

#22092 Count threads at shutdown, warn if not all finished and optionally block
  Cargo.lock
  components/config/opts.rs
  ports/servo/Cargo.toml
  ports/servo/build.rs
  ports/servo/platform/macos/count_threads.c
  ports/servo/platform/macos/mod.rs
Labels: S-awaiting-merge

#22117 Add magicleap builder
  etc/ci/buildbot_steps.yml
Labels: P-magic leap, S-blocked-on-external, S-tests-failed

#22120 Replace http with https in docs
  CONTRIBUTING.md
  README.md
  components/script/docs/JS-Servos-only-GC.md
  components/style/servo/restyle_damage.rs
  docs/HACKING_QUICKSTART.md
  docs/components/style.md
  etc/doc.servo.org/README.md
Labels: S-awaiting-merge

#22122 Consistent servo-deps download URL
  .travis.yml
  python/servo/build_commands.py
  support/android/openssl.makefile
  support/linux/gstreamer/gstreamer.sh
  support/magicleap/openssl.sh
Labels: S-awaiting-merge

#22119 Update Firefox version in user agent string
  components/config/opts.rs
Labels: S-awaiting-merge

#22125 Download buildbot metadata via https
  etc/ci/performance/download_buildbot_timings.py
Labels: S-awaiting-merge

#22074 Update webrender.
  Cargo.lock
  components/gfx/Cargo.toml
  components/gfx/platform/windows/font.rs
  components/layout/display_list/webrender_helpers.rs
  tests/wpt/metadata/css/css-backgrounds/border-image-width-008.html.ini
  tests/wpt/mozilla/meta/css/text_node_opacity.html.ini
Labels: S-awaiting-merge

#22127 Connect to intermittent trackers via https
  python/servo/testing_commands.py
Labels: S-awaiting-merge

#22129 HTMLMediaElement - use media element instead of dom manipulation task…
  components/script/dom/htmlmediaelement.rs
Labels: S-awaiting-merge

#22136 Correct select all
  components/script/textinput.rs
  tests/unit/script/textinput.rs
Labels: S-awaiting-merge

#22141 Hint ./mach fmt
  python/servo/testing_commands.py
Labels: S-awaiting-merge

#22144 Fix downloading huge files (broken since hyperup)
  components/net/connector.rs
Labels: S-tests-failed

#22151 Update rayon-core
  Cargo.lock
Labels: S-awaiting-merge

#22095 Add icon for launching Magic Leap Servo
  support/magicleap/Servo2D/Icon/Model/Model_UFO.fbx
  support/magicleap/Servo2D/Icon/Model/Model_UFO.kmat
  support/magicleap/Servo2D/Icon/Model/Model_UFO_Albedo.png
  support/magicleap/Servo2D/Icon/Model/Model_UFO_Albedo_Ring.png
  support/magicleap/Servo2D/Icon/Portal/InsidePortal_SkySphere.fbx
  support/magicleap/Servo2D/Icon/Portal/InsidePortal_SkySphere.kmat
  support/magicleap/Servo2D/Icon/Portal/InsidePortal_SkySphere.png
  support/magicleap/Servo2D/manifest.xml
Labels: P-magic leap, S-awaiting-merge

#22153 Sync WPT with upstream (08-11-2018)
  tests/wpt/metadata/css/CSS2/floats/computed-float-position-absolute.html.ini
  tests/wpt/metadata/encoding/single-byte-decoder.html.ini
  tests/wpt/metadata/html/browsers/history/the-history-interface/traverse_the_history_1.html.ini
  tests/wpt/metadata/html/browsers/history/the-history-interface/traverse_the_history_5.html.ini
  tests/wpt/metadata/html/semantics/embedded-content/media-elements/event_timeupdate_noautoplay.html.ini
  tests/wpt/metadata/html/semantics/embedded-content/the-img-element/environment-changes/viewport-change.html.ini
  tests/wpt/metadata/html/semantics/embedded-content/the-img-element/sizes/parse-a-sizes-attribute-standards-mode.html.ini
  tests/wpt/metadata/html/semantics/interactive-elements/the-details-element/toggleEvent.html.ini
  tests/wpt/metadata/quirks/unitless-length/limited-quirks.html.ini
  tests/wpt/metadata/quirks/unitless-length/quirks.html.ini
  tests/wpt/metadata/webaudio/the-audio-api/the-analysernode-interface/realtimeanalyser-fft-scaling.html.ini
  tests/wpt/metadata/webaudio/the-audio-api/the-mediaelementaudiosourcenode-interface/cors-check.https.html.ini
  tests/wpt/metadata/webaudio/the-audio-api/the-mediaelementaudiosourcenode-interface/no-cors.https.html.ini
  tests/wpt/metadata/workers/semantics/multiple-workers/005.html.ini
  tests/wpt/web-platform-tests/css/CSS2/floats/computed-float-position-absolute.html
  tests/wpt/web-platform-tests/css/css-scoping/slotted-parsing.html
  tests/wpt/web-platform-tests/css/css-scoping/slotted-placeholder-ref.html
  tests/wpt/web-platform-tests/css/css-scoping/slotted-placeholder.html
  tests/wpt/web-platform-tests/css/css-transforms/parsing/scale-parsing-valid.html
  tests/wpt/web-platform-tests/css/filter-effects/META.yml
  tests/wpt/web-platform-tests/html/semantics/forms/the-input-element/type-change-state.html
  tests/wpt/web-platform-tests/payment-request/META.yml
  tests/wpt/web-platform-tests/resources/chromium/webxr-test.js
  tests/wpt/web-platform-tests/tools/wpt/requirements.txt
  tests/wpt/web-platform-tests/tools/wptrunner/requirements_sauce.txt
  tests/wpt/web-platform-tests/web-animations/animation-model/animation-types/property-types.js
  tests/wpt/web-platform-tests/webaudio/js/worklet-recorder.js
  tests/wpt/web-platform-tests/webaudio/resources/4ch-440.wav
  tests/wpt/web-platform-tests/webaudio/the-audio-api/the-audioparam-interface/event-insertion.html
  tests/wpt/web-platform-tests/webaudio/the-audio-api/the-mediaelementaudiosourcenode-interface/cors-check.https.html
  tests/wpt/web-platform-tests/webaudio/the-audio-api/the-mediaelementaudiosourcenode-interface/no-cors.https.html
  tests/wpt/web-platform-tests/webdriver/tests/element_click/interactability.py
Labels: S-awaiting-merge

#22155 Update servo-tidy.toml
  servo-tidy.toml
Labels: S-awaiting-merge

#22098 Update uuid
  Cargo.lock
  components/bluetooth/Cargo.toml
  components/net/Cargo.toml
  components/net/http_loader.rs
  components/net/tests/fetch.rs
  components/net_traits/Cargo.toml
  components/rand/Cargo.toml
  components/script/Cargo.toml
  components/script/dom/baseaudiocontext.rs
  components/script/dom/node.rs
  components/script/dom/url.rs
  components/url/Cargo.toml
  components/webdriver_server/Cargo.toml
Labels: S-tests-failed

#22156 Add a transparent hit-testing rectangle for scrollable block content.
  components/layout/display_list/builder.rs
Labels: S-awaiting-merge

#22172 Fix wrong spec link in align specified value
  components/style/values/specified/align.rs
Labels: S-awaiting-merge

#22166 Add gstreamer and gstreamer-vaapi to Arch Linux dependencies
  README.md
Labels: S-awaiting-merge

#22180 Package and release the Servo magicleap app
  etc/ci/buildbot_steps.yml
  python/servo/command_base.py
  python/servo/package_commands.py
Labels: A-build, P-magic leap, S-awaiting-merge

#22165 Enable old glyph assertion
  components/gfx/text/glyph.rs
Labels: S-awaiting-merge

#22171 Update webidl of ServiceWorkerRegistration
  components/script/dom/serviceworkerregistration.rs
  components/script/dom/webidls/ServiceWorkerRegistration.webidl
Labels: S-awaiting-merge

#22175 Fix linux-rel-intermittent build.
  etc/ci/buildbot_steps.yml
Labels: S-awaiting-merge

#22196 Add only one architecture per apk
  support/android/apk/servoapp/build.gradle
Labels: S-awaiting-merge

#22191 Update webidl of ServiceWorkerGlobalScope
  components/script/dom/serviceworkerglobalscope.rs
  components/script/dom/webidls/ServiceWorkerGlobalScope.webidl
Labels: S-awaiting-merge

#22210 Add debuggable flag to magicleap taildata
  python/servo/package_commands.py
Labels: A-build, P-magic leap, S-awaiting-merge

#22176 Don't try to use test-css command in CI.
  etc/ci/check_intermittents.sh
Labels: S-awaiting-merge

#22206 Use a laser pointer rather than the trackpad to control web content
  ports/libmlservo/src/lib.rs
  support/magicleap/Servo2D/Servo2D.mlproject
  support/magicleap/Servo2D/code/inc.gen/scenesGen.h
  support/magicleap/Servo2D/code/inc/Servo2D.h
  support/magicleap/Servo2D/code/src.gen/scenesGen.cpp
  support/magicleap/Servo2D/code/src/Servo2D.cpp
  support/magicleap/Servo2D/manifest.xml
  support/magicleap/Servo2D/scenes/Servo2D.design
  support/magicleap/Servo2D/scenes/Servo2D.scene.xml
Labels: P-magic leap, S-awaiting-merge

#22178 Properly cancel looping before triggering another drawing loop
  support/android/apk/servoview/src/main/java/org/mozilla/servoview/ServoView.java
Labels: S-awaiting-merge

#22214 Add GetShaderPrecisionFormat argument validation
  components/script/dom/webglrenderingcontext.rs
Labels: S-awaiting-merge

#22209 Update image related dependencies
  Cargo.lock
  components/compositing/Cargo.toml
  components/net_traits/Cargo.toml
  components/script/Cargo.toml
  components/webdriver_server/Cargo.toml
  ports/servo/Cargo.toml
  servo-tidy.toml
  tests/wpt/metadata/css/css-backgrounds/background-repeat/background-repeat-round-roundup.xht.ini
  tests/wpt/metadata/css/css-backgrounds/border-image-width-008.html.ini
Labels: S-awaiting-merge

#22217 Remove duplicate code
  components/net_traits/request.rs
Labels: S-awaiting-merge

#22224 Forward WebDriver CompositionEvent
  Cargo.lock
  components/atoms/static_atoms.txt
  components/constellation/constellation.rs
  components/script/Cargo.toml
  components/script/dom/compositionevent.rs
  components/script/dom/document.rs
  components/script/dom/htmlinputelement.rs
  components/script/dom/htmltextareaelement.rs
  components/script/script_thread.rs
  components/script/textinput.rs
  components/script_traits/lib.rs
  components/webdriver_server/lib.rs
Labels: S-awaiting-merge

#22231 Fix unused import warning in new Rust Nightly
  components/script/lib.rs
Labels: S-awaiting-merge

#22227 Implement Audio constructor
  components/script/dom/htmlaudioelement.rs
  components/script/dom/webidls/HTMLAudioElement.webidl
  tests/wpt/metadata/html/dom/interfaces.https.html.ini
  tests/wpt/metadata/html/semantics/embedded-content/media-elements/loading-the-media-resource/resource-selection-invoke-audio-constructor-no-src.html.ini
  tests/wpt/metadata/html/semantics/embedded-content/media-elements/loading-the-media-resource/resource-selection-invoke-audio-constructor.html.ini
  tests/wpt/metadata/html/semantics/embedded-content/media-elements/playing-the-media-resource/pause-remove-from-document.html.ini
  tests/wpt/metadata/html/semantics/embedded-content/the-audio-element/__dir__.ini
  tests/wpt/metadata/html/semantics/embedded-content/the-audio-element/audio_constructor.html.ini
  tests/wpt/mozilla/meta/MANIFEST.json
  tests/wpt/mozilla/tests/mozilla/interfaces.html
Labels: S-awaiting-merge

#22093 HTMLMediaElement played attribute
  components/script/dom/htmlmediaelement.rs
  components/script/dom/timeranges.rs
  components/script/dom/webidls/HTMLMediaElement.webidl
  tests/wpt/metadata/html/dom/interfaces.https.html.ini
Labels: S-awaiting-merge

#22229 Add support for touch events on Android
  ports/libsimpleservo/src/api.rs
  ports/libsimpleservo/src/capi.rs
  ports/libsimpleservo/src/jniapi.rs
  support/android/apk/servoview/src/main/java/org/mozilla/servoview/JNIServo.java
  support/android/apk/servoview/src/main/java/org/mozilla/servoview/Servo.java
  support/android/apk/servoview/src/main/java/org/mozilla/servoview/ServoView.java
Labels: S-awaiting-merge

#22233 Make Taskcluster tasks show up on Treeherder
  .taskcluster.yml
  etc/taskcluster/decision_task.py
  etc/taskcluster/decisionlib.py
Labels: S-awaiting-merge

#22246 Handle more config changes
  support/android/apk/servoapp/src/main/AndroidManifest.xml
Labels: S-awaiting-merge

#22249 Update public_domains.txt
  resources/public_domains.txt
Labels: S-tests-failed

#22239 shutdown synchronously
  support/android/apk/servoview/src/main/java/org/mozilla/servoview/Servo.java
  support/android/apk/servoview/src/main/java/org/mozilla/servoview/ServoSurface.java
  support/android/apk/servoview/src/main/java/org/mozilla/servoview/ServoView.java
Labels: S-awaiting-merge

#22234 Fix android GL crash
  components/canvas/webgl_thread.rs
Labels: S-awaiting-merge

#22245 Make it possible to reset options
  components/config/opts.rs
  components/servo/lib.rs
Labels: S-awaiting-merge

#21673 Add background hang monitor
  Cargo.lock
  components/background_hang_monitor/Cargo.toml
  components/background_hang_monitor/background_hang_monitor.rs
  components/background_hang_monitor/lib.rs
  components/background_hang_monitor/sampler.rs
  components/background_hang_monitor/sampler_linux.rs
  components/background_hang_monitor/sampler_mac.rs
  components/background_hang_monitor/sampler_windows.rs
  components/background_hang_monitor/tests/hang_monitor_tests.rs
  components/constellation/Cargo.toml
  components/constellation/constellation.rs
  components/constellation/pipeline.rs
  components/layout_thread/lib.rs
  components/layout_traits/lib.rs
  components/msg/constellation_msg.rs
  components/script/script_thread.rs
  components/script_layout_interface/message.rs
  components/script_traits/lib.rs
  components/servo/Cargo.toml
  components/servo/lib.rs
  etc/ci/check_dynamic_symbols.py
  python/servo/build_commands.py
  python/servo/testing_commands.py
Labels: S-awaiting-merge

#22237 Update webrender
  Cargo.lock
  components/canvas/canvas_data.rs
  components/canvas/webgl_thread.rs
  components/compositing/compositor.rs
  components/compositing/compositor_thread.rs
  components/compositing/windowing.rs
  components/embedder_traits/lib.rs
  components/layout/display_list/border.rs
  components/layout/display_list/builder.rs
  components/layout/display_list/webrender_helpers.rs
  components/net/image_cache.rs
  components/script/dom/htmlmediaelement.rs
  components/script/dom/screen.rs
  components/script/dom/window.rs
  components/script_traits/lib.rs
  components/script_traits/script_msg.rs
  components/webdriver_server/lib.rs
  ports/libmlservo/src/lib.rs
  ports/libsimpleservo/src/api.rs
  ports/servo/glutin_app/window.rs
Labels: S-awaiting-merge, S-blocked-on-external

#22277 Put every Android build artefact in target/android/
  etc/ci/check_dynamic_symbols.py
  etc/taskcluster/decision_task.py
  python/servo/build_commands.py
  python/servo/command_base.py
  python/servo/package_commands.py
  support/android/apk/build.gradle
  support/android/apk/servoapp/build.gradle
  support/android/apk/servoview/build.gradle
  support/magicleap/README.md
  support/magicleap/Servo2D/Servo2D.mabu
Labels: S-awaiting-merge

#22281 Instructions for checking magicleap builds on linux
  python/servo/build_commands.py
Labels: S-tests-failed

#22244 Change Response's statusText default value from 'Ok' to an empty string
  components/net/fetch/methods.rs
  components/net_traits/lib.rs
  components/net_traits/response.rs
  components/script/dom/webidls/Response.webidl
  tests/wpt/metadata/fetch/api/response/response-clone.html.ini
  tests/wpt/metadata/fetch/api/response/response-init-001.html.ini
Labels: S-awaiting-merge

#22310 Update env_logger to 0.6
  Cargo.lock
  components/config/Cargo.toml
  components/servo/Cargo.toml
Labels: S-awaiting-merge

#22323 Don’t run warnings into errors when trying Nightly
  etc/taskcluster/decision_task.py
Labels: S-awaiting-merge

#22085 Update syn
  Cargo.lock
  components/deny_public_fields/Cargo.toml
  components/dom_struct/Cargo.toml
  components/domobject_derive/Cargo.toml
  components/domobject_derive/lib.rs
  components/jstraceable_derive/Cargo.toml
  components/jstraceable_derive/lib.rs
  components/malloc_size_of_derive/Cargo.toml
  components/malloc_size_of_derive/lib.rs
  components/style/Cargo.toml
  components/style_derive/Cargo.toml
  components/style_derive/animate.rs
  components/style_derive/cg.rs
  components/style_derive/compute_squared_distance.rs
  components/style_derive/lib.rs
  components/style_derive/parse.rs
  components/style_derive/specified_value_info.rs
  components/style_derive/to_animated_value.rs
  components/style_derive/to_animated_zero.rs
  components/style_derive/to_computed_value.rs
  components/style_derive/to_css.rs
  servo-tidy.toml
Labels: S-awaiting-merge

#22322 Remove extra backslash from Gstreamer info added to the PATH on Windows
  support/windows/Servo.wxs.mako
Labels: S-tests-failed
