Repository servo/servo, pull requests merged in 2018-08, with the labels that each got.

#21282 Code style: Use canonical naming and formatting
  ports/servo/browser.rs
Labels: S-tests-failed

#21199 Publish a AAR with servoview
  python/servo/package_commands.py
  support/android/apk/build.gradle
  support/android/apk/jni/Android.mk
  support/android/apk/jni/Application.mk
  support/android/apk/servoapp/build.gradle
  support/android/apk/servoapp/src/main/java/com/mozilla/servo/MainActivity.java
  support/android/apk/servoview/build.gradle
  support/android/apk/servoview/proguard-rules.pro
  support/android/apk/servoview/src/googlevr/AndroidManifest.xml
  support/android/apk/servoview/src/main/AndroidManifest.xml
  support/android/apk/servoview/src/main/java/com/mozilla/servoview/NativeServo.java
  support/android/apk/servoview/src/main/java/com/mozilla/servoview/ServoGLRenderer.java
  support/android/apk/servoview/src/main/java/com/mozilla/servoview/ServoView.java
  support/android/apk/servoview/src/main/res/values/strings.xml
  support/android/apk/servoview/src/oculusvr/AndroidManifest.xml
  support/android/apk/settings.gradle
Labels: S-awaiting-merge

#21308 Android: Fix JSON error when no arguments are passed
  ports/libsimpleservo/src/api.rs
Labels: S-tests-failed

#21301 Do not manually keep the modifiers state
  Cargo.lock
  ports/servo/Cargo.toml
  ports/servo/glutin_app/keyutils.rs
  ports/servo/glutin_app/window.rs
  ports/servo/non_android_main.rs
Labels: S-awaiting-merge

#21309 Actually clean all build artifacts.
  etc/ci/clean_build_artifacts.sh
Labels: S-tests-failed

#21316 mach: Avoid python error when there's no cargo cache.
  python/servo/bootstrap_commands.py
Labels: S-tests-failed

#21324 Properly set initial values for WebGL texture filters
  components/canvas_traits/webgl.rs
  components/script/dom/webglrenderingcontext.rs
  components/script/dom/webgltexture.rs
Labels: S-awaiting-merge

#21335 Merge code from Draw* and Draw*Instanced methods
  components/canvas/webgl_thread.rs
  components/canvas_traits/webgl.rs
  components/script/dom/webglrenderingcontext.rs
Labels: S-tests-failed

#21334 Upload AAR alongside the APK
  python/servo/package_commands.py
Labels: S-awaiting-merge

#21223 Webrender update
  Cargo.lock
  components/canvas/Cargo.toml
  components/canvas_traits/Cargo.toml
  components/compositing/Cargo.toml
  components/config/Cargo.toml
  components/constellation/Cargo.toml
  components/geometry/Cargo.toml
  components/gfx/Cargo.toml
  components/layout/Cargo.toml
  components/layout_thread/Cargo.toml
  components/malloc_size_of/Cargo.toml
  components/script/Cargo.toml
  components/script_layout_interface/Cargo.toml
  components/script_traits/Cargo.toml
  components/servo/Cargo.toml
  components/style/Cargo.toml
  components/style_traits/Cargo.toml
  components/webdriver_server/Cargo.toml
  components/webvr/Cargo.toml
  ports/servo/Cargo.toml
  tests/unit/script/Cargo.toml
  tests/unit/style/Cargo.toml
Labels: S-tests-failed

#21302 Fix page size when device-pixel-ratio is set manually
  ports/servo/glutin_app/window.rs
Labels: S-tests-failed

#21218 Use a structured clone holder to store rooted clones
  components/script/dom/bindings/structuredclone.rs
Labels: S-awaiting-merge

#21347 Update README.md
  README.md
Labels: S-awaiting-merge

#21345 Add --cap-lints warn to rustdoc script
  etc/rustdoc-with-private
Labels: S-awaiting-merge

#21346 Remove unused compositing dependency from bluetooth crate
  Cargo.lock
  components/bluetooth/Cargo.toml
Labels: S-tests-failed

#21360 Add more methods to ServoSurface and relabel the inner surface class name
  support/android/apk/servoview/src/main/java/com/mozilla/servoview/ServoSurface.java
Labels: S-awaiting-merge

#21365 Avoid crash using freetype in debug android builds
  components/gfx/font.rs
  components/gfx/platform/freetype/font.rs
  components/gfx/platform/macos/font.rs
  components/gfx/platform/windows/font.rs
Labels: S-awaiting-merge

#21368 Upgrade bitflags to latest version
  Cargo.lock
Labels: S-awaiting-merge

#21361 Compile less
  support/android/apk/servoview/build.gradle
Labels: S-awaiting-merge

#21364 Avoid crash when pressing stop button on Android
  ports/libsimpleservo/src/api.rs
  ports/libsimpleservo/src/capi.rs
  ports/libsimpleservo/src/jniapi.rs
Labels: S-awaiting-merge

#21366 Add ndk-stack mach command
  python/servo/devenv_commands.py
Labels: S-tests-failed

#21376 Add rustfmt command to devenv commands
  python/servo/devenv_commands.py
Labels: S-awaiting-merge, S-fails-tidy

#21384 Sync WPT with upstream (10-08-2018)
  tests/wpt/metadata/css/CSS2/floats/floats-in-table-caption-001.html.ini
  tests/wpt/metadata/css/CSS2/positioning/abspos-inline-007.xht.ini
  tests/wpt/metadata/css/css-text/i18n/css3-text-line-break-opclns-050.html.ini
  tests/wpt/metadata/css/css-text/i18n/css3-text-line-break-opclns-054.html.ini
  tests/wpt/metadata/css/css-text/i18n/css3-text-line-break-opclns-059.html.ini
  tests/wpt/metadata/css/css-text/i18n/css3-text-line-break-opclns-164.html.ini
  tests/wpt/metadata/css/css-text/i18n/css3-text-line-break-opclns-165.html.ini
  tests/wpt/metadata/css/css-values/vh_not_refreshing_on_chrome.html.ini
  tests/wpt/metadata/encoding/idlharness.any.js.ini
  tests/wpt/metadata/fetch/api/abort/general.any.js.ini
  tests/wpt/metadata/fetch/api/idl.any.js.ini
  tests/wpt/metadata/fetch/cors-rfc1918/idlharness.tentative.any.js.ini
  tests/wpt/metadata/hr-time/idlharness.any.js.ini
  tests/wpt/metadata/html/semantics/embedded-content/image-maps/image-map-processing-model/hash-name-reference.html.ini
  tests/wpt/metadata/html/webappapis/microtask-queuing/queue-microtask-exceptions.any.js.ini
  tests/wpt/metadata/html/webappapis/microtask-queuing/queue-microtask.any.js.ini
  tests/wpt/metadata/performance-timeline/idlharness.any.js.ini
  tests/wpt/metadata/url/urlencoded-parser.any.js.ini
  tests/wpt/metadata/websockets/basic-auth.any.js.ini
  tests/wpt/metadata/xhr/xmlhttprequest-sync-default-feature-policy.sub.html.ini
  tests/wpt/mozilla/meta/css/transition_calc_implicit.html.ini
  tests/wpt/mozilla/meta/webgl/conformance-1.0.3/conformance/glsl/misc/shader-with-non-reserved-words.html.ini
  tests/wpt/web-platform-tests/background-fetch/resources/sw.js
  tests/wpt/web-platform-tests/background-fetch/resources/utils.js
  tests/wpt/web-platform-tests/background-fetch/service_workers/sw-helpers.js
  tests/wpt/web-platform-tests/background-fetch/service_workers/sw-update-ui.js
  tests/wpt/web-platform-tests/background-fetch/service_workers/sw.js
  tests/wpt/web-platform-tests/background-fetch/update-ui.https.window.js
  tests/wpt/web-platform-tests/budget-api/idlharness.https.any.js
  tests/wpt/web-platform-tests/budget-api/interfaces.any.js
  tests/wpt/web-platform-tests/css/CSS2/positioning/abspos-inline-007-ref.xht
  tests/wpt/web-platform-tests/css/CSS2/positioning/abspos-inline-007.xht
  tests/wpt/web-platform-tests/css/css-backgrounds/background-attachment-local/reftest.list
  tests/wpt/web-platform-tests/css/css-writing-modes/relpos-inline-overflowing-block-vrl.html
  tests/wpt/web-platform-tests/infrastructure/server/context.any.js
  tests/wpt/web-platform-tests/infrastructure/server/secure-context.https.any.js
  tests/wpt/web-platform-tests/svg/render/reftests/blending-svg-foreign-object-ref.html
  tests/wpt/web-platform-tests/svg/render/reftests/blending-svg-foreign-object.html
  tests/wpt/web-platform-tests/svg/render/reftests/blending-svg-root-ref.html
  tests/wpt/web-platform-tests/svg/render/reftests/blending-svg-root.html
  tests/wpt/web-platform-tests/tools/manifest/item.py
  tests/wpt/web-platform-tests/tools/manifest/sourcefile.py
  tests/wpt/web-platform-tests/tools/manifest/tests/test_item.py
  tests/wpt/web-platform-tests/tools/manifest/tests/test_sourcefile.py
  tests/wpt/web-platform-tests/tools/serve/serve.py
Labels: S-tests-failed

#21391 Android: Use info! instead of debug!
  ports/libsimpleservo/src/api.rs
  ports/libsimpleservo/src/gl_glue.rs
  ports/libsimpleservo/src/jniapi.rs
Labels: S-awaiting-merge

#21394 Remove unnecessary CEReactions.
  components/script/dom/webidls/HTMLTextAreaElement.webidl
Labels: S-awaiting-merge

#21404 Make it possible to use a custom AAR to build servoapp
  support/android/apk/servoapp/build.gradle
  support/android/apk/servoview-local/build.gradle
  support/android/apk/settings.gradle
Labels: S-awaiting-merge

#21405 Behave properly when app is suspended
  ports/libsimpleservo/src/api.rs
  ports/libsimpleservo/src/capi.rs
  ports/libsimpleservo/src/jniapi.rs
  support/android/apk/servoapp/src/main/java/com/mozilla/servo/MainActivity.java
  support/android/apk/servoview/src/main/java/com/mozilla/servoview/JNIServo.java
  support/android/apk/servoview/src/main/java/com/mozilla/servoview/Servo.java
  support/android/apk/servoview/src/main/java/com/mozilla/servoview/ServoView.java
Labels: S-awaiting-merge

#21420 Add needed gstreamer packages for Gentoo build
  README.md
Labels: S-awaiting-merge

#21421 Add configuration for using ./wpt serve
  tests/wpt/aliases
Labels: S-awaiting-merge

#21386 Replace servo-websocket by ws
  Cargo.lock
  components/net/Cargo.toml
  components/net/lib.rs
  components/net/websocket_loader.rs
  tests/wpt/metadata/websockets/interfaces/WebSocket/close/close-connecting.html.ini
Labels: S-awaiting-merge

#21436 The WS protocols should be case sensitive, not insensitive
  components/net/websocket_loader.rs
  tests/wpt/metadata/websockets/constructor/011.html.ini
Labels: S-awaiting-merge

#21427 More gstreamer dependencies
  README.md
Labels: S-awaiting-merge

#21437 Add gstreamer instructions for windows.
  README.md
Labels: S-awaiting-merge

#21428 Format component allocator
  components/allocator/lib.rs
Labels: S-awaiting-merge

#21422 Add macOS gstreamer setup
  README.md
Labels: S-awaiting-merge

#21440 Format components atoms
  components/atoms/build.rs
Labels: S-awaiting-merge

#21447 README: clarify Mac keyboard shortcuts
  README.md
Labels: S-tests-failed

#21433 Clean more build artifacts.
  etc/ci/buildbot_steps.yml
Labels: S-awaiting-merge

#21454 Network: Preserve HEAD on 303 redirect
  components/net/http_loader.rs
Labels: S-tests-failed

#21434 Remove warnings about WPT syncing process.
  etc/ci/update-wpt-checkout
Labels: S-awaiting-review

#21464 Revert "build(mach): locate vs via vswhere on win32"
  mach
  mach.bat
Labels: S-tests-failed

#21439 Fix Android back button behavior
  support/android/apk/servoapp/src/main/java/com/mozilla/servo/MainActivity.java
Labels: S-awaiting-merge

#21472 Add `autoconf` as required dependency for macOS
  README.md
Labels: S-awaiting-merge

#21460 List additional keyboard shortcuts
  README.md
Labels: S-tests-failed

#21473 Handle wpt version number changes when updating the manifest.
  tests/wpt/manifestupdate.py
Labels: S-awaiting-merge

#21477 Fix zoom keybindings
  ports/servo/browser.rs
Labels: S-awaiting-merge

#21470 Update to mozjs_sys 0.60.1 to get libc++ on macOS
  Cargo.lock
Labels: S-awaiting-merge

#21430 Properly set the origin on websocket messages
  components/script/dom/dedicatedworkerglobalscope.rs
  components/script/dom/messageevent.rs
  components/script/dom/websocket.rs
  components/script/dom/window.rs
  components/script/dom/worker.rs
  tests/wpt/metadata/websockets/opening-handshake/003.html.ini
Labels: S-awaiting-merge

#21487 Remove outdated comment in stylist.rs
  components/style/stylist.rs
Labels: S-awaiting-merge

#21490 appveyor: Append to LIB variable instead of overwriting it.
  appveyor.yml
Labels: S-awaiting-merge

#21341 Properly check limit in gl.activeTexture()
  components/canvas_traits/webgl.rs
  components/script/dom/webgl_validations/tex_image_2d.rs
  components/script/dom/webglrenderingcontext.rs
Labels: S-tests-failed

#21494 Publish selectors v0.20.0
  Cargo.lock
  components/selectors/Cargo.toml
Labels: S-tests-failed

#21500 Include autoconf2.13 in readme
  README.md
Labels: S-awaiting-merge

#21514 add autoconf213 for Fedora
  README.md
Labels: S-tests-failed

#21516 Update bindgen to 0.39.0
  Cargo.lock
  components/malloc_size_of/Cargo.toml
  components/script/Cargo.toml
  components/style/Cargo.toml
Labels: S-tests-failed

#21399 Fire error when placeholder is loaded
  components/script/dom/htmlimageelement.rs
  tests/wpt/mozilla/meta/MANIFEST.json
  tests/wpt/mozilla/tests/mozilla/img_placeholder_load.html
Labels: S-tests-failed

#21529 Upgrade to rustc 1.30.0-nightly (721913067 2018-08-26)
  Cargo.lock
  components/script/lib.rs
  components/script_plugins/lib.rs
  components/script_plugins/unrooted_must_root.rs
  components/script_plugins/utils.rs
  rust-toolchain
Labels: S-awaiting-merge

#21532 Update x11-dl to pickup the fix for x11 startup crash
  Cargo.lock
Labels: S-tests-failed

#21515 Update pkg-config to avoid setting LIBPATH to point to gstreamer deps…
  Cargo.lock
  appveyor.yml
Labels: S-awaiting-merge

#21540 Fix setup instructions for Arch
  README.md
Labels: S-awaiting-merge

#21536 Upgrade to rustc 1.30.0-nightly (7061b2775 2018-08-28)
  components/script_plugins/unrooted_must_root.rs
  rust-toolchain
Labels: S-awaiting-merge

#21535 Decrease error rate of chocolatey intermittent issues
  appveyor.yml
Labels: S-tests-failed

#21547 Fedora pkg names
  README.md
Labels: S-tests-failed

#21551 Format component compositing #21373
  components/compositing/build.rs
  components/compositing/compositor.rs
  components/compositing/compositor_thread.rs
  components/compositing/gl.rs
  components/compositing/touch.rs
Labels: S-tests-failed
