Repository servo/servo, pull requests merged in 2018-10, with the labels that each got.

#21833 Fix appveyor build
  appveyor.yml
Labels: S-awaiting-merge

#21848 Remove unnecessary thread specification when flushing GL on Android.
  support/android/apk/servoview/src/main/java/com/mozilla/servoview/ServoView.java
Labels: S-awaiting-merge

#21828 Warn when using slow WebGL code path.
  components/canvas/webgl_thread.rs
Labels: S-awaiting-merge

#21826 Enable fake fillText API in nightly builds.
  resources/prefs.json
  tests/wpt/metadata/2dcontext/__dir__.ini
  tests/wpt/metadata/html/dom/interfaces.https.html.ini
Labels: S-awaiting-merge

#21851 Create a Maven repository on package
  python/servo/package_commands.py
  support/android/apk/servoview/build.gradle
Labels: S-awaiting-merge

#21842 Fix flickering on Android
  support/android/apk/servoview/src/main/java/org/mozilla/servoview/Servo.java
  support/android/apk/servoview/src/main/java/org/mozilla/servoview/ServoView.java
Labels: S-awaiting-merge

#21872 Upgrade to rustc 1.31.0-nightly (8c4ad4e9e 2018-10-04)
  components/script/dom/bindings/codegen/CodegenRust.py
  rust-toolchain
Labels: S-awaiting-merge

#21876 Support uploading maven artifacts.
  etc/ci/buildbot_steps.yml
  python/servo/package_commands.py
Labels: S-awaiting-merge

#21889 Add optional section to README for using lld-link on Windows
  README.md
Labels: S-awaiting-merge

#21785 Add framebuffer check for mark_as_dirty, #21691
  components/script/dom/webglrenderingcontext.rs
Labels: S-awaiting-merge

#21890 ServoView: Add default constructor.
  support/android/apk/servoview/src/main/java/org/mozilla/servoview/ServoView.java
Labels: S-awaiting-merge

#21895 Revert "Disable event_timeupdate_noautoplay test on mac"
  tests/wpt/metadata/html/semantics/embedded-content/media-elements/event_timeupdate_noautoplay.html.ini
Labels: S-tests-failed

#21799 Bug 1172897 - Rename Tab Actor to BrowsingContextActor
  components/devtools/actors/browsing_context.rs
  components/devtools/actors/root.rs
  components/devtools/lib.rs
Labels: S-awaiting-merge

#21594 Try to fix travis
  .travis.yml
Labels: S-awaiting-merge

#21902 Windows installer: set GStreamer installation path based on registry …
  support/windows/Servo.wxs.mako
Labels: S-awaiting-merge

#21879 Add task source for media element
  components/script/dom/htmlmediaelement.rs
  components/script/dom/window.rs
  components/script/script_thread.rs
  components/script/task_source/media_element.rs
  components/script/task_source/mod.rs
Labels: S-tests-failed

#21905 Reduce log spam for large downloads made from mach
  python/servo/util.py
Labels: S-awaiting-merge

#21904 Remove gst-plugins-ugly dep from README
  README.md
Labels: S-awaiting-merge

#21918 Taskcluster: cache ~/.gradle
  .taskcluster.yml
  etc/taskcluster/decision_task.py
Labels: S-awaiting-merge

#21915 Update servo-media
  Cargo.lock
  tests/wpt/metadata/webaudio/the-audio-api/the-analysernode-interface/realtimeanalyser-fft-scaling.html.ini
  tests/wpt/metadata/webaudio/the-audio-api/the-audiobuffersourcenode-interface/buffer-resampling.html.ini
  tests/wpt/metadata/webaudio/the-audio-api/the-biquadfilternode-interface/biquad-automation.html.ini
Labels: S-awaiting-merge

#21911 Simplify ctx.drawImage a bit
  components/canvas/canvas_paint_thread.rs
  components/script/dom/canvasrenderingcontext2d.rs
Labels: S-awaiting-merge

#21921 Use a depth buffer when embedding Servo on android.
  support/android/apk/servoview/src/main/java/org/mozilla/servoview/ServoSurface.java
Labels: S-tests-failed

#21922 Add support for StorageEvent.initstorageevent()
  components/script/dom/storageevent.rs
  components/script/dom/webidls/StorageEvent.webidl
  tests/wpt/metadata/webstorage/event_initstorageevent.html.ini
Labels: S-tests-failed

#21898 Skip css-text i18n tests.
  tests/wpt/include.ini
Labels: S-tests-failed

#21927 Remove Origin::unicode_serialization
  components/net_traits/blob_url_store.rs
  components/script/dom/eventsource.rs
  components/script/dom/htmlanchorelement.rs
  components/url/origin.rs
  tests/wpt/metadata/eventsource/eventsource-cross-origin.htm.ini
  tests/wpt/metadata/url/a-element-origin-xhtml.xhtml.ini
  tests/wpt/metadata/url/a-element-origin.html.ini
Labels: S-awaiting-merge

#21941 DevTools - add preliminary StyleSheetActor
  components/devtools/actors/browsing_context.rs
  components/devtools/actors/stylesheets.rs
  components/devtools/lib.rs
Labels: S-tests-failed

#21943 DevTools - add ListWorkers method to BrowsingContextTargetActor
  components/devtools/actors/browsing_context.rs
Labels: S-awaiting-merge

#21944 DevTools - add Interrupt method to ThreadActor
  components/devtools/actors/thread.rs
Labels: S-awaiting-merge

#21945 DevTools - add Emulation Actor
  components/devtools/actors/browsing_context.rs
  components/devtools/actors/emulation.rs
  components/devtools/lib.rs
Labels: S-tests-failed

#21950 Make android logging work for multiple println calls
  ports/libsimpleservo/src/jniapi.rs
Labels: S-awaiting-merge

#20757 style: Some animation cleanups and fixes.
  components/layout/animation.rs
  components/style/animation.rs
  components/style/matching.rs
  components/style/properties/helpers/animated_properties.mako.rs
  tests/wpt/metadata/css/css-fonts/variations/font-style-interpolation.html.ini
  tests/wpt/metadata/css/css-variables/variable-transitions-transition-property-all-before-value.html.ini
  tests/wpt/metadata/css/css-variables/variable-transitions-value-before-transition-property-all.html.ini
Labels: S-awaiting-merge

#21951 Don't strip final character of directory name for maven package.
  python/servo/package_commands.py
Labels: S-tests-failed

#21923 🐈🐈🐈 Implement basic <source> take-first-then-fail algo for HtmlMediaElement
  components/script/dom/htmlmediaelement.rs
Labels: S-awaiting-merge

#21913 Clean some temporary files from Windows packaging process
  python/servo/package_commands.py
Labels: S-awaiting-merge

#21882 Update document.open to latest spec
  components/script/dom/document.rs
  components/script/dom/webidls/Document.webidl
  tests/wpt/metadata/html/webappapis/dynamic-markup-insertion/opening-the-input-stream/001.html.ini
  tests/wpt/metadata/html/webappapis/dynamic-markup-insertion/opening-the-input-stream/005.html.ini
  tests/wpt/metadata/html/webappapis/dynamic-markup-insertion/opening-the-input-stream/008.html.ini
  tests/wpt/metadata/html/webappapis/dynamic-markup-insertion/opening-the-input-stream/009.https.html.ini
  tests/wpt/metadata/html/webappapis/dynamic-markup-insertion/opening-the-input-stream/document.open-02.html.ini
  tests/wpt/metadata/html/webappapis/dynamic-markup-insertion/opening-the-input-stream/document.open-03.html.ini
  tests/wpt/metadata/html/webappapis/dynamic-markup-insertion/opening-the-input-stream/event-listeners.window.js.ini
  tests/wpt/metadata/html/webappapis/dynamic-markup-insertion/opening-the-input-stream/quirks.window.js.ini
  tests/wpt/metadata/html/webappapis/dynamic-markup-insertion/opening-the-input-stream/readiness.window.js.ini
  tests/wpt/metadata/html/webappapis/dynamic-markup-insertion/opening-the-input-stream/url-fragment.window.js.ini
Labels: S-awaiting-merge

#21965 Return the expected response when webdriver requests a session deletion.
  components/webdriver_server/lib.rs
Labels: S-tests-failed

#21975 Correctly determine text selection direction
  components/script/textinput.rs
Labels: S-tests-failed

#21971 Revert "style: Make the transitions code make sense again."
  components/style/animation.rs
  components/style/matching.rs
  tests/wpt/metadata/css/css-fonts/variations/font-style-interpolation.html.ini
  tests/wpt/metadata/css/css-variables/variable-transitions-transition-property-all-before-value.html.ini
  tests/wpt/metadata/css/css-variables/variable-transitions-value-before-transition-property-all.html.ini
Labels: S-tests-failed

#22000 Add a workaround for a rustc ICE
  components/script/build.rs
Labels: S-awaiting-merge

#21999 Update servo-media
  Cargo.lock
  components/script/dom/htmlmediaelement.rs
  tests/wpt/metadata/html/semantics/embedded-content/media-elements/event_timeupdate_noautoplay.html.ini
  tests/wpt/metadata/html/semantics/embedded-content/media-elements/readyState_during_loadeddata.html.ini
Labels: A-content/media, S-tests-failed

#22013 Handle open URL intent on Android
  support/android/apk/servoapp/src/main/java/org/mozilla/servo/MainActivity.java
Labels: S-tests-failed

#22014 Update servo-media to fix intermittent timeouts
  Cargo.lock
  components/script/dom/htmlmediaelement.rs
Labels: S-tests-failed

#22023 Disable ImageBitmap tests
  tests/wpt/metadata/2dcontext/imagebitmap/__dir__.ini
  tests/wpt/metadata/2dcontext/imagebitmap/canvas-createImageBitmap-resize.html.ini
  tests/wpt/metadata/2dcontext/imagebitmap/canvas-createImageBitmap-video-resize.html.ini
  tests/wpt/metadata/2dcontext/imagebitmap/createImageBitmap-blob-invalidtype.html.ini
  tests/wpt/metadata/2dcontext/imagebitmap/createImageBitmap-bounds.html.ini
  tests/wpt/metadata/2dcontext/imagebitmap/createImageBitmap-drawImage.html.ini
  tests/wpt/metadata/2dcontext/imagebitmap/createImageBitmap-invalid-args.html.ini
  tests/wpt/metadata/2dcontext/imagebitmap/createImageBitmap-origin.sub.html.ini
  tests/wpt/metadata/2dcontext/imagebitmap/createImageBitmap-sizeOverflow.html.ini
  tests/wpt/metadata/2dcontext/imagebitmap/createImageBitmap-transfer.html.ini
Labels: S-awaiting-merge

#22002 Update osmesa-src
  Cargo.lock
  ports/servo/Cargo.toml
Labels: S-tests-failed

#22033 Sync WPT with upstream (27-10-2018)
  tests/wpt/metadata/FileAPI/url/url-in-tags-revoke.window.js.ini
  tests/wpt/metadata/FileAPI/url/url-with-fetch.any.js.ini
  tests/wpt/metadata/css/css-transforms/inheritance.html.ini
  tests/wpt/metadata/css/css-transitions/properties-value-inherit-001.html.ini
  tests/wpt/metadata/css/css-transitions/properties-value-inherit-002.html.ini
  tests/wpt/metadata/css/css-transitions/transitions-animatable-properties-01.html.ini
  tests/wpt/metadata/encoding/single-byte-decoder.html.ini
  tests/wpt/metadata/html/browsers/browsing-the-web/navigating-across-documents/006.html.ini
  tests/wpt/metadata/html/browsers/history/the-history-interface/traverse_the_history_3.html.ini
  tests/wpt/metadata/html/browsers/history/the-history-interface/traverse_the_history_5.html.ini
  tests/wpt/metadata/html/browsers/history/the-location-interface/location-protocol-setter-non-broken.html.ini
  tests/wpt/metadata/html/semantics/embedded-content/the-iframe-element/iframe_sandbox_block_modals-1.html.ini
  tests/wpt/metadata/html/semantics/embedded-content/the-img-element/non-active-document.html.ini
  tests/wpt/metadata/html/semantics/embedded-content/the-img-element/sizes/parse-a-sizes-attribute-width-1000px.html.ini
  tests/wpt/metadata/html/semantics/interactive-elements/the-details-element/toggleEvent.html.ini
  tests/wpt/metadata/html/syntax/parsing/DOMContentLoaded-defer.html.ini
  tests/wpt/metadata/html/webappapis/dynamic-markup-insertion/opening-the-input-stream/aborted-parser.window.js.ini
  tests/wpt/metadata/quirks/unitless-length/limited-quirks.html.ini
  tests/wpt/metadata/quirks/unitless-length/quirks.html.ini
  tests/wpt/metadata/referrer-policy/generic/iframe-inheritance.html.ini
  tests/wpt/metadata/url/urlencoded-parser.any.js.ini
  tests/wpt/mozilla/meta/mozilla/paint_timing.html.ini
  tests/wpt/mozilla/meta/mozilla/scroll_root.html.ini
  tests/wpt/mozilla/meta/mozilla/unitless-length.html.ini
  tests/wpt/web-platform-tests/css/css-transforms/inheritance.html
  tests/wpt/web-platform-tests/css/motion/inheritance.html
Labels: S-tests-failed

#22037 Sync WPT with upstream (28-10-2018)
  tests/wpt/metadata/css/css-transitions/properties-value-inherit-001.html.ini
  tests/wpt/metadata/css/css-transitions/properties-value-inherit-002.html.ini
  tests/wpt/metadata/css/css-transitions/transitions-animatable-properties-01.html.ini
  tests/wpt/metadata/css/filter-effects/parsing/filter-computed.html.ini
  tests/wpt/metadata/css/filter-effects/parsing/filter-parsing-valid.html.ini
  tests/wpt/metadata/encoding/single-byte-decoder.html.ini
  tests/wpt/metadata/fetch/cross-origin-resource-policy/fetch-in-iframe.html.ini
  tests/wpt/metadata/html/browsers/history/the-history-interface/traverse_the_history_3.html.ini
  tests/wpt/metadata/html/browsers/history/the-history-interface/traverse_the_history_5.html.ini
  tests/wpt/metadata/html/browsers/history/the-location-interface/location-protocol-setter-non-broken-weird.html.ini
  tests/wpt/metadata/html/semantics/embedded-content/the-img-element/environment-changes/viewport-change.html.ini
  tests/wpt/metadata/html/semantics/embedded-content/the-img-element/sizes/parse-a-sizes-attribute-width-1000px.html.ini
  tests/wpt/metadata/html/syntax/parsing/DOMContentLoaded-defer.html.ini
  tests/wpt/metadata/html/webappapis/dynamic-markup-insertion/opening-the-input-stream/aborted-parser.window.js.ini
  tests/wpt/metadata/html/webappapis/dynamic-markup-insertion/opening-the-input-stream/bailout-exception-vs-return-xml.window.js.ini
  tests/wpt/metadata/quirks/unitless-length/limited-quirks.html.ini
  tests/wpt/metadata/quirks/unitless-length/no-quirks.html.ini
  tests/wpt/metadata/url/urlencoded-parser.any.js.ini
  tests/wpt/metadata/workers/semantics/multiple-workers/005.html.ini
  tests/wpt/mozilla/meta/mozilla/paint_timing.html.ini
  tests/wpt/mozilla/meta/mozilla/unitless-length.html.ini
  tests/wpt/web-platform-tests/css/filter-effects/parsing/filter-computed.html
  tests/wpt/web-platform-tests/css/filter-effects/parsing/filter-parsing-invalid.html
  tests/wpt/web-platform-tests/css/filter-effects/parsing/filter-parsing-valid.html
  tests/wpt/web-platform-tests/css/support/computed-testcommon.js
  tests/wpt/web-platform-tests/payment-request/META.yml
  tests/wpt/web-platform-tests/svg/render/reftests/filter-effects-on-pattern-ref.html
  tests/wpt/web-platform-tests/svg/render/reftests/filter-effects-on-pattern.html
  tests/wpt/web-platform-tests/svg/shapes/circle-01-ref.svg
  tests/wpt/web-platform-tests/svg/shapes/circle-01.svg
  tests/wpt/web-platform-tests/svg/shapes/ellipse-09.svg
  tests/wpt/web-platform-tests/svg/shapes/rect-05-ref.svg
  tests/wpt/web-platform-tests/svg/shapes/rect-05.svg
Labels: S-tests-failed

#22040 Exit Canvas paint thread on shutdown
  components/canvas/canvas_paint_thread.rs
  components/canvas_traits/canvas.rs
  components/constellation/constellation.rs
Labels: S-awaiting-merge

#21985 Support building for Magic Leap.
  Cargo.lock
  Cargo.toml
  components/gfx/platform/freetype/android/font_list.rs
  ports/libmlservo/Cargo.toml
  ports/libmlservo/src/lib.rs
  python/servo/build_commands.py
  servo-tidy.toml
  support/magicleap/.gitignore
  support/magicleap/README.md
  support/magicleap/Servo2D/.vscode/launch.json
  support/magicleap/Servo2D/.vscode/settings.json
  support/magicleap/Servo2D/.vscode/tasks.json
  support/magicleap/Servo2D/Servo2D.mabu
  support/magicleap/Servo2D/Servo2D.mlproject
  support/magicleap/Servo2D/Servo2D.package
  support/magicleap/Servo2D/code/inc.gen/SceneDescriptor.h
  support/magicleap/Servo2D/code/inc.gen/scenesGen.h
  support/magicleap/Servo2D/code/inc/Servo2D.h
  support/magicleap/Servo2D/code/src.gen/SceneDescriptor.cpp
  support/magicleap/Servo2D/code/src.gen/scenesGen.cpp
  support/magicleap/Servo2D/code/src/Servo2D.cpp
  support/magicleap/Servo2D/code/src/main.cpp
  support/magicleap/Servo2D/code/srcsGen.comp
  support/magicleap/Servo2D/fonts.xml
  support/magicleap/Servo2D/manifest.xml
  support/magicleap/Servo2D/pipeline/cache/AssetManifest.comp
  support/magicleap/Servo2D/pipeline/lap/project.json
  support/magicleap/Servo2D/scenes.comp
  support/magicleap/Servo2D/scenes/Servo2D.design
  support/magicleap/Servo2D/scenes/Servo2D.scene.res.xml
  support/magicleap/Servo2D/scenes/Servo2D.scene.xml
  support/magicleap/fake-ld.sh
  support/magicleap/openssl.sh
  support/magicleap/toolchain.cmake
Labels: S-awaiting-merge

#22028 Add lots of derived Debug impls
  components/bluetooth_traits/lib.rs
  components/bluetooth_traits/scanfilter.rs
  components/canvas_traits/canvas.rs
  components/canvas_traits/webgl.rs
  components/canvas_traits/webgl_channel/mod.rs
  components/config/opts.rs
  components/constellation/constellation.rs
  components/gfx/text/text_run.rs
  components/msg/constellation_msg.rs
  components/net/hsts.rs
  components/net/resource_thread.rs
  components/net_traits/filemanager_thread.rs
  components/net_traits/image_cache.rs
  components/net_traits/lib.rs
  components/net_traits/request.rs
  components/net_traits/response.rs
  components/net_traits/storage_thread.rs
  components/profile_traits/mem.rs
  components/profile_traits/time.rs
  components/script_traits/lib.rs
  components/script_traits/script_msg.rs
  components/script_traits/webdriver_msg.rs
  components/webvr_traits/webvr_traits.rs
Labels: S-awaiting-merge

#22045 Get the ML port to follow hyperlinks
  ports/libmlservo/src/lib.rs
  support/magicleap/Servo2D/.vscode/settings.json
  support/magicleap/Servo2D/code/inc/Servo2D.h
  support/magicleap/Servo2D/code/src/Servo2D.cpp
Labels: P-magic leap, S-awaiting-merge

#22048 remove useless arguments from prepare_for_composite
  components/compositing/compositor.rs
  components/compositing/windowing.rs
  components/servo/lib.rs
  ports/libsimpleservo/src/api.rs
  ports/servo/glutin_app/window.rs
Labels: S-awaiting-merge

#22044 Reduce the amount of EGL buffer swapping the ML port is doing
  ports/libmlservo/src/lib.rs
  support/magicleap/Servo2D/code/src/Servo2D.cpp
Labels: P-magic leap, S-awaiting-merge

#22052 HTMLMediaElement - fire durationchange and resize iff something changes
  components/script/dom/htmlmediaelement.rs
  components/script/dom/htmlvideoelement.rs
Labels: S-awaiting-merge

#22057 Magic Leap history traversal
  ports/libmlservo/src/lib.rs
  support/magicleap/Servo2D/code/inc/Servo2D.h
  support/magicleap/Servo2D/code/src/Servo2D.cpp
Labels: P-magic leap, S-tests-failed

#22049 Implement TimeRanges interface
  components/script/dom/mod.rs
  components/script/dom/timeranges.rs
  components/script/dom/webidls/TimeRanges.webidl
  components/script/test.rs
  tests/unit/script/lib.rs
  tests/unit/script/timeranges.rs
  tests/wpt/metadata/html/dom/interfaces.https.html.ini
  tests/wpt/mozilla/meta/MANIFEST.json
  tests/wpt/mozilla/tests/mozilla/interfaces.html
Labels: S-awaiting-merge

#21983 style: Re-enable the rule that was accidentally disabled by a typo in the CSS parser.
  resources/servo.css
Labels: S-awaiting-merge
