Repository servo/servo, pull requests merged in 2018-06, with the labels that each got.

#20894 readme add llvm clang
  README.md
Labels: S-awaiting-merge

#20895 build(servo): bump up llvm to 6.0.0
  python/servo/packages.py
Labels: S-tests-failed

#20901 dom: Remove CSSStyleDeclaration.setPropertyValue/setPropertyPriority.
  components/script/dom/cssstyledeclaration.rs
  components/script/dom/webidls/CSSStyleDeclaration.webidl
  tests/wpt/metadata/css/cssom/historical.html.ini
  tests/wpt/mozilla/meta/MANIFEST.json
  tests/wpt/mozilla/tests/css/setpropertypriority.html
  tests/wpt/mozilla/tests/css/setpropertypriority_ref.html
Labels: S-tests-failed

#20905 Fix typo for worklet in globalscope
  components/script/dom/globalscope.rs
Labels: S-tests-failed

#20915 Implement EXT_shader_texture_lod
  components/script/dom/webgl_extensions/ext/extshadertexturelod.rs
  components/script/dom/webgl_extensions/ext/mod.rs
  components/script/dom/webidls/EXTShaderTextureLod.webidl
  tests/wpt/mozilla/meta/webgl/conformance-1.0.3/conformance/extensions/ext-shader-texture-lod.html.ini
Labels: S-tests-failed

#20789 Don't try to list files in directories that don't exist
  python/servo/bootstrap_commands.py
Labels: S-awaiting-merge

#20998 Change to pip dependency install invocation during virtualenv setup in build
  python/mach_bootstrap.py
Labels: S-tests-failed

#20959 Implement EXT_texture_filter_anisotropic
  Cargo.lock
  components/canvas/webgl_thread.rs
  components/canvas_traits/Cargo.toml
  components/canvas_traits/webgl.rs
  components/script/dom/webgl_extensions/ext/exttexturefilteranisotropic.rs
  components/script/dom/webgl_extensions/ext/mod.rs
  components/script/dom/webgl_extensions/extensions.rs
  components/script/dom/webglrenderingcontext.rs
  components/script/dom/webgltexture.rs
  components/script/dom/webidls/EXTTextureFilterAnisotropic.webidl
Labels: S-awaiting-merge

#21015 Support cloning steps for textarea/input
  components/script/dom/htmltextareaelement.rs
  tests/wpt/metadata/html/semantics/forms/the-textarea-element/cloning-steps.html.ini
Labels: S-tests-failed

#21019 Make a doc URL a clickable link
  components/net/http_cache.rs
Labels: S-awaiting-merge

#21023 Refactor draw_image and make draw_image_self call draw_image in canvas.
  components/canvas/canvas_data.rs
Labels: S-awaiting-merge

#21028 Fixed panic due to GC while parsing
  components/script/script_thread.rs
Labels: A-content/script, I-panic, S-tests-failed

#21034 Don't check for GL_OES_element_index_unit with desktop GL (fixes #20921)
  components/script/dom/webgl_extensions/ext/oeselementindexuint.rs
  tests/wpt/mozilla/meta/webgl/conformance-1.0.3/conformance/extensions/oes-element-index-uint.html.ini
Labels: S-tests-failed

#20891 Implement getter for child BCs correctly
  components/constellation/constellation.rs
  tests/wpt/metadata/html/semantics/forms/resetting-a-form/reset-form-event-realm.html.ini
Labels: S-awaiting-merge

#21046 Upgrade to rustc 1.28.0-nightly (b68432d56 2018-06-12)
  Cargo.lock
  components/allocator/Cargo.toml
  components/allocator/lib.rs
  components/script/Cargo.toml
  rust-toolchain
Labels: S-tests-failed

#21045 Allow window.parent attribute to be replaceable by JavaScript.
  components/script/dom/webidls/Window.webidl
  tests/wpt/metadata/html/browsers/the-window-object/window-properties.https.html.ini
Labels: S-awaiting-merge

#21051 Implement window.length DOM attribute.
  components/script/dom/webidls/Window.webidl
  components/script/dom/window.rs
  tests/wpt/metadata/html/browsers/the-window-object/accessing-other-browsing-contexts/window_length.html.ini
  tests/wpt/metadata/html/browsers/the-window-object/security-window/window-security.https.html.ini
  tests/wpt/metadata/html/browsers/the-window-object/window-properties.https.html.ini
Labels: S-awaiting-merge

#21064 Let the popstate and hashchange events not bubble
  components/script/dom/history.rs
  components/script/dom/popstateevent.rs
  tests/wpt/metadata/html/browsers/browsing-the-web/history-traversal/popstate_event.html.ini
Labels: S-awaiting-merge

#20699 Issue #20593: Implement proper checks in WebGLRenderingContext's getFramebufferAttachmentParameter().
  components/script/dom/webglrenderingcontext.rs
  tests/wpt/mozilla/meta/MANIFEST.json
  tests/wpt/mozilla/tests/mozilla/webgl/getFramebufferAttachmentParameter.html
Labels: S-awaiting-merge

#20421 mach: android install/run: infer adb path from SDK dir
  python/servo/command_base.py
  python/servo/package_commands.py
  python/servo/post_build_commands.py
Labels: S-awaiting-merge

#21050 Allow supported window attributes to be replacable.
  components/script/dom/webidls/Window.webidl
  tests/wpt/metadata/css/cssom-view/window-interface.xht.ini
  tests/wpt/metadata/html/browsers/the-window-object/window-properties.https.html.ini
Labels: S-awaiting-merge

#21071 Update mozjs_sys to include cross-compilation fixes.
  Cargo.lock
  python/servo/build_commands.py
Labels: S-tests-failed

#21072 Implement checks for vertex attribs enabled as arrays without a bound buffer
  components/script/dom/webgl_extensions/ext/oesvertexarrayobject.rs
  components/script/dom/webglrenderingcontext.rs
  components/script/dom/webglvertexarrayobjectoes.rs
  tests/wpt/mozilla/meta/webgl/conformance-1.0.3/conformance/buffers/index-validation-copies-indices.html.ini
  tests/wpt/mozilla/meta/webgl/conformance-1.0.3/conformance/buffers/index-validation-verifies-too-many-indices.html.ini
  tests/wpt/mozilla/meta/webgl/conformance-1.0.3/conformance/buffers/index-validation.html.ini
  tests/wpt/mozilla/meta/webgl/conformance-1.0.3/conformance/extensions/oes-element-index-uint.html.ini
  tests/wpt/mozilla/meta/webgl/conformance-1.0.3/conformance/rendering/draw-elements-out-of-bounds.html.ini
  tests/wpt/mozilla/meta/webgl/conformance-2.0.0/conformance2/rendering/element-index-uint.html.ini
Labels: S-tests-failed

#21074 Implement support for Element.toggleAttribute
  components/script/dom/element.rs
  components/script/dom/webidls/Element.webidl
Labels: S-awaiting-merge

#21081 Properly enable EXT_shader_texture_lod
  components/script/dom/webgl_extensions/ext/extshadertexturelod.rs
  components/script/dom/webgl_extensions/extensions.rs
  components/script/dom/webglshader.rs
Labels: S-awaiting-merge

#21080 Implement EXT_blend_minmax
  components/script/dom/webgl_extensions/ext/extblendminmax.rs
  components/script/dom/webgl_extensions/ext/mod.rs
  components/script/dom/webgl_extensions/extensions.rs
  components/script/dom/webglrenderingcontext.rs
  components/script/dom/webidls/EXTBlendMinmax.webidl
  tests/wpt/mozilla/meta/webgl/conformance-1.0.3/conformance/extensions/ext-blend-minmax.html.ini
Labels: S-tests-failed

#21079 Handle case of refreshed cache entry still receiving data
  components/net/http_cache.rs
  components/net/http_loader.rs
  components/net/tests/http_cache.rs
Labels: S-needs-tests, S-tests-failed

#21102 Updated mozjs_sys to v0.51.3
  Cargo.lock
Labels: S-awaiting-merge
