Repository servo/servo, pull requests merged in 2019-02, with the labels that each got.

#22806 Update gstreamer binaries for Android with webrtc related plugins
  python/servo/build_commands.py
Labels: S-awaiting-merge

#22809 Add a reftest that entering fullscreen mode takes over the window
  components/script/dom/document.rs
  tests/wpt/mozilla/meta/MANIFEST.json
  tests/wpt/mozilla/meta/mozilla/fullscreen/reftests/__dir__.ini
  tests/wpt/mozilla/meta/mozilla/fullscreen/reftests/fullscreen-hides-others.html.ini
  tests/wpt/mozilla/tests/mozilla/fullscreen/reftests/fullscreen-baseline-ref.html
  tests/wpt/mozilla/tests/mozilla/fullscreen/reftests/fullscreen-baseline.html
  tests/wpt/mozilla/tests/mozilla/fullscreen/reftests/fullscreen-hides-others.html
Labels: A-testing, S-tests-failed

#22823 Compat with rustc 1.34.0-nightly (f6fac4225 2019-02-03)
  components/script_plugins/unrooted_must_root.rs
Labels: S-awaiting-merge

#22836 Remove readfile callback
  ports/libsimpleservo/api/src/lib.rs
  ports/libsimpleservo/capi/src/lib.rs
  ports/libsimpleservo/jniapi/src/lib.rs
  support/android/apk/servoview/build.gradle
  support/android/apk/servoview/src/main/java/org/mozilla/servoview/JNIServo.java
  support/android/apk/servoview/src/main/java/org/mozilla/servoview/Servo.java
Labels: S-awaiting-merge

#22825 Layout fullscreen top layer
  components/layout/display_list/builder.rs
  components/layout/display_list/items.rs
  components/style/properties/longhands/box.mako.rs
  components/style/properties/properties.mako.rs
  resources/user-agent.css
  tests/wpt/mozilla/meta/mozilla/fullscreen/reftests/fullscreen-hides-others.html.ini
Labels: A-content/css, A-layout/uncategorized, S-awaiting-merge

#22839 Ensure transparent hit test region is sized and positioned correctly.
  components/layout/display_list/builder.rs
  tests/wpt/mozilla/meta/MANIFEST.json
  tests/wpt/mozilla/tests/mozilla/hit-test-background.html
Labels: S-awaiting-merge

#22773 Support for ExternalVR implementation
  Cargo.lock
  components/compositing/windowing.rs
  components/servo/lib.rs
  components/webvr/Cargo.toml
  components/webvr/lib.rs
  components/webvr/webvr_thread.rs
  ports/libsimpleservo/api/src/lib.rs
  ports/libsimpleservo/capi/src/lib.rs
  ports/libsimpleservo/jniapi/src/lib.rs
  support/android/apk/servoview/src/main/java/org/mozilla/servoview/JNIServo.java
  support/android/apk/servoview/src/main/java/org/mozilla/servoview/ServoSurface.java
Labels: S-awaiting-merge

#22850 Implement the target attribute for HTMLAreaElement
  components/script/dom/htmlareaelement.rs
  components/script/dom/webidls/HTMLAreaElement.webidl
  tests/wpt/metadata/html/dom/interfaces.https.html.ini
Labels: S-awaiting-merge

#22798 Report all messages processed by the webgl thread.
  components/canvas/webgl_thread.rs
  components/canvas_traits/webgl.rs
  components/script/dom/webglrenderingcontext.rs
Labels: S-awaiting-merge

#22864 style: Rename MozLength to Size, and MaxLength to MaxSize.
  components/layout/block.rs
  components/layout/flex.rs
  components/layout/floats.rs
  components/layout/fragment.rs
  components/layout/model.rs
  components/layout/multicol.rs
  components/layout/table.rs
  components/layout/table_cell.rs
  components/layout/table_colgroup.rs
  components/layout/table_row.rs
  components/layout/table_wrapper.rs
  components/script/dom/element.rs
  components/style/gecko/values.rs
  components/style/properties/gecko.mako.rs
  components/style/properties/longhands/position.mako.rs
  components/style/properties/properties.mako.rs
  components/style/values/computed/flex.rs
  components/style/values/computed/length.rs
  components/style/values/computed/mod.rs
  components/style/values/generics/length.rs
  components/style/values/specified/flex.rs
  components/style/values/specified/length.rs
  components/style/values/specified/mod.rs
  tests/wpt/metadata/css/css-flexbox/getcomputedstyle/flexbox_computedstyle_min-auto-size.html.ini
  tests/wpt/metadata/css/css-flexbox/getcomputedstyle/flexbox_computedstyle_min-height-auto.html.ini
  tests/wpt/metadata/css/css-flexbox/getcomputedstyle/flexbox_computedstyle_min-width-auto.html.ini
Labels: S-awaiting-merge

#22872 Update servo-media
  Cargo.lock
  components/script/dom/bindings/trace.rs
  components/script/dom/mediadevices.rs
  components/script/dom/mediastream.rs
  components/script/dom/rtcpeerconnection.rs
Labels: S-awaiting-merge

#22886 Allow the embedder to register their own VRServices
  Cargo.lock
  components/compositing/Cargo.toml
  components/compositing/windowing.rs
  components/servo/lib.rs
  components/webvr/Cargo.toml
  components/webvr/lib.rs
  components/webvr/webvr_thread.rs
  components/webvr_traits/Cargo.toml
  ports/libsimpleservo/api/src/lib.rs
Labels: A-webvr, S-awaiting-merge

#22844 Generate simpleservo.h
  Cargo.lock
  ports/libsimpleservo/capi/Cargo.toml
  ports/libsimpleservo/capi/build.rs
Labels: S-awaiting-merge

#22894 Fix installing dependencies on macOS using Homebrew
  etc/taskcluster/macos/Brewfile
Labels: S-awaiting-merge

#22852 libsimpleservo: OpenGL support for Linux (glx)
  Cargo.lock
  ports/libsimpleservo/api/Cargo.toml
  ports/libsimpleservo/api/build.rs
  ports/libsimpleservo/api/src/gl_glue.rs
Labels: S-awaiting-merge

#22910 Fix log filter. simpleservo::api doesn't exist anymore
  ports/libsimpleservo/jniapi/src/lib.rs
Labels: S-awaiting-merge

#22347 Implement HTMLMediaElement muted and defaultMuted attributes
  components/script/dom/htmlmediaelement.rs
  components/script/dom/webidls/HTMLMediaElement.webidl
  tests/wpt/metadata/html/dom/interfaces.https.html.ini
  tests/wpt/metadata/html/semantics/embedded-content/media-elements/event_volumechange.html.ini
  tests/wpt/metadata/html/semantics/embedded-content/media-elements/user-interface/muted.html.ini
Labels: S-awaiting-merge

#22940 Call start_present and stop_present on VRDisplay
  components/webvr/webvr_thread.rs
Labels: A-webvr, S-awaiting-merge

#22938 Use webvr future_frame_data to avoid blocking the WebGL thread
  Cargo.lock
  components/canvas_traits/Cargo.toml
  components/canvas_traits/webgl.rs
  components/script/dom/vrdisplay.rs
  components/webvr/webvr_thread.rs
  components/webvr_traits/Cargo.toml
  components/webvr_traits/lib.rs
Labels: A-webvr, S-awaiting-merge, S-blocked-on-external

#22917 Add optional annotations for initEvent method of Event interface
  components/script/dom/webidls/Event.webidl
  tests/wpt/metadata/dom/events/Event-initEvent.html.ini
  tests/wpt/metadata/dom/interfaces.html.ini
Labels: S-awaiting-merge

#22939 Pass the GL context to the VRDisplay when rendering
  Cargo.lock
  components/canvas/webgl_mode/inprocess.rs
  components/canvas/webgl_thread.rs
  components/canvas_traits/webgl.rs
  components/webvr/Cargo.toml
  components/webvr/webvr_thread.rs
  components/webvr_traits/Cargo.toml
Labels: A-webvr, S-awaiting-merge

#22945 Fixed inconsistency in import of gl::Gl
  components/canvas/webgl_mode/inprocess.rs
Labels: S-awaiting-merge, S-fails-tidy

#22948 Move RenderNotifier from compositing component to servo component
  components/compositing/compositor.rs
  components/compositing/lib.rs
  components/servo/lib.rs
Labels: S-awaiting-merge
