Repository servo/servo, pull requests merged in 2019-08, with the labels that each got.

#23901 Missing libraries for HoloLens x64
  support/hololens/ServoApp/ServoApp.vcxproj
Labels: S-awaiting-merge

#23900 Use tasks instead of events
  support/hololens/ServoApp/BrowserPage.cpp
  support/hololens/ServoApp/BrowserPage.h
  support/hololens/ServoApp/Servo.cpp
Labels: S-awaiting-merge

#23902 Do not start up webvr services when running webxr and vice versa
  components/servo/lib.rs
Labels: S-awaiting-merge

#23903 Webxr magicleap
  Cargo.lock
  ports/libmlservo/Cargo.toml
  ports/libmlservo/src/lib.rs
  ports/libsimpleservo/api/Cargo.toml
  ports/libsimpleservo/api/src/lib.rs
  ports/libsimpleservo/capi/src/lib.rs
  ports/libsimpleservo/jniapi/src/lib.rs
Labels: A-xr-zomg, S-awaiting-merge

#23920 Fix a panic when using layout 2020
  components/style/properties/properties.mako.rs
Labels: S-awaiting-merge, S-fails-tidy

#23921 Sync WPT with upstream (06-08-2019)
  tests/wpt/metadata/css/css-flexbox/percentage-heights-006.html.ini
  tests/wpt/metadata/css/css-transitions/properties-value-001.html.ini
  tests/wpt/metadata/css/css-transitions/properties-value-inherit-001.html.ini
  tests/wpt/metadata/css/cssom-view/matchMedia-display-none-iframe.html.ini
  tests/wpt/metadata/fetch/content-type/response.window.js.ini
  tests/wpt/metadata/fetch/content-type/script.window.js.ini
  tests/wpt/metadata/fetch/nosniff/parsing-nosniff.window.js.ini
  tests/wpt/metadata/html/browsers/history/the-history-interface/traverse_the_history_3.html.ini
  tests/wpt/metadata/html/browsers/the-window-object/apis-for-creating-and-navigating-browsing-contexts-by-name/open-features-negative-innerwidth-innerheight.html.ini
  tests/wpt/metadata/html/browsers/the-window-object/apis-for-creating-and-navigating-browsing-contexts-by-name/open-features-negative-screenx-screeny.html.ini
  tests/wpt/metadata/html/browsers/the-window-object/apis-for-creating-and-navigating-browsing-contexts-by-name/open-features-negative-top-left.html.ini
  tests/wpt/metadata/html/browsers/the-window-object/apis-for-creating-and-navigating-browsing-contexts-by-name/open-features-negative-width-height.html.ini
  tests/wpt/metadata/html/browsers/the-window-object/apis-for-creating-and-navigating-browsing-contexts-by-name/open-features-non-integer-height.html.ini
  tests/wpt/metadata/html/browsers/the-window-object/apis-for-creating-and-navigating-browsing-contexts-by-name/open-features-non-integer-innerheight.html.ini
  tests/wpt/metadata/html/browsers/the-window-object/apis-for-creating-and-navigating-browsing-contexts-by-name/open-features-non-integer-innerwidth.html.ini
  tests/wpt/metadata/html/browsers/the-window-object/apis-for-creating-and-navigating-browsing-contexts-by-name/open-features-non-integer-left.html.ini
  tests/wpt/metadata/html/browsers/the-window-object/apis-for-creating-and-navigating-browsing-contexts-by-name/open-features-non-integer-screenx.html.ini
  tests/wpt/metadata/html/browsers/the-window-object/apis-for-creating-and-navigating-browsing-contexts-by-name/open-features-non-integer-screeny.html.ini
  tests/wpt/metadata/html/browsers/the-window-object/apis-for-creating-and-navigating-browsing-contexts-by-name/open-features-non-integer-top.html.ini
  tests/wpt/metadata/html/browsers/the-window-object/apis-for-creating-and-navigating-browsing-contexts-by-name/open-features-non-integer-width.html.ini
  tests/wpt/metadata/html/semantics/forms/form-submission-0/form-submission-algorithm.html.ini
  tests/wpt/metadata/html/semantics/interactive-elements/the-details-element/toggleEvent.html.ini
  tests/wpt/metadata/resource-timing/resource_TAO_origin.htm.ini
  tests/wpt/metadata/resource-timing/resource_TAO_zero.htm.ini
  tests/wpt/metadata/url/url-setters.html.ini
  tests/wpt/metadata/webaudio/the-audio-api/the-analysernode-interface/realtimeanalyser-fft-scaling.html.ini
  tests/wpt/metadata/webaudio/the-audio-api/the-audiobuffersourcenode-interface/sub-sample-buffer-stitching.html.ini
  tests/wpt/metadata/webaudio/the-audio-api/the-audioparam-interface/set-target-conv.html.ini
  tests/wpt/metadata/workers/constructors/Worker/Worker-constructor.html.ini
  tests/wpt/web-platform-tests/css/css-contain/contain-size-replaced-004-ref.html
  tests/wpt/web-platform-tests/css/css-contain/contain-size-replaced-004.html
  tests/wpt/web-platform-tests/css/css-contain/contain-size-replaced-005-ref.html
  tests/wpt/web-platform-tests/css/css-contain/contain-size-replaced-005.html
  tests/wpt/web-platform-tests/css/css-contain/contain-size-replaced-006-ref.html
  tests/wpt/web-platform-tests/css/css-contain/contain-size-replaced-006.html
  tests/wpt/web-platform-tests/css/css-flexbox/percentage-heights-006.html
  tests/wpt/web-platform-tests/css/css-grid/animation/grid-template-columns-interpolation.html
  tests/wpt/web-platform-tests/css/css-grid/animation/grid-template-rows-interpolation.html
  tests/wpt/web-platform-tests/css/css-lists/list-and-margin-collapse-003.html
  tests/wpt/web-platform-tests/css/css-lists/list-and-margin-collapse-004.html
  tests/wpt/web-platform-tests/interfaces/speech-api.idl
  tests/wpt/web-platform-tests/pointerlock/movementX_Y_basic.html
  tests/wpt/web-platform-tests/url/resources/setters_tests.json
  tests/wpt/web-platform-tests/webaudio/the-audio-api/the-audioparam-interface/set-target-conv.html
  tests/wpt/web-platform-tests/webrtc/RTCPeerConnection-onicecandidateerror.html
  tests/wpt/web-platform-tests/webrtc/RTCPeerConnection-onicecandidateerror.https.html
Labels: S-awaiting-merge

#23927 Update cmake
  Cargo.lock
  Cargo.toml
Labels: S-tests-failed

#23929 Added gstreamer support to the magicleap port
  components/servo/Cargo.toml
  components/servo/lib.rs
  python/servo/build_commands.py
  python/servo/package_commands.py
  support/magicleap/Servo2D/Servo2D.mabu
  support/magicleap/Servo2D/code/src/Servo2D.cpp
  support/magicleap/Servo3D/Servo3D.mabu
  support/magicleap/gstreamer/.gitignore
  support/magicleap/gstreamer/README.md
  support/magicleap/gstreamer/gstreamer.sh
  support/magicleap/gstreamer/mlsdk.txt.in
Labels: A-content/media, P-magic leap, S-awaiting-merge

#23930 Assert incumbent global is always some in get_incumbent_global hook
  components/script/script_runtime.rs
Labels: S-awaiting-merge

#23941 Update webdriver
  Cargo.lock
  components/webdriver_server/Cargo.toml
  components/webdriver_server/lib.rs
  servo-tidy.toml
Labels: S-awaiting-merge

#23942 Updated Servo2D to LRE v0.22.0
  support/magicleap/Servo2D/.gitignore
  support/magicleap/Servo2D/Servo2D.mabu
  support/magicleap/Servo2D/Servo2D.mlproject
  support/magicleap/Servo2D/Servo2D.package
  support/magicleap/Servo2D/code/inc.gen/PrismSceneManager.h
  support/magicleap/Servo2D/code/inc.gen/SceneDescriptor.h
  support/magicleap/Servo2D/code/inc.gen/Servo2D/Servo2D.h
  support/magicleap/Servo2D/code/inc.gen/SpawnedSceneBase.h
  support/magicleap/Servo2D/code/inc.gen/SpawnedSceneHandlers.h
  support/magicleap/Servo2D/code/inc.gen/SpawnedSceneUserData.h
  support/magicleap/Servo2D/code/inc.gen/scenes.h
  support/magicleap/Servo2D/code/inc/Servo2D.h
  support/magicleap/Servo2D/code/src.gen/PrismSceneManager.cpp
  support/magicleap/Servo2D/code/src.gen/SceneDescriptor.cpp
  support/magicleap/Servo2D/code/src.gen/Servo2D/Servo2D.cpp
  support/magicleap/Servo2D/code/src.gen/SpawnedSceneBase.cpp
  support/magicleap/Servo2D/code/src.gen/SpawnedSceneHandlers.cpp
  support/magicleap/Servo2D/code/src.gen/SpawnedSceneUserData.cpp
  support/magicleap/Servo2D/code/src.gen/scenes.cpp
  support/magicleap/Servo2D/code/src.gen/scenesGen.cpp
  support/magicleap/Servo2D/code/src/Servo2D.cpp
  support/magicleap/Servo2D/code/srcs.comp
  support/magicleap/Servo2D/code/srcsGen.comp
  support/magicleap/Servo2D/pipeline/cache/AssetManifest.comp
  support/magicleap/Servo2D/pipeline/lap/project.json
  support/magicleap/Servo2D/scenes.comp
  support/magicleap/Servo2D/scenes/Servo2D.design
  support/magicleap/Servo2D/scenes/Servo2D.scene.res.xml
  support/magicleap/Servo2D/scenes/Servo2D.scene.xml
Labels: P-magic leap, S-awaiting-merge

#23922 Redirect stdout/stderr on windows
  Cargo.lock
  ports/glutin/Cargo.toml
  ports/libsimpleservo/capi/Cargo.toml
  ports/libsimpleservo/capi/src/lib.rs
Labels: S-awaiting-merge

#23725 Support for returning array-like types from the Execute(Async)Script wd command
  Cargo.lock
  components/script/Cargo.toml
  components/script/dom/window.rs
  components/script/webdriver_handlers.rs
  components/script_traits/Cargo.toml
  components/script_traits/webdriver_msg.rs
  components/webdriver_server/lib.rs
  tests/wpt/metadata/webdriver/tests/element_send_keys/events.py.ini
  tests/wpt/metadata/webdriver/tests/element_send_keys/form_controls.py.ini
  tests/wpt/metadata/webdriver/tests/execute_script/collections.py.ini
  tests/wpt/metadata/webdriver/tests/execute_script/cyclic.py.ini
  tests/wpt/metadata/webdriver/tests/execute_script/execute.py.ini
  tests/wpt/metadata/webdriver/tests/execute_script/properties.py.ini
  tests/wpt/metadata/webdriver/tests/find_element/find.py.ini
  tests/wpt/metadata/webdriver/tests/find_element_from_element/find.py.ini
  tests/wpt/metadata/webdriver/tests/find_elements/find.py.ini
  tests/wpt/metadata/webdriver/tests/find_elements_from_element/find.py.ini
  tests/wpt/metadata/webdriver/tests/get_active_element/get.py.ini
  tests/wpt/metadata/webdriver/tests/get_current_url/get.py.ini
  tests/wpt/metadata/webdriver/tests/get_element_property/get.py.ini
  tests/wpt/metadata/webdriver/tests/get_title/get.py.ini
  tests/wpt/metadata/webdriver/tests/take_screenshot/screenshot.py.ini
Labels: S-awaiting-merge

#23940 Always send epochs to webrender in layout 2020
  components/layout_thread_2020/lib.rs
Labels: S-awaiting-merge

#23944 Fix scrolling on hololens
  support/hololens/ServoApp/BrowserPage.cpp
Labels: S-awaiting-merge

#23946 Sync WPT with upstream (10-08-2019)
  tests/wpt/metadata/FileAPI/url/url-in-tags-revoke.window.js.ini
  tests/wpt/metadata/FileAPI/url/url-with-fetch.any.js.ini
  tests/wpt/metadata/css/cssom-view/scroll-behavior-smooth.html.ini
  tests/wpt/metadata/css/filter-effects/backdrop-filter-containing-block.html.ini
  tests/wpt/metadata/custom-elements/form-associated/ElementInternals-accessibility.html.ini
  tests/wpt/metadata/fetch/content-type/response.window.js.ini
  tests/wpt/metadata/fetch/content-type/script.window.js.ini
  tests/wpt/metadata/fetch/nosniff/parsing-nosniff.window.js.ini
  tests/wpt/metadata/html/browsers/history/the-history-interface/traverse_the_history_2.html.ini
  tests/wpt/metadata/html/browsers/the-window-object/apis-for-creating-and-navigating-browsing-contexts-by-name/creating_browsing_context_test_01.html.ini
  tests/wpt/metadata/html/semantics/embedded-content/the-img-element/non-active-document.html.ini
  tests/wpt/metadata/html/semantics/forms/form-submission-0/form-submission-algorithm.html.ini
  tests/wpt/metadata/html/semantics/scripting-1/the-script-element/script-onerror-insertion-point-2.html.ini
  tests/wpt/metadata/html/webappapis/dynamic-markup-insertion/document-write/iframe_005.html.ini
  tests/wpt/metadata/resource-timing/resource_TAO_zero.htm.ini
  tests/wpt/metadata/webaudio/the-audio-api/the-audiobuffersourcenode-interface/sub-sample-buffer-stitching.html.ini
  tests/wpt/metadata/webdriver/tests/new_session/invalid_capabilities.py.ini
  tests/wpt/metadata/webxr/xrBoundedReferenceSpace_updates.https.html.ini
  tests/wpt/metadata/workers/WorkerGlobalScope-close.html.ini
  tests/wpt/web-platform-tests/contacts/contacts-select.https.window.js
  tests/wpt/web-platform-tests/contacts/resources/helpers.js
  tests/wpt/web-platform-tests/contacts/resources/non-main-frame-select.html
  tests/wpt/web-platform-tests/cookie-store/serviceworker_cookieStore_arguments.tentative.https.html
  tests/wpt/web-platform-tests/cookie-store/serviceworker_cookieStore_basic.tentative.https.html
  tests/wpt/web-platform-tests/cookie-store/serviceworker_cookieStore_subscriptions.tentative.https.html
  tests/wpt/web-platform-tests/cookie-store/serviceworker_cookieStore_subscriptions_basic.tentative.https.html
  tests/wpt/web-platform-tests/cookie-store/serviceworker_cookieStore_subscriptions_empty.tentative.https.html
  tests/wpt/web-platform-tests/css/css-inline/inheritance.html
  tests/wpt/web-platform-tests/css/css-sizing/inheritance-001.html
  tests/wpt/web-platform-tests/css/css-sizing/inheritance-002.html
  tests/wpt/web-platform-tests/css/css-sizing/inheritance.html
  tests/wpt/web-platform-tests/css/filter-effects/backdrop-filter-containing-block-ref.html
  tests/wpt/web-platform-tests/css/filter-effects/backdrop-filter-containing-block.html
  tests/wpt/web-platform-tests/custom-elements/form-associated/ElementInternals-accessibility.html
  tests/wpt/web-platform-tests/fetch/sec-metadata/resources/unload-with-beacon.html
  tests/wpt/web-platform-tests/fetch/sec-metadata/unload.tentative.https.sub.html
  tests/wpt/web-platform-tests/interfaces/accelerometer.idl
  tests/wpt/web-platform-tests/interfaces/ambient-light.idl
  tests/wpt/web-platform-tests/interfaces/animation-worklet.idl
  tests/wpt/web-platform-tests/interfaces/console.idl
  tests/wpt/web-platform-tests/interfaces/dom.idl
  tests/wpt/web-platform-tests/interfaces/encoding.idl
  tests/wpt/web-platform-tests/interfaces/web-nfc.idl
  tests/wpt/web-platform-tests/interfaces/web-share.idl
  tests/wpt/web-platform-tests/resources/chromium/contacts_manager_mock.js
  tests/wpt/web-platform-tests/service-workers/service-worker/ServiceWorkerGlobalScope/fetch-on-the-right-interface.https.any.js
  tests/wpt/web-platform-tests/svg/extensibility/foreignObject/filter-repaint-ref.html
  tests/wpt/web-platform-tests/svg/extensibility/foreignObject/filter-repaint.html
  tests/wpt/web-platform-tests/tools/wptrunner/requirements_firefox.txt
  tests/wpt/web-platform-tests/tools/wptrunner/wptrunner/browsers/firefox.py
  tests/wpt/web-platform-tests/web-share/META.yml
  tests/wpt/web-platform-tests/web-share/idlharness.https.window.js
  tests/wpt/web-platform-tests/webdriver/tests/switch_to_window/alerts.py
  tests/wpt/web-platform-tests/webxr/xrInputSource_gamepad_disconnect.https.html
  tests/wpt/web-platform-tests/webxr/xrInputSource_gamepad_input_registered.https.html
Labels: S-awaiting-merge

#23950 Update rand to 0.6
  Cargo.lock
  components/constellation/constellation.rs
  components/rand/Cargo.toml
  components/rand/lib.rs
  components/script/dom/crypto.rs
  servo-tidy.toml
Labels: S-awaiting-merge

#23956 Remove more stuff from layout_2020
  components/layout_2020/display_list/builder.rs
  components/layout_2020/display_list/mod.rs
  components/layout_2020/flow.rs
  components/layout_2020/flow_ref.rs
  components/layout_2020/fragment.rs
  components/layout_2020/lib.rs
  components/layout_2020/query.rs
  components/layout_thread_2020/lib.rs
Labels: S-awaiting-merge

#23953 Use the built-in laser pointer for magicleap
  support/magicleap/Servo2D/Servo2D.mlproject
  support/magicleap/Servo2D/code/inc.gen/Servo2D/Servo2D.h
  support/magicleap/Servo2D/code/inc/Servo2D.h
  support/magicleap/Servo2D/code/src.gen/Servo2D/Servo2D.cpp
  support/magicleap/Servo2D/code/src.gen/scenes.cpp
  support/magicleap/Servo2D/code/src/Servo2D.cpp
  support/magicleap/Servo2D/pipeline/lap/project.json
  support/magicleap/Servo2D/scenes/Servo2D.design
  support/magicleap/Servo2D/scenes/Servo2D.scene.xml
Labels: P-magic leap, S-tests-failed

#23967 Remove redundant windowproxy transplanting
  components/script/dom/windowproxy.rs
Labels: S-awaiting-merge

#23919 ISSUE-21803: Implement ConstantSourceNode audionode
  components/script/dom/baseaudiocontext.rs
  components/script/dom/constantsourcenode.rs
  components/script/dom/mod.rs
  components/script/dom/webidls/BaseAudioContext.webidl
  components/script/dom/webidls/ConstantSourceNode.webidl
  tests/wpt/metadata/webaudio/idlharness.https.window.js.ini
  tests/wpt/metadata/webaudio/the-audio-api/the-audioparam-interface/audioparam-close.html.ini
  tests/wpt/metadata/webaudio/the-audio-api/the-audioparam-interface/event-insertion.html.ini
  tests/wpt/metadata/webaudio/the-audio-api/the-audioparam-interface/k-rate-constant-source.html.ini
  tests/wpt/metadata/webaudio/the-audio-api/the-audioparam-interface/k-rate-panner.html.ini
  tests/wpt/metadata/webaudio/the-audio-api/the-audioparam-interface/set-target-conv.html.ini
  tests/wpt/metadata/webaudio/the-audio-api/the-constantsourcenode-interface/constant-source-basic.html.ini
  tests/wpt/metadata/webaudio/the-audio-api/the-constantsourcenode-interface/constant-source-output.html.ini
  tests/wpt/metadata/webaudio/the-audio-api/the-constantsourcenode-interface/ctor-constantsource.html.ini
  tests/wpt/metadata/webaudio/the-audio-api/the-constantsourcenode-interface/test-constantsourcenode.html.ini
  tests/wpt/metadata/webaudio/the-audio-api/the-pannernode-interface/panner-azimuth.html.ini
  tests/wpt/mozilla/meta/MANIFEST.json
  tests/wpt/mozilla/tests/mozilla/interfaces.html
Labels: S-awaiting-merge

#23805 Initial Actions support in WebDriver
  components/constellation/constellation.rs
  components/script_traits/lib.rs
  components/webdriver_server/actions.rs
  components/webdriver_server/lib.rs
  tests/wpt/metadata/webdriver/tests/perform_actions/none.py.ini
  tests/wpt/metadata/webdriver/tests/perform_actions/validity.py.ini
Labels: S-awaiting-merge, S-fails-tidy

#23957 Clarify instructions for installing GStreamer dependencies on Windows
  README.md
Labels: S-awaiting-merge

#23958 Update toml to 0.5 and cbindgen to 0.9
  Cargo.lock
  components/compositing/Cargo.toml
  components/style/Cargo.toml
  ports/libsimpleservo/capi/Cargo.toml
Labels: S-awaiting-merge

#23966 Fix build error when using the 'webgl_backtrace' feature
  components/script/dom/webglrenderingcontext.rs
Labels: S-awaiting-merge

#23976 Package both Servo2D and Servo3D in one magicleap mpk
  python/servo/package_commands.py
  support/magicleap/Servo.package
  support/magicleap/Servo2D/Servo2D.mabu
  support/magicleap/Servo3D/Servo3D.package
  support/magicleap/manifest.xml
Labels: P-magic leap, S-awaiting-merge

#23977 Use correct openxr loader path for x64
  python/servo/build_commands.py
Labels: S-awaiting-merge

#23978 Enable webxr for the UWP port.
  support/hololens/ServoApp/Servo.cpp
Labels: S-awaiting-merge

#23979 Update webrender, image, png and raqote
  Cargo.lock
  components/compositing/Cargo.toml
  components/layout/display_list/webrender_helpers.rs
  components/net_traits/Cargo.toml
  components/script/Cargo.toml
  components/webdriver_server/Cargo.toml
  ports/glutin/Cargo.toml
  ports/glutin/headed_window.rs
Labels: S-awaiting-merge

#23972 Restructure content process shutdown ack with threaded sender
  components/constellation/pipeline.rs
  components/layout_thread/lib.rs
  components/layout_thread_2020/lib.rs
  components/layout_traits/lib.rs
  components/script/dom/htmliframeelement.rs
  components/script/dom/windowproxy.rs
  components/script/script_thread.rs
  components/script_layout_interface/message.rs
  components/script_traits/lib.rs
Labels: S-awaiting-merge

#23992 Update taskcluster for new Servo mpk name
  etc/taskcluster/decision_task.py
Labels: A-build, P-magic leap, S-awaiting-merge

#23988 Implement pointerDown and pointerUp webdriver actions
  components/compositing/compositor.rs
  components/compositing/compositor_thread.rs
  components/constellation/constellation.rs
  components/script_traits/lib.rs
  components/webdriver_server/actions.rs
Labels: S-awaiting-merge

#23951 Return ErrorStatus from webdriver_handlers
  components/script/dom/node.rs
  components/script/script_thread.rs
  components/script/webdriver_handlers.rs
  components/script_traits/webdriver_msg.rs
  components/webdriver_server/lib.rs
  tests/wpt/metadata/webdriver/tests/get_element_attribute/get.py.ini
  tests/wpt/metadata/webdriver/tests/get_element_css_value/get.py.ini
  tests/wpt/metadata/webdriver/tests/get_element_property/get.py.ini
  tests/wpt/metadata/webdriver/tests/get_element_rect/get.py.ini
  tests/wpt/metadata/webdriver/tests/get_element_tag_name/get.py.ini
  tests/wpt/metadata/webdriver/tests/get_element_text/get.py.ini
  tests/wpt/metadata/webdriver/tests/switch_to_frame/switch.py.ini
Labels: S-awaiting-merge

#23989 Update webxr crate
  Cargo.lock
Labels: S-awaiting-merge

#24000 Update servo-media. Remove implicit shutdown requests. It all happens…
  Cargo.lock
  components/script/dom/baseaudiocontext.rs
  components/script/dom/htmlmediaelement.rs
  servo-tidy.toml
Labels: S-awaiting-merge

#24003 Add --magicleap option to mach install
  python/servo/package_commands.py
Labels: P-magic leap, S-awaiting-merge

#24006 Deduplicate idna, log, mime, mime_guess, percent-encoding, unicase, url, ws
  Cargo.lock
  components/net/fetch/methods.rs
  components/net/filemanager_thread.rs
  servo-tidy.toml
Labels: S-awaiting-merge

#23943 Implement TakeElementScreenshot WebDriver command
  Cargo.lock
  components/compositing/compositor.rs
  components/compositing/compositor_thread.rs
  components/compositing/gl.rs
  components/constellation/constellation.rs
  components/script/script_thread.rs
  components/script/webdriver_handlers.rs
  components/script_traits/lib.rs
  components/script_traits/webdriver_msg.rs
  components/webdriver_server/Cargo.toml
  components/webdriver_server/lib.rs
  tests/wpt/metadata/webdriver/tests/take_element_screenshot/screenshot.py.ini
Labels: S-awaiting-merge

#23983 [hololens] Handle servo panic
  Cargo.lock
  ports/libsimpleservo/capi/Cargo.toml
  ports/libsimpleservo/capi/src/lib.rs
  support/hololens/ServoApp/ServoControl/Servo.cpp
Labels: S-awaiting-merge, S-blocked-on-external, S-fails-tidy

#24007 Use ipc router in webdriver
  components/webdriver_server/lib.rs
Labels: S-awaiting-merge

#24008 HoloLens URL handler
  support/hololens/ServoApp/App.cpp
  support/hololens/ServoApp/App.h
  support/hololens/ServoApp/BrowserPage.cpp
  support/hololens/ServoApp/BrowserPage.h
  support/hololens/ServoApp/Package.appxmanifest
  support/hololens/ServoApp/ServoControl/Servo.cpp
  support/hololens/ServoApp/ServoControl/Servo.h
  support/hololens/ServoApp/ServoControl/ServoControl.cpp
  support/hololens/ServoApp/ServoControl/ServoControl.h
  support/hololens/ServoApp/pch.h
Labels: S-awaiting-merge

#23934 Introduce a namespace installer
  Cargo.lock
  components/constellation/constellation.rs
  components/constellation/pipeline.rs
  components/msg/Cargo.toml
  components/msg/constellation_msg.rs
  components/msg/lib.rs
  components/script/dom/workerglobalscope.rs
Labels: S-awaiting-merge

#24025 Add x64 UWP to CI
  etc/taskcluster/decision_task.py
Labels: S-awaiting-merge

#23947 Finish the JSON clone algorithm for WebDriver
  components/script/webdriver_handlers.rs
  components/script_traits/webdriver_msg.rs
  components/webdriver_server/lib.rs
  tests/wpt/metadata/webdriver/tests/execute_script/cyclic.py.ini
  tests/wpt/metadata/webdriver/tests/get_element_property/get.py.ini
  tests/wpt/metadata/webdriver/tests/get_window_rect/get.py.ini
Labels: S-awaiting-merge

#23998 Do not leak the CAPI strings
  ports/libsimpleservo/capi/src/lib.rs
Labels: S-awaiting-merge

#23999 Missing C methods
  ports/libsimpleservo/api/src/lib.rs
  support/hololens/ServoApp/ServoControl/Servo.cpp
  support/hololens/ServoApp/ServoControl/Servo.h
  support/hololens/ServoApp/ServoControl/ServoControl.cpp
  support/hololens/ServoApp/ServoControl/ServoControl.h
Labels: S-awaiting-merge

#24018 Allow setting near/far clip planes
  Cargo.lock
  components/script/dom/xrsession.rs
Labels: S-awaiting-merge

#24041 In mach, add arguments to bare uses of is_windows
  python/servo/command_base.py
Labels: A-build, S-awaiting-merge

#24040 Updated magicleap gtstreamer tarball
  python/servo/build_commands.py
Labels: A-content/media, P-magic leap, S-awaiting-merge

#24046 Update Window::open and document::open parameters to match the spec
  components/script/dom/document.rs
  components/script/dom/webidls/Document.webidl
  components/script/dom/webidls/Window.webidl
  components/script/dom/window.rs
  components/script/dom/windowproxy.rs
  tests/wpt/metadata/fetch/security/embedded-credentials.tentative.sub.html.ini
  tests/wpt/metadata/html/browsers/the-window-object/window-open-defaults.window.js.ini
Labels: S-awaiting-merge

#23996 Implement pointerMove webdriver action
  components/compositing/compositor.rs
  components/compositing/compositor_thread.rs
  components/constellation/constellation.rs
  components/script/script_thread.rs
  components/script/webdriver_handlers.rs
  components/script_traits/lib.rs
  components/script_traits/webdriver_msg.rs
  components/webdriver_server/actions.rs
  components/webdriver_server/lib.rs
Labels: S-awaiting-merge

#24027 Updated magicleap signing cert
  etc/taskcluster/decision_task.py
Labels: P-magic leap, S-awaiting-merge

#24051 build_commands: Make Visual Studio detection not assume environment
  python/servo/build_commands.py
Labels: S-awaiting-merge

#24054 Upgrade to rustc 1.39.0-nightly (521d78407 2019-08-25)
  components/script_plugins/unrooted_must_root.rs
  components/script_plugins/webidl_must_inherit.rs
  rust-toolchain
Labels: S-awaiting-merge

#24004 Enable GStreamer on Windows.
  components/servo/Cargo.toml
  components/servo/lib.rs
  python/servo/build_commands.py
  support/hololens/ServoApp/ServoApp.vcxproj
  support/hololens/ServoApp/ServoApp.vcxproj.filters
Labels: S-awaiting-merge

#24055 Fix extension querying when using WebGL2
  components/canvas/webgl_thread.rs
Labels: S-awaiting-merge

#24058 Update ipc-channel and related dependencies
  Cargo.lock
  components/background_hang_monitor/Cargo.toml
  components/bluetooth/Cargo.toml
  components/bluetooth_traits/Cargo.toml
  components/canvas/Cargo.toml
  components/canvas_traits/Cargo.toml
  components/compositing/Cargo.toml
  components/constellation/Cargo.toml
  components/devtools/Cargo.toml
  components/devtools_traits/Cargo.toml
  components/embedder_traits/Cargo.toml
  components/gfx/Cargo.toml
  components/layout/Cargo.toml
  components/layout_2020/Cargo.toml
  components/layout_thread/Cargo.toml
  components/layout_thread_2020/Cargo.toml
  components/layout_traits/Cargo.toml
  components/media/Cargo.toml
  components/metrics/Cargo.toml
  components/msg/Cargo.toml
  components/net/Cargo.toml
  components/net_traits/Cargo.toml
  components/profile/Cargo.toml
  components/profile_traits/Cargo.toml
  components/script/Cargo.toml
  components/script_layout_interface/Cargo.toml
  components/script_traits/Cargo.toml
  components/servo/Cargo.toml
  components/webdriver_server/Cargo.toml
  components/webvr/Cargo.toml
  components/webvr_traits/Cargo.toml
  ports/glutin/Cargo.toml
  ports/libmlservo/Cargo.toml
  servo-tidy.toml
  tests/unit/metrics/Cargo.toml
  tests/unit/profile/Cargo.toml
Labels: S-awaiting-merge

#24063 Download platform-tools even for non-emulator builds
  python/servo/bootstrap_commands.py
Labels: S-awaiting-merge

#24065 Implement window.alert on Android
  support/android/apk/servoapp/src/main/java/org/mozilla/servo/MainActivity.java
Labels: S-awaiting-merge

#24072 Ensure documents drop when a pipeline exits
  components/script/dom/window.rs
  tests/wpt/metadata/html/cross-origin-embedder-policy/blob.https.html.ini
Labels: S-awaiting-merge

#24076 Update mozjs for VS 2017 changes.
  Cargo.lock
Labels: S-awaiting-merge

#24081 Update webxr for immersive-vr support.
  Cargo.lock
Labels: S-awaiting-merge

#24095 Switch to chromeless mode when app opens from a servo:// link
  support/hololens/ServoApp/App.cpp
  support/hololens/ServoApp/BrowserPage.cpp
  support/hololens/ServoApp/BrowserPage.h
  support/hololens/ServoApp/ServoControl/ServoControl.cpp
  support/hololens/ServoApp/ServoControl/ServoControl.h
  support/hololens/ServoApp/ServoControl/ServoControl.idl
  support/hololens/ServoApp/pch.h
Labels: S-awaiting-merge

#24099 Call gstreamer_root with top_dir string, not func.
  python/servo/command_base.py
Labels: S-awaiting-merge

#24105 Update hyper to 0.12.33.
  Cargo.lock
  components/net/tests/main.rs
Labels: S-awaiting-merge

#24120 Work around crash on Windows when returning JS::Value by value.
  Cargo.lock
  components/script/script_runtime.rs
Labels: S-awaiting-merge
