Repository servo/servo, pull requests merged in 2019-03, with the labels that each got.

#22954 Put the docs task into its own builder until it learns to behave
  etc/taskcluster/decision_task.py
Labels: S-awaiting-merge

#22933 Implement historical returnValue attribute for Event interface
  components/script/dom/event.rs
  components/script/dom/webidls/Event.webidl
  tests/wpt/metadata/dom/events/Event-defaultPrevented.html.ini
  tests/wpt/metadata/dom/events/Event-returnValue.html.ini
  tests/wpt/metadata/dom/events/EventTarget-dispatchEvent-returnvalue.html.ini
  tests/wpt/metadata/dom/interfaces.html.ini
Labels: S-awaiting-merge

#22928 implement historical cancelBubble attribute for Event interface
  components/script/dom/event.rs
  components/script/dom/webidls/Event.webidl
  tests/wpt/metadata/dom/events/Event-cancelBubble.html.ini
  tests/wpt/metadata/dom/events/Event-dispatch-bubble-canceled.html.ini
  tests/wpt/metadata/dom/events/Event-dispatch-multiple-cancelBubble.html.ini
  tests/wpt/metadata/dom/events/Event-initEvent.html.ini
  tests/wpt/metadata/dom/events/Event-propagation.html.ini
  tests/wpt/metadata/dom/interfaces.html.ini
Labels: S-awaiting-merge

#22622 Added AudioTrack, AudioTrackList, VideoTrack, and VideoTrackList inte…
  components/script/dom/audiotrack.rs
  components/script/dom/audiotracklist.rs
  components/script/dom/htmlmediaelement.rs
  components/script/dom/mod.rs
  components/script/dom/texttracklist.rs
  components/script/dom/trackevent.rs
  components/script/dom/videotrack.rs
  components/script/dom/videotracklist.rs
  components/script/dom/webidls/AudioTrack.webidl
  components/script/dom/webidls/AudioTrackList.webidl
  components/script/dom/webidls/HTMLMediaElement.webidl
  components/script/dom/webidls/TrackEvent.webidl
  components/script/dom/webidls/VideoTrack.webidl
  components/script/dom/webidls/VideoTrackList.webidl
  tests/wpt/metadata/html/dom/interfaces.https.html.ini
  tests/wpt/metadata/html/semantics/embedded-content/media-elements/interfaces/TrackEvent/constructor.html.ini
  tests/wpt/metadata/html/semantics/embedded-content/media-elements/interfaces/TrackEvent/createEvent.html.ini
  tests/wpt/mozilla/meta/MANIFEST.json
  tests/wpt/mozilla/tests/mozilla/interfaces.html
Labels: S-awaiting-merge

#22963 Upgrade to rustc 1.34.0-nightly (0ea22717a 2019-03-02)
  components/script/dom/bindings/conversions.rs
  components/script/lib.rs
  components/script_plugins/unrooted_must_root.rs
  rust-toolchain
Labels: S-awaiting-merge

#22953 Use a test VRDisplay that renders to a GL window
  Cargo.lock
  components/compositing/Cargo.toml
  components/compositing/compositor.rs
  components/compositing/compositor_thread.rs
  components/compositing/windowing.rs
  components/servo/lib.rs
  components/webvr/Cargo.toml
  components/webvr/lib.rs
  components/webvr_traits/lib.rs
  ports/libsimpleservo/api/src/lib.rs
  ports/servo/Cargo.toml
  ports/servo/glutin_app/window.rs
Labels: A-webvr, S-awaiting-merge

#22808 Avoid locking network timing data unnecessarily.
  components/net/http_loader.rs
Labels: S-tests-failed

#22992 Remove offscreen_gl_context dependency from canvas_traits and script
  Cargo.lock
  components/canvas/gl_context.rs
  components/canvas/webgl_thread.rs
  components/canvas_traits/Cargo.toml
  components/canvas_traits/webgl.rs
  components/script/Cargo.toml
  components/script/dom/bindings/trace.rs
  components/script/dom/htmlcanvaselement.rs
  components/script/dom/webgl2renderingcontext.rs
  components/script/dom/webglrenderingcontext.rs
  components/script/dom/webglshader.rs
Labels: S-awaiting-merge

#22995 Remove an unnecessary synchronous full reflow.
  components/script/dom/document.rs
Labels: S-awaiting-merge

#22851 Make blank target imply noopener, implement "opener" link type
  components/script/dom/htmlanchorelement.rs
Labels: S-awaiting-merge

#23010 Sync WPT with upstream (09-03-2019)
  tests/wpt/metadata/FileAPI/url/url-with-fetch.any.js.ini
  tests/wpt/metadata/css/css-flexbox/intrinsic-width-overflow-auto.tentative.html.ini
  tests/wpt/metadata/css/css-fonts/variations/at-font-face-font-matching.html.ini
  tests/wpt/metadata/html/browsers/history/the-history-interface/traverse_the_history_3.html.ini
  tests/wpt/metadata/html/browsers/history/the-history-interface/traverse_the_history_4.html.ini
  tests/wpt/metadata/html/browsers/history/the-history-interface/traverse_the_history_5.html.ini
  tests/wpt/metadata/html/semantics/embedded-content/the-img-element/non-active-document.html.ini
  tests/wpt/metadata/html/semantics/interactive-elements/the-details-element/toggleEvent.html.ini
  tests/wpt/metadata/html/semantics/scripting-1/the-script-element/script-onerror-insertion-point-2.html.ini
  tests/wpt/metadata/html/syntax/parsing/DOMContentLoaded-defer.html.ini
  tests/wpt/metadata/html/webappapis/dynamic-markup-insertion/document-write/iframe_005.html.ini
  tests/wpt/web-platform-tests/css/css-flexbox/intrinsic-width-overflow-auto.tentative.html
  tests/wpt/web-platform-tests/idle-detection/interceptor.https.html
  tests/wpt/web-platform-tests/idle-detection/mock.js
  tests/wpt/web-platform-tests/interfaces/mediasession.idl
Labels: S-awaiting-merge

#22966 Simplify VideoTrackList::set_selected
  components/script/dom/videotracklist.rs
Labels: S-awaiting-merge

#23014 Move docs build back into tidy+unit builder, disable minification
  etc/taskcluster/decision_task.py
Labels: S-awaiting-merge

#23007 Remove pipeline visibility checks
  components/constellation/constellation.rs
  components/script/dom/htmliframeelement.rs
  components/script_traits/script_msg.rs
Labels: S-awaiting-merge

#23022 Route all trychooser tasks to servo-try.
  .taskcluster.yml
Labels: S-awaiting-merge

#23033 Stop cloning response text on every chunk in XHR
  components/script/dom/xmlhttprequest.rs
Labels: S-tests-failed

#23016 Remove 'on' prefix from event handler macros
  components/script/dom/permissionstatus.rs
  components/script/dom/texttrack.rs
  components/script/dom/texttrackcue.rs
  components/script/dom/texttracklist.rs
  tests/wpt/metadata/html/semantics/embedded-content/media-elements/interfaces/TextTrack/oncuechange.html.ini
  tests/wpt/metadata/html/semantics/embedded-content/media-elements/interfaces/TextTrackList/onaddtrack.html.ini
  tests/wpt/metadata/html/semantics/embedded-content/media-elements/interfaces/TextTrackList/onremovetrack.html.ini
Labels: S-awaiting-merge

#23036 Fix substraction with overflow in range request
  components/net/http_cache.rs
Labels: S-awaiting-merge

#23048 Add url for LayoutImageContext
  components/script/layout_image.rs
Labels: S-tests-failed

#23021 Assert fail #18439
  components/script/document_loader.rs
  components/script/script_thread.rs
Labels: S-awaiting-merge

#22891 Implement CDATASection interface and createCDATASection method
  components/layout_thread/dom_wrapper.rs
  components/script/dom/cdatasection.rs
  components/script/dom/characterdata.rs
  components/script/dom/document.rs
  components/script/dom/mod.rs
  components/script/dom/node.rs
  components/script/dom/range.rs
  components/script/dom/servoparser/html.rs
  components/script/dom/text.rs
  components/script/dom/webidls/CDATASection.webidl
  components/script/dom/webidls/Document.webidl
  components/script/lib.rs
  tests/wpt/metadata/dom/interfaces.html.ini
  tests/wpt/metadata/dom/nodes/Node-insertBefore.html.ini
  tests/wpt/metadata/dom/nodes/Node-replaceChild.html.ini
  tests/wpt/metadata/html/semantics/forms/the-textarea-element/value-defaultValue-textContent-xhtml.xhtml.ini
  tests/wpt/mozilla/meta/MANIFEST.json
  tests/wpt/mozilla/tests/mozilla/interfaces.html
Labels: S-awaiting-merge

#23060 Fix the broken link in about-page
  tests/html/about-mozilla.html
Labels: S-awaiting-merge

#23058 Update webdriver crate
  Cargo.lock
Labels: S-awaiting-merge

#23029 Update StyleSheet.insertRule WebIDL to make index optional.
  components/script/dom/webidls/CSSStyleSheet.webidl
  tests/wpt/metadata/css/cssom/insertRule-charset-no-index.html.ini
  tests/wpt/metadata/css/cssom/insertRule-import-no-index.html.ini
  tests/wpt/metadata/css/cssom/insertRule-namespace-no-index.html.ini
  tests/wpt/metadata/css/cssom/insertRule-no-index.html.ini
  tests/wpt/metadata/css/cssom/interfaces.html.ini
Labels: S-awaiting-merge

#22923 #8539 Config preferences backend restructure
  Cargo.lock
  components/bluetooth/lib.rs
  components/canvas/webgl_mode/inprocess.rs
  components/config/Cargo.toml
  components/config/lib.rs
  components/config/opts.rs
  components/config/pref_util.rs
  components/config/prefs.rs
  components/config/tests/opts.rs
  components/config/tests/prefs.rs
  components/config_plugins/Cargo.toml
  components/config_plugins/lib.rs
  components/config_plugins/parse.rs
  components/constellation/constellation.rs
  components/constellation/pipeline.rs
  components/layout_thread/lib.rs
  components/net/filemanager_thread.rs
  components/net/http_cache.rs
  components/net/lib.rs
  components/net/tests/filemanager_thread.rs
  components/script/dom/bindings/codegen/CodegenRust.py
  components/script/dom/bindings/guard.rs
  components/script/dom/create.rs
  components/script/dom/document.rs
  components/script/dom/htmlcanvaselement.rs
  components/script/dom/htmlmediaelement.rs
  components/script/dom/htmlmetaelement.rs
  components/script/dom/mouseevent.rs
  components/script/dom/paintworkletglobalscope.rs
  components/script/dom/permissions.rs
  components/script/dom/serviceworkerglobalscope.rs
  components/script/dom/servoparser/mod.rs
  components/script/dom/testbinding.rs
  components/script/dom/webglrenderingcontext.rs
  components/script/script_runtime.rs
  components/script/serviceworker_manager.rs
  components/script/timers.rs
  components/servo/lib.rs
  components/style/global_style_data.rs
  components/style/properties/properties.mako.rs
  components/style/stylesheets/viewport_rule.rs
  components/webdriver_server/lib.rs
  components/webvr/webvr_thread.rs
  docs/COMMAND_LINE_ARGS.md
  ports/libsimpleservo/api/src/lib.rs
  ports/servo/browser.rs
  ports/servo/glutin_app/window.rs
  ports/servo/non_android_main.rs
  resources/prefs.json
  tests/unit/style/stylesheets.rs
  tests/unit/style/viewport.rs
  tests/wpt/metadata/css/css-flexbox/__dir__.ini
  tests/wpt/mozilla/meta/css/__dir__.ini
Labels: S-awaiting-merge

#23045 create uuid before sending PromoteMemory message
  components/net/filemanager_thread.rs
  components/net/tests/fetch.rs
  components/net_traits/filemanager_thread.rs
  components/script/dom/blob.rs
Labels: S-awaiting-merge

#23049 Edit Selector Implementation to be concise
  docs/components/style.md
Labels: S-awaiting-merge

#23044 Implement XMLSerializer interface
  components/script/dom/mod.rs
  components/script/dom/webidls/XMLSerializer.webidl
  components/script/dom/xmlserializer.rs
  tests/wpt/metadata/domparsing/XMLSerializer-serializeToString.html.ini
  tests/wpt/metadata/domparsing/interfaces.any.js.ini
  tests/wpt/metadata/domparsing/xml-serialization.xhtml.ini
  tests/wpt/mozilla/meta/MANIFEST.json
  tests/wpt/mozilla/tests/mozilla/interfaces.html
Labels: S-awaiting-merge

#23079 #23065 removed unnecessary headless checking
  components/bluetooth/lib.rs
Labels: S-awaiting-merge

#23084 Update README.md - fixes Requirements for Fedora
  README.md
Labels: S-awaiting-merge

#23011 Add tokenizer for features in window.open
  components/script/dom/windowproxy.rs
  tests/wpt/metadata/html/browsers/the-window-object/apis-for-creating-and-navigating-browsing-contexts-by-name/open-features-tokenization-noopener.html.ini
  tests/wpt/metadata/html/browsers/the-window-object/apis-for-creating-and-navigating-browsing-contexts-by-name/open-features-tokenization-noreferrer.html.ini
Labels: S-awaiting-merge

#23069 Compare gstreamer version via `pkg-config --modversion` in bootstrap python script
  python/servo/bootstrap.py
Labels: S-awaiting-merge

#23002 Fix bleeding in FxR by adding Padding support to ServoSurface
  components/compositing/compositor.rs
  components/compositing/windowing.rs
  ports/libmlservo/src/lib.rs
  ports/libsimpleservo/api/src/lib.rs
  ports/libsimpleservo/capi/src/lib.rs
  ports/libsimpleservo/jniapi/src/lib.rs
  support/android/apk/servoview/src/main/java/org/mozilla/servoview/JNIServo.java
  support/android/apk/servoview/src/main/java/org/mozilla/servoview/Servo.java
  support/android/apk/servoview/src/main/java/org/mozilla/servoview/ServoSurface.java
  support/android/apk/servoview/src/main/java/org/mozilla/servoview/ServoView.java
Labels: S-awaiting-merge

#23085 Defer update of dom_content_loaded_event_end
  components/script/dom/document.rs
Labels: S-awaiting-merge

#23094 Update Event's timestamp
  components/script/dom/event.rs
  components/script/dom/webidls/Event.webidl
  tests/wpt/metadata/dom/events/Event-timestamp-high-resolution.html.ini
  tests/wpt/metadata/dom/events/Event-timestamp-safe-resolution.html.ini
Labels: S-awaiting-merge

#23095 Use mozjs profiling feature when building with frame pointer enabled
  Cargo.lock
  components/script/Cargo.toml
  components/servo/Cargo.toml
  ports/servo/Cargo.toml
  python/servo/build_commands.py
Labels: S-awaiting-merge

#23092 ISSUE-23088: updated deprecated links in HACKING_QUICKSTART
  docs/HACKING_QUICKSTART.md
Labels: S-awaiting-merge

#23102 Upgrade to rustc 1.35.0-nightly (4c27fb19b 2019-03-25)
  components/script/dom/bindings/error.rs
  components/script/dom/webglrenderingcontext.rs
  components/script_plugins/unrooted_must_root.rs
  components/style/bloom.rs
  components/style/font_face.rs
  components/style/stylist.rs
  rust-toolchain
Labels: S-awaiting-merge

#23106 Invert worker type selection logic for taskcluster.
  etc/taskcluster/decision_task.py
  etc/taskcluster/decisionlib.py
Labels: S-awaiting-merge

#23111 Update `mach bootstrap-gstreamer` to use the latest binaries
  python/servo/bootstrap.py
  python/servo/command_base.py
  support/linux/gstreamer/.gitignore
  support/linux/gstreamer/gstreamer.sh
Labels: S-awaiting-merge

#23117 Set the target when packaging for magicleap
  python/servo/package_commands.py
Labels: A-build, P-magic leap, S-awaiting-merge

#23112 Use consistent local branch name for WPT sync.
  etc/ci/update-wpt-checkout
Labels: S-awaiting-merge

#23142 Sync WPT with upstream (30-03-2019)
  tests/wpt/metadata/FileAPI/url/url-with-fetch.any.js.ini
  tests/wpt/metadata/fetch/content-type/response.window.js.ini
  tests/wpt/metadata/fetch/nosniff/parsing-nosniff.window.js.ini
  tests/wpt/metadata/html/browsers/browsing-the-web/navigating-across-documents/javascript-url-abort/javascript-url-abort-return-value-string.tentative.html.ini
  tests/wpt/metadata/html/browsers/history/the-history-interface/traverse_the_history_4.html.ini
  tests/wpt/metadata/html/browsers/history/the-history-interface/traverse_the_history_5.html.ini
  tests/wpt/metadata/html/semantics/interactive-elements/the-details-element/toggleEvent.html.ini
  tests/wpt/metadata/performance-timeline/idlharness.any.js.ini
  tests/wpt/mozilla/meta/mozilla/scroll_root.html.ini
  tests/wpt/web-platform-tests/css/css-lists/list-item-definition-ref.html
  tests/wpt/web-platform-tests/css/css-lists/list-item-definition.html
  tests/wpt/web-platform-tests/css/css-position/position-absolute-crash-chrome-004.html
  tests/wpt/web-platform-tests/fetch/sec-metadata/embed.tentative.https.sub.html
  tests/wpt/web-platform-tests/fetch/sec-metadata/fetch.tentative.https.sub.html
  tests/wpt/web-platform-tests/fetch/sec-metadata/font.tentative.https.sub.html
  tests/wpt/web-platform-tests/fetch/sec-metadata/iframe.tentative.https.sub.html
  tests/wpt/web-platform-tests/fetch/sec-metadata/img.tentative.https.sub.html
  tests/wpt/web-platform-tests/fetch/sec-metadata/object.tentative.https.sub.html
  tests/wpt/web-platform-tests/fetch/sec-metadata/redirect/cross-site-redirect.tentative.https.sub.html
  tests/wpt/web-platform-tests/fetch/sec-metadata/redirect/multiple-redirect-cross-site.tentative.https.sub.html
  tests/wpt/web-platform-tests/fetch/sec-metadata/redirect/multiple-redirect-same-site.tentative.https.sub.html
  tests/wpt/web-platform-tests/fetch/sec-metadata/redirect/same-origin-redirect.tentative.https.sub.html
  tests/wpt/web-platform-tests/fetch/sec-metadata/redirect/same-site-redirect.tentative.https.sub.html
  tests/wpt/web-platform-tests/fetch/sec-metadata/report.tentative.https.sub.html
  tests/wpt/web-platform-tests/fetch/sec-metadata/script.tentative.https.sub.html
  tests/wpt/web-platform-tests/fetch/sec-metadata/serviceworker.tentative.https.sub.html
  tests/wpt/web-platform-tests/fetch/sec-metadata/sharedworker.tentative.https.sub.html
  tests/wpt/web-platform-tests/fetch/sec-metadata/style.tentative.https.sub.html
  tests/wpt/web-platform-tests/fetch/sec-metadata/track.tentative.https.sub.html
  tests/wpt/web-platform-tests/fetch/sec-metadata/trailing-dot.tentative.https.sub.html
  tests/wpt/web-platform-tests/fetch/sec-metadata/window-open.tentative.https.sub.html
  tests/wpt/web-platform-tests/fetch/sec-metadata/worker.tentative.https.sub.html
  tests/wpt/web-platform-tests/fetch/sec-metadata/xslt.tentative.https.sub.html
  tests/wpt/web-platform-tests/html/semantics/scripting-1/the-script-element/module/dynamic-import/string-compilation-integrity-classic.sub.html
  tests/wpt/web-platform-tests/html/semantics/scripting-1/the-script-element/module/dynamic-import/string-compilation-integrity-module.sub.html
  tests/wpt/web-platform-tests/interfaces/performance-timeline.idl
Labels: S-awaiting-merge

#23139 Bound sampler buffer, add length feedback message, fix intermittence in test
  components/background_hang_monitor/background_hang_monitor.rs
  components/background_hang_monitor/tests/hang_monitor_tests.rs
  components/compositing/windowing.rs
  components/constellation/constellation.rs
  components/msg/constellation_msg.rs
  components/script_traits/lib.rs
  components/servo/lib.rs
  ports/servo/browser.rs
Labels: S-awaiting-merge
