Repository servo/servo, pull requests merged in 2019-11, with the labels that each got.

#24597 UWP: More mouse events
  ports/libmlservo/src/lib.rs
  ports/libsimpleservo/api/src/lib.rs
  ports/libsimpleservo/capi/src/lib.rs
  support/hololens/ServoApp/ServoControl/Servo.h
  support/hololens/ServoApp/ServoControl/ServoControl.cpp
  support/hololens/ServoApp/ServoControl/ServoControl.h
Labels: S-awaiting-merge

#24482 Use surfman for managing GL surfaces
  Cargo.lock
  components/background_hang_monitor/Cargo.toml
  components/canvas/Cargo.toml
  components/canvas/gl_context.rs
  components/canvas/lib.rs
  components/canvas/webgl_limits.rs
  components/canvas/webgl_mode/inprocess.rs
  components/canvas/webgl_mode/mod.rs
  components/canvas/webgl_thread.rs
  components/canvas_traits/Cargo.toml
  components/canvas_traits/webgl.rs
  components/compositing/compositor.rs
  components/compositing/windowing.rs
  components/constellation/Cargo.toml
  components/constellation/constellation.rs
  components/script/dom/bindings/trace.rs
  components/script/dom/document.rs
  components/script/dom/webgl2renderingcontext.rs
  components/script/dom/webglframebuffer.rs
  components/script/dom/webglprogram.rs
  components/script/dom/webglrenderbuffer.rs
  components/script/dom/webglrenderingcontext.rs
  components/script/dom/webgltexture.rs
  components/script/dom/webgluniformlocation.rs
  components/script/dom/xrsession.rs
  components/script/dom/xrwebgllayer.rs
  components/servo/Cargo.toml
  components/servo/lib.rs
  etc/ci/check_dynamic_symbols.py
  etc/taskcluster/decision_task.py
  ports/glutin/Cargo.toml
  ports/glutin/embedder.rs
  ports/glutin/headed_window.rs
  ports/glutin/headless_window.rs
  ports/libsimpleservo/api/Cargo.toml
  ports/libsimpleservo/api/src/lib.rs
  ports/libsimpleservo/capi/Cargo.toml
  python/servo/build_commands.py
  python/servo/command_base.py
  servo-tidy.toml
  support/hololens/ServoApp/ServoApp.vcxproj
  tests/wpt/metadata/webxr/xrWebGLLayer_framebuffer_draw.https.html.ini
  tests/wpt/metadata/webxr/xrWebGLLayer_opaque_framebuffer.https.html.ini
  tests/wpt/webgl/meta/MANIFEST.json
  tests/wpt/webgl/meta/conformance/canvas/drawingbuffer-static-canvas-test.html.ini
  tests/wpt/webgl/meta/conformance/canvas/drawingbuffer-test.html.ini
  tests/wpt/webgl/meta/conformance/rendering/more-than-65536-indices.html.ini
  tests/wpt/webgl/meta/conformance/rendering/rendering-stencil-large-viewport.html.ini
  tests/wpt/webgl/meta/conformance/textures/misc/copy-tex-image-and-sub-image-2d.html.ini
  tests/wpt/webgl/meta/conformance2/reading/read-pixels-pack-parameters.html.ini
  tests/wpt/webgl/tests/conformance/rendering/preservedrawingbuffer-leak.html
  tests/wpt/webgl/tools/timeout.patch
Labels: S-awaiting-merge

#24620 Update surfman for EGL alpha fix.
  Cargo.lock
Labels: S-awaiting-merge

#24616 Store Option<ImageInfo> instead of making fields of ImageInfo optional
  components/script/dom/webgl_validations/tex_image_2d.rs
  components/script/dom/webglframebuffer.rs
  components/script/dom/webglrenderingcontext.rs
  components/script/dom/webgltexture.rs
Labels: S-awaiting-merge

#24619 Adding a check for "Linux Mint" with a space
  python/servo/bootstrap.py
Labels: S-awaiting-merge

#24603 Install rustc-dev for nightly rust toolchain
  etc/taskcluster/decision_task.py
Labels: S-awaiting-merge

#24563 Binding stream consumer to support asynchronous WebAssembly compilation
  components/script/script_runtime.rs
Labels: S-awaiting-merge

#24639 Xaml keybindings
  support/hololens/ServoApp/BrowserPage.cpp
  support/hololens/ServoApp/BrowserPage.h
  support/hololens/ServoApp/BrowserPage.xaml
Labels: S-awaiting-merge

#24655 Patch surfman and webxr
  Cargo.lock
  Cargo.toml
Labels: S-awaiting-merge

#24473 Implement the basic WebGL2 buffer data operations
  components/canvas/webgl_thread.rs
  components/canvas_traits/webgl.rs
  components/script/dom/webgl2renderingcontext.rs
  components/script/dom/webglbuffer.rs
  components/script/dom/webglrenderingcontext.rs
  components/script/dom/webidls/WebGL2RenderingContext.webidl
  tests/wpt/webgl/meta/conformance2/buffers/buffer-copying-contents.html.ini
  tests/wpt/webgl/meta/conformance2/buffers/buffer-copying-restrictions.html.ini
  tests/wpt/webgl/meta/conformance2/buffers/buffer-data-and-buffer-sub-data-sub-source.html.ini
  tests/wpt/webgl/meta/conformance2/buffers/get-buffer-sub-data.html.ini
  tests/wpt/webgl/meta/conformance2/context/methods-2.html.ini
  tests/wpt/webgl/meta/conformance2/reading/read-pixels-into-pixel-pack-buffer.html.ini
  tests/wpt/webgl/meta/conformance2/rendering/out-of-bounds-index-buffers-after-copying.html.ini
Labels: S-awaiting-merge

#24644 Use IDL sequence default value
  components/script/dom/bindings/codegen/CodegenRust.py
  components/script/dom/bluetooth.rs
  components/script/dom/dedicatedworkerglobalscope.rs
  components/script/dom/dissimilaroriginwindow.rs
  components/script/dom/messageport.rs
  components/script/dom/serviceworker.rs
  components/script/dom/webidls/Bluetooth.webidl
  components/script/dom/webidls/BluetoothPermissionResult.webidl
  components/script/dom/webidls/DissimilarOriginWindow.webidl
  components/script/dom/webidls/MessagePort.webidl
  components/script/dom/webidls/Window.webidl
  components/script/dom/window.rs
  components/script/dom/worker.rs
Labels: S-awaiting-merge

#24590 Fix timing allow check
  components/net/http_loader.rs
Labels: S-awaiting-merge

#24661 Only updated history once
  components/constellation/constellation.rs
Labels: S-awaiting-merge

#24634 Do not assume UWP and Servo agree on URL validity
  ports/libsimpleservo/api/src/lib.rs
  ports/libsimpleservo/capi/src/lib.rs
  support/hololens/ServoApp/BrowserPage.cpp
  support/hololens/ServoApp/ServoControl/Servo.h
  support/hololens/ServoApp/ServoControl/ServoControl.cpp
  support/hololens/ServoApp/ServoControl/ServoControl.h
  support/hololens/ServoApp/ServoControl/ServoControl.idl
Labels: S-awaiting-merge

#24646 No need to cancel the task. The thread is ending.
  support/hololens/ServoApp/ServoControl/ServoControl.cpp
Labels: S-awaiting-merge

#24672 Print an error if Glutin port needs to manage a new tab
  ports/glutin/browser.rs
Labels: S-awaiting-merge

#24683 Split doc generation into its own task
  etc/taskcluster/decision_task.py
Labels: S-awaiting-merge

#24681 Add missing import to docs upload script.
  etc/taskcluster/decision_task.py
Labels: S-awaiting-merge

#24689 Move all tasks to Community-TC
  etc/taskcluster/decision_task.py
  etc/taskcluster/decisionlib.py
  etc/taskcluster/mock.py
Labels: S-awaiting-merge

#24514 Add WebGL Transformfeedback support
  Cargo.lock
  components/canvas/webgl_limits.rs
  components/canvas/webgl_thread.rs
  components/canvas_traits/webgl.rs
  components/script/dom/mod.rs
  components/script/dom/webgl2renderingcontext.rs
  components/script/dom/webglprogram.rs
  components/script/dom/webglrenderingcontext.rs
  components/script/dom/webgltransformfeedback.rs
  components/script/dom/webidls/WebGL2RenderingContext.webidl
  components/script/dom/webidls/WebGLTransformFeedback.webidl
  tests/wpt/webgl/meta/conformance2/buffers/get-buffer-sub-data-validity.html.ini
  tests/wpt/webgl/meta/conformance2/context/methods-2.html.ini
  tests/wpt/webgl/meta/conformance2/misc/expando-loss-2.html.ini
  tests/wpt/webgl/meta/conformance2/state/gl-object-get-calls.html.ini
  tests/wpt/webgl/meta/conformance2/transform_feedback/non-existent-varying.html.ini
  tests/wpt/webgl/meta/conformance2/transform_feedback/unwritten-output-defaults-to-zero.html.ini
Labels: S-awaiting-merge

#24690 derive_common: Fix example in documentation
  components/derive_common/cg.rs
Labels: S-awaiting-merge

#24524 Make offscreen canvas rendering context use offscreen canvas' size; Consolidate size helpers
  Cargo.lock
  components/canvas/canvas_data.rs
  components/canvas/canvas_paint_thread.rs
  components/canvas_traits/canvas.rs
  components/pixels/lib.rs
  components/script/canvas_state.rs
  components/script/dom/canvasrenderingcontext2d.rs
  components/script/dom/htmlcanvaselement.rs
  components/script/dom/imagedata.rs
  components/script/dom/offscreencanvas.rs
  components/script/dom/offscreencanvasrenderingcontext2d.rs
  components/script/dom/paintrenderingcontext2d.rs
  components/script/dom/webglrenderingcontext.rs
  components/script/euclidext.rs
  components/script/lib.rs
  tests/wpt/metadata/offscreen-canvas/fill-and-stroke-styles/2d.gradient.interpolate.multiple.html.ini
  tests/wpt/metadata/offscreen-canvas/fill-and-stroke-styles/2d.gradient.interpolate.multiple.worker.js.ini
  tests/wpt/metadata/offscreen-canvas/fill-and-stroke-styles/2d.gradient.interpolate.overlap.html.ini
  tests/wpt/metadata/offscreen-canvas/fill-and-stroke-styles/2d.gradient.interpolate.overlap.worker.js.ini
  tests/wpt/metadata/offscreen-canvas/the-offscreen-canvas/initial.reset.2dstate.html.ini
  tests/wpt/metadata/offscreen-canvas/the-offscreen-canvas/initial.reset.2dstate.worker.js.ini
  tests/wpt/metadata/offscreen-canvas/the-offscreen-canvas/initial.reset.clip.html.ini
  tests/wpt/metadata/offscreen-canvas/the-offscreen-canvas/initial.reset.clip.worker.js.ini
  tests/wpt/metadata/offscreen-canvas/the-offscreen-canvas/initial.reset.different.html.ini
  tests/wpt/metadata/offscreen-canvas/the-offscreen-canvas/initial.reset.different.worker.js.ini
  tests/wpt/metadata/offscreen-canvas/the-offscreen-canvas/initial.reset.gradient.html.ini
  tests/wpt/metadata/offscreen-canvas/the-offscreen-canvas/initial.reset.gradient.worker.js.ini
  tests/wpt/metadata/offscreen-canvas/the-offscreen-canvas/initial.reset.same.html.ini
  tests/wpt/metadata/offscreen-canvas/the-offscreen-canvas/initial.reset.same.worker.js.ini
  tests/wpt/metadata/offscreen-canvas/the-offscreen-canvas/initial.reset.transform.html.ini
  tests/wpt/metadata/offscreen-canvas/the-offscreen-canvas/initial.reset.transform.worker.js.ini
  tests/wpt/metadata/offscreen-canvas/the-offscreen-canvas/offscreencanvas.resize.html.ini
Labels: S-awaiting-merge

#24653 Add consume stream callback
  components/script/script_runtime.rs
  tests/wpt/metadata/wasm/jsapi/constructor/compile.any.js.ini
  tests/wpt/metadata/wasm/jsapi/constructor/instantiate-bad-imports.any.js.ini
  tests/wpt/metadata/wasm/jsapi/constructor/instantiate.any.js.ini
  tests/wpt/metadata/wasm/jsapi/idlharness.any.js.ini
  tests/wpt/metadata/wasm/serialization/module/broadcastchannel-success.html.ini
  tests/wpt/metadata/wasm/serialization/module/identity-not-preserved.html.ini
  tests/wpt/metadata/wasm/serialization/module/nested-worker-success.any.js.ini
  tests/wpt/metadata/wasm/serialization/module/window-domain-success.sub.html.ini
  tests/wpt/metadata/wasm/serialization/module/window-messagechannel-success.html.ini
  tests/wpt/metadata/wasm/serialization/module/window-similar-but-cross-origin-success.sub.html.ini
  tests/wpt/metadata/wasm/serialization/module/window-simple-success.html.ini
  tests/wpt/metadata/wasm/webapi/body.any.js.ini
  tests/wpt/metadata/wasm/webapi/contenttype.any.js.ini
  tests/wpt/metadata/wasm/webapi/empty-body.any.js.ini
  tests/wpt/metadata/wasm/webapi/instantiateStreaming-bad-imports.any.js.ini
  tests/wpt/metadata/wasm/webapi/instantiateStreaming.any.js.ini
  tests/wpt/metadata/wasm/webapi/invalid-args.any.js.ini
  tests/wpt/metadata/wasm/webapi/invalid-code.any.js.ini
  tests/wpt/metadata/wasm/webapi/origin.sub.any.js.ini
  tests/wpt/metadata/wasm/webapi/rejected-arg.any.js.ini
  tests/wpt/metadata/wasm/webapi/status.any.js.ini
Labels: S-tests-failed

#24709 Properly set event.buttons value on mousemove
  components/compositing/compositor.rs
  components/constellation/constellation.rs
  support/hololens/ServoApp/ServoControl/ServoControl.cpp
Labels: S-awaiting-merge

#24712 Revert "Upload uncompressed Docker images"
  etc/taskcluster/decisionlib.py
Labels: S-awaiting-merge

#24711 Make `./mach rustup` install the rustc-dev component
  python/servo/devenv_commands.py
Labels: S-awaiting-merge

#24674 Correct inverted logic for available image checks.
  components/script/dom/htmlimageelement.rs
Labels: S-awaiting-merge

#24624 Fix keypress trigger condition
  components/script/dom/document.rs
Labels: S-awaiting-merge

#24717 Fix sccache failure when rustc generates thousands of warnings
  etc/ci/buildbot_steps.yml
  etc/taskcluster/decision_task.py
Labels: S-awaiting-merge

#24567 mach bootstrap - activate virtual env
  python/mach_bootstrap.py
Labels: S-awaiting-merge

#24734 Better tooltip for UWP port
  support/hololens/ServoApp/BrowserPage.xaml
Labels: S-awaiting-merge

#24741 Update Tetsuharu OHZEKI's entry in mailmap
  .mailmap
Labels: S-awaiting-merge

#24736 layout: Ensure abs-pos elements establish block formatting contexts
  components/layout/block.rs
  tests/wpt/mozilla/meta/MANIFEST.json
  tests/wpt/mozilla/tests/css/absolute_block_format_ctx.html
  tests/wpt/mozilla/tests/css/absolute_block_format_ctx_ref.html
Labels: S-awaiting-merge

#24746 Update surfman-chains
  Cargo.lock
Labels: S-awaiting-merge

#24749 Update to rustc 1.41.0-nightly (1bd30ce2a 2019-11-15)
  rust-toolchain
Labels: S-awaiting-merge

#24665 Use TimerHandler IDL union type
  components/script/dom/bindings/codegen/CodegenRust.py
  components/script/dom/webidls/WindowOrWorkerGlobalScope.webidl
  components/script/dom/window.rs
  components/script/dom/workerglobalscope.rs
  tests/wpt/metadata/html/webappapis/timers/evil-spec-example.html.ini
Labels: S-awaiting-merge

#24767 Update xargo
  python/servo/packages.py
Labels: S-awaiting-merge

#24664 Fix loophole in messageport transfer
  components/constellation/constellation.rs
  components/script/dom/globalscope.rs
  components/script_traits/lib.rs
  components/script_traits/script_msg.rs
  tests/wpt/mozilla/meta/MANIFEST.json
  tests/wpt/mozilla/tests/mozilla/Channel_postMessage_with_second_transfer_in_timeout.window.js
  tests/wpt/mozilla/tests/mozilla/Channel_postMessage_with_second_transfer_in_timeout_with_delay.window.js
Labels: S-awaiting-merge

#24775 Update harfbuzz-sys
  Cargo.lock
Labels: S-awaiting-merge

#24669 Set response mime_type based on Content-Type
  components/script/dom/response.rs
  tests/wpt/metadata/fetch/api/response/response-consume.html.ini
  tests/wpt/metadata/fetch/corb/script-html-via-cross-origin-blob-url.sub.html.ini
Labels: S-awaiting-merge

#24685 Fix revoke blob url
  components/net_traits/blob_url_store.rs
  components/script/dom/url.rs
  tests/wpt/metadata/FileAPI/url/url-with-fetch.any.js.ini
  tests/wpt/metadata/FileAPI/url/url-with-xhr.any.js.ini
Labels: S-awaiting-merge

#24752 Avoid recompiling script every time surfman changes
  Cargo.lock
  components/canvas/Cargo.toml
  components/canvas/webgl_mode/inprocess.rs
  components/canvas/webgl_thread.rs
  components/compositing/Cargo.toml
  components/compositing/compositor.rs
  components/compositing/compositor_thread.rs
  components/compositing/windowing.rs
  components/servo/Cargo.toml
  components/servo/lib.rs
  ports/glutin/embedder.rs
  ports/libsimpleservo/api/Cargo.toml
  ports/libsimpleservo/api/src/lib.rs
Labels: S-awaiting-merge

#24782 Prepend `-Ztimings=info`, don’t append, so it can be overridden
  python/servo/build_commands.py
Labels: S-awaiting-merge

#24651 Remove appveyor CI badge.
  README.md
  appveyor.yml
Labels: S-awaiting-merge

#24776 Support translation in webxr on desktop
  Cargo.lock
  ports/glutin/headed_window.rs
  ports/glutin/headless_window.rs
Labels: S-awaiting-merge

#24777 Enable webxr by default
  resources/prefs.json
  tests/wpt/metadata/webvr/__dir__.ini
  tests/wpt/mozilla/meta/MANIFEST.json
  tests/wpt/mozilla/tests/mozilla/interfaces.html
  tests/wpt/webgl/meta/conformance/context/methods.html.ini
Labels: S-awaiting-merge

#24798 Update jemalloc-sys to 0.3.2
  Cargo.lock
  components/allocator/Cargo.toml
Labels: S-awaiting-merge

#24692 Run test-tidy with CPP files check on Windows
  .clang-format
  etc/taskcluster/decision_task.py
  python/servo/lints/wpt_lint.py
  python/servo/testing_commands.py
  python/tidy/servo_tidy/tidy.py
Labels: S-awaiting-merge

#24817 Unindent Document::set_activity
  components/script/dom/document.rs
Labels: S-awaiting-merge

#24816 Require PromiseRejectionEventInit dictionary
  components/script/dom/bindings/codegen/CodegenRust.py
  components/script/dom/promiserejectionevent.rs
  components/script/dom/webidls/PromiseRejectionEvent.webidl
  tests/wpt/metadata/html/dom/idlharness.https.html.ini
  tests/wpt/metadata/html/dom/idlharness.worker.js.ini
Labels: S-awaiting-merge

#24789 Fix unloading, active BC, and clearing js runtime
  components/script/dom/window.rs
  components/script/script_thread.rs
  tests/wpt/metadata/html/semantics/scripting-1/the-script-element/execution-timing/083.html.ini
Labels: S-awaiting-merge

#24818 Prevent panic on layout send in finish-load
  components/script/script_thread.rs
Labels: S-awaiting-merge

#24838 Add support for squeeze events
  Cargo.lock
  components/atoms/static_atoms.txt
  components/script/dom/webidls/XRSession.webidl
  components/script/dom/xrsession.rs
  tests/wpt/metadata/webxr/idlharness.https.window.js.ini
Labels: S-awaiting-merge

#24680 Require FormDataEventInit dictionary
  components/script/dom/formdataevent.rs
  components/script/dom/webidls/FormDataEvent.webidl
  tests/wpt/metadata/html/dom/idlharness.https.html.ini
Labels: S-awaiting-merge

#24854 Prompt user to install OpenXR package if not installed
  support/hololens/ServoApp/BrowserPage.cpp
  support/hololens/ServoApp/BrowserPage.h
  support/hololens/ServoApp/BrowserPage.xaml
  support/hololens/ServoApp/Package.appxmanifest
  support/hololens/ServoApp/ServoApp.vcxproj
  support/hololens/ServoApp/ServoApp.vcxproj.filters
  support/hololens/ServoApp/XRPkgChecker.cpp
  support/hololens/ServoApp/XRPkgChecker.h
Labels: S-awaiting-merge

#24863 The gstreamer plugin should resize when it's presented with frames to fill
  ports/gstplugin/servosrc.rs
Labels: S-awaiting-merge

#24842 Make JS runnables for workers execute on correct event loop
  components/script/dom/dedicatedworkerglobalscope.rs
  tests/wpt/metadata/wasm/jsapi/constructor/compile.any.js.ini
  tests/wpt/metadata/wasm/jsapi/constructor/instantiate-bad-imports.any.js.ini
  tests/wpt/metadata/wasm/jsapi/constructor/instantiate.any.js.ini
  tests/wpt/metadata/wasm/jsapi/constructor/multi-value.any.js.ini
  tests/wpt/metadata/wasm/serialization/module/nested-worker-success.any.js.ini
Labels: S-awaiting-merge

#24783 Add support for WebGL2 ReadPixels functions
  Cargo.lock
  components/canvas/Cargo.toml
  components/canvas/webgl_thread.rs
  components/canvas_traits/webgl.rs
  components/script/dom/webgl2renderingcontext.rs
  components/script/dom/webglrenderingcontext.rs
  components/script/dom/webidls/WebGL2RenderingContext.webidl
  tests/wpt/webgl/meta/conformance2/reading/read-pixels-into-pixel-pack-buffer.html.ini
  tests/wpt/webgl/meta/conformance2/reading/read-pixels-pack-parameters.html.ini
Labels: S-awaiting-merge

#24758 Implement timer-task-source, time-out service worker
  components/script/dom/abstractworkerglobalscope.rs
  components/script/dom/dedicatedworkerglobalscope.rs
  components/script/dom/dissimilaroriginwindow.rs
  components/script/dom/globalscope.rs
  components/script/dom/serviceworkerglobalscope.rs
  components/script/dom/window.rs
  components/script/dom/workerglobalscope.rs
  components/script/dom/workletglobalscope.rs
  components/script/script_thread.rs
  components/script/task_manager.rs
  components/script/task_source/mod.rs
  components/script/task_source/timer.rs
  components/script/timers.rs
Labels: S-awaiting-merge

#24859 Don't panic if surfman initialization fails.
  components/servo/lib.rs
Labels: S-awaiting-merge

#24861 Add url parameter to the servosrc gstreamer plugin
  ports/gstplugin/servosrc.rs
Labels: P-gst-plugin, S-awaiting-merge

#24877 Update some URLs
  components/selectors/README.md
Labels: S-awaiting-merge

#24870 Fix #2909 (squashed version of PR #24865)
  Cargo.lock
  components/net/Cargo.toml
  components/net/data_loader.rs
  tests/wpt/metadata/fetch/data-urls/base64.any.js.ini
Labels: S-awaiting-merge

#24858 Handle u32 property indices
  components/script/dom/bindings/utils.rs
  tests/wpt/metadata/dom/collections/HTMLCollection-supported-property-indices.html.ini
Labels: S-awaiting-merge

#24883 Add WebGPU identity management
  components/script/dom/bindings/trace.rs
  components/script/dom/gpu.rs
  components/script/dom/identityhub.rs
  components/script/dom/mod.rs
  components/script/dom/navigator.rs
  components/webgpu/lib.rs
Labels: S-awaiting-merge

#24887 Remove stuff depending on syn 0.15
  Cargo.lock
Labels: S-awaiting-merge

#24933 Update README with new brew bundle file
  README.md
Labels: S-awaiting-merge

#24929 Extend WPT update job timeout.
  etc/taskcluster/decision_task.py
Labels: S-awaiting-merge

#24670 Add CRLF to encoded multipart form data
  components/script/dom/htmlformelement.rs
  tests/wpt/metadata/fetch/api/response/response-consume.html.ini
  tests/wpt/mozilla/meta/MANIFEST.json
  tests/wpt/mozilla/tests/mozilla/FileAPI/resource/file-submission.py
Labels: S-awaiting-merge
