Repository servo/servo, pull requests merged in 2019-10, with the labels that each got.

#24322 Assign bot reviewer for automated sync PRs.
  etc/ci/update-wpt-checkout
Labels: S-awaiting-merge

#24325 Update mozjs
  Cargo.lock
Labels: S-awaiting-merge

#24324 Make it possible to navigate with the keyboard in the webxr glwindow view
  Cargo.lock
  ports/glutin/app.rs
  ports/glutin/headed_window.rs
  ports/glutin/headless_window.rs
  ports/glutin/window_trait.rs
Labels: S-awaiting-merge

#24329 FileReader.read sets `result` to null before performing read operation
  components/script/dom/filereader.rs
  tests/wpt/metadata/FileAPI/reading-data-section/filereader_result.html.ini
Labels: S-awaiting-merge

#24178 Initial implementation of WebGLQueries
  components/canvas/webgl_thread.rs
  components/canvas_traits/webgl.rs
  components/script/dom/bindings/trace.rs
  components/script/dom/mod.rs
  components/script/dom/webgl2renderingcontext.rs
  components/script/dom/webglquery.rs
  components/script/dom/webglrenderingcontext.rs
  components/script/dom/webidls/WebGL2RenderingContext.webidl
  components/script/dom/webidls/WebGLQuery.webidl
  tests/wpt/webgl/meta/conformance2/context/methods-2.html.ini
  tests/wpt/webgl/meta/conformance2/query/occlusion-query.html.ini
  tests/wpt/webgl/meta/conformance2/query/query.html.ini
Labels: S-awaiting-merge

#24332 Migrate to IDL mixin syntax
  components/script/dom/webidls/ActivatableElement.webidl
  components/script/dom/webidls/Bluetooth.webidl
  components/script/dom/webidls/BluetoothDevice.webidl
  components/script/dom/webidls/BluetoothRemoteGATTCharacteristic.webidl
  components/script/dom/webidls/BluetoothRemoteGATTService.webidl
  components/script/dom/webidls/Body.webidl
  components/script/dom/webidls/CanvasRenderingContext2D.webidl
  components/script/dom/webidls/CharacterData.webidl
  components/script/dom/webidls/ChildNode.webidl
  components/script/dom/webidls/Crypto.webidl
  components/script/dom/webidls/Document.webidl
  components/script/dom/webidls/DocumentFragment.webidl
  components/script/dom/webidls/DocumentOrShadowRoot.webidl
  components/script/dom/webidls/DocumentType.webidl
  components/script/dom/webidls/Element.webidl
  components/script/dom/webidls/ElementCSSInlineStyle.webidl
  components/script/dom/webidls/ElementContentEditable.webidl
  components/script/dom/webidls/EventHandler.webidl
  components/script/dom/webidls/Fetch.webidl
  components/script/dom/webidls/HTMLAnchorElement.webidl
  components/script/dom/webidls/HTMLAreaElement.webidl
  components/script/dom/webidls/HTMLBodyElement.webidl
  components/script/dom/webidls/HTMLElement.webidl
  components/script/dom/webidls/HTMLFrameSetElement.webidl
  components/script/dom/webidls/HTMLHyperlinkElementUtils.webidl
  components/script/dom/webidls/HTMLLinkElement.webidl
  components/script/dom/webidls/HTMLStyleElement.webidl
  components/script/dom/webidls/Navigator.webidl
  components/script/dom/webidls/NonElementParentNode.webidl
  components/script/dom/webidls/OffscreenCanvasRenderingContext2D.webidl
  components/script/dom/webidls/PaintRenderingContext2D.webidl
  components/script/dom/webidls/ParentNode.webidl
  components/script/dom/webidls/Request.webidl
  components/script/dom/webidls/Response.webidl
  components/script/dom/webidls/SVGElement.webidl
  components/script/dom/webidls/SVGGraphicsElement.webidl
  components/script/dom/webidls/SVGSVGElement.webidl
  components/script/dom/webidls/ServiceWorker.webidl
  components/script/dom/webidls/ShadowRoot.webidl
  components/script/dom/webidls/StyleSheet.webidl
  components/script/dom/webidls/WebGL2RenderingContext.webidl
  components/script/dom/webidls/WebGLRenderingContext.webidl
  components/script/dom/webidls/Window.webidl
  components/script/dom/webidls/WindowOrWorkerGlobalScope.webidl
  components/script/dom/webidls/Worker.webidl
  components/script/dom/webidls/WorkerNavigator.webidl
Labels: S-awaiting-merge

#24341 Update HACKING_QUICKSTART doc
  docs/HACKING_QUICKSTART.md
Labels: S-awaiting-merge

#24335 Remove unused dependencies
  Cargo.lock
  components/background_hang_monitor/Cargo.toml
  components/canvas/Cargo.toml
  components/canvas_traits/Cargo.toml
  components/config/Cargo.toml
  components/constellation/Cargo.toml
  components/devtools/Cargo.toml
  components/embedder_traits/Cargo.toml
  components/geometry/Cargo.toml
  components/layout/Cargo.toml
  components/layout_2020/Cargo.toml
  components/layout_thread_2020/Cargo.toml
  components/media/Cargo.toml
  components/net/Cargo.toml
  components/net_traits/Cargo.toml
  components/script/Cargo.toml
  components/script_layout_interface/Cargo.toml
  components/to_shmem/Cargo.toml
  components/url/Cargo.toml
  components/webdriver_server/Cargo.toml
  components/webvr/Cargo.toml
  ports/glutin/Cargo.toml
  tests/unit/metrics/Cargo.toml
  tests/unit/style/Cargo.toml
Labels: S-awaiting-merge

#24310 Clean up gating and order of getting display/glcontext from glutin
  ports/glutin/context.rs
  ports/glutin/headed_window.rs
Labels: S-awaiting-merge

#24265 Integrates media track selection
  components/script/dom/audiotrack.rs
  components/script/dom/audiotracklist.rs
  components/script/dom/htmlmediaelement.rs
  components/script/dom/videotrack.rs
  components/script/dom/videotracklist.rs
Labels: S-awaiting-merge

#24257 Update to UWP compatible OpenSSL build.
  python/servo/build_commands.py
  python/servo/command_base.py
  python/servo/packages.py
Labels: S-awaiting-merge

#24344 Support `--features vslatestinstalled`
  Cargo.lock
  components/script/Cargo.toml
  components/servo/Cargo.toml
  ports/glutin/Cargo.toml
Labels: S-awaiting-merge

#24347 Fix intermittent macOS reftest failures
  components/gfx/platform/macos/font_template.rs
  tests/wpt/metadata/css/css-text/word-break/word-break-normal-bo-000.html.ini
Labels: S-awaiting-merge

#24352 Use correct OpenSSL arch in UWP builds.
  python/servo/command_base.py
Labels: S-awaiting-merge

#24356 Use unfiltered response body when replicating body of cached responses.
  components/net/http_cache.rs
Labels: S-awaiting-merge

#24364 Remove outdated userscript content.
  resources/user-agent-js/00.example.js
Labels: S-awaiting-merge

#24361 Add missing package dependency for Arch Linux in README
  README.md
Labels: S-awaiting-merge

#24359 Remove intermittent failure reporting.
  python/servo/testing_commands.py
Labels: S-awaiting-merge

#24334 Switch to the new Cargo.lock format
  Cargo.lock
Labels: S-awaiting-merge

#24365 Update test expectations
  tests/wpt/metadata/navigation-timing/idlharness.window.js.ini
  tests/wpt/metadata/navigation-timing/nav2_test_instance_accessible_from_the_start.html.ini
  tests/wpt/metadata/navigation-timing/nav2_test_navigate_iframe.html.ini
  tests/wpt/metadata/navigation-timing/nav2_test_navigate_within_document.html.ini
  tests/wpt/metadata/navigation-timing/unload-event-same-origin-check.html.ini
  tests/wpt/metadata/resource-timing/clear_resource_timing_functionality.html.ini
  tests/wpt/metadata/resource-timing/idlharness.any.js.ini
  tests/wpt/metadata/resource-timing/resource_cached.htm.ini
  tests/wpt/metadata/resource-timing/resource_connection_reuse.html.ini
  tests/wpt/metadata/resource-timing/resource_connection_reuse.https.html.ini
  tests/wpt/metadata/resource-timing/resource_connection_reuse_mixed_content.html.ini
  tests/wpt/metadata/resource-timing/resource_connection_reuse_mixed_content_redirect.html.ini
  tests/wpt/metadata/resource-timing/resource_reparenting.html.ini
  tests/wpt/metadata/resource-timing/resource_script_types.html.ini
  tests/wpt/metadata/resource-timing/resource_timing_buffer_full_when_shrink_buffer_size.html.ini
Labels: S-awaiting-merge

#24374 Pass argument by reference to CacheKey constructor
  components/net/http_cache.rs
Labels: S-awaiting-merge

#24382 Update tinyfiledialogs
  Cargo.lock
Labels: S-awaiting-merge

#24378 response: remove text from default statusCode
  components/script/dom/response.rs
Labels: S-awaiting-merge

#24383 style: Use consistent naming and shared code for out-of-flow stuff.
  components/style/properties/longhands/box.mako.rs
  components/style/properties/properties.mako.rs
  components/style/style_adjuster.rs
Labels: S-awaiting-merge

#24387 macos: Remove font size attribute from font descriptor.
  components/gfx/platform/macos/font_template.rs
Labels: S-awaiting-merge

#24391 Remove MacPorts instructions from Readme
  README.md
Labels: S-awaiting-merge

#24333 Add WebGLSampler support
  components/canvas/webgl_thread.rs
  components/canvas_traits/webgl.rs
  components/script/dom/bindings/trace.rs
  components/script/dom/macros.rs
  components/script/dom/mod.rs
  components/script/dom/webgl2renderingcontext.rs
  components/script/dom/webglrenderingcontext.rs
  components/script/dom/webglsampler.rs
  components/script/dom/webidls/WebGL2RenderingContext.webidl
  components/script/dom/webidls/WebGLSampler.webidl
  tests/wpt/webgl/meta/conformance2/context/methods-2.html.ini
  tests/wpt/webgl/meta/conformance2/misc/expando-loss-2.html.ini
  tests/wpt/webgl/meta/conformance2/misc/object-deletion-behaviour-2.html.ini
  tests/wpt/webgl/meta/conformance2/samplers/multi-context-sampler-test.html.ini
  tests/wpt/webgl/meta/conformance2/samplers/sampler-drawing-test.html.ini
  tests/wpt/webgl/meta/conformance2/samplers/samplers.html.ini
Labels: S-awaiting-merge

#24392 Allow building and cleaning for UWP without system GStreamer
  python/servo/command_base.py
Labels: S-awaiting-merge

#23860 Use RequestBuilder for CORS preflight fetch
  components/net/http_loader.rs
Labels: S-awaiting-merge

#24402 Websocket: use ipc router to handle ws dom-action messages
  components/net/websocket_loader.rs
Labels: S-awaiting-merge

#24401 Fetch: ensure consistency between response, done-chan, and cache state.
  components/net/http_loader.rs
Labels: S-awaiting-merge

#24339 Remove obsolete logic for LRUCache size
  components/style/sharing/mod.rs
Labels: S-awaiting-merge

#24411 Update iovec
  Cargo.lock
  Cargo.toml
Labels: S-awaiting-merge

#24386 webgl: Clear the drawing buffer when preserveDrawingBuffer is false.
  components/canvas/gl_context.rs
  components/canvas/webgl_thread.rs
  components/canvas_traits/webgl.rs
  components/script/dom/bindings/trace.rs
  components/script/dom/document.rs
  components/script/dom/webglrenderingcontext.rs
  components/script/dom/window.rs
  tests/wpt/webgl/meta/conformance/context/context-creation.html.ini
Labels: S-awaiting-merge

#24312 don't send progress event for empty blob
  components/script/dom/filereader.rs
  tests/wpt/metadata/FileAPI/reading-data-section/filereader_events.any.js.ini
Labels: S-awaiting-merge

#23990 Add secure connection start
  components/net/http_loader.rs
  components/net_traits/lib.rs
  components/script/dom/performanceresourcetiming.rs
Labels: S-awaiting-merge

#24417 Create a zip of all UWP packaging artifacts.
  etc/taskcluster/decision_task.py
  python/servo/package_commands.py
Labels: S-awaiting-merge

#24416 Update mozjs crate for new WASM APIs.
  Cargo.lock
Labels: S-awaiting-merge

#24379 Dom response check opaque filter
  components/script/dom/response.rs
  components/script/fetch.rs
  tests/wpt/metadata/fetch/api/basic/integrity.sub.any.js.ini
  tests/wpt/metadata/fetch/api/basic/mode-no-cors.sub.any.js.ini
  tests/wpt/metadata/fetch/api/cors/cors-basic.any.js.ini
  tests/wpt/metadata/fetch/api/redirect/redirect-empty-location.any.js.ini
  tests/wpt/metadata/fetch/api/redirect/redirect-location.any.js.ini
Labels: S-tests-failed

#24420 Handle inline-block as block for now in layout 2020
  components/layout_2020/flow/construct.rs
Labels: S-awaiting-merge

#24445 Update malloc_size_of_derive
  Cargo.lock
Labels: S-awaiting-merge

#24377 Support WebIDL `record<>`
  components/script/dom/bindings/codegen/CodegenRust.py
  components/script/dom/bindings/mod.rs
  components/script/dom/bindings/mozmap.rs
  components/script/dom/bindings/record.rs
  components/script/dom/bindings/str.rs
  components/script/dom/headers.rs
  components/script/dom/request.rs
  components/script/dom/testbinding.rs
  components/script/dom/webidls/Headers.webidl
  components/script/dom/webidls/TestBinding.webidl
  tests/wpt/metadata/fetch/api/headers/headers-record.html.ini
  tests/wpt/metadata/url/urlsearchparams-constructor.any.js.ini
Labels: S-awaiting-merge

#24429 Return false when GetPropertyKeys fails
  components/script/dom/bindings/codegen/CodegenRust.py
Labels: S-awaiting-merge

#24436 Use Tapped event instead of PointerReleased
  support/hololens/ServoApp/App.cpp
  support/hololens/ServoApp/ServoControl/ServoControl.cpp
  support/hololens/ServoApp/ServoControl/ServoControl.h
  support/hololens/ServoApp/Themes/Generic.xaml
Labels: S-awaiting-merge

#24443 Allow setting GST_DEBUG on Android through mach
  Cargo.lock
  ports/libsimpleservo/jniapi/Cargo.toml
  ports/libsimpleservo/jniapi/src/lib.rs
  python/servo/post_build_commands.py
  support/android/apk/servoapp/src/main/java/org/mozilla/servo/MainActivity.java
  support/android/apk/servoview/src/main/java/org/mozilla/servoview/JNIServo.java
  support/android/apk/servoview/src/main/java/org/mozilla/servoview/ServoView.java
Labels: S-awaiting-merge

#24451 Restore convenience UWP build flags.
  python/servo/build_commands.py
Labels: S-awaiting-merge

#24444 Update servo-media. Temporarily disable progressive download on Android
  Cargo.lock
Labels: S-awaiting-merge

#24452 Always request new XR frames
  components/script/dom/xrsession.rs
Labels: S-awaiting-merge

#24408 Synchronize WebGL layer creation with underlying GL APIs
  components/script/dom/xrwebgllayer.rs
Labels: S-awaiting-merge

#24315 Add simple implementation of content-security-policy on network requests
  Cargo.lock
  components/malloc_size_of/Cargo.toml
  components/malloc_size_of/lib.rs
  components/net/Cargo.toml
  components/net/fetch/methods.rs
  components/net_traits/Cargo.toml
  components/net_traits/request.rs
  components/script/Cargo.toml
  components/script/dom/bindings/trace.rs
  components/script/dom/document.rs
  components/script/dom/globalscope.rs
  components/script/dom/htmlscriptelement.rs
  components/script/dom/request.rs
  components/script/dom/servoparser/mod.rs
  components/script/fetch.rs
  tests/wpt/metadata/fetch/api/policies/csp-blocked.html.ini
Labels: S-awaiting-merge

#24460 Add PYTHON3 and Universal Windows C Runtime requirements to README
  README.md
Labels: S-awaiting-merge

#24453 Update OpenXR loader package
  support/hololens/ServoApp/ServoApp.vcxproj
  support/hololens/ServoApp/ServoApp.vcxproj.filters
  support/hololens/ServoApp/packages.config
Labels: S-awaiting-merge

#24464 fix getimagedata returns empty pixels
  components/script/dom/canvasrenderingcontext2d.rs
  components/script/dom/offscreencanvasrenderingcontext2d.rs
  tests/wpt/metadata/offscreen-canvas/fill-and-stroke-styles/2d.gradient.interpolate.zerosize.fill.html.ini
  tests/wpt/metadata/offscreen-canvas/fill-and-stroke-styles/2d.gradient.interpolate.zerosize.fill.worker.js.ini
  tests/wpt/metadata/offscreen-canvas/fill-and-stroke-styles/2d.gradient.interpolate.zerosize.fillRect.html.ini
  tests/wpt/metadata/offscreen-canvas/fill-and-stroke-styles/2d.gradient.interpolate.zerosize.fillRect.worker.js.ini
  tests/wpt/metadata/offscreen-canvas/fill-and-stroke-styles/2d.gradient.interpolate.zerosize.stroke.html.ini
  tests/wpt/metadata/offscreen-canvas/fill-and-stroke-styles/2d.gradient.interpolate.zerosize.stroke.worker.js.ini
  tests/wpt/metadata/offscreen-canvas/fill-and-stroke-styles/2d.gradient.interpolate.zerosize.strokeRect.html.ini
  tests/wpt/metadata/offscreen-canvas/fill-and-stroke-styles/2d.gradient.interpolate.zerosize.strokeRect.worker.js.ini
  tests/wpt/metadata/offscreen-canvas/filter/offscreencanvas.filter.html.ini
  tests/wpt/metadata/offscreen-canvas/line-styles/2d.line.cap.closed.html.ini
  tests/wpt/metadata/offscreen-canvas/line-styles/2d.line.cap.closed.worker.js.ini
  tests/wpt/metadata/offscreen-canvas/line-styles/2d.line.cap.open.html.ini
  tests/wpt/metadata/offscreen-canvas/line-styles/2d.line.cap.open.worker.js.ini
  tests/wpt/metadata/offscreen-canvas/line-styles/2d.line.cross.html.ini
  tests/wpt/metadata/offscreen-canvas/line-styles/2d.line.cross.worker.js.ini
  tests/wpt/metadata/offscreen-canvas/line-styles/2d.line.join.closed.html.ini
  tests/wpt/metadata/offscreen-canvas/line-styles/2d.line.join.closed.worker.js.ini
  tests/wpt/metadata/offscreen-canvas/line-styles/2d.line.join.open.html.ini
  tests/wpt/metadata/offscreen-canvas/line-styles/2d.line.join.open.worker.js.ini
  tests/wpt/metadata/offscreen-canvas/line-styles/2d.line.join.parallel.html.ini
  tests/wpt/metadata/offscreen-canvas/line-styles/2d.line.join.parallel.worker.js.ini
  tests/wpt/metadata/offscreen-canvas/line-styles/2d.line.miter.acute.html.ini
  tests/wpt/metadata/offscreen-canvas/line-styles/2d.line.miter.acute.worker.js.ini
  tests/wpt/metadata/offscreen-canvas/line-styles/2d.line.miter.exceeded.html.ini
  tests/wpt/metadata/offscreen-canvas/line-styles/2d.line.miter.exceeded.worker.js.ini
  tests/wpt/metadata/offscreen-canvas/line-styles/2d.line.miter.lineedge.html.ini
  tests/wpt/metadata/offscreen-canvas/line-styles/2d.line.miter.lineedge.worker.js.ini
  tests/wpt/metadata/offscreen-canvas/line-styles/2d.line.miter.obtuse.html.ini
  tests/wpt/metadata/offscreen-canvas/line-styles/2d.line.miter.obtuse.worker.js.ini
  tests/wpt/metadata/offscreen-canvas/line-styles/2d.line.miter.rightangle.html.ini
  tests/wpt/metadata/offscreen-canvas/line-styles/2d.line.miter.rightangle.worker.js.ini
  tests/wpt/metadata/offscreen-canvas/line-styles/2d.line.miter.within.html.ini
  tests/wpt/metadata/offscreen-canvas/line-styles/2d.line.miter.within.worker.js.ini
  tests/wpt/metadata/offscreen-canvas/line-styles/2d.line.union.html.ini
  tests/wpt/metadata/offscreen-canvas/line-styles/2d.line.union.worker.js.ini
  tests/wpt/metadata/offscreen-canvas/pixel-manipulation/2d.imageData.get.clamp.html.ini
  tests/wpt/metadata/offscreen-canvas/pixel-manipulation/2d.imageData.get.clamp.worker.js.ini
  tests/wpt/metadata/offscreen-canvas/pixel-manipulation/2d.imageData.get.nonpremul.html.ini
  tests/wpt/metadata/offscreen-canvas/pixel-manipulation/2d.imageData.get.nonpremul.worker.js.ini
  tests/wpt/metadata/offscreen-canvas/pixel-manipulation/2d.imageData.get.order.alpha.html.ini
  tests/wpt/metadata/offscreen-canvas/pixel-manipulation/2d.imageData.get.order.alpha.worker.js.ini
  tests/wpt/metadata/offscreen-canvas/pixel-manipulation/2d.imageData.get.order.cols.html.ini
  tests/wpt/metadata/offscreen-canvas/pixel-manipulation/2d.imageData.get.order.cols.worker.js.ini
  tests/wpt/metadata/offscreen-canvas/pixel-manipulation/2d.imageData.get.order.rgb.html.ini
  tests/wpt/metadata/offscreen-canvas/pixel-manipulation/2d.imageData.get.order.rgb.worker.js.ini
  tests/wpt/metadata/offscreen-canvas/pixel-manipulation/2d.imageData.get.order.rows.html.ini
  tests/wpt/metadata/offscreen-canvas/pixel-manipulation/2d.imageData.get.order.rows.worker.js.ini
  tests/wpt/metadata/offscreen-canvas/pixel-manipulation/2d.imageData.get.range.html.ini
  tests/wpt/metadata/offscreen-canvas/pixel-manipulation/2d.imageData.get.range.worker.js.ini
  tests/wpt/metadata/offscreen-canvas/pixel-manipulation/2d.imageData.put.unchanged.html.ini
  tests/wpt/metadata/offscreen-canvas/pixel-manipulation/2d.imageData.put.unchanged.worker.js.ini
  tests/wpt/metadata/offscreen-canvas/the-offscreen-canvas/initial.reset.path.html.ini
  tests/wpt/metadata/offscreen-canvas/the-offscreen-canvas/initial.reset.path.worker.js.ini
  tests/wpt/metadata/offscreen-canvas/the-offscreen-canvas/offscreencanvas.getcontext.html.ini
  tests/wpt/metadata/offscreen-canvas/the-offscreen-canvas/offscreencanvas.getcontext.worker.js.ini
Labels: S-awaiting-merge

#24476 Mark @@iterator as nonenumerable
  components/script/dom/bindings/codegen/CodegenRust.py
  tests/wpt/metadata/dom/idlharness.window.js.ini
  tests/wpt/metadata/fetch/api/idlharness.any.js.ini
  tests/wpt/metadata/url/idlharness.any.js.ini
  tests/wpt/metadata/xhr/idlharness.any.js.ini
Labels: S-awaiting-merge

#24475 Support [LegacyWindowAlias]
  components/script/dom/bindings/codegen/CodegenRust.py
  components/script/dom/bindings/interface.rs
  components/script/dom/webidls/DOMMatrix.webidl
  components/script/dom/webidls/URL.webidl
  tests/wpt/metadata/css/geometry/WebKitCSSMatrix.html.ini
  tests/wpt/metadata/url/idlharness.any.js.ini
  tests/wpt/mozilla/meta/MANIFEST.json
  tests/wpt/mozilla/tests/mozilla/interfaces.html
  tests/wpt/mozilla/tests/mozilla/interfaces.js
Labels: S-awaiting-merge

#24471 Support enum value as a union default value
  components/script/dom/audiocontext.rs
  components/script/dom/bindings/codegen/CodegenRust.py
  components/script/dom/webidls/AudioContext.webidl
  tests/wpt/metadata/webaudio/the-audio-api/the-audiocontext-interface/audiocontextoptions.html.ini
Labels: S-awaiting-merge

#24492 Update timer scheduler to use crossbeam
  components/constellation/constellation.rs
  components/constellation/timer_scheduler.rs
  components/script/timers.rs
  components/script_traits/lib.rs
Labels: S-awaiting-merge

#24500 Remove usage of opts::get() from style.
  components/servo/lib.rs
  components/style/context.rs
  components/style/traversal.rs
Labels: S-awaiting-merge

#24517 Sync WPT with upstream (21-10-2019)
  tests/wpt/metadata/FileAPI/url/url-with-fetch.any.js.ini
  tests/wpt/metadata/css/CSS2/linebox/inline-negative-margin-001.html.ini
  tests/wpt/metadata/css/compositing/mix-blend-mode/mix-blend-mode-animation.html.ini
  tests/wpt/metadata/css/css-transforms/animation/perspective-interpolation.html.ini
  tests/wpt/metadata/encoding/single-byte-decoder.html.ini
  tests/wpt/metadata/fetch/content-type/response.window.js.ini
  tests/wpt/metadata/fetch/content-type/script.window.js.ini
  tests/wpt/metadata/fetch/nosniff/parsing-nosniff.window.js.ini
  tests/wpt/metadata/fetch/security/embedded-credentials.tentative.sub.html.ini
  tests/wpt/metadata/html/browsers/history/the-history-interface/traverse_the_history_5.html.ini
  tests/wpt/metadata/html/browsers/history/the-location-interface/location-protocol-setter-non-broken.html.ini
  tests/wpt/metadata/html/browsers/windows/embedded-opener-remove-frame.html.ini
  tests/wpt/metadata/html/interaction/focus/the-autofocus-attribute/skip-document-with-fragment.html.ini
  tests/wpt/metadata/html/semantics/embedded-content/the-iframe-element/iframe_sandbox_popups_escaping-3.html.ini
  tests/wpt/metadata/html/semantics/embedded-content/the-iframe-element/iframe_sandbox_popups_nonescaping-1.html.ini
  tests/wpt/metadata/html/semantics/embedded-content/the-iframe-element/iframe_sandbox_popups_nonescaping-3.html.ini
  tests/wpt/metadata/html/semantics/forms/form-submission-0/form-double-submit.html.ini
  tests/wpt/metadata/html/semantics/forms/form-submission-0/form-submission-algorithm.html.ini
  tests/wpt/metadata/html/semantics/interactive-elements/the-details-element/toggleEvent.html.ini
  tests/wpt/metadata/webaudio/the-audio-api/the-analysernode-interface/realtimeanalyser-fft-scaling.html.ini
  tests/wpt/metadata/webmessaging/with-ports/018.html.ini
  tests/wpt/metadata/workers/semantics/multiple-workers/005.html.ini
  tests/wpt/web-platform-tests/README.md
  tests/wpt/web-platform-tests/compat/webkit-box-ignore-box-pack.html
  tests/wpt/web-platform-tests/css/css-values/percentage-rem-low.html
  tests/wpt/web-platform-tests/css/selectors/focus-visible-011.html
  tests/wpt/web-platform-tests/css/support/interpolation-testcommon.js
  tests/wpt/web-platform-tests/interfaces/media-capabilities.idl
  tests/wpt/web-platform-tests/interfaces/web-nfc.idl
  tests/wpt/web-platform-tests/media-source/mediasource-replay.html
  tests/wpt/web-platform-tests/web-share/share-image-manual.https.html
  tests/wpt/web-platform-tests/web-share/share-image-manual.tentative.https.html
  tests/wpt/webgl/meta/conformance2/rendering/canvas-resizing-with-pbo-bound.html.ini
Labels: S-awaiting-merge

#24511 Don’t install rust-docs, rust-src, or clippy on CI
  etc/taskcluster/decision_task.py
  etc/taskcluster/decisionlib.py
  etc/taskcluster/docker/build.dockerfile
Labels: S-awaiting-merge

#24516 Add remaining macs to salt roster.
  etc/taskcluster/macos/config/roster
Labels: S-awaiting-merge

#24489 Refactor submission
  components/script/dom/activation.rs
  components/script/dom/document.rs
  components/script/dom/htmlanchorelement.rs
  components/script/dom/htmlareaelement.rs
  components/script/dom/htmlbuttonelement.rs
  components/script/dom/htmlinputelement.rs
  components/script/dom/htmllabelelement.rs
Labels: S-awaiting-merge

#24532 Add `./mach test-tidy --no-wpt`, for a git pre-push hook
  python/servo/testing_commands.py
Labels: S-awaiting-merge

#24533 Update smallvec
  Cargo.lock
Labels: S-awaiting-merge

#24535 2020: paint borders
  components/layout_2020/display_list.rs
  components/style/properties/helpers.mako.rs
  components/style/properties/longhands/border.mako.rs
  components/style/properties/shorthands/border.mako.rs
  components/style/values/specified/border.rs
Labels: S-awaiting-merge

#24550 Update html5ever and xml5ever
  Cargo.lock
Labels: S-awaiting-merge

#24519 Cleanup canvasrenderingcontext
  components/script/canvas_state.rs
  components/script/dom/canvasrenderingcontext2d.rs
  components/script/dom/offscreencanvasrenderingcontext2d.rs
  components/script/lib.rs
Labels: S-awaiting-merge

#24562 Update the maximum version of Ubuntu suppported to 19.10
  python/servo/bootstrap.py
Labels: S-awaiting-merge

#24546 Re-add missing commit in PR #24489
  components/script/dom/document.rs
Labels: S-awaiting-merge

#24542 Update UWP ANGLE to a modern version
  python/servo/build_commands.py
  support/hololens/ServoApp/ServoApp.vcxproj
  support/hololens/ServoApp/ServoControl/OpenGLES.cpp
  support/hololens/ServoApp/packages.config
Labels: S-awaiting-merge

#24565 Delete superfluous comment
  components/script/dom/webidls/WebGL2RenderingContext.webidl
Labels: S-awaiting-merge

#24573 Return false from CanvasState::is_point_in_path for NaN/infinite values
  components/script/canvas_state.rs
Labels: S-awaiting-merge

#24564 Properly set MouseEvent buttons property
  components/script/dom/mouseevent.rs
  tests/wpt/metadata/dom/events/Event-subclasses-constructors.html.ini
Labels: S-awaiting-merge

#24572 Allow setting Visual Studio logger level from cli arg
  components/config/opts.rs
  ports/libsimpleservo/capi/src/lib.rs
  ports/libsimpleservo/capi/src/vslogger.rs
Labels: S-awaiting-merge

#24547 UWP: better mouse interaction support
  ports/libmlservo/src/lib.rs
  ports/libsimpleservo/capi/src/lib.rs
  support/android/apk/servoview/src/main/java/org/mozilla/servoview/JNIServo.java
  support/android/apk/servoview/src/main/java/org/mozilla/servoview/Servo.java
  support/android/apk/servoview/src/main/java/org/mozilla/servoview/ServoSurface.java
  support/hololens/ServoApp/DefaultUrl.h
  support/hololens/ServoApp/ServoControl/Servo.h
  support/hololens/ServoApp/ServoControl/ServoControl.cpp
  support/hololens/ServoApp/ServoControl/ServoControl.h
Labels: S-awaiting-merge

#24583 Fix GL panic with updated ANGLE
  components/script/dom/webgl_extensions/ext/oestexturefloat.rs
  components/script/dom/webgl_extensions/ext/oestexturehalffloat.rs
Labels: S-awaiting-merge

#24577 Add a loading indicator in transient mode
  support/hololens/ServoApp/BrowserPage.cpp
  support/hololens/ServoApp/BrowserPage.xaml
Labels: S-awaiting-merge

#24612 Avoid instaling rustc-dev twice.
  etc/taskcluster/decision_task.py
Labels: S-awaiting-review

#24594 Load hololens demo page by default
  support/hololens/ServoApp/DefaultUrl.h
Labels: S-awaiting-merge
