Repository servo/servo, pull requests merged in 2019-09, with the labels that each got.

#24097 Add [Default] toJSON() to performance interfaces
  components/script/dom/bindings/codegen/CodegenRust.py
  components/script/dom/webidls/Performance.webidl
  components/script/dom/webidls/PerformanceEntry.webidl
  components/script/dom/webidls/PerformanceNavigation.webidl
  components/script/dom/webidls/PerformanceNavigationTiming.webidl
  components/script/dom/webidls/PerformanceResourceTiming.webidl
  tests/wpt/metadata/hr-time/idlharness.any.js.ini
  tests/wpt/metadata/navigation-timing/idlharness.window.js.ini
  tests/wpt/metadata/performance-timeline/idlharness.any.js.ini
  tests/wpt/metadata/performance-timeline/performanceentry-tojson.any.js.ini
  tests/wpt/metadata/resource-timing/idlharness.any.js.ini
  tests/wpt/metadata/resource-timing/resource-timing-tojson.html.ini
  tests/wpt/metadata/workers/worker-performance.worker.js.ini
Labels: S-awaiting-merge

#24122 Update rayon to dedupe crossbeam-deque
  Cargo.lock
  servo-tidy.toml
Labels: S-awaiting-merge

#24128 Fallback to old extensions API if NUM_EXTENSIONS errors
  components/canvas/webgl_thread.rs
Labels: I-panic, S-awaiting-merge

#24090 Implement ElementClick wd command
  components/atoms/static_atoms.txt
  components/script/script_thread.rs
  components/script/webdriver_handlers.rs
  components/script_traits/webdriver_msg.rs
  components/webdriver_server/actions.rs
  components/webdriver_server/lib.rs
  tests/wpt/metadata/webdriver/tests/element_click/bubbling.py.ini
  tests/wpt/metadata/webdriver/tests/element_click/center_point.py.ini
  tests/wpt/metadata/webdriver/tests/element_click/click.py.ini
  tests/wpt/metadata/webdriver/tests/element_click/file_upload.py.ini
  tests/wpt/metadata/webdriver/tests/element_click/interactability.py.ini
  tests/wpt/metadata/webdriver/tests/element_click/navigate.py.ini
  tests/wpt/metadata/webdriver/tests/element_click/scroll_into_view.py.ini
  tests/wpt/metadata/webdriver/tests/element_click/select.py.ini
  tests/wpt/metadata/webdriver/tests/element_click/stale.py.ini
  tests/wpt/metadata/webdriver/tests/execute_script/cyclic.py.ini
Labels: S-awaiting-merge

#24094 Create depth and stencil attachments for XRWebGLLayer
  components/script/dom/webglrenderingcontext.rs
  components/script/dom/xrwebgllayer.rs
Labels: A-xr-zomg, S-awaiting-merge

#24132 Updated performance userscript for new perf API
  etc/ci/performance/user-agent-js/01.perf-timing.js
Labels: A-perf-measurement, S-awaiting-merge

#24109 Performance: limit buffer size, clear on pipeline exit
  components/script/dom/performance.rs
  components/script/dom/window.rs
Labels: S-awaiting-merge

#24107 Added support in CInitOptions to pass logging/filter modules to VSLog…
  ports/libsimpleservo/capi/Cargo.toml
  ports/libsimpleservo/capi/src/lib.rs
  ports/libsimpleservo/capi/src/vslogger.rs
  support/hololens/ServoApp/ServoControl/Servo.cpp
Labels: S-awaiting-merge

#24135 Update backtrace dependency.
  Cargo.lock
Labels: S-tests-failed

#24137 Codegen: throw type error when encountering an unknown argument
  components/script/dom/bindings/codegen/CodegenRust.py
  tests/wpt/metadata/webaudio/the-audio-api/the-iirfilternode-interface/iirfilter.html.ini
Labels: S-awaiting-merge

#24129 Deduplicate parking_lot by updating it to 0.9
  Cargo.lock
  components/background_hang_monitor/sampler.rs
  components/layout/Cargo.toml
  components/layout_thread/Cargo.toml
  components/layout_thread_2020/Cargo.toml
  components/msg/Cargo.toml
  components/script/Cargo.toml
  components/style/Cargo.toml
  ports/libsimpleservo/api/src/gl_glue.rs
  servo-tidy.toml
Labels: S-awaiting-merge

#24125 Branding: s/servo/firefox reality/
  .gitignore
  support/hololens/ServoApp/Assets/LargeTile.scale-100.png
  support/hololens/ServoApp/Assets/LargeTile.scale-200.png
  support/hololens/ServoApp/Assets/LargeTile.scale-400.png
  support/hololens/ServoApp/Assets/LockScreenLogo.scale-200.png
  support/hololens/ServoApp/Assets/SmallTile.scale-100.png
  support/hololens/ServoApp/Assets/SmallTile.scale-200.png
  support/hololens/ServoApp/Assets/SmallTile.scale-400.png
  support/hololens/ServoApp/Assets/SplashScreen.scale-100.png
  support/hololens/ServoApp/Assets/SplashScreen.scale-200.png
  support/hololens/ServoApp/Assets/SplashScreen.scale-400.png
  support/hololens/ServoApp/Assets/Square150x150Logo.scale-100.png
  support/hololens/ServoApp/Assets/Square150x150Logo.scale-200.png
  support/hololens/ServoApp/Assets/Square150x150Logo.scale-400.png
  support/hololens/ServoApp/Assets/Square44x44Logo.altform-unplated_targetsize-16.png
  support/hololens/ServoApp/Assets/Square44x44Logo.altform-unplated_targetsize-256.png
  support/hololens/ServoApp/Assets/Square44x44Logo.altform-unplated_targetsize-48.png
  support/hololens/ServoApp/Assets/Square44x44Logo.scale-100.png
  support/hololens/ServoApp/Assets/Square44x44Logo.scale-200.png
  support/hololens/ServoApp/Assets/Square44x44Logo.scale-400.png
  support/hololens/ServoApp/Assets/Square44x44Logo.targetsize-16.png
  support/hololens/ServoApp/Assets/Square44x44Logo.targetsize-256.png
  support/hololens/ServoApp/Assets/Square44x44Logo.targetsize-48.png
  support/hololens/ServoApp/Assets/StoreLogo.png
  support/hololens/ServoApp/Assets/StoreLogo.scale-100.png
  support/hololens/ServoApp/Assets/StoreLogo.scale-200.png
  support/hololens/ServoApp/Assets/StoreLogo.scale-400.png
  support/hololens/ServoApp/Assets/Wide310x150Logo.scale-100.png
  support/hololens/ServoApp/Assets/Wide310x150Logo.scale-200.png
  support/hololens/ServoApp/Assets/Wide310x150Logo.scale-400.png
  support/hololens/ServoApp/BrowserPage.h
  support/hololens/ServoApp/Package.appxmanifest
  support/hololens/ServoApp/ServoApp.vcxproj
  support/hololens/ServoApp/ServoApp.vcxproj.filters
  support/hololens/ServoApp/ServoApp_TemporaryKey.pfx
  support/hololens/ServoApp/ServoControl/ServoControl.h
Labels: S-awaiting-merge

#24034 Make inline elements work in fullscreen mode
  components/layout/construct.rs
  tests/wpt/mozilla/meta/MANIFEST.json
  tests/wpt/mozilla/tests/css/blockify_inline_element.html
  tests/wpt/mozilla/tests/css/blockify_inline_element_ref.html
Labels: S-awaiting-merge

#24142 Show warning when module scripts are ignored
  components/script/dom/htmlscriptelement.rs
Labels: S-awaiting-merge

#24150 Update servo-tidy
  servo-tidy.toml
Labels: S-awaiting-merge

#24155 Update and dedupe nix
  Cargo.lock
  components/background_hang_monitor/Cargo.toml
  servo-tidy.toml
Labels: S-awaiting-merge

#24160 Remove the nonexistent optional params in the document
  docs/HACKING_QUICKSTART.md
Labels: S-awaiting-merge

#24174 Enable video frames as OES textures
  Cargo.lock
  components/script/dom/htmlmediaelement.rs
Labels: S-awaiting-merge

#24177 Fix UWP icons
  support/hololens/ServoApp/Assets/Square44x44Logo.altform-unplated_targetsize-24.png
  support/hololens/ServoApp/Assets/Square44x44Logo.altform-unplated_targetsize-32.png
  support/hololens/ServoApp/Assets/Square44x44Logo.scale-125.png
  support/hololens/ServoApp/Assets/Square44x44Logo.scale-150.png
  support/hololens/ServoApp/Assets/Square44x44Logo.targetsize-24.png
  support/hololens/ServoApp/Assets/Square44x44Logo.targetsize-24_altform-unplated.png
  support/hololens/ServoApp/Assets/Square44x44Logo.targetsize-32.png
  support/hololens/ServoApp/ServoApp.vcxproj
  support/hololens/ServoApp/ServoApp.vcxproj.filters
Labels: S-awaiting-merge

#24126 Make the HoloLens UI look better
  support/hololens/ServoApp/Assets/UI/back.png
  support/hololens/ServoApp/Assets/UI/forward.png
  support/hololens/ServoApp/Assets/UI/reload.png
  support/hololens/ServoApp/Assets/UI/stop.png
  support/hololens/ServoApp/BrowserPage.cpp
  support/hololens/ServoApp/BrowserPage.xaml
  support/hololens/ServoApp/ServoApp.vcxproj
  support/hololens/ServoApp/ServoApp.vcxproj.filters
Labels: S-awaiting-merge

#24212 Update sparkle for GLES fix.
  Cargo.lock
Labels: S-awaiting-merge

#24216 Skip timing out test directories for unimplemented features
  tests/wpt/include.ini
Labels: S-awaiting-merge

#24111 webgl: Support vertex array objects on macOS.
  components/canvas/gl_context.rs
  components/canvas/webgl_thread.rs
Labels: S-awaiting-merge

#24224 Added description of debugging gstreamer in magicleap
  support/magicleap/README.md
Labels: A-content/media, P-magic leap, S-awaiting-merge

#24149 Add explicit packaging step for UWP apps
  etc/taskcluster/decision_task.py
  python/servo/build_commands.py
  python/servo/command_base.py
  python/servo/package_commands.py
  support/hololens/ServoApp.sln
  support/hololens/ServoApp/ServoApp.vcxproj
  support/hololens/package.msbuild
Labels: S-awaiting-merge

#24220 add webidl bindings for DOMStringList
  components/script/dom/domstringlist.rs
  components/script/dom/mod.rs
  components/script/dom/webidls/DOMStringList.webidl
  tests/wpt/metadata/html/dom/idlharness.https.html.ini
  tests/wpt/metadata/html/dom/idlharness.worker.js.ini
  tests/wpt/metadata/html/dom/interfaces.https.html.ini
  tests/wpt/metadata/html/dom/interfaces.worker.js.ini
  tests/wpt/metadata/html/infrastructure/common-dom-interfaces/collections/domstringlist-interface.html.ini
  tests/wpt/metadata/html/infrastructure/common-dom-interfaces/collections/domstringlist-interface.worker.js.ini
  tests/wpt/mozilla/meta/MANIFEST.json
  tests/wpt/mozilla/tests/mozilla/interfaces.html
  tests/wpt/mozilla/tests/mozilla/interfaces.worker.js
Labels: S-awaiting-merge

#24229 Fix python precedence issue.
  etc/taskcluster/decision_task.py
Labels: S-awaiting-merge

#24134 Upgrade webxr
  Cargo.lock
Labels: S-awaiting-merge

#24235 Use EGL context and display parameters when initializing magicleap servo
  ports/libmlservo/src/lib.rs
Labels: P-magic leap, S-awaiting-merge

#24236 Update servo-media
  Cargo.lock
Labels: A-content/media, S-tests-failed

#24249 Go back to original window size after exiting fullscreen
  ports/glutin/headed_window.rs
Labels: S-awaiting-merge

#24266 Update sparkle crate
  Cargo.lock
Labels: S-awaiting-merge

#24217 ISSUE-23995: lazily generate UniqueIds for Nodes
  components/script/dom/node.rs
  components/script/dom/raredata.rs
  tests/unit/script/size_of.rs
Labels: S-awaiting-merge

#23987 Update WebIDL parser
  components/script/dom/bindings/codegen/CodegenRust.py
  components/script/dom/bindings/codegen/parser/WebIDL.py
  components/script/dom/bindings/codegen/parser/abstract.patch
  components/script/dom/bindings/codegen/parser/debug.patch
  components/script/dom/bindings/codegen/parser/exposed-globals.patch
  components/script/dom/bindings/codegen/parser/inline.patch
  components/script/dom/bindings/codegen/parser/tests/test_conditional_dictionary_member.py
  components/script/dom/bindings/codegen/parser/tests/test_interfacemixin.py
  components/script/dom/bindings/codegen/parser/union-typedef.patch
  components/script/dom/bindings/codegen/parser/update.sh
Labels: S-awaiting-merge

#24268 Extend nightly WPT update timeout by an hour.
  etc/taskcluster/decision_task.py
Labels: S-awaiting-merge

#23686 Ignore VSCode IDE files
  .gitignore
Labels: S-awaiting-merge

#24280 Allow playing video/webm on Windows
  components/servo/lib.rs
  python/servo/build_commands.py
Labels: S-awaiting-merge

#24261 Temporary implementation of Canvas.MeasureText
  components/script/dom/canvasrenderingcontext2d.rs
  components/script/dom/mod.rs
  components/script/dom/offscreencanvasrenderingcontext2d.rs
  components/script/dom/textmetrics.rs
  components/script/dom/webidls/CanvasRenderingContext2D.webidl
  components/script/dom/webidls/TextMetrics.webidl
  tests/wpt/metadata/html/dom/idlharness.https.html.ini
  tests/wpt/metadata/html/dom/idlharness.worker.js.ini
  tests/wpt/metadata/workers/semantics/interface-objects/001.worker.js.ini
  tests/wpt/mozilla/meta/MANIFEST.json
  tests/wpt/mozilla/tests/mozilla/interfaces.js
Labels: S-awaiting-merge

#24264 Make tidy report when a rand exception is no longer needed
  python/tidy/servo_tidy/tidy.py
  python/tidy/servo_tidy_tests/blocked_package.lock
  python/tidy/servo_tidy_tests/test_tidy.py
Labels: S-awaiting-merge

#24294 Fix error message for invalid combination of style crate feature flags
  components/style/build.rs
Labels: S-awaiting-merge

#24300 Remove unused checking in GetResponseXML
  components/script/dom/xmlhttprequest.rs
Labels: S-awaiting-merge

#24306 Upgrade to rustc 1.40.0-nightly (ddf43867a 2019-09-26)
  components/script_plugins/unrooted_must_root.rs
  components/script_plugins/webidl_must_inherit.rs
  rust-toolchain
Labels: S-awaiting-merge

#24143 Improve spec compliance of discarding BCs
  components/script/dom/htmliframeelement.rs
  components/script/dom/window.rs
  components/script/dom/windowproxy.rs
  components/script/script_thread.rs
  tests/wpt/metadata/html/browsers/the-window-object/close-method.window.js.ini
  tests/wpt/metadata/resource-timing/nested-context-navigations-iframe.html.ini
  tests/wpt/metadata/workers/modules/dedicated-worker-import-csp.html.ini
Labels: S-awaiting-merge

#24304 Remove use of packed_simd
  Cargo.lock
  components/gfx/Cargo.toml
  components/gfx/text/glyph.rs
Labels: S-awaiting-merge

#24313 Upgrade to rustc 1.40.0-nightly (084beb83e 2019-09-27)
  components/script_plugins/unrooted_must_root.rs
  components/script_plugins/webidl_must_inherit.rs
  rust-toolchain
Labels: S-tests-failed

#24317 Sync WPT with upstream (29-09-2019)
  tests/wpt/metadata/FileAPI/url/url-in-tags-revoke.window.js.ini
  tests/wpt/metadata/css/compositing/mix-blend-mode/mix-blend-mode-animation.html.ini
  tests/wpt/metadata/dom/nodes/Document-contentType/contentType/contenttype_txt.html.ini
  tests/wpt/metadata/fetch/content-type/response.window.js.ini
  tests/wpt/metadata/fetch/content-type/script.window.js.ini
  tests/wpt/metadata/fetch/nosniff/parsing-nosniff.window.js.ini
  tests/wpt/metadata/html/browsers/browsing-the-web/navigating-across-documents/navigation-unload-same-origin-fragment.html.ini
  tests/wpt/metadata/html/browsers/history/the-history-interface/traverse_the_history_1.html.ini
  tests/wpt/metadata/html/browsers/history/the-history-interface/traverse_the_history_2.html.ini
  tests/wpt/metadata/html/browsers/history/the-history-interface/traverse_the_history_3.html.ini
  tests/wpt/metadata/html/browsers/the-window-object/apis-for-creating-and-navigating-browsing-contexts-by-name/open-features-negative-screenx-screeny.html.ini
  tests/wpt/metadata/html/browsers/windows/auxiliary-browsing-contexts/opener-setter.html.ini
  tests/wpt/metadata/html/browsers/windows/embedded-opener-remove-frame.html.ini
  tests/wpt/metadata/html/semantics/embedded-content/media-elements/media_fragment_seek.html.ini
  tests/wpt/metadata/html/semantics/embedded-content/the-iframe-element/iframe_sandbox_popups_escaping-2.html.ini
  tests/wpt/metadata/html/semantics/embedded-content/the-iframe-element/iframe_sandbox_popups_escaping-3.html.ini
  tests/wpt/metadata/html/semantics/embedded-content/the-iframe-element/iframe_sandbox_popups_nonescaping-3.html.ini
  tests/wpt/metadata/html/semantics/forms/autofocus/skip-document-with-fragment.html.ini
  tests/wpt/metadata/html/semantics/interactive-elements/the-details-element/toggleEvent.html.ini
  tests/wpt/metadata/html/semantics/scripting-1/the-script-element/script-onerror-insertion-point-2.html.ini
  tests/wpt/metadata/resource-timing/nested-context-navigations-iframe.html.ini
  tests/wpt/metadata/workers/baseurl/alpha/import-in-moduleworker.html.ini
  tests/wpt/metadata/workers/constructors/Worker/Worker-constructor.html.ini
  tests/wpt/web-platform-tests/interfaces/accelerometer.idl
  tests/wpt/webgl/meta/conformance2/rendering/canvas-resizing-with-pbo-bound.html.ini
Labels: S-awaiting-merge
