Repository servo/servo, pull requests merged in 2019-12, with the labels that each got.

#24987 Un-allow and fix warnings in `components/layout_2020`
  components/layout_2020/context.rs
  components/layout_2020/display_list.rs
  components/layout_2020/dom_traversal.rs
  components/layout_2020/flow/float.rs
  components/layout_2020/flow/inline.rs
  components/layout_2020/flow/mod.rs
  components/layout_2020/flow/root.rs
  components/layout_2020/formatting_contexts.rs
  components/layout_2020/geom.rs
  components/layout_2020/lib.rs
  components/layout_2020/positioned.rs
  components/layout_2020/replaced.rs
  components/layout_thread_2020/lib.rs
Labels: S-awaiting-merge

#24940 Trim header values in GetResponseHeader
  components/script/dom/xmlhttprequest.rs
  tests/wpt/metadata/xhr/headers-normalize-response.htm.ini
Labels: S-awaiting-merge

#25025 Origin offset fixes
  components/script/dom/xrreferencespace.rs
Labels: S-awaiting-merge

#24977 Add StreamConsumer wrapper and methods to response
  components/script/dom/bindings/trace.rs
  components/script/dom/response.rs
  components/script/fetch.rs
  components/script/script_runtime.rs
  tests/wpt/metadata/wasm/webapi/contenttype.any.js.ini
  tests/wpt/metadata/wasm/webapi/status.any.js.ini
Labels: S-awaiting-merge

#25074 Home button and larger buttons in toolbar
  support/hololens/ServoApp/Assets/UI/home.png
  support/hololens/ServoApp/BrowserPage.cpp
  support/hololens/ServoApp/BrowserPage.h
  support/hololens/ServoApp/BrowserPage.xaml
  support/hololens/ServoApp/DefaultUrl.h
  support/hololens/ServoApp/ServoApp.vcxproj
  support/hololens/ServoApp/ServoApp.vcxproj.filters
Labels: S-awaiting-merge

#25075 Upgrade to rustc 1.41.0-nightly (7afe6d9d1 2019-12-03)
  components/script_plugins/lib.rs
  etc/rustdoc-with-private
  rust-toolchain
Labels: S-awaiting-merge

#25076 Properly send TouchEvents to Servo
  support/hololens/ServoApp/ServoControl/Servo.h
  support/hololens/ServoApp/ServoControl/ServoControl.cpp
  support/hololens/ServoApp/ServoControl/ServoControl.h
Labels: S-awaiting-merge

#25114 Update to rustc 1.41.0-nightly (6d77e45f0 2019-12-04)
  rust-toolchain
Labels: S-awaiting-merge

#25029 Initial implementation of GPUDevice for WebGPU
  components/script/dom/bindings/codegen/Bindings.conf
  components/script/dom/bindings/trace.rs
  components/script/dom/gpuadapter.rs
  components/script/dom/gpudevice.rs
  components/script/dom/identityhub.rs
  components/script/dom/mod.rs
  components/script/dom/navigator.rs
  components/script/dom/webidls/GPUAdapter.webidl
  components/script/dom/webidls/GPUDevice.webidl
  components/script/dom/webidls/GPUObjectBase.webidl
  components/webgpu/lib.rs
Labels: S-awaiting-merge

#25116 Fix Python Unicode error in './mach filter-intermittents'
  python/servo/testing_commands.py
Labels: S-awaiting-merge

#25117 Move WPT sync-from-upstream task to Linux
  etc/ci/update-wpt-checkout
  etc/taskcluster/decision_task.py
Labels: S-awaiting-merge

#25073 Increase parallelism in macOS WPT testing
  etc/taskcluster/decision_task.py
Labels: S-awaiting-merge

#25185 Surfman v0.1.2
  Cargo.lock
Labels: A-content/canvas, A-content/webgl, S-awaiting-merge

#25161 devtools: save and send cached messages
  components/devtools/actors/console.rs
  components/devtools/lib.rs
  components/devtools_traits/lib.rs
  components/script/devtools.rs
  components/script/dom/dedicatedworkerglobalscope.rs
  components/script/dom/globalscope.rs
  components/script/dom/serviceworkerglobalscope.rs
  components/script/script_thread.rs
Labels: S-awaiting-merge

#25035 Replace wgpu-native with wgpu-core
  Cargo.lock
  Cargo.toml
  components/script/dom/gpu.rs
  components/script/dom/gpuadapter.rs
  components/script/dom/identityhub.rs
  components/script/dom/navigator.rs
  components/webgpu/Cargo.toml
  components/webgpu/lib.rs
Labels: S-awaiting-merge

#25158 Fix "Tried to use SpatialId before it was defined" layout panic
  components/layout/display_list/builder.rs
  tests/wpt/mozilla/meta/MANIFEST.json
  tests/wpt/mozilla/tests/mozilla/text-overflow-ellipsis-stacking-context-ref.html
  tests/wpt/mozilla/tests/mozilla/text-overflow-ellipsis-stacking-context.html
Labels: S-awaiting-merge

#25139 Use a glmemory bufferpool
  Cargo.lock
  ports/gstplugin/Cargo.toml
  ports/gstplugin/README.md
  ports/gstplugin/servosrc.rs
  ports/gstplugin/test.html
Labels: P-gst-plugin, S-awaiting-merge

#25188 Add extra debug assertions for WebGL errors
  components/canvas/webgl_thread.rs
Labels: A-content/canvas, A-content/webgl, S-awaiting-merge

#25157 Fix intermittent android build error
  Cargo.lock
Labels: S-awaiting-merge

#25162 uwp: add dependency on openxr
  support/hololens/ServoApp/BrowserPage.cpp
  support/hololens/ServoApp/BrowserPage.h
  support/hololens/ServoApp/BrowserPage.xaml
  support/hololens/ServoApp/Package.appxmanifest
  support/hololens/ServoApp/ServoApp.vcxproj
  support/hololens/ServoApp/ServoApp.vcxproj.filters
  support/hololens/ServoApp/XRPkgChecker.cpp
  support/hololens/ServoApp/XRPkgChecker.h
Labels: S-awaiting-merge

#24976 Add ALPN and signature algorithms to OpenSSL config
  Cargo.lock
  components/net/connector.rs
  components/net/http_loader.rs
  components/net/resource_thread.rs
  components/net/tests/fetch.rs
  components/net/tests/main.rs
  components/net/websocket_loader.rs
Labels: S-awaiting-merge

#25171 Install dependencies for the WPT update task
  etc/taskcluster/decision_task.py
  etc/taskcluster/docker/run.dockerfile
  etc/taskcluster/docker/wpt-update.dockerfile
Labels: S-awaiting-merge

#25202 Return a boolean from DOMTokenList::replace to match the spec
  components/script/dom/domtokenlist.rs
  components/script/dom/webidls/DOMTokenList.webidl
  tests/wpt/metadata/dom/nodes/Element-classlist.html.ini
Labels: S-awaiting-merge

#25201 Add onformdata to GlobalEventHandlers
  components/script/dom/macros.rs
  components/script/dom/webidls/EventHandler.webidl
  tests/wpt/metadata/html/dom/idlharness.https.html.ini
  tests/wpt/metadata/html/webappapis/scripting/events/event-handler-all-global-events.html.ini
  tests/wpt/metadata/html/webappapis/scripting/events/event-handler-attributes-body-window.html.ini
  tests/wpt/metadata/html/webappapis/scripting/events/event-handler-attributes-frameset-window.html.ini
  tests/wpt/metadata/html/webappapis/scripting/events/event-handler-attributes-windowless-body.html.ini
Labels: S-awaiting-merge

#25204 Link to Gecko’s reftest analyzer
  tests/wpt/README.md
Labels: S-awaiting-merge

#25218 Rename the ServoSrc type to ServoGstSrc to avoid a name clash
  ports/gstplugin/lib.rs
  ports/gstplugin/servosrc.rs
Labels: S-awaiting-merge

#25217 hidden field named _charset_ now appears in FormData as UTF-8
  components/script/dom/formdata.rs
  components/script/dom/htmlformelement.rs
  components/script/dom/htmlinputelement.rs
  tests/wpt/metadata/html/semantics/forms/form-submission-0/constructing-form-data-set.html.ini
Labels: S-awaiting-merge

#25163 Make tasks easier to find in Treeherder
  etc/taskcluster/decision_task.py
  etc/taskcluster/decisionlib.py
Labels: S-awaiting-merge

#25219 Update ANGLE for UWP fix.
  python/servo/build_commands.py
  support/hololens/ServoApp/ServoApp.vcxproj
  support/hololens/ServoApp/packages.config
Labels: S-awaiting-merge

#24716 Install gperf for linux CI builds.
  etc/taskcluster/docker/build.dockerfile
Labels: S-awaiting-merge

#25227 Remove unnecessary thread in filereader, add stream TODO
  components/script/dom/filereader.rs
  components/script/task_source/file_reading.rs
Labels: S-awaiting-merge

#25222 adding .isConnected DOM attribute
  components/script/dom/node.rs
  components/script/dom/webidls/Node.webidl
  tests/wpt/metadata/dom/idlharness.window.js.ini
  tests/wpt/metadata/dom/nodes/Node-isConnected.html.ini
  tests/wpt/metadata/html/semantics/forms/the-option-element/option-text-setter.html.ini
Labels: S-awaiting-merge

#25243 Rename servosrc to servowebsrc
  ports/gstplugin/README.md
  ports/gstplugin/lib.rs
  ports/gstplugin/servowebsrc.rs
Labels: P-gst-plugin, S-awaiting-merge

#25250 Update surfman for UWP fix.
  Cargo.lock
Labels: S-awaiting-merge

#25159 implement composition event creation in Document.createEvent
  components/script/dom/compositionevent.rs
  components/script/dom/document.rs
  tests/wpt/metadata/dom/events/EventTarget-dispatchEvent.html.ini
  tests/wpt/metadata/dom/nodes/Document-createEvent.https.html.ini
Labels: S-awaiting-merge

#25247 mach clean now finds the right virtualenv to remove
  python/servo/build_commands.py
Labels: S-awaiting-merge

#25246 Block the gstreamer plugin waiting for the next frame
  ports/gstplugin/README.md
  ports/gstplugin/servowebsrc.rs
Labels: P-gst-plugin, S-awaiting-merge

#25255 Use filename instead of opened file descriptor when calling ZipFile
  python/servo/command_base.py
Labels: S-awaiting-merge

#25164 Increase parallelism on Linux WPT testing
  etc/taskcluster/decision_task.py
  tests/wpt/metadata/webdriver/tests/execute_script/cyclic.py.ini
Labels: S-awaiting-merge

#25248 Workaround for #24984 - Solve crashes when panicking / Hang Monitoring by using cargo's patch mechanism to work around a bug in libbacktrace
  Cargo.lock
  Cargo.toml
Labels: S-awaiting-merge

#25267 Issue warning to devtools when module scripts in use.
  components/script/dom/globalscope.rs
  components/script/dom/htmlscriptelement.rs
Labels: S-awaiting-merge

#25272 DOMException now inherits its Javascript toString from Error
  components/script/dom/bindings/error.rs
  components/script/dom/domexception.rs
  components/script/dom/webidls/DOMException.webidl
  tests/wpt/metadata/WebIDL/ecmascript-binding/es-exceptions/DOMException-custom-bindings.any.js.ini
Labels: S-awaiting-merge

#25271 Run GL commands on the GStreamer GL thread
  ports/gstplugin/servowebsrc.rs
Labels: P-gst-plugin, S-awaiting-merge

#25287 Disable H2 ALPN.
  components/net/resource_thread.rs
Labels: S-awaiting-merge

#25289 Cap the number of glyphs per WebRender text run to avoid overflowing WR's limit.
  components/layout/display_list/builder.rs
Labels: S-awaiting-merge

#25253 Make `mach test-tidy --self-test` compatible with Python3
  etc/taskcluster/decision_task.py
  python/tidy/servo_tidy/tidy.py
  python/tidy/servo_tidy_tests/test_tidy.py
Labels: S-awaiting-merge

#25306 Do not wake up embedder on each animation tick
  components/compositing/compositor_thread.rs
  components/constellation/constellation.rs
  components/constellation/pipeline.rs
  components/script_traits/lib.rs
Labels: S-awaiting-merge

#25309 Adjust UWP packaging for submission.
  support/hololens/ServoApp/Package.appxmanifest
  support/hololens/ServoApp/ServoApp.vcxproj
  support/hololens/ServoApp/ServoApp_TemporaryKey.pfx
  support/hololens/package.msbuild
Labels: S-awaiting-merge

#25236 De-deplicate is_cors_safelisted_request_header helper functions
  components/net/fetch/methods.rs
  components/net/http_loader.rs
  components/net_traits/request.rs
  components/script/dom/headers.rs
  components/script/dom/request.rs
  tests/wpt/metadata/fetch/api/headers/headers-no-cors.window.js.ini
Labels: S-awaiting-merge

#25254 Removed createEvent cases, removed now-unused new_uninitializeds
  components/script/dom/closeevent.rs
  components/script/dom/document.rs
  components/script/dom/progressevent.rs
  components/script/dom/webglcontextevent.rs
  tests/wpt/metadata/dom/nodes/Document-createEvent.https.html.ini
Labels: S-awaiting-merge

#25303 Sync WPT with upstream (16-12-2019)
  tests/wpt/metadata/fetch/content-type/response.window.js.ini
  tests/wpt/metadata/fetch/nosniff/parsing-nosniff.window.js.ini
  tests/wpt/metadata/html/browsers/history/the-history-interface/traverse_the_history_1.html.ini
  tests/wpt/metadata/html/browsers/history/the-history-interface/traverse_the_history_4.html.ini
  tests/wpt/metadata/html/browsers/history/the-history-interface/traverse_the_history_5.html.ini
  tests/wpt/metadata/html/interaction/focus/the-autofocus-attribute/skip-document-with-fragment.html.ini
  tests/wpt/metadata/html/semantics/embedded-content/the-iframe-element/iframe_sandbox_popups_nonescaping-3.html.ini
  tests/wpt/metadata/html/semantics/scripting-1/the-script-element/script-onerror-insertion-point-2.html.ini
  tests/wpt/metadata/resource-timing/crossorigin-sandwich-TAO.sub.html.ini
  tests/wpt/metadata/webmessaging/without-ports/017.html.ini
  tests/wpt/web-platform-tests/loading/lazyload/META.yml
  tests/wpt/web-platform-tests/loading/lazyload/disconnected-image-loading-lazy.tentative.html
  tests/wpt/web-platform-tests/loading/lazyload/invisible-lazy-image.tentative.html
  tests/wpt/web-platform-tests/loading/lazyload/original-base-url-applied-2-tentative.html
  tests/wpt/web-platform-tests/loading/lazyload/original-base-url-applied-iframe-tentative.html
Labels: S-awaiting-merge

#25304 Add `layout-2020` option to the `.servobuild` file
  python/servo/command_base.py
  servobuild.example
Labels: S-awaiting-merge

#25264 Initial implementation of GPUBuffer for WebGPU
  Cargo.lock
  components/script/dom/bindings/trace.rs
  components/script/dom/gpuadapter.rs
  components/script/dom/gpubuffer.rs
  components/script/dom/gpubufferusage.rs
  components/script/dom/gpudevice.rs
  components/script/dom/identityhub.rs
  components/script/dom/mod.rs
  components/script/dom/navigator.rs
  components/script/dom/webidls/GPUBuffer.webidl
  components/script/dom/webidls/GPUBufferUsage.webidl
  components/script/dom/webidls/GPUDevice.webidl
  components/webgpu/lib.rs
  servo-tidy.toml
Labels: S-awaiting-merge

#25294 Let hyper automatically set the host header if needed
  components/net/http_loader.rs
  components/net/resource_thread.rs
  components/net/tests/fetch.rs
  components/net/tests/http_loader.rs
Labels: S-awaiting-merge

#25308 Use Windows 10 instead of 7 in user agent string
  components/config/opts.rs
Labels: S-awaiting-merge

#25330 Bump selectors.
  Cargo.lock
  components/selectors/Cargo.toml
Labels: S-awaiting-merge

#25338 Remove Optional pipeline_id
  components/script/dom/dedicatedworkerglobalscope.rs
  components/script/dom/serviceworkerglobalscope.rs
  components/script/dom/serviceworkerregistration.rs
  components/script/dom/worker.rs
  components/script_traits/lib.rs
Labels: S-awaiting-merge

#25350 Print OSMesa environment variables when starting debugger under WPT.
  python/servo/command_base.py
  python/servo/testing_commands.py
Labels: S-awaiting-merge

#25354 Add &DomRoot<T> lint check
  components/script/dom/bindings/serializable.rs
  components/script/dom/bindings/structuredclone.rs
  components/script/dom/bindings/transferable.rs
  components/script/dom/blob.rs
  components/script/dom/globalscope.rs
  components/script/dom/messageport.rs
  python/tidy/servo_tidy/tidy.py
  python/tidy/servo_tidy_tests/rust_tidy.rs
  python/tidy/servo_tidy_tests/test_tidy.py
Labels: S-awaiting-merge

#25359 Autocomputed content-type header now reaches net request
  components/script/dom/request.rs
  tests/wpt/metadata/fetch/api/basic/request-headers.any.js.ini
Labels: S-awaiting-merge

#25366 Remove obsolete HasInstance behavior per heycam/webidl #356
  components/script/dom/bindings/interface.rs
  tests/wpt/metadata/WebIDL/ecmascript-binding/has-instance.html.ini
Labels: S-awaiting-merge

#25371 Upgrade to rustc 1.42.0-nightly (9b98af84c 2019-12-22)
  components/config/Cargo.toml
  components/net/http_cache.rs
  components/script_plugins/lib.rs
  rust-toolchain
Labels: S-awaiting-merge

#25367 apply is: to Document.createElement even when name isn't registered yet
  components/script/dom/create.rs
  components/script/dom/customelementregistry.rs
  tests/wpt/metadata/custom-elements/Document-createElement.html.ini
  tests/wpt/metadata/custom-elements/builtin-coverage.html.ini
  tests/wpt/metadata/custom-elements/upgrading/Document-importNode.html.ini
  tests/wpt/metadata/custom-elements/upgrading/Node-cloneNode.html.ini
Labels: S-awaiting-merge

#25373 let document.createElement[NS] accept a string for options
  components/script/dom/document.rs
  components/script/dom/domimplementation.rs
  components/script/dom/webidls/Document.webidl
  tests/wpt/metadata/custom-elements/Document-createElement.html.ini
  tests/wpt/metadata/custom-elements/Document-createElementNS.html.ini
Labels: S-awaiting-merge
