Repository servo/servo, pull requests merged in 2019-07, with the labels that each got.

#23574 Don't process events while borrowing the event loop
  ports/glutin/app.rs
Labels: A-embedding, S-awaiting-merge

#23575 Pass events loop to glwindow test webvr implementation
  Cargo.lock
  components/webvr/Cargo.toml
  components/webvr_traits/Cargo.toml
  ports/glutin/Cargo.toml
  ports/glutin/embedder.rs
  ports/glutin/events_loop.rs
  ports/libmlservo/Cargo.toml
Labels: A-testing, A-webvr, S-awaiting-merge, S-blocked-on-external

#23665 Support DOMMatrix string constructor
  components/script/dom/dommatrix.rs
  components/script/dom/dommatrixreadonly.rs
  components/script/dom/webidls/DOMMatrix.webidl
  components/script/dom/webidls/DOMMatrixReadOnly.webidl
  components/style/values/generics/transform.rs
  tests/wpt/metadata/css/geometry/DOMMatrix-001.html.ini
Labels: S-awaiting-merge

#23677 Move pre-review PR testing from Travis-CI to Taskcluster
  .travis.yml
  etc/taskcluster/decision_task.py
Labels: S-awaiting-merge

#23690 Get a WebXR device registry to each script thread
  Cargo.lock
  components/canvas_traits/Cargo.toml
  components/canvas_traits/webgl.rs
  components/constellation/Cargo.toml
  components/constellation/constellation.rs
  components/constellation/pipeline.rs
  components/script/Cargo.toml
  components/script/dom/bindings/trace.rs
  components/script/script_thread.rs
  components/script_traits/Cargo.toml
  components/script_traits/lib.rs
  components/servo/lib.rs
Labels: A-webvr, A-xr-zomg, S-awaiting-merge

#23701 Don't suppress build errors.
  python/servo/build_commands.py
Labels: S-awaiting-merge

#23654 Fix panic when running test-background-fetch-permission.html
  components/script/dom/bindings/error.rs
  components/script/dom/permissions.rs
  tests/wpt/metadata/permissions/interfaces.any.js.ini
  tests/wpt/metadata/permissions/test-background-fetch-permission.html.ini
Labels: S-awaiting-merge

#23694 Fix DOMMatrix rotate test failure
  components/script/dom/dommatrixreadonly.rs
  tests/wpt/metadata/css/geometry/DOMMatrix-003.html.ini
Labels: S-awaiting-merge

#23669 Add support for more array-like types in is_array_like
  components/script/dom/bindings/conversions.rs
Labels: S-awaiting-merge

#20885 updated rustup requirement
  python/servo/command_base.py
Labels: S-awaiting-merge

#23707 Ensure GL context is prepared for deinitialization.
  components/compositing/compositor.rs
Labels: S-awaiting-merge

#23717 Upgrade to rustc 1.37.0-nightly (088b98730 2019-07-03)
  components/layout/lib.rs
  components/layout_thread/lib.rs
  components/script/lib.rs
  components/script_plugins/unrooted_must_root.rs
  components/script_plugins/webidl_must_inherit.rs
  etc/rustdoc-with-private
  rust-toolchain
Labels: S-awaiting-merge, S-fails-tidy

#23718 Declare image files as binaries in gitignore
  .gitattributes
Labels: S-awaiting-merge

#23720 Support WebXR devices with main thread affinity
  Cargo.lock
  components/compositing/compositor.rs
  components/compositing/compositor_thread.rs
  components/compositing/windowing.rs
  components/servo/lib.rs
Labels: A-xr-zomg, S-awaiting-merge

#23721 Register a glwindow test XR device
  Cargo.lock
  ports/glutin/Cargo.toml
  ports/glutin/embedder.rs
Labels: A-xr-zomg, S-awaiting-merge, S-blocked-on-external

#23715 Update hololens doc
  docs/hololens.md
Labels: S-awaiting-merge

#23736 Enable uwp feature when building with --uwp.
  python/servo/command_base.py
Labels: S-awaiting-merge

#23738 Add clipboard cut functionality
  components/script/textinput.rs
Labels: S-awaiting-merge

#23746 WebGLSender doesn't really implement Serializable
  components/canvas_traits/webgl.rs
  components/canvas_traits/webgl_channel/mod.rs
Labels: A-xr-zomg, S-awaiting-merge

#23740 Load GST videofilter plugins.
  components/servo/lib.rs
Labels: S-awaiting-merge

#23758 Remove canvas->compositing dependency
  Cargo.lock
  components/canvas/Cargo.toml
  components/canvas/gl_context.rs
  components/servo/Cargo.toml
  components/servo/lib.rs
Labels: S-awaiting-merge

#23744 Make GL/GLES decisions based on the API in use
  Cargo.lock
  components/canvas/gl_context.rs
  components/canvas/webgl_thread.rs
  components/canvas_traits/webgl.rs
  components/script/dom/bindings/trace.rs
  components/script/dom/webgl_extensions/ext/extshadertexturelod.rs
  components/script/dom/webgl_extensions/ext/oeselementindexuint.rs
  components/script/dom/webgl_extensions/ext/oesstandardderivatives.rs
  components/script/dom/webgl_extensions/extensions.rs
  components/script/dom/webglrenderbuffer.rs
  components/script/dom/webglrenderingcontext.rs
  components/script/dom/webglshader.rs
  components/servo/lib.rs
Labels: S-awaiting-merge

#23762 Support no_wgl feature in desktop builds.
  ports/glutin/Cargo.toml
Labels: S-awaiting-merge

#23763 Don't enable azure canvas feature by default.
  components/canvas/Cargo.toml
Labels: S-awaiting-merge

#23765 Appveyor: Fix missing gstreamer dlls
  appveyor.yml
Labels: S-awaiting-merge

#23764 Adjust gstreamer plugins for UWP.
  components/servo/lib.rs
  python/servo/build_commands.py
  support/hololens/ServoApp.vcxproj
  support/hololens/ServoApp.vcxproj.filters
Labels: S-awaiting-merge

#23770 track and update cursor while scrolling
  components/compositing/compositor.rs
Labels: S-awaiting-merge

#23776 Sync WPT with upstream (15-07-2019)
  tests/wpt/metadata/FileAPI/url/url-with-fetch.any.js.ini
  tests/wpt/metadata/css/css-transitions/properties-value-inherit-002.html.ini
  tests/wpt/metadata/css/cssom-view/matchMedia-display-none-iframe.html.ini
  tests/wpt/metadata/fetch/content-type/response.window.js.ini
  tests/wpt/metadata/fetch/content-type/script.window.js.ini
  tests/wpt/metadata/fetch/nosniff/parsing-nosniff.window.js.ini
  tests/wpt/metadata/html/browsers/history/the-history-interface/traverse_the_history_3.html.ini
  tests/wpt/metadata/html/browsers/history/the-history-interface/traverse_the_history_5.html.ini
  tests/wpt/metadata/html/browsers/the-window-object/apis-for-creating-and-navigating-browsing-contexts-by-name/open-features-negative-innerwidth-innerheight.html.ini
  tests/wpt/metadata/html/browsers/the-window-object/apis-for-creating-and-navigating-browsing-contexts-by-name/open-features-negative-screenx-screeny.html.ini
  tests/wpt/metadata/html/browsers/the-window-object/apis-for-creating-and-navigating-browsing-contexts-by-name/open-features-negative-top-left.html.ini
  tests/wpt/metadata/html/browsers/the-window-object/apis-for-creating-and-navigating-browsing-contexts-by-name/open-features-negative-width-height.html.ini
  tests/wpt/metadata/html/browsers/the-window-object/apis-for-creating-and-navigating-browsing-contexts-by-name/open-features-non-integer-height.html.ini
  tests/wpt/metadata/html/browsers/the-window-object/apis-for-creating-and-navigating-browsing-contexts-by-name/open-features-non-integer-innerheight.html.ini
  tests/wpt/metadata/html/browsers/the-window-object/apis-for-creating-and-navigating-browsing-contexts-by-name/open-features-non-integer-innerwidth.html.ini
  tests/wpt/metadata/html/browsers/the-window-object/apis-for-creating-and-navigating-browsing-contexts-by-name/open-features-non-integer-left.html.ini
  tests/wpt/metadata/html/browsers/the-window-object/apis-for-creating-and-navigating-browsing-contexts-by-name/open-features-non-integer-screenx.html.ini
  tests/wpt/metadata/html/browsers/the-window-object/apis-for-creating-and-navigating-browsing-contexts-by-name/open-features-non-integer-screeny.html.ini
  tests/wpt/metadata/html/browsers/the-window-object/apis-for-creating-and-navigating-browsing-contexts-by-name/open-features-non-integer-top.html.ini
  tests/wpt/metadata/html/browsers/the-window-object/apis-for-creating-and-navigating-browsing-contexts-by-name/open-features-non-integer-width.html.ini
  tests/wpt/metadata/html/semantics/interactive-elements/the-details-element/toggleEvent.html.ini
  tests/wpt/metadata/html/webappapis/scripting/processing-model-2/unhandled-promise-rejections/promise-rejection-events-onerror.html.ini
  tests/wpt/metadata/resource-timing/resource_TAO_origin.htm.ini
  tests/wpt/metadata/resource-timing/resource_TAO_zero.htm.ini
  tests/wpt/metadata/webaudio/the-audio-api/the-audiobuffersourcenode-interface/sub-sample-buffer-stitching.html.ini
  tests/wpt/metadata/workers/baseurl/alpha/import-in-moduleworker.html.ini
  tests/wpt/metadata/workers/constructors/Worker/Worker-constructor.html.ini
  tests/wpt/mozilla/meta/css/iframe/stacking_context_position_a.html.ini
  tests/wpt/web-platform-tests/interfaces/webrtc.idl
Labels: S-awaiting-merge

#23203 Implement PerformanceNavigation interface
  components/script/dom/mod.rs
  components/script/dom/performance.rs
  components/script/dom/performancenavigation.rs
  components/script/dom/webidls/Performance.webidl
  components/script/dom/webidls/PerformanceNavigation.webidl
  tests/wpt/metadata/navigation-timing/test_navigation_attributes_exist.html.ini
  tests/wpt/metadata/navigation-timing/test_navigation_redirectCount_none.html.ini
  tests/wpt/metadata/navigation-timing/test_navigation_type_backforward.html.ini
  tests/wpt/metadata/navigation-timing/test_navigation_type_enums.html.ini
  tests/wpt/metadata/navigation-timing/test_navigation_type_reload.html.ini
  tests/wpt/metadata/navigation-timing/test_no_previous_document.html.ini
  tests/wpt/metadata/navigation-timing/test_performance_attributes_exist.html.ini
  tests/wpt/metadata/navigation-timing/test_timing_attributes_order.html.ini
  tests/wpt/metadata/navigation-timing/test_timing_client_redirect.html.ini
  tests/wpt/metadata/navigation-timing/test_timing_reload.html.ini
  tests/wpt/metadata/navigation-timing/test_timing_server_redirect.html.ini
  tests/wpt/metadata/navigation-timing/test_timing_xserver_redirect.html.ini
  tests/wpt/mozilla/meta/MANIFEST.json
  tests/wpt/mozilla/tests/mozilla/interfaces.html
Labels: S-awaiting-merge

#23785 Dirty the canvas when WebXR draws to its GL context
  components/script/dom/xrsession.rs
Labels: A-content/script, A-xr-zomg, S-awaiting-merge

#23630 Update rayon to dedupe crossbeam-epoch
  Cargo.lock
  components/layout/parallel.rs
  components/style/driver.rs
  components/style/global_style_data.rs
  components/style/parallel.rs
  servo-tidy.toml
  tests/unit/style/rule_tree/bench.rs
Labels: S-awaiting-merge

#23784 Get the glwindow test XR device to share a GL context with WebGL
  Cargo.lock
  ports/glutin/app.rs
  ports/glutin/context.rs
  ports/glutin/embedder.rs
  ports/glutin/headed_window.rs
  ports/glutin/headless_window.rs
  ports/glutin/window_trait.rs
Labels: A-xr-zomg, S-awaiting-merge

#23792 Update README about local gstreamer copy path
  README.md
Labels: S-awaiting-merge

#23783 Add source module to UWP logging output
  ports/libsimpleservo/capi/src/vslogger.rs
  support/hololens/Servo.cpp
Labels: S-awaiting-merge, S-fails-tidy

#23801 Expose javascript:window.alert() to libsimpleservo
  ports/libmlservo/src/lib.rs
  ports/libsimpleservo/api/src/lib.rs
  ports/libsimpleservo/capi/src/lib.rs
  ports/libsimpleservo/jniapi/src/lib.rs
  support/android/apk/servoapp/src/main/java/org/mozilla/servo/MainActivity.java
  support/android/apk/servoview/src/main/java/org/mozilla/servoview/JNIServo.java
  support/android/apk/servoview/src/main/java/org/mozilla/servoview/Servo.java
Labels: S-awaiting-merge

#23812 ISSUE-21257: set redirectEnd on PerformanceResourceTiming
  components/net/http_loader.rs
  components/net_traits/lib.rs
  components/script/dom/performanceresourcetiming.rs
  components/script/dom/webidls/PerformanceResourceTiming.webidl
  tests/wpt/metadata/resource-timing/idlharness.any.js.ini
  tests/wpt/metadata/resource-timing/resource_TAO_origin.htm.ini
  tests/wpt/metadata/resource-timing/resource_TAO_zero.htm.ini
Labels: S-awaiting-merge

#23808 Add a HOST_FILE env variable and fix the wdspec setup errors that it causes
  python/servo/testing_commands.py
  tests/wpt/metadata/webdriver/tests/delete_session/delete.py.ini
  tests/wpt/metadata/webdriver/tests/element_send_keys/scroll_into_view.py.ini
  tests/wpt/metadata/webdriver/tests/element_send_keys/send_keys.py.ini
  tests/wpt/metadata/webdriver/tests/execute_script/properties.py.ini
  tests/wpt/metadata/webdriver/tests/find_element_from_element/find.py.ini
  tests/wpt/metadata/webdriver/tests/find_elements/find.py.ini
  tests/wpt/metadata/webdriver/tests/find_elements_from_element/find.py.ini
  tests/wpt/metadata/webdriver/tests/get_element_attribute/get.py.ini
  tests/wpt/metadata/webdriver/tests/get_element_css_value/get.py.ini
  tests/wpt/metadata/webdriver/tests/get_element_rect/get.py.ini
  tests/wpt/metadata/webdriver/tests/get_element_tag_name/get.py.ini
  tests/wpt/metadata/webdriver/tests/get_element_text/get.py.ini
  tests/wpt/metadata/webdriver/tests/get_named_cookie/get.py.ini
  tests/wpt/metadata/webdriver/tests/is_element_enabled/enabled.py.ini
  tests/wpt/metadata/webdriver/tests/is_element_selected/selected.py.ini
  tests/wpt/metadata/webdriver/tests/set_window_rect/set.py.ini
  tests/wpt/metadata/webdriver/tests/switch_to_frame/cross_origin.py.ini
  tests/wpt/metadata/webdriver/tests/switch_to_frame/switch.py.ini
  tests/wpt/metadata/webdriver/tests/switch_to_parent_frame/switch.py.ini
Labels: S-awaiting-merge

#23819 Fix Python and gstreamer instructions for Windows
  README.md
Labels: S-awaiting-merge

#23568 Remove some duplicate dependencies
  Cargo.lock
  servo-tidy.toml
Labels: S-awaiting-merge

#23820 Implement Link and PartialLink text selectors for FindElement and related WebDriver commands
  components/script/script_thread.rs
  components/script/webdriver_handlers.rs
  components/script_traits/webdriver_msg.rs
  components/webdriver_server/lib.rs
  tests/wpt/metadata/webdriver/tests/find_element/find.py.ini
  tests/wpt/metadata/webdriver/tests/find_element_from_element/find.py.ini
  tests/wpt/metadata/webdriver/tests/find_elements/find.py.ini
  tests/wpt/metadata/webdriver/tests/find_elements_from_element/find.py.ini
Labels: S-awaiting-merge

#23824 Stylo: replace uses of mem::uninitialized with MaybeUninit
  components/servo_arc/lib.rs
  components/style/gecko/profiler.rs
  components/style/gecko_string_cache/mod.rs
  components/style/macros.rs
  components/style/properties/gecko.mako.rs
  components/style/properties/helpers/animated_properties.mako.rs
  components/style/properties/longhands/font.mako.rs
  components/style/properties/properties.mako.rs
  components/to_shmem/lib.rs
Labels: S-awaiting-merge

#23829 Use Servo's ANGLE fork for UWP.
  python/servo/build_commands.py
  support/hololens/ServoApp/ServoApp.vcxproj
  support/hololens/ServoApp/packages.config
Labels: S-awaiting-merge

#23830 Generate simpleservo.h in appropriate target directory.
  ports/libsimpleservo/capi/build.rs
Labels: S-awaiting-merge

#23833 Remove forked gst-plugins-bad formula
  etc/taskcluster/macos/Brewfile-gstreamer
  etc/taskcluster/macos/Formula/gst-plugins-bad.diff
  etc/taskcluster/macos/Formula/gst-plugins-bad.rb
  etc/taskcluster/macos/Formula/recreate.sh
Labels: S-awaiting-merge

#23831 Support Scroll in HoloLens mode
  support/hololens/ServoApp/BrowserPage.cpp
  support/hololens/ServoApp/BrowserPage.h
  support/hololens/ServoApp/BrowserPage.xaml
  support/hololens/ServoApp/Servo.cpp
  support/hololens/ServoApp/Servo.h
Labels: S-awaiting-merge

#23837 update link_called when link function called.
  components/script/dom/webglprogram.rs
Labels: S-awaiting-merge

#23828 Made all "free" extern "C" APIs in simpleservo fallible by returning …
  ports/libsimpleservo/capi/src/lib.rs
Labels: S-awaiting-merge

#23845 [hololens] More events, remove most of the statics, better shutdown
  support/hololens/ServoApp/App.cpp
  support/hololens/ServoApp/BrowserPage.cpp
  support/hololens/ServoApp/BrowserPage.h
  support/hololens/ServoApp/BrowserPage.xaml
  support/hololens/ServoApp/Common/DeviceResources.h
  support/hololens/ServoApp/Servo.cpp
  support/hololens/ServoApp/Servo.h
  support/hololens/ServoApp/pch.h
Labels: S-awaiting-merge

#23843 Don't insta-free in UniqueArc::assume_init.
  components/servo_arc/lib.rs
Labels: S-awaiting-merge

#23847 Pass the event loop waker into WebXR
  Cargo.lock
  components/embedder_traits/Cargo.toml
  components/embedder_traits/lib.rs
  components/net/tests/main.rs
  components/servo/lib.rs
  ports/glutin/events_loop.rs
  ports/libmlservo/src/lib.rs
  ports/libsimpleservo/capi/src/lib.rs
  ports/libsimpleservo/jniapi/src/lib.rs
Labels: A-xr-zomg, S-awaiting-merge

#23852 Update SpiderMonkey bindings for Windows arm64 crash fix
  Cargo.lock
  components/script/dom/bindings/codegen/CodegenRust.py
  components/script/dom/bindings/interface.rs
Labels: S-awaiting-merge

#23855 Changed DOMString usages to string in MediaFragmentParser
  components/script/dom/htmlmediaelement.rs
  components/script/dom/mediafragmentparser.rs
Labels: S-awaiting-merge

#23868 When using the WebGL external image API, use sync calls if we happen to be on the WebGL thread
  components/canvas/webgl_mode/inprocess.rs
  components/canvas/webgl_thread.rs
  components/servo/lib.rs
Labels: A-content/webgl, S-awaiting-merge

#23866 Hololens: Fix shutdown
  support/hololens/ServoApp/BrowserPage.cpp
  support/hololens/ServoApp/Servo.cpp
  support/hololens/ServoApp/Servo.h
Labels: S-awaiting-merge

#23848 Replace use of callbacks in webxr by channels
  Cargo.lock
  Cargo.toml
  components/canvas/Cargo.toml
  components/canvas/webgl_mode/inprocess.rs
  components/canvas/webgl_thread.rs
  components/canvas_traits/webgl.rs
  components/script/dom/webglrenderingcontext.rs
  components/script/dom/xr.rs
  components/script/dom/xrsession.rs
  components/script/dom/xrtest.rs
  components/servo/lib.rs
Labels: A-xr-zomg, S-awaiting-merge, S-blocked-on-external

#23871 Sync WPT with upstream (27-07-2019)
  tests/wpt/metadata/FileAPI/url/url-with-fetch.any.js.ini
  tests/wpt/metadata/dom/nodes/remove-and-adopt-crash.html.ini
  tests/wpt/metadata/fetch/content-type/response.window.js.ini
  tests/wpt/metadata/fetch/content-type/script.window.js.ini
  tests/wpt/metadata/fetch/nosniff/parsing-nosniff.window.js.ini
  tests/wpt/metadata/html/browsers/history/the-history-interface/traverse_the_history_1.html.ini
  tests/wpt/metadata/html/browsers/history/the-history-interface/traverse_the_history_2.html.ini
  tests/wpt/metadata/html/browsers/the-window-object/apis-for-creating-and-navigating-browsing-contexts-by-name/creating_browsing_context_test_01.html.ini
  tests/wpt/metadata/html/syntax/parsing/DOMContentLoaded-defer.html.ini
  tests/wpt/metadata/html/webappapis/dynamic-markup-insertion/opening-the-input-stream/ignore-opens-during-unload.window.js.ini
  tests/wpt/metadata/webaudio/the-audio-api/the-analysernode-interface/realtimeanalyser-fft-scaling.html.ini
  tests/wpt/metadata/webaudio/the-audio-api/the-audiobuffersourcenode-interface/sub-sample-buffer-stitching.html.ini
  tests/wpt/web-platform-tests/cookies/cookie-enabled-noncookie-frame.html
  tests/wpt/web-platform-tests/css/css-writing-modes/wm-propagation-001-ref.html
  tests/wpt/web-platform-tests/css/css-writing-modes/wm-propagation-001.html
  tests/wpt/web-platform-tests/css/css-writing-modes/wm-propagation-002-ref.html
  tests/wpt/web-platform-tests/css/css-writing-modes/wm-propagation-002.html
  tests/wpt/web-platform-tests/dom/nodes/remove-and-adopt-crash.html
  tests/wpt/web-platform-tests/element-timing/image-TAO.sub.html
  tests/wpt/web-platform-tests/element-timing/resources/TAOImage.py
  tests/wpt/web-platform-tests/interfaces/shape-detection-api.idl
  tests/wpt/web-platform-tests/largest-contentful-paint/contracted-image.html
  tests/wpt/web-platform-tests/largest-contentful-paint/cross-origin-image.sub.html
  tests/wpt/web-platform-tests/largest-contentful-paint/expanded-image.html
  tests/wpt/web-platform-tests/largest-contentful-paint/image-TAO.sub.html
  tests/wpt/web-platform-tests/largest-contentful-paint/image-src-change.html
  tests/wpt/web-platform-tests/largest-contentful-paint/loadTime-after-appendChild.html
  tests/wpt/web-platform-tests/largest-contentful-paint/observe-image.html
  tests/wpt/web-platform-tests/largest-contentful-paint/observe-text.html
  tests/wpt/web-platform-tests/largest-contentful-paint/repeated-image.html
  tests/wpt/web-platform-tests/mathml/relations/css-styling/attribute-mapping-001.html
  tests/wpt/web-platform-tests/mathml/relations/css-styling/attribute-mapping-002.html
  tests/wpt/web-platform-tests/mathml/relations/css-styling/padding-border-margin/border-001.html
  tests/wpt/web-platform-tests/mathml/support/mathml-fragments.js
  tests/wpt/web-platform-tests/mediacapture-image/ImageCapture-MediaTrackSupportedConstraints.https.html
  tests/wpt/web-platform-tests/mediacapture-image/MediaStreamTrack-applyConstraints-getSettings.html
  tests/wpt/web-platform-tests/mediacapture-image/MediaStreamTrack-applyConstraints.html
  tests/wpt/web-platform-tests/mediacapture-image/MediaStreamTrack-getCapabilities.html
  tests/wpt/web-platform-tests/mediacapture-image/MediaStreamTrack-getConstraints-fast.html
  tests/wpt/web-platform-tests/mediacapture-image/MediaStreamTrack-getSettings.html
  tests/wpt/web-platform-tests/pointerevents/pointerlock/pointerevent_pointermove_in_pointerlock.html
  tests/wpt/web-platform-tests/resources/chromium/image_capture.mojom.js
  tests/wpt/web-platform-tests/resources/chromium/mock-imagecapture.js
  tests/wpt/web-platform-tests/shape-detection/idlharness.any.js
  tests/wpt/web-platform-tests/shape-detection/idlharness.https.any.js
  tests/wpt/web-platform-tests/shape-detection/resources/shapedetection-helpers.js
  tests/wpt/web-platform-tests/webxr/resources/webxr_util.js
Labels: S-awaiting-merge

#23857 WebXR sessions track draw texture
  Cargo.lock
  Cargo.toml
  components/canvas/webgl_mode/inprocess.rs
  components/script/dom/xrsession.rs
  components/script/dom/xrwebgllayer.rs
  tests/wpt/metadata/webxr/xrBoundedReferenceSpace_updates.https.html.ini
  tests/wpt/metadata/webxr/xrSession_end.https.html.ini
  tests/wpt/metadata/webxr/xrSession_input_events_end.https.html.ini
  tests/wpt/metadata/webxr/xrSession_prevent_multiple_exclusive.https.html.ini
Labels: A-xr-zomg, S-awaiting-merge, S-blocked-on-external

#23878 Fix ARM64 app startup
  support/hololens/ServoApp/ServoApp.vcxproj
  support/hololens/ServoApp/ServoApp.vcxproj.filters
Labels: S-awaiting-merge

#23876 Make another webgl test have a longer timeout.
  tests/wpt/webgl/meta/MANIFEST.json
  tests/wpt/webgl/tests/conformance/glsl/misc/shader-with-reserved-words.html
  tests/wpt/webgl/tools/timeout.patch
Labels: S-awaiting-merge

#23883 Drop webgl main thread data during shutdown.
  components/canvas/webgl_thread.rs
Labels: S-awaiting-merge

#23884 Don't panic if WebGL thread can't be reached during finalization.
  components/script/dom/webglbuffer.rs
  components/script/dom/webglframebuffer.rs
  components/script/dom/webglprogram.rs
  components/script/dom/webglrenderbuffer.rs
  components/script/dom/webglrenderingcontext.rs
  components/script/dom/webglshader.rs
  components/script/dom/webgltexture.rs
  components/script/dom/webglvertexarrayobjectoes.rs
Labels: S-awaiting-merge

#23886 Avoid panic during shutdown when Blobs exist
  components/script/dom/blob.rs
Labels: S-awaiting-merge

#23839 Improve session test lifecycle code
  components/script/dom/fakexrdevice.rs
  components/script/dom/webidls/FakeXRDevice.webidl
  components/script/dom/xrtest.rs
  tests/wpt/metadata/webxr/xrDevice_disconnect_ends.https.html.ini
Labels: S-awaiting-merge

#23887 Use origin of final HTTP response as document origin
  components/script/script_thread.rs
  tests/wpt/mozilla/meta/MANIFEST.json
  tests/wpt/mozilla/tests/mozilla/document_origin_redirect.html
  tests/wpt/mozilla/tests/mozilla/document_origin_redirect_subpage.html
Labels: S-awaiting-merge

#23891 WebXr: allow for only a single raf message, until callbacks execute
  components/script/dom/xrsession.rs
Labels: S-awaiting-merge

#23893 Remove GStreamer dependencies from UWP app.
  components/servo/Cargo.toml
  components/servo/lib.rs
  python/servo/build_commands.py
  support/hololens/ServoApp/ServoApp.vcxproj
  support/hololens/ServoApp/ServoApp.vcxproj.filters
Labels: S-awaiting-merge

#23870 Upgrade to rustc 1.38.0-nightly (dddb7fca0 2019-07-30)
  components/config/lib.rs
  components/config/pref_util.rs
  components/profile_traits/energy.rs
  components/script/dom/attr.rs
  components/script/dom/bindings/codegen/CodegenRust.py
  components/script/dom/bindings/root.rs
  components/script/dom/compositionevent.rs
  components/script/dom/document.rs
  components/script/dom/element.rs
  components/script/dom/event.rs
  components/script/dom/focusevent.rs
  components/script/dom/htmlelement.rs
  components/script/dom/htmlformelement.rs
  components/script/dom/htmlheadelement.rs
  components/script/dom/htmlinputelement.rs
  components/script/dom/htmloptionscollection.rs
  components/script/dom/htmlscriptelement.rs
  components/script/dom/htmltableelement.rs
  components/script/dom/htmltablerowelement.rs
  components/script/dom/htmltablesectionelement.rs
  components/script/dom/inputevent.rs
  components/script/dom/keyboardevent.rs
  components/script/dom/mouseevent.rs
  components/script/dom/node.rs
  components/script/dom/nodelist.rs
  components/script/dom/range.rs
  components/script/dom/servoparser/mod.rs
  components/script/dom/storageevent.rs
  components/script/dom/text.rs
  components/script/dom/uievent.rs
  components/script/dom/vrdisplay.rs
  components/script/dom/wheelevent.rs
  components/script/dom/windowproxy.rs
  components/script/script_thread.rs
  components/script/task.rs
  components/script/textinput.rs
  components/style/rule_tree/mod.rs
  rust-toolchain
Labels: S-awaiting-merge
