Repository servo/servo, pull requests merged in 2019-04, with the labels that each got.

#23147 README: Specify Xcode version.
  README.md
Labels: S-tests-failed

#23126 Fix various Windows dependency issues
  python/servo/build_commands.py
Labels: S-tests-failed

#23128 Pass not none value in setfullscreen
  components/compositing/windowing.rs
  components/constellation/constellation.rs
  components/script/dom/document.rs
  components/script/script_thread.rs
  components/script_traits/lib.rs
  components/servo/lib.rs
  ports/servo/browser.rs
  ports/servo/glutin_app/window.rs
Labels: S-awaiting-merge

#23145 Add connectEnd attribute to PerformanceResourceTiming interface
  components/net/http_loader.rs
  components/net_traits/lib.rs
  components/script/dom/performanceresourcetiming.rs
  components/script/dom/webidls/PerformanceResourceTiming.webidl
  tests/wpt/metadata/resource-timing/idlharness.any.js.ini
  tests/wpt/metadata/resource-timing/resource_TAO_zero.htm.ini
Labels: S-awaiting-merge

#23143 Remove compound microtasks
  components/script/dom/mutationobserver.rs
  components/script/script_thread.rs
Labels: S-tests-failed

#23175 Add a note to indicate PKG_CONFIG_PATH required
  README.md
Labels: S-awaiting-merge

#23174 Add default paths for WPT tests
  tests/wpt/run.py
Labels: S-awaiting-merge, S-fails-tidy

#23166 call window.gl() once
  components/compositing/compositor.rs
Labels: S-awaiting-merge, S-fails-tidy

#23162 Review WPT sync PRs automatically
  etc/ci/update-wpt-checkout
Labels: S-awaiting-merge

#22521 Refactoring RequestInit to use a Builder Pattern
  components/constellation/constellation.rs
  components/constellation/network_listener.rs
  components/gfx/font_cache_thread.rs
  components/net/resource_thread.rs
  components/net/tests/http_loader.rs
  components/net/websocket_loader.rs
  components/net_traits/lib.rs
  components/net_traits/request.rs
  components/script/document_loader.rs
  components/script/dom/bindings/trace.rs
  components/script/dom/dedicatedworkerglobalscope.rs
  components/script/dom/document.rs
  components/script/dom/eventsource.rs
  components/script/dom/htmlimageelement.rs
  components/script/dom/htmlmediaelement.rs
  components/script/dom/htmlscriptelement.rs
  components/script/dom/htmlvideoelement.rs
  components/script/dom/serviceworkerglobalscope.rs
  components/script/dom/websocket.rs
  components/script/dom/workerglobalscope.rs
  components/script/dom/worklet.rs
  components/script/dom/xmlhttprequest.rs
  components/script/fetch.rs
  components/script/layout_image.rs
  components/script/script_thread.rs
  components/script/stylesheet_loader.rs
  components/script_traits/script_msg.rs
Labels: S-awaiting-merge

#23183 Replace panic with warn in DocumentLoader.finish_load.
  components/script/document_loader.rs
Labels: S-awaiting-merge

#23184 Force python 2.7 on TravisCI.
  .travis.yml
Labels: S-awaiting-merge

#23191 Remove useless embedder proxy clone
  components/constellation/constellation.rs
Labels: S-awaiting-merge

#23196 Make use of RefCell::try_borrow_unguarded
  components/constellation/constellation.rs
  components/script/dom/bindings/cell.rs
  components/script/dom/xmlhttprequest.rs
  components/script/lib.rs
  components/style/error_reporting.rs
  components/style/servo/selector_parser.rs
  rust-toolchain
Labels: S-awaiting-merge

#23204 Move media backend initialization to process startup
  Cargo.lock
  components/script/Cargo.toml
  components/script/dom/baseaudiocontext.rs
  components/script/dom/htmlmediaelement.rs
  components/script/dom/mediadevices.rs
  components/script/dom/rtcpeerconnection.rs
  components/servo/Cargo.toml
  components/servo/lib.rs
Labels: S-awaiting-merge

#23197 Update bindgen and crates that depend on it.
  Cargo.lock
  components/style/Cargo.toml
Labels: S-awaiting-merge

#23206 Sync WPT with upstream (16-04-2019)
  tests/wpt/metadata/FileAPI/blob/Blob-array-buffer.any.js.ini
  tests/wpt/metadata/FileAPI/blob/Blob-stream.any.js.ini
  tests/wpt/metadata/FileAPI/blob/Blob-text.any.js.ini
  tests/wpt/metadata/FileAPI/idlharness.html.ini
  tests/wpt/metadata/FileAPI/idlharness.worker.js.ini
  tests/wpt/metadata/css/css-fonts/variations/at-font-face-font-matching.html.ini
  tests/wpt/metadata/css/css-text-decor/parsing/text-decoration-line-valid.html.ini
  tests/wpt/metadata/custom-elements/upgrading/Node-cloneNode.html.ini
  tests/wpt/metadata/custom-elements/upgrading/upgrading-parser-created-element.html.ini
  tests/wpt/metadata/encoding/single-byte-decoder.html.ini
  tests/wpt/metadata/fetch/sec-metadata/prefetch.tentative.https.sub.html.ini
  tests/wpt/metadata/fetch/sec-metadata/preload.tentative.https.sub.html.ini
  tests/wpt/metadata/html/browsers/history/the-history-interface/traverse_the_history_5.html.ini
  tests/wpt/metadata/html/browsers/the-window-object/closed-attribute.window.js.ini
  tests/wpt/metadata/html/dom/elements/global-attributes/dataset-binding.window.js.ini
  tests/wpt/metadata/html/semantics/embedded-content/the-img-element/non-active-document.html.ini
  tests/wpt/metadata/html/webappapis/dynamic-markup-insertion/document-write/iframe_005.html.ini
  tests/wpt/metadata/offscreen-canvas/the-offscreen-canvas/offscreencanvas.commit.w.html.ini
  tests/wpt/metadata/webaudio/the-audio-api/the-analysernode-interface/realtimeanalyser-fft-scaling.html.ini
  tests/wpt/metadata/webaudio/the-audio-api/the-audioworklet-interface/audioworklet-suspend.https.html.ini
  tests/wpt/metadata/webstorage/set.window.js.ini
  tests/wpt/mozilla/meta/css/transition_calc_implicit.html.ini
  tests/wpt/web-platform-tests/FileAPI/blob/Blob-array-buffer.any.js
  tests/wpt/web-platform-tests/FileAPI/blob/Blob-stream.any.js
  tests/wpt/web-platform-tests/FileAPI/blob/Blob-text.any.js
  tests/wpt/web-platform-tests/FileAPI/support/Blob.js
  tests/wpt/web-platform-tests/css/css-text-decor/parsing/text-decoration-line-invalid.html
  tests/wpt/web-platform-tests/css/css-text-decor/parsing/text-decoration-line-valid.html
  tests/wpt/web-platform-tests/custom-elements/upgrading/Node-cloneNode.html
  tests/wpt/web-platform-tests/custom-elements/upgrading/upgrading-parser-created-element.html
  tests/wpt/web-platform-tests/feature-policy/experimental-features/lazyload/loading-frame-default-eager-disabled-tentative.sub.html
  tests/wpt/web-platform-tests/feature-policy/experimental-features/lazyload/loading-frame-default-eager-disabled-tentative.sub.html.headers
  tests/wpt/web-platform-tests/fetch/sec-metadata/prefetch.tentative.https.sub.html
  tests/wpt/web-platform-tests/fetch/sec-metadata/preload.tentative.https.sub.html
  tests/wpt/web-platform-tests/fetch/sec-metadata/resources/record-header.py
  tests/wpt/web-platform-tests/html/dom/elements/global-attributes/dataset-binding.window.js
  tests/wpt/web-platform-tests/interfaces/FileAPI.idl
  tests/wpt/web-platform-tests/pointerevents/pointerlock/pointerevent_coordinates_when_locked.html
  tests/wpt/web-platform-tests/portals/portal-activate-event-constructor.html
  tests/wpt/web-platform-tests/tools/manifest/download.py
  tests/wpt/web-platform-tests/tools/manifest/manifest.py
  tests/wpt/web-platform-tests/tools/manifest/tests/test_utils.py
  tests/wpt/web-platform-tests/tools/manifest/tests/test_vcs.py
  tests/wpt/web-platform-tests/tools/manifest/update.py
  tests/wpt/web-platform-tests/tools/manifest/utils.py
  tests/wpt/web-platform-tests/tools/manifest/vcs.py
  tests/wpt/web-platform-tests/webaudio/resources/audit.js
  tests/wpt/web-platform-tests/webaudio/the-audio-api/the-audioworklet-interface/audioworklet-suspend.https.html
  tests/wpt/web-platform-tests/webstorage/set.window.js
  tests/wpt/web-platform-tests/webxr/xrSession_transfer_outputContext.https.html
Labels: S-awaiting-merge

#23187 Do not unwrap empty unminified_js_dir in HTMLScriptElement.unminify_js.
  components/script/dom/htmlscriptelement.rs
Labels: S-awaiting-merge

#23216 Allow replaying media
  components/script/dom/htmlmediaelement.rs
Labels: S-awaiting-merge

#23228 Remove :-servo-case-sensitive-type-attr()
  components/layout_thread/dom_wrapper.rs
  components/script/dom/element.rs
  components/style/servo/selector_parser.rs
  resources/presentational-hints.css
Labels: S-awaiting-merge

#23230 Update to 4/18 Rust nightly.
  rust-toolchain
Labels: S-awaiting-merge

#23215 Keep a map between channel position and channel index for decoded audio
  components/script/dom/baseaudiocontext.rs
Labels: S-awaiting-merge

#23006 Added WebDriver DeleteCookies Function
  components/net/cookie.rs
  components/net/cookie_storage.rs
  components/net/resource_thread.rs
  components/net_traits/lib.rs
  components/script/script_thread.rs
  components/script/webdriver_handlers.rs
  components/script_traits/webdriver_msg.rs
  components/webdriver_server/lib.rs
Labels: S-awaiting-merge

#22769 Use a threadpool for fetch
  Cargo.lock
  components/net/Cargo.toml
  components/net/resource_thread.rs
  tests/wpt/mozilla/meta/MANIFEST.json
  tests/wpt/mozilla/meta/mozilla/fetch_cannot_overwhelm_system.window.js.ini
  tests/wpt/mozilla/tests/mozilla/fetch_cannot_overwhelm_system.window.js
Labels: S-awaiting-merge

#23234 Update webdriver to 0.39
  Cargo.lock
  components/webdriver_server/Cargo.toml
  components/webdriver_server/lib.rs
Labels: S-awaiting-merge

#23237 Adds webdriver command Get Timeouts
  components/webdriver_server/lib.rs
Labels: S-awaiting-merge

#23247 Remove use of auto media backend. And update servo-media
  Cargo.lock
  components/script/dom/htmlmediaelement.rs
  components/servo/Cargo.toml
  components/servo/lib.rs
Labels: S-awaiting-merge

#23178 Add PerformanceResourceTiming: ResponseEnd
  components/net/http_loader.rs
  components/net_traits/lib.rs
  components/script/dom/performanceresourcetiming.rs
  components/script/dom/webidls/PerformanceResourceTiming.webidl
  tests/wpt/metadata/resource-timing/idlharness.any.js.ini
  tests/wpt/metadata/resource-timing/resource_reuse.sub.html.ini
Labels: S-awaiting-merge

#23246 Don't run full WPT testsuite twice.
  etc/ci/update-wpt-checkout
Labels: S-awaiting-merge

#23252 Allow mac WPT jobs to run longer than 60 minutes
  etc/taskcluster/decision_task.py
Labels: S-awaiting-merge

#23263 Upgrade to rustc 1.36.0-nightly (e305df184 2019-04-24)
  Cargo.lock
  components/style_derive/animate.rs
  rust-toolchain
  tests/unit/script/size_of.rs
Labels: S-awaiting-merge

#23262 Update SetCursor behavior
  components/compositing/compositor.rs
  components/constellation/constellation.rs
  components/script_traits/script_msg.rs
Labels: S-awaiting-merge

#23270 Add input validation for AudioParam methods
  components/script/dom/audioparam.rs
  components/script/dom/webidls/AudioParam.webidl
  tests/wpt/metadata/webaudio/the-audio-api/the-audioparam-interface/audioparam-exceptional-values.html.ini
Labels: S-awaiting-merge

#23211 Add Windows x86 build job.
  Cargo.lock
  components/script/build.rs
  components/script/vcvars.bat
  etc/taskcluster/decision_task.py
  etc/taskcluster/decisionlib.py
  python/servo/packages.py
Labels: S-awaiting-merge

#23182 Switch to Xenial for Linux CI.
  .travis.yml
Labels: S-awaiting-merge

#23275 Use llvm's linker for x86 builds.
  .cargo/config
Labels: S-awaiting-merge

#23276 Install gcc-6 on TravisCI.
  .travis.yml
Labels: S-awaiting-merge

#23259 Implement AudioParam.setValueCurveAtTime #22897
  components/script/dom/audioparam.rs
  components/script/dom/webidls/AudioParam.webidl
  tests/wpt/metadata/webaudio/idlharness.https.window.js.ini
  tests/wpt/metadata/webaudio/the-audio-api/the-audioparam-interface/audioparam-exceptional-values.html.ini
  tests/wpt/metadata/webaudio/the-audio-api/the-audioparam-interface/audioparam-method-chaining.html.ini
  tests/wpt/metadata/webaudio/the-audio-api/the-audioparam-interface/audioparam-setValueCurve-exceptions.html.ini
  tests/wpt/metadata/webaudio/the-audio-api/the-audioparam-interface/audioparam-setValueCurveAtTime.html.ini
Labels: S-awaiting-merge

#23279 Implement deprecated setPosition and setOrientation methods for AudioListener #22898
  components/script/dom/audiolistener.rs
  components/script/dom/webidls/AudioListener.webidl
  tests/wpt/metadata/webaudio/idlharness.https.window.js.ini
  tests/wpt/metadata/webaudio/the-audio-api/the-pannernode-interface/panner-equalpower.html.ini
Labels: S-awaiting-merge

#23284 Sync WPT with upstream (28-04-2019)
  tests/wpt/metadata/FileAPI/url/url-with-fetch.any.js.ini
  tests/wpt/metadata/encoding/single-byte-decoder.html.ini
  tests/wpt/metadata/fetch/content-type/response.window.js.ini
  tests/wpt/metadata/fetch/nosniff/parsing-nosniff.window.js.ini
  tests/wpt/metadata/html/browsers/history/the-history-interface/traverse_the_history_2.html.ini
  tests/wpt/metadata/html/browsers/history/the-history-interface/traverse_the_history_3.html.ini
  tests/wpt/metadata/html/browsers/history/the-history-interface/traverse_the_history_5.html.ini
  tests/wpt/metadata/html/browsers/windows/nested-browsing-contexts/name-attribute.window.js.ini
  tests/wpt/metadata/html/semantics/interactive-elements/the-details-element/toggleEvent.html.ini
  tests/wpt/metadata/html/syntax/parsing/DOMContentLoaded-defer.html.ini
  tests/wpt/metadata/workers/WorkerGlobalScope-close.html.ini
  tests/wpt/mozilla/meta/css/transition_calc_implicit.html.ini
  tests/wpt/web-platform-tests/css/css-sizing/image-min-max-content-intrinsic-size-change-001-ref.html
  tests/wpt/web-platform-tests/css/css-sizing/image-min-max-content-intrinsic-size-change-001.html
  tests/wpt/web-platform-tests/css/css-sizing/image-min-max-content-intrinsic-size-change-002.html
  tests/wpt/web-platform-tests/css/css-sizing/image-min-max-content-intrinsic-size-change-003-ref.html
  tests/wpt/web-platform-tests/css/css-sizing/image-min-max-content-intrinsic-size-change-003.html
  tests/wpt/web-platform-tests/css/css-sizing/image-min-max-content-intrinsic-size-change-004.html
  tests/wpt/web-platform-tests/css/css-sizing/image-min-max-content-intrinsic-size-change-005-ref.html
  tests/wpt/web-platform-tests/css/css-sizing/image-min-max-content-intrinsic-size-change-005.html
  tests/wpt/web-platform-tests/css/css-sizing/image-min-max-content-intrinsic-size-change-006.html
  tests/wpt/web-platform-tests/css/css-sizing/image-min-max-content-intrinsic-size-change-007-ref.html
  tests/wpt/web-platform-tests/css/css-sizing/image-min-max-content-intrinsic-size-change-007.html
  tests/wpt/web-platform-tests/css/css-sizing/image-min-max-content-intrinsic-size-change-008.html
  tests/wpt/webgl/meta/conformance/textures/misc/texture-upload-size.html.ini
Labels: S-awaiting-merge

#23233 Glutin port refactoring
  Cargo.toml
  components/compositing/compositor.rs
  components/compositing/windowing.rs
  components/servo/lib.rs
  etc/ci/check_no_panic.sh
  ports/glutin/Cargo.toml
  ports/glutin/app.rs
  ports/glutin/browser.rs
  ports/glutin/build.rs
  ports/glutin/embedder.rs
  ports/glutin/events_loop.rs
  ports/glutin/headed_window.rs
  ports/glutin/headless_window.rs
  ports/glutin/keyutils.rs
  ports/glutin/main.rs
  ports/glutin/main2.rs
  ports/glutin/platform/macos/Info.plist
  ports/glutin/platform/macos/count_threads.c
  ports/glutin/platform/macos/mod.rs
  ports/glutin/platform/windows/servo.exe.manifest
  ports/glutin/resources.rs
  ports/glutin/skia_symbols.rs
  ports/glutin/window_trait.rs
  ports/libsimpleservo/api/src/lib.rs
  ports/servo/glutin_app/mod.rs
  ports/servo/glutin_app/window.rs
  python/servo/build_commands.py
  python/servo/command_base.py
  python/servo/post_build_commands.py
  python/servo/testing_commands.py
Labels: S-awaiting-merge

#23289 Update regex to 1.1
  Cargo.lock
  components/bluetooth_traits/Cargo.toml
  components/profile/Cargo.toml
  components/script/Cargo.toml
  components/style/Cargo.toml
  components/webdriver_server/Cargo.toml
Labels: S-awaiting-merge
