Repository servo/servo, pull requests merged in 2019-06, with the labels that each got.

#23491 Switch windows openssl binaries to ones generated by vcpkg.
  python/servo/build_commands.py
  python/servo/command_base.py
  python/servo/packages.py
Labels: S-awaiting-merge

#23335 Implement worker origin member of WorkerLocation
  components/script/dom/webidls/WorkerLocation.webidl
  components/script/dom/workerlocation.rs
  tests/wpt/metadata/FileAPI/url/url-format.any.js.ini
  tests/wpt/metadata/FileAPI/url/url-with-fetch.any.js.ini
  tests/wpt/metadata/css/CSS2/floats/floats-in-table-caption-001.html.ini
  tests/wpt/metadata/css/CSS2/positioning/abspos-float-with-inline-container.html.ini
  tests/wpt/metadata/css/CSS2/text/white-space-002.xht.ini
  tests/wpt/metadata/css/CSS2/text/white-space-003.xht.ini
  tests/wpt/metadata/css/CSS2/visudet/line-height-204.html.ini
  tests/wpt/metadata/css/compositing/mix-blend-mode/mix-blend-mode-paragraph.html.ini
  tests/wpt/metadata/css/css-backgrounds/background-repeat/background-repeat-round-roundup.xht.ini
  tests/wpt/metadata/css/css-fonts/variations/at-font-face-font-matching.html.ini
  tests/wpt/metadata/css/css-text/line-break/line-break-normal-018.xht.ini
  tests/wpt/metadata/css/css-text/line-break/line-break-strict-018.xht.ini
  tests/wpt/metadata/css/css-text/text-transform/text-transform-full-size-kana-001.html.ini
  tests/wpt/metadata/css/css-text/text-transform/text-transform-full-size-kana-002.html.ini
  tests/wpt/metadata/css/css-text/text-transform/text-transform-full-size-kana-003.html.ini
  tests/wpt/metadata/css/css-text/text-transform/text-transform-full-size-kana-004.html.ini
  tests/wpt/metadata/css/css-text/white-space/trailing-ideographic-space-004.html.ini
  tests/wpt/metadata/css/css-text/word-break/word-break-break-all-007.html.ini
  tests/wpt/metadata/css/css-text/word-break/word-break-keep-all-006.html.ini
  tests/wpt/metadata/css/css-transforms/css-transforms-3d-on-anonymous-block-001.html.ini
  tests/wpt/metadata/css/css-transitions/transitions-animatable-properties-01.html.ini
  tests/wpt/metadata/custom-elements/reactions/HTMLMediaElement.html.ini
  tests/wpt/metadata/fetch/api/basic/request-headers.any.js.ini
  tests/wpt/metadata/fetch/api/cors/cors-cookies-redirect.any.js.ini
  tests/wpt/metadata/fetch/api/cors/cors-cookies.any.js.ini
  tests/wpt/metadata/fetch/api/cors/cors-expose-star.sub.any.js.ini
  tests/wpt/metadata/fetch/api/cors/cors-preflight-star.any.js.ini
  tests/wpt/metadata/fetch/api/cors/cors-redirect.any.js.ini
  tests/wpt/metadata/fetch/content-type/response.window.js.ini
  tests/wpt/metadata/fetch/nosniff/parsing-nosniff.window.js.ini
  tests/wpt/metadata/html/browsers/the-window-object/apis-for-creating-and-navigating-browsing-contexts-by-name/open-features-negative-innerwidth-innerheight.html.ini
  tests/wpt/metadata/html/browsers/the-window-object/apis-for-creating-and-navigating-browsing-contexts-by-name/open-features-negative-screenx-screeny.html.ini
  tests/wpt/metadata/html/browsers/the-window-object/apis-for-creating-and-navigating-browsing-contexts-by-name/open-features-negative-top-left.html.ini
  tests/wpt/metadata/html/browsers/the-window-object/apis-for-creating-and-navigating-browsing-contexts-by-name/open-features-negative-width-height.html.ini
  tests/wpt/metadata/html/browsers/the-window-object/apis-for-creating-and-navigating-browsing-contexts-by-name/open-features-non-integer-height.html.ini
  tests/wpt/metadata/html/browsers/the-window-object/apis-for-creating-and-navigating-browsing-contexts-by-name/open-features-non-integer-innerheight.html.ini
  tests/wpt/metadata/html/browsers/the-window-object/apis-for-creating-and-navigating-browsing-contexts-by-name/open-features-non-integer-innerwidth.html.ini
  tests/wpt/metadata/html/browsers/the-window-object/apis-for-creating-and-navigating-browsing-contexts-by-name/open-features-non-integer-left.html.ini
  tests/wpt/metadata/html/browsers/the-window-object/apis-for-creating-and-navigating-browsing-contexts-by-name/open-features-non-integer-screenx.html.ini
  tests/wpt/metadata/html/browsers/the-window-object/apis-for-creating-and-navigating-browsing-contexts-by-name/open-features-non-integer-screeny.html.ini
  tests/wpt/metadata/html/browsers/the-window-object/apis-for-creating-and-navigating-browsing-contexts-by-name/open-features-non-integer-top.html.ini
  tests/wpt/metadata/html/browsers/the-window-object/apis-for-creating-and-navigating-browsing-contexts-by-name/open-features-non-integer-width.html.ini
  tests/wpt/metadata/html/dom/interfaces.worker.js.ini
  tests/wpt/metadata/html/semantics/embedded-content/the-img-element/non-active-document.html.ini
  tests/wpt/metadata/html/semantics/interactive-elements/the-details-element/toggleEvent.html.ini
  tests/wpt/metadata/html/webappapis/scripting/processing-model-2/unhandled-promise-rejections/promise-rejection-events-onerror.html.ini
  tests/wpt/metadata/html/webappapis/scripting/processing-model-2/unhandled-promise-rejections/promise-rejection-events.html.ini
  tests/wpt/metadata/resource-timing/resource_timing_buffer_full_eventually.html.ini
  tests/wpt/metadata/websockets/Create-on-worker-shutdown.any.js.ini
  tests/wpt/metadata/workers/WorkerLocation-origin.sub.window.js.ini
  tests/wpt/metadata/workers/data-url.html.ini
  tests/wpt/metadata/workers/interfaces.worker.js.ini
  tests/wpt/metadata/workers/semantics/run-a-worker/003.html.ini
  tests/wpt/mozilla/meta/css/transition_calc_implicit.html.ini
  tests/wpt/mozilla/meta/mozilla/task_queue_throttling.any.js.ini
Labels: S-awaiting-merge

#23372 Change XHRContext and resource timing information to use request URL
  components/script/dom/xmlhttprequest.rs
  tests/wpt/mozilla/meta/MANIFEST.json
  tests/wpt/mozilla/tests/mozilla/xmlhttprequest_url.html
Labels: S-awaiting-merge

#23493 compositing: removed opts-get
  Cargo.lock
  components/compositing/Cargo.toml
  components/compositing/compositor.rs
  components/servo/lib.rs
Labels: S-awaiting-merge

#23498 Remove unused code (2/N)
  components/net/fetch/cors_cache.rs
  components/net/http_cache.rs
  components/net/image_cache.rs
  components/net_traits/filemanager_thread.rs
  components/net_traits/image_cache.rs
  components/net_traits/lib.rs
  components/net_traits/net_error_list.rs
  components/net_traits/request.rs
  components/net_traits/response.rs
Labels: S-awaiting-merge

#23400 Include missing dependency requirements
  python/tidy/setup.py
Labels: S-awaiting-merge

#23505 Check for python's version in mach
  mach
Labels: S-awaiting-merge

#23486 Update more test expectations
  tests/wpt/metadata/html/semantics/embedded-content/media-elements/interfaces/TrackEvent/constructor.html.ini
  tests/wpt/metadata/html/semantics/embedded-content/media-elements/interfaces/TrackEvent/createEvent.html.ini
  tests/wpt/metadata/resource-timing/resource_TAO_origin.htm.ini
  tests/wpt/metadata/resource-timing/resource_TAO_zero.htm.ini
Labels: S-awaiting-merge

#23497 Fix behaviour of window resizing on Windows.
  components/compositing/compositor.rs
  ports/glutin/context.rs
  ports/glutin/headed_window.rs
Labels: S-awaiting-merge

#23506 Constellation: removed almost all opts::get
  Cargo.lock
  components/config/opts.rs
  components/constellation/Cargo.toml
  components/constellation/constellation.rs
  components/constellation/pipeline.rs
  components/servo/lib.rs
Labels: S-awaiting-merge

#23512 Fix `#[webidl_must_inherit]` building when cwd is not servo crate root
  components/script_plugins/webidl_must_inherit.rs
Labels: S-awaiting-merge

#23515 Layout_thread: removed all possible opts::get()
  Cargo.lock
  components/config/opts.rs
  components/constellation/pipeline.rs
  components/layout_thread/lib.rs
  components/layout_traits/Cargo.toml
  components/layout_traits/lib.rs
Labels: S-awaiting-merge

#23517 Make prepare_for_composite return void
  components/compositing/compositor.rs
  components/compositing/windowing.rs
  ports/glutin/headed_window.rs
  ports/glutin/headless_window.rs
  ports/libsimpleservo/api/src/lib.rs
Labels: S-awaiting-merge

#23501 handle null args pointer
  ports/libsimpleservo/capi/src/lib.rs
Labels: S-awaiting-merge

#23523 Use media element task source to receive the player's events
  components/script/dom/htmlmediaelement.rs
Labels: S-awaiting-merge

#23525 Sync WPT with upstream (06-06-2019)
  tests/wpt/metadata/FileAPI/url/url-with-fetch.any.js.ini
  tests/wpt/metadata/css/CSS2/stacking-context/composite-change-after-scroll-preserves-stacking-order.html.ini
  tests/wpt/metadata/css/css-backgrounds/inheritance.sub.html.ini
  tests/wpt/metadata/css/css-text-decor/text-underline-offset-computed.html.ini
  tests/wpt/metadata/css/css-text-decor/text-underline-offset-initial.html.ini
  tests/wpt/metadata/css/css-text-decor/text-underline-offset-valid.html.ini
  tests/wpt/metadata/css/css-transitions/properties-value-inherit-001.html.ini
  tests/wpt/metadata/css/css-transitions/transitions-animatable-properties-01.html.ini
  tests/wpt/metadata/css/css-ui/text-overflow-023.html.ini
  tests/wpt/metadata/css/css-values/vh_not_refreshing_on_chrome.html.ini
  tests/wpt/metadata/css/cssom-view/matchMedia-display-none-iframe.html.ini
  tests/wpt/metadata/fetch/content-type/response.window.js.ini
  tests/wpt/metadata/fetch/nosniff/parsing-nosniff.window.js.ini
  tests/wpt/metadata/html/browsers/history/the-history-interface/traverse_the_history_2.html.ini
  tests/wpt/metadata/html/browsers/the-window-object/apis-for-creating-and-navigating-browsing-contexts-by-name/open-features-negative-innerwidth-innerheight.html.ini
  tests/wpt/metadata/html/browsers/the-window-object/apis-for-creating-and-navigating-browsing-contexts-by-name/open-features-negative-screenx-screeny.html.ini
  tests/wpt/metadata/html/browsers/the-window-object/apis-for-creating-and-navigating-browsing-contexts-by-name/open-features-negative-top-left.html.ini
  tests/wpt/metadata/html/browsers/the-window-object/apis-for-creating-and-navigating-browsing-contexts-by-name/open-features-negative-width-height.html.ini
  tests/wpt/metadata/html/browsers/the-window-object/apis-for-creating-and-navigating-browsing-contexts-by-name/open-features-non-integer-height.html.ini
  tests/wpt/metadata/html/browsers/the-window-object/apis-for-creating-and-navigating-browsing-contexts-by-name/open-features-non-integer-innerheight.html.ini
  tests/wpt/metadata/html/browsers/the-window-object/apis-for-creating-and-navigating-browsing-contexts-by-name/open-features-non-integer-innerwidth.html.ini
  tests/wpt/metadata/html/browsers/the-window-object/apis-for-creating-and-navigating-browsing-contexts-by-name/open-features-non-integer-left.html.ini
  tests/wpt/metadata/html/browsers/the-window-object/apis-for-creating-and-navigating-browsing-contexts-by-name/open-features-non-integer-screenx.html.ini
  tests/wpt/metadata/html/browsers/the-window-object/apis-for-creating-and-navigating-browsing-contexts-by-name/open-features-non-integer-screeny.html.ini
  tests/wpt/metadata/html/browsers/the-window-object/apis-for-creating-and-navigating-browsing-contexts-by-name/open-features-non-integer-top.html.ini
  tests/wpt/metadata/html/browsers/the-window-object/apis-for-creating-and-navigating-browsing-contexts-by-name/open-features-non-integer-width.html.ini
  tests/wpt/metadata/webaudio/the-audio-api/the-analysernode-interface/realtimeanalyser-fft-scaling.html.ini
  tests/wpt/metadata/workers/baseurl/alpha/import-in-moduleworker.html.ini
  tests/wpt/metadata/workers/constructors/Worker/Worker-constructor.html.ini
  tests/wpt/mozilla/meta/css/transition_calc_implicit.html.ini
  tests/wpt/web-platform-tests/css/CSS2/stacking-context/composite-change-after-scroll-preserves-stacking-order-ref.html
  tests/wpt/web-platform-tests/css/CSS2/stacking-context/composite-change-after-scroll-preserves-stacking-order.html
  tests/wpt/web-platform-tests/css/css-backgrounds/border-radius-dynamic-from-no-radius-ref.html
  tests/wpt/web-platform-tests/css/css-backgrounds/inheritance.html
  tests/wpt/web-platform-tests/css/css-backgrounds/inheritance.sub.html
  tests/wpt/web-platform-tests/css/css-contain/contain-size-select-002.html
  tests/wpt/web-platform-tests/css/css-grid/grid-layout-properties.html
  tests/wpt/web-platform-tests/css/css-sizing/clone-nowrap-intrinsic-size-bidi-ref.html
  tests/wpt/web-platform-tests/css/css-sizing/clone-nowrap-intrinsic-size-bidi.html
  tests/wpt/web-platform-tests/css/css-sizing/clone-nowrap-intrinsic-size-ref.html
  tests/wpt/web-platform-tests/css/css-sizing/clone-nowrap-intrinsic-size.html
  tests/wpt/web-platform-tests/css/css-sizing/slice-nowrap-intrinsic-size-bidi-ref.html
  tests/wpt/web-platform-tests/css/css-sizing/slice-nowrap-intrinsic-size-bidi.html
  tests/wpt/web-platform-tests/css/css-sizing/slice-nowrap-intrinsic-size-ref.html
  tests/wpt/web-platform-tests/css/css-sizing/slice-nowrap-intrinsic-size.html
  tests/wpt/web-platform-tests/css/css-text-decor/text-underline-offset-computed.html
  tests/wpt/web-platform-tests/css/css-text-decor/text-underline-offset-initial.html
  tests/wpt/web-platform-tests/css/css-text-decor/text-underline-offset-invalid.html
  tests/wpt/web-platform-tests/css/css-text-decor/text-underline-offset-valid.html
  tests/wpt/web-platform-tests/css/css-ui/text-overflow-023.html
  tests/wpt/web-platform-tests/element-timing/background-image-multiple-elements.html
  tests/wpt/web-platform-tests/element-timing/observe-text.html
  tests/wpt/web-platform-tests/element-timing/resources/element-timing-helpers.js
  tests/wpt/web-platform-tests/native-file-system/FileSystemBaseHandle-copyTo.tentative.window.js
  tests/wpt/web-platform-tests/native-file-system/FileSystemBaseHandle-moveTo.tentative.window.js
  tests/wpt/web-platform-tests/service-workers/service-worker/getregistration.https.html
  tests/wpt/web-platform-tests/service-workers/service-worker/unregister-then-register-new-script.https.html
  tests/wpt/web-platform-tests/service-workers/service-worker/unregister-then-register.https.html
Labels: S-awaiting-merge

#23528 Fix typo in malloc_size_of docs
  components/malloc_size_of/lib.rs
Labels: S-awaiting-merge

#23507 Implement browsing context group and set
  components/constellation/browsingcontext.rs
  components/constellation/constellation.rs
  components/msg/constellation_msg.rs
Labels: S-awaiting-merge

#23521 Profile: removed opts::get()
  components/profile/heartbeats.rs
  components/profile/time.rs
  components/servo/lib.rs
  tests/unit/profile/time.rs
Labels: S-awaiting-merge

#23520 Net: removed opts::get() usage
  components/net/resource_thread.rs
  components/net/tests/resource_thread.rs
  components/net/websocket_loader.rs
  components/servo/lib.rs
Labels: S-awaiting-merge

#23532 Remove unused code (4/4)
  components/style/animation.rs
  components/style/attr.rs
  components/style/bloom.rs
  components/style/data.rs
  components/style/invalidation/element/restyle_hints.rs
  components/style/rule_tree/mod.rs
  components/style/sharing/mod.rs
  components/style/stylesheets/import_rule.rs
  components/style/values/specified/source_size_list.rs
Labels: S-awaiting-merge

#23530 Use TypeError instead of InvalidState for exception.
  components/script/dom/bindings/htmlconstructor.rs
  components/script/dom/customelementregistry.rs
  components/script/dom/webidls/CustomElementRegistry.webidl
  tests/wpt/metadata/custom-elements/upgrading/Node-cloneNode.html.ini
  tests/wpt/metadata/custom-elements/upgrading/upgrading-parser-created-element.html.ini
Labels: S-awaiting-merge

#23529 Split getter for mutation_observers() into two methods.
  components/script/dom/mutationobserver.rs
  components/script/dom/node.rs
Labels: S-awaiting-merge

#23544 Fix already borrowed error in webdriver
  components/script/script_thread.rs
  components/script/webdriver_handlers.rs
Labels: S-awaiting-merge

#23555 Add a linux release build to every push.
  etc/taskcluster/decision_task.py
Labels: S-awaiting-merge

#23561 Enable cookies related wdspec tests
  tests/wpt/include.ini
  tests/wpt/metadata/webdriver/tests/add_cookie/add.py.ini
  tests/wpt/metadata/webdriver/tests/add_cookie/user_prompts.py.ini
  tests/wpt/metadata/webdriver/tests/delete_all_cookies/delete.py.ini
  tests/wpt/metadata/webdriver/tests/delete_all_cookies/user_prompts.py.ini
  tests/wpt/metadata/webdriver/tests/delete_cookie/delete.py.ini
  tests/wpt/metadata/webdriver/tests/delete_cookie/user_prompts.py.ini
  tests/wpt/metadata/webdriver/tests/get_named_cookie/get.py.ini
  tests/wpt/metadata/webdriver/tests/get_named_cookie/user_prompts.py.ini
Labels: S-awaiting-merge

#23562 Update mozjs to remove NSPR.
  Cargo.lock
  python/servo/build_commands.py
Labels: S-awaiting-merge

#23546 Add Servo3D immersive demo for magicleap
  Cargo.lock
  components/compositing/windowing.rs
  components/script/dom/window.rs
  components/servo/lib.rs
  components/webvr/Cargo.toml
  components/webvr/lib.rs
  components/webvr_traits/Cargo.toml
  ports/glutin/embedder.rs
  ports/libmlservo/Cargo.toml
  ports/libmlservo/src/lib.rs
  ports/libsimpleservo/api/src/lib.rs
  ports/libsimpleservo/capi/src/lib.rs
  ports/libsimpleservo/jniapi/src/lib.rs
  python/servo/package_commands.py
  support/magicleap/Servo2D/code/src/Servo2D.cpp
  support/magicleap/Servo3D/Servo3D.cpp
  support/magicleap/Servo3D/Servo3D.mabu
  support/magicleap/Servo3D/Servo3D.package
  support/magicleap/Servo3D/fonts.xml
  support/magicleap/Servo3D/manifest.xml
Labels: P-magic leap, S-awaiting-merge

#23559 Remove dirs crate from use in UWP builds.
  components/config/Cargo.toml
  components/config/basedir.rs
  components/config/prefs.rs
  components/config/tests/prefs.rs
  components/servo/Cargo.toml
  ports/libsimpleservo/api/Cargo.toml
  ports/libsimpleservo/capi/Cargo.toml
Labels: S-awaiting-merge

#23565 Finish reintroducing parallelism in bluetooth tests
  etc/ci/buildbot_steps.yml
  etc/ci/update-wpt-checkout
Labels: S-awaiting-merge

#23571 Remove sampling profiler unit test.
  components/background_hang_monitor/tests/hang_monitor_tests.rs
Labels: S-awaiting-merge

#23576 Fixed magicleap Servo2D application
  ports/libmlservo/src/lib.rs
Labels: P-magic leap, S-awaiting-merge

#23586 Update remove_dir_all
  Cargo.lock
  Cargo.toml
Labels: S-awaiting-merge

#23445 Taskcluster: use current rustup.rs on Windows
  etc/taskcluster/decisionlib.py
Labels: S-awaiting-merge

#23598 Filter intermittent wdspec tests failures
  etc/ci/buildbot_steps.yml
  etc/taskcluster/decision_task.py
Labels: S-awaiting-merge

#23581 Implement GetPageSource WebDriver command
  components/script/script_thread.rs
  components/script/webdriver_handlers.rs
  components/script_traits/webdriver_msg.rs
  components/webdriver_server/lib.rs
  tests/wpt/metadata/webdriver/tests/get_page_source/source.py.ini
Labels: S-awaiting-merge

#23593 Fix panic on opening a directory
  components/net/fetch/methods.rs
  tests/wpt/metadata/webdriver/tests/get_current_url/get.py.ini
  tests/wpt/metadata/webdriver/tests/navigate_to/navigate.py.ini
Labels: S-awaiting-merge

#23588 Implement Status WebDriver command
  components/webdriver_server/lib.rs
  tests/wpt/metadata/webdriver/tests/status/status.py.ini
Labels: S-awaiting-merge

#23611 Update Travis CI URLs
  README.md
  components/selectors/README.md
Labels: S-awaiting-merge

#23536 Let resources timing entries be added to performance entry buffer.
  components/script/network_listener.rs
  tests/wpt/metadata/html/semantics/embedded-content/the-img-element/srcset/avoid-reload-on-resize.html.ini
  tests/wpt/metadata/performance-timeline/case-sensitivity.any.js.ini
  tests/wpt/metadata/resource-timing/idlharness.any.js.ini
  tests/wpt/metadata/resource-timing/no-entries-for-cross-origin-css-fetched.sub.html.ini
  tests/wpt/metadata/resource-timing/resource_TAO_origin.htm.ini
  tests/wpt/metadata/resource-timing/resource_TAO_zero.htm.ini
  tests/wpt/metadata/resource-timing/resource_connection_reuse.html.ini
  tests/wpt/metadata/resource-timing/resource_connection_reuse.https.html.ini
  tests/wpt/metadata/resource-timing/resource_connection_reuse_mixed_content.html.ini
  tests/wpt/metadata/resource-timing/resource_connection_reuse_mixed_content_redirect.html.ini
  tests/wpt/metadata/resource-timing/resource_dedicated_worker.html.ini
  tests/wpt/metadata/resource-timing/test_resource_timing.html.ini
  tests/wpt/metadata/resource-timing/test_resource_timing.https.html.ini
  tests/wpt/metadata/workers/worker-performance.worker.js.ini
  tests/wpt/mozilla/meta/MANIFEST.json
  tests/wpt/mozilla/tests/mozilla/xmlhttprequest_url.html
Labels: S-awaiting-merge

#23580 Implement SwitchToWindow and DismissAlert WebDriver commands
  components/webdriver_server/lib.rs
Labels: S-awaiting-merge

#23597 chore(vscode): Add VSCode recommended extensions
  .gitignore
  .vscode/extensions.json
Labels: S-awaiting-merge

#23613 Prevent CRLF conversion on Windows
  .gitattributes
Labels: S-awaiting-merge

#23626 Sync WPT with upstream (24-06-2019)
  tests/wpt/metadata/FileAPI/url/url-with-fetch.any.js.ini
  tests/wpt/metadata/css/css-transitions/properties-value-inherit-002.html.ini
  tests/wpt/metadata/css/cssom-view/matchMedia-display-none-iframe.html.ini
  tests/wpt/metadata/fetch/content-type/response.window.js.ini
  tests/wpt/metadata/fetch/content-type/script.window.js.ini
  tests/wpt/metadata/fetch/nosniff/parsing-nosniff.window.js.ini
  tests/wpt/metadata/html/browsers/history/the-history-interface/traverse_the_history_1.html.ini
  tests/wpt/metadata/html/browsers/history/the-history-interface/traverse_the_history_2.html.ini
  tests/wpt/metadata/html/browsers/history/the-history-interface/traverse_the_history_3.html.ini
  tests/wpt/metadata/html/browsers/history/the-history-interface/traverse_the_history_5.html.ini
  tests/wpt/metadata/workers/baseurl/alpha/sharedworker-in-worker.html.ini
  tests/wpt/metadata/workers/semantics/multiple-workers/005.html.ini
  tests/wpt/web-platform-tests/shape-detection/detection-HTMLVideoElement-invalid-state.html
  tests/wpt/web-platform-tests/shape-detection/shapedetection-cross-origin.sub.html
  tests/wpt/web-platform-tests/svg/scripted/script-runs-in-shadow-tree.html
  tests/wpt/web-platform-tests/webrtc-identity/RTCPeerConnection-peerIdentity.https.html
  tests/wpt/web-platform-tests/webrtc/RTCPeerConnection-ontrack.https.html
  tests/wpt/web-platform-tests/webvtt/rendering/cues-with-video/processing-model/2_tracks-ref.html
  tests/wpt/web-platform-tests/webvtt/rendering/cues-with-video/processing-model/2_tracks.html
  tests/wpt/web-platform-tests/webvtt/rendering/cues-with-video/processing-model/3_tracks-ref.html
  tests/wpt/web-platform-tests/webvtt/rendering/cues-with-video/processing-model/3_tracks.html
Labels: S-awaiting-merge

#23605 Always create a WPT update task.
  etc/taskcluster/decision_task.py
Labels: S-awaiting-merge

#23633 Remove some jobs from Buildbot
  etc/ci/buildbot_steps.yml
  etc/ci/check_intermittents.sh
  etc/ci/former_intermittents_css.txt
  etc/ci/former_intermittents_wpt.txt
Labels: S-awaiting-merge

#23636 Update to rust-webvr 0.11.5
  Cargo.lock
Labels: A-webvr, P-magic leap, S-awaiting-merge

#23587 Upgrade to SpiderMonkey 67
  Cargo.lock
  components/script/dom/audiobuffer.rs
  components/script/dom/bindings/codegen/CodegenRust.py
  components/script/dom/bindings/conversions.rs
  components/script/dom/bindings/error.rs
  components/script/dom/bindings/htmlconstructor.rs
  components/script/dom/bindings/proxyhandler.rs
  components/script/dom/bindings/structuredclone.rs
  components/script/dom/bindings/trace.rs
  components/script/dom/bindings/utils.rs
  components/script/dom/customelementregistry.rs
  components/script/dom/globalscope.rs
  components/script/dom/promise.rs
  components/script/dom/windowproxy.rs
  components/script/dom/workerglobalscope.rs
  components/script/microtask.rs
  components/script/script_runtime.rs
  components/script/script_thread.rs
  etc/taskcluster/docker/build.dockerfile
Labels: S-awaiting-merge

#23539 Script: removed a few opts::get()
  components/config/opts.rs
  components/constellation/pipeline.rs
  components/script/dom/bindings/trace.rs
  components/script/dom/characterdata.rs
  components/script/dom/dissimilaroriginwindow.rs
  components/script/dom/globalscope.rs
  components/script/dom/htmlscriptelement.rs
  components/script/dom/navigator.rs
  components/script/dom/navigatorinfo.rs
  components/script/dom/permissions.rs
  components/script/dom/userscripts.rs
  components/script/dom/window.rs
  components/script/dom/workerglobalscope.rs
  components/script/dom/workernavigator.rs
  components/script/dom/workletglobalscope.rs
  components/script/script_thread.rs
  components/script_traits/lib.rs
Labels: S-awaiting-merge

#23583 Force clang use on all platforms.
  python/servo/build_commands.py
Labels: S-awaiting-merge

#23650 Update Gentoo instructions to work with 17.1 and add missing dependency
  README.md
Labels: S-awaiting-merge

#23628 build: Cleanup some path-munging code.
  python/servo/command_base.py
Labels: S-awaiting-merge

#23647 Run DOM permissions tests in WPT.
  tests/wpt/include.ini
  tests/wpt/metadata/permissions/__dir__.ini
  tests/wpt/metadata/permissions/interfaces.any.js.ini
  tests/wpt/metadata/permissions/test-background-fetch-permission.html.ini
Labels: S-awaiting-merge

#23649 Add support for market:// urls
  ports/libmlservo/src/lib.rs
  ports/libsimpleservo/api/src/lib.rs
  ports/libsimpleservo/capi/src/lib.rs
  ports/libsimpleservo/jniapi/src/lib.rs
  support/android/apk/servoapp/src/main/java/org/mozilla/servo/MainActivity.java
  support/android/apk/servoview/src/main/java/org/mozilla/servoview/Servo.java
Labels: S-awaiting-merge

#23653 Improve support for nested dictionaries
  components/script/dom/bindings/codegen/parser/WebIDL.py
  components/script/dom/bindings/codegen/parser/undo-dictionary-optional.patch
  components/script/dom/bindings/codegen/parser/update.sh
  components/script/dom/mediadevices.rs
  components/script/dom/webidls/DOMQuad.webidl
  components/script/dom/webidls/TestBinding.webidl
Labels: S-awaiting-merge

#23344 Enter dom compartment wrapper
  components/script/compartments.rs
  components/script/devtools.rs
  components/script/dom/audiobuffer.rs
  components/script/dom/bindings/structuredclone.rs
  components/script/dom/dedicatedworkerglobalscope.rs
  components/script/dom/eventsource.rs
  components/script/dom/eventtarget.rs
  components/script/dom/filereader.rs
  components/script/dom/promise.rs
  components/script/dom/serviceworkerglobalscope.rs
  components/script/dom/windowproxy.rs
  components/script/dom/worker.rs
  components/script/fetch.rs
  components/script/script_thread.rs
Labels: S-awaiting-merge

#23667 Support VS Build Tools 2019
  python/servo/build_commands.py
Labels: S-awaiting-merge

#23662 Remove passing test
  tests/wpt/metadata/resource-timing/resource_TAO_zero.htm.ini
Labels: S-awaiting-merge
