Repository servo/servo, pull requests merged in 2019-05, with the labels that each got.

#21780 Upgrade NDK to v15c.
  etc/ci/check_dynamic_symbols.py
  python/servo/bootstrap_commands.py
  python/servo/build_commands.py
  python/servo/command_base.py
  support/android/apk/jni/Application.mk
  support/android/apk/servoapp/build.gradle
  support/android/openssl.sh
  support/android/toolchain.cmake
Labels: S-awaiting-merge

#23294 Update Player instantiator API
  Cargo.lock
  components/script/dom/htmlmediaelement.rs
  tests/wpt/metadata/webaudio/the-audio-api/the-audiobuffersourcenode-interface/buffer-resampling.html.ini
  tests/wpt/metadata/webaudio/the-audio-api/the-audioparam-interface/audioparam-method-chaining.html.ini
  tests/wpt/metadata/webaudio/the-audio-api/the-oscillatornode-interface/detune-limiting.html.ini
Labels: S-awaiting-merge

#23312 Bug 1546777 - Upgrade generic-worker to 14.1.0 in Windows AMI
  etc/taskcluster/windows/first-boot.ps1
Labels: S-awaiting-merge

#23316 Give the correct scopes to daily tasks
  etc/taskcluster/decision_task.py
Labels: S-awaiting-merge

#23299 Remove mozjs dep from malloc_size_of.
  Cargo.lock
  components/malloc_size_of/Cargo.toml
  components/malloc_size_of/lib.rs
  components/script/dom/audiobuffer.rs
  components/script/dom/customelementregistry.rs
  components/script/dom/extendablemessageevent.rs
  components/script/dom/filereader.rs
  components/script/dom/gamepad.rs
  components/script/dom/globalscope.rs
  components/script/dom/history.rs
  components/script/dom/imagedata.rs
  components/script/dom/messageevent.rs
  components/script/dom/paintworkletglobalscope.rs
  components/script/dom/vreyeparameters.rs
  components/script/dom/vrframedata.rs
  components/script/dom/vrpose.rs
  components/script/dom/vrstageparameters.rs
  components/script/dom/xmlhttprequest.rs
  components/script/dom/xrrigidtransform.rs
  components/script/dom/xrview.rs
  components/script/dom/xrviewerpose.rs
Labels: S-awaiting-merge

#23333 Explicitly provide module names to mach so it doesn't try to autogenerate them
  python/mach_bootstrap.py
Labels: S-awaiting-merge

#23229 Finish the implementation of the HTMLMediaElement canPlayType method
  components/script/dom/htmlmediaelement.rs
  tests/wpt/metadata/html/semantics/embedded-content/media-elements/mime-types/canPlayType.html.ini
Labels: S-awaiting-merge

#23283 Update harfbuzz to 0.3
  Cargo.lock
  components/gfx/Cargo.toml
  components/gfx/text/shaping/harfbuzz.rs
  components/layout/Cargo.toml
  tests/wpt/metadata/css/css-text/word-break/word-break-break-all-005.html.ini
Labels: S-awaiting-merge

#23324 Changes for Ubuntu/Ubuntu 19.04 in bootstrap.py
  python/servo/bootstrap.py
Labels: S-awaiting-merge

#23340 Express GC thresholds as percentages
  resources/prefs.json
Labels: A-content/script, S-awaiting-merge

#23352 Fix WPT nightly sync credentials.
  etc/ci/update-wpt-checkout
Labels: S-awaiting-merge

#23349 No need to clone again the raw data.
  components/script/dom/htmlmediaelement.rs
Labels: S-awaiting-merge

#23322 Create performance resource timing entry for synchronous network fetch
  components/net_traits/lib.rs
  components/script/dom/dedicatedworkerglobalscope.rs
  components/script/dom/serviceworkerglobalscope.rs
  components/script/dom/workerglobalscope.rs
  components/script/dom/worklet.rs
  components/script/fetch.rs
  components/script/network_listener.rs
Labels: S-awaiting-merge

#23359 Add libffi to pkgconfig's search path.
  etc/taskcluster/decision_task.py
Labels: S-awaiting-merge

#23309 Support WorkerOptions for Worker
  components/script/dom/dedicatedworkerglobalscope.rs
  components/script/dom/serviceworkercontainer.rs
  components/script/dom/serviceworkerglobalscope.rs
  components/script/dom/webidls/ServiceWorkerContainer.webidl
  components/script/dom/webidls/Worker.webidl
  components/script/dom/worker.rs
  components/script/dom/workerglobalscope.rs
  components/script/serviceworkerjob.rs
  tests/wpt/metadata/html/dom/interfaces.https.html.ini
  tests/wpt/metadata/html/dom/interfaces.worker.js.ini
  tests/wpt/metadata/workers/modules/dedicated-worker-options-type.html.ini
Labels: S-awaiting-merge

#23374 Fix libffi pkg-config in WPT nightly job.
  etc/taskcluster/decision_task.py
Labels: S-awaiting-merge

#23382 Upgrade to rustc 1.36.0-nightly (a9ec99f42 2019-05-13)
  components/script_plugins/lib.rs
  components/script_plugins/unrooted_must_root.rs
  components/script_plugins/utils.rs
  components/script_plugins/webidl_must_inherit.rs
  rust-toolchain
Labels: S-awaiting-merge, S-fails-tidy

#23388 Install webrtc-required components for gstreamer
  etc/taskcluster/macos/Brewfile-gstreamer
Labels: S-awaiting-merge

#23395 Bump Windows build tasks time out
  etc/taskcluster/decision_task.py
Labels: S-awaiting-merge

#23401 Remove unsupported homebrew options
  etc/taskcluster/macos/Brewfile-gstreamer
Labels: S-awaiting-merge

#23397 Document gstreamer installation
  README.md
Labels: S-awaiting-merge

#23402 Improve output for local WPT sync runs.
  etc/ci/update-wpt-checkout
Labels: S-awaiting-merge

#23249 Implement MouseEvent buttons attribute
  components/compositing/compositor.rs
  components/constellation/constellation.rs
  components/script/dom/activation.rs
  components/script/dom/document.rs
  components/script/dom/mouseevent.rs
  components/script/dom/webidls/MouseEvent.webidl
  components/script/script_thread.rs
  components/script_traits/lib.rs
  tests/wpt/metadata/dom/events/Event-subclasses-constructors.html.ini
  tests/wpt/metadata/uievents/idlharness.window.js.ini
Labels: S-awaiting-merge

#23411 Add debugging info to macOS TC build tasks.
  etc/taskcluster/decision_task.py
Labels: S-awaiting-merge

#23403 Add gst-plugins-bad homebrew formula that enables webrtc.
  etc/taskcluster/macos/Brewfile-gstreamer
  etc/taskcluster/macos/Formula/gst-plugins-bad.diff
  etc/taskcluster/macos/Formula/gst-plugins-bad.rb
  etc/taskcluster/macos/Formula/recreate.sh
Labels: S-awaiting-merge

#23419 Fix magicleap nightly upload
  etc/taskcluster/decision_task.py
Labels: S-awaiting-merge

#23416 Update servo-media
  Cargo.lock
Labels: S-awaiting-merge

#23426 Add gnutls dependency for gstreamer plugins build
  etc/taskcluster/macos/Brewfile-gstreamer
Labels: S-awaiting-merge

#23424 Use correct plugin search path for locally cloned gstreamer
  python/servo/command_base.py
Labels: S-awaiting-merge

#23410 spec update: window.name deals with lack of browsing context
  components/script/dom/window.rs
  tests/wpt/metadata/html/browsers/the-window-object/name-attribute.window.js.ini
Labels: S-awaiting-merge

#23420 Upgrade gstreamer binaries for Android to 1.16.0
  python/servo/build_commands.py
Labels: S-awaiting-merge

#23405 Switch from webidl to weedle in script_plugins
  Cargo.lock
  components/script_plugins/Cargo.toml
  components/script_plugins/lib.rs
  components/script_plugins/webidl_must_inherit.rs
Labels: S-awaiting-merge

#23427 Update xml5ever and html5ever
  Cargo.lock
  components/gfx/Cargo.toml
  components/layout/Cargo.toml
  components/layout_thread/Cargo.toml
  components/malloc_size_of/Cargo.toml
  components/script/Cargo.toml
  components/script/dom/servoparser/xml.rs
  components/script_layout_interface/Cargo.toml
  components/style/Cargo.toml
  tests/unit/style/Cargo.toml
Labels: S-awaiting-merge

#23226 Add initial support for WebGL compressed textures
  components/canvas/webgl_thread.rs
  components/canvas_traits/webgl.rs
  components/script/dom/webgl_extensions/ext/mod.rs
  components/script/dom/webgl_extensions/ext/webglcompressedtextureetc1.rs
  components/script/dom/webgl_extensions/ext/webglcompressedtextures3tc.rs
  components/script/dom/webgl_extensions/extensions.rs
  components/script/dom/webgl_validations/tex_image_2d.rs
  components/script/dom/webglrenderingcontext.rs
  components/script/dom/webgltexture.rs
  components/script/dom/webidls/WEBGLCompressedTextureETC1.webidl
  components/script/dom/webidls/WEBGLCompressedTextureS3TC.webidl
  tests/wpt/webgl/meta/MANIFEST.json
  tests/wpt/webgl/tests/conformance/extensions/webgl-compressed-texture-s3tc.html
  tests/wpt/webgl/tools/compressed-images.patch
  tests/wpt/webgl/tools/import-conformance-tests.py
  tests/wpt/webgl/tools/timeout.patch
Labels: S-awaiting-merge

#23435 Disable sccache on macOS
  etc/taskcluster/decision_task.py
Labels: S-awaiting-merge

#23434 Fix nightly WPT sync job
  etc/taskcluster/decision_task.py
  etc/taskcluster/decisionlib.py
Labels: S-awaiting-merge

#23188 Implement HTMLMediaElement.crossorigin attribute logic.
  components/script/dom/htmlmediaelement.rs
  components/script/dom/webidls/HTMLMediaElement.webidl
  tests/wpt/metadata/html/dom/interfaces.https.html.ini
  tests/wpt/metadata/html/semantics/embedded-content/media-elements/interfaces/HTMLElement/HTMLMediaElement/crossOrigin.html.ini
Labels: S-awaiting-merge

#23407 Reintroduce parallelism in the bluetooth tests
  etc/taskcluster/decision_task.py
Labels: S-awaiting-merge

#23412 Add some SSH keys to tc-mac workers
  etc/taskcluster/macos/config/master
  etc/taskcluster/macos/modules/pillar/ssh_keys.py
  etc/taskcluster/macos/states/generic-worker.sls
Labels: S-awaiting-merge

#23383 Reuse more tasks
  .taskcluster.yml
  etc/taskcluster/decisionlib.py
Labels: S-awaiting-merge

#23437 Update darling to 0.9
  Cargo.lock
  components/derive_common/Cargo.toml
  components/style_derive/Cargo.toml
  components/to_shmem_derive/Cargo.toml
Labels: S-awaiting-merge

#23364 Use llvm toolchain for android build
  python/servo/build_commands.py
  support/android/fakeld/fake-ld-arm.sh
  support/android/fakeld/fake-ld-arm64.sh
  support/android/fakeld/fake-ld-armv7.sh
  support/android/fakeld/fake-ld-x86.sh
  support/android/fakeld/fake-ld.sh
  support/android/toolchain.cmake
Labels: S-awaiting-merge

#23449 Dedupe winapi
  Cargo.lock
  Cargo.toml
  servo-tidy.toml
Labels: S-awaiting-merge

#23460 Sync WPT with upstream (25-05-2019)
  tests/wpt/metadata/FileAPI/url/url-with-fetch.any.js.ini
  tests/wpt/metadata/css/css-transitions/transitions-animatable-properties-01.html.ini
  tests/wpt/metadata/fetch/content-type/response.window.js.ini
  tests/wpt/metadata/html/browsers/history/the-history-interface/traverse_the_history_1.html.ini
  tests/wpt/metadata/html/browsers/history/the-history-interface/traverse_the_history_2.html.ini
  tests/wpt/metadata/html/browsers/history/the-history-interface/traverse_the_history_5.html.ini
  tests/wpt/metadata/html/semantics/embedded-content/the-img-element/non-active-document.html.ini
  tests/wpt/metadata/webaudio/the-audio-api/the-scriptprocessornode-interface/simple-input-output.html.ini
  tests/wpt/web-platform-tests/css/css-break/break-before-with-no-fragmentation-crash.html
  tests/wpt/web-platform-tests/css/css-contain/contain-layout-baseline-005.html
  tests/wpt/web-platform-tests/css/css-contain/contain-layout-button-001.html
  tests/wpt/web-platform-tests/css/css-contain/reference/contain-layout-baseline-005-ref.html
  tests/wpt/web-platform-tests/css/css-contain/reference/contain-layout-button-001-ref.html
  tests/wpt/web-platform-tests/css/css-flexbox/flexbox_stf-fixpos.html
  tests/wpt/web-platform-tests/css/css-lists/nested-marker-dynamic.html
  tests/wpt/web-platform-tests/css/css-lists/nested-marker-ref.html
  tests/wpt/web-platform-tests/css/css-lists/nested-marker.html
  tests/wpt/web-platform-tests/css/css-scoping/slotted-matches.html
  tests/wpt/web-platform-tests/css/motion/inheritance.html
  tests/wpt/web-platform-tests/css/motion/offset-rotate-003.html
  tests/wpt/web-platform-tests/css/motion/offset-rotate-004.html
  tests/wpt/web-platform-tests/css/motion/offset-rotate-005.html
  tests/wpt/web-platform-tests/css/motion/parsing/offset-rotate-computed.html
  tests/wpt/web-platform-tests/css/motion/parsing/offset-rotate-parsing-valid.html
  tests/wpt/web-platform-tests/css/support/computed-testcommon.js
  tests/wpt/web-platform-tests/css/support/inheritance-testcommon.js
  tests/wpt/web-platform-tests/feature-policy/resources/feature-policy-wakelock.html
  tests/wpt/web-platform-tests/html/semantics/embedded-content/the-object-element/block-object-with-ruby-crash.html
  tests/wpt/web-platform-tests/payment-handler/app-change-payment-method.js
  tests/wpt/web-platform-tests/tools/wptrunner/requirements.txt
  tests/wpt/web-platform-tests/wake-lock/idlharness.https.any.js
  tests/wpt/web-platform-tests/wake-lock/resources/page1.html
  tests/wpt/web-platform-tests/wake-lock/resources/page2.html
  tests/wpt/web-platform-tests/wake-lock/wakelock-abortsignal-set.https.html
  tests/wpt/web-platform-tests/wake-lock/wakelock-active-document.https.window.js
  tests/wpt/web-platform-tests/wake-lock/wakelock-applicability-manual.https.html
  tests/wpt/web-platform-tests/wake-lock/wakelock-disabled-by-feature-policy.https.sub.html
  tests/wpt/web-platform-tests/wake-lock/wakelock-document-hidden-manual.https.html
  tests/wpt/web-platform-tests/wake-lock/wakelock-document-hidden.https.html
  tests/wpt/web-platform-tests/wake-lock/wakelock-enabled-by-feature-policy-attribute-redirect-on-load.https.sub.html
  tests/wpt/web-platform-tests/wake-lock/wakelock-enabled-by-feature-policy-attribute.https.sub.html
  tests/wpt/web-platform-tests/wake-lock/wakelock-enabled-by-feature-policy.https.sub.html
  tests/wpt/web-platform-tests/wake-lock/wakelock-enabled-on-self-origin-by-feature-policy.https.sub.html
  tests/wpt/web-platform-tests/wake-lock/wakelock-onactivechange.https.html
  tests/wpt/web-platform-tests/webaudio/the-audio-api/the-scriptprocessornode-interface/simple-input-output.html
  tests/wpt/web-platform-tests/webrtc/RTCPeerConnection-helper.js
  tests/wpt/web-platform-tests/webrtc/protocol/dtls-fingerprint-validation.html
Labels: S-awaiting-merge

#23453 Remove restrictions on cross-compiling on Windows.
  components/script/CMakeLists.txt
  components/script/build.rs
  components/script/vcvars.bat
Labels: S-awaiting-merge

#23464 Use type alias enums in layout code
  components/layout/display_list/conversions.rs
  components/layout/display_list/gradient.rs
Labels: S-awaiting-merge

#23461 Switched from using thread for websocket requests to ipc_channel::router::ROUTER
  components/script/dom/websocket.rs
Labels: S-awaiting-merge

#23471 Update magicleap SDK to v0.20.0+ndk19c
  etc/taskcluster/decision_task.py
Labels: A-build, P-magic leap, S-awaiting-merge

#23478 Update servo-fontconfig to 0.4
  Cargo.lock
  components/gfx/Cargo.toml
Labels: S-awaiting-merge

#23476 Allow simultaneous playback of audio and video for getUserMedia
  Cargo.lock
  components/script/dom/htmlmediaelement.rs
Labels: S-awaiting-merge

#23350 Disable video if audio element
  components/script/dom/htmlmediaelement.rs
Labels: S-awaiting-merge

#23480 Update test expectations
  tests/wpt/metadata/html/dom/interfaces.https.html.ini
  tests/wpt/metadata/html/semantics/embedded-content/media-elements/video_loop_base.html.ini
Labels: S-awaiting-merge

#23472 Add value sanitization for input[type=email]
  components/script/dom/htmlinputelement.rs
  tests/wpt/metadata/html/semantics/forms/the-input-element/email.html.ini
  tests/wpt/metadata/html/semantics/forms/the-input-element/type-change-state.html.ini
  tests/wpt/metadata/html/semantics/forms/the-input-element/valueMode.html.ini
Labels: S-awaiting-merge

#23487 Update README.md to point to latest bugfix of Python 2 on Windows
  README.md
Labels: S-awaiting-merge
