Repository servo/servo, pull requests merged in 2020-01, with the labels that each got.

#25408 Now using eq_ignore_case on WASM mimetype, per #25317
  components/script/script_runtime.rs
Labels: S-awaiting-merge

#25418 Fix some warnings in future Rust nightlies
  components/bluetooth/lib.rs
  components/devtools/protocol.rs
  components/net/http_loader.rs
  components/net/resource_thread.rs
  components/net_traits/lib.rs
  components/profile/heartbeats.rs
  components/profile/time.rs
  components/script/dom/webgl_validations/tex_image_2d.rs
Labels: S-awaiting-merge

#25358 Header values no longer have to be ASCII or UTF-8
  components/script/dom/headers.rs
  tests/wpt/metadata/fetch/api/basic/request-forbidden-headers.any.js.ini
  tests/wpt/metadata/fetch/api/headers/header-values-normalize.html.ini
  tests/wpt/metadata/fetch/api/headers/headers-no-cors.window.js.ini
  tests/wpt/metadata/fetch/api/request/request-headers.html.ini
  tests/wpt/metadata/fetch/api/response/response-init-002.html.ini
Labels: S-awaiting-merge

#25364 Add `track_list` member to AudioTrack, VideoTrack, TextTrack structs
  components/script/dom/audiotrack.rs
  components/script/dom/audiotracklist.rs
  components/script/dom/htmlmediaelement.rs
  components/script/dom/htmltrackelement.rs
  components/script/dom/texttrack.rs
  components/script/dom/texttracklist.rs
  components/script/dom/videotrack.rs
  components/script/dom/videotracklist.rs
Labels: S-awaiting-merge

#25407 Radio button grouping is now case-sensitive
  components/script/dom/htmlinputelement.rs
  tests/wpt/metadata/html/semantics/forms/the-input-element/radio-groupname-case.html.ini
Labels: S-awaiting-merge

#25410 Implement CustomElementRegistry.upgrade
  components/script/dom/customelementregistry.rs
  components/script/dom/webidls/CustomElementRegistry.webidl
  tests/wpt/metadata/custom-elements/custom-element-registry/upgrade.html.ini
  tests/wpt/metadata/html/dom/idlharness.https.html.ini
Labels: S-awaiting-merge

#25399 Add chocolatey steps for easier VS017 install
  README.md
Labels: S-awaiting-merge

#25393 Implement HTMLOptionElement named constructor
  components/script/dom/htmloptionelement.rs
  components/script/dom/webidls/HTMLOptionElement.webidl
  tests/wpt/metadata/html/dom/idlharness.https.html.ini
  tests/wpt/metadata/html/infrastructure/common-dom-interfaces/collections/htmloptionscollection.html.ini
  tests/wpt/metadata/html/semantics/forms/constraints/form-validation-checkValidity.html.ini
  tests/wpt/metadata/html/semantics/forms/constraints/form-validation-reportValidity.html.ini
  tests/wpt/metadata/html/semantics/forms/constraints/form-validation-validity-customError.html.ini
  tests/wpt/metadata/html/semantics/forms/constraints/form-validation-validity-valid.html.ini
  tests/wpt/metadata/html/semantics/forms/constraints/form-validation-validity-valueMissing.html.ini
  tests/wpt/metadata/html/semantics/forms/constraints/form-validation-willValidate.html.ini
  tests/wpt/metadata/html/semantics/forms/the-option-element/option-element-constructor.html.ini
  tests/wpt/mozilla/meta/MANIFEST.json
  tests/wpt/mozilla/tests/mozilla/interfaces.html
Labels: S-awaiting-merge

#25397 Implement HTMLInputElement cloning steps
  components/script/dom/htmlinputelement.rs
  tests/wpt/metadata/html/semantics/forms/the-input-element/clone.html.ini
  tests/wpt/metadata/html/semantics/forms/the-input-element/cloning-steps.html.ini
Labels: S-awaiting-merge

#25409 Remove "menu" from legal button types
  components/script/dom/htmlbuttonelement.rs
  tests/wpt/metadata/html/semantics/forms/the-button-element/button-menu-historical.html.ini
Labels: S-awaiting-merge

#25414 Add "active parser was aborted boolean" to Document
  components/script/dom/document.rs
  tests/wpt/metadata/html/webappapis/dynamic-markup-insertion/opening-the-input-stream/aborted-parser.window.js.ini
Labels: S-awaiting-merge

#25426 Remove `origin` parameter from `Worker::handle_message`
  components/script/dom/dedicatedworkerglobalscope.rs
  components/script/dom/worker.rs
  tests/wpt/metadata/workers/interfaces/DedicatedWorkerGlobalScope/postMessage/message-event.html.ini
Labels: S-awaiting-merge

#25437 Sync WPT with upstream (06-01-2020)
  tests/wpt/metadata/css/cssom-view/elementFromPoint-001.html.ini
  tests/wpt/metadata/css/cssom-view/getClientRects-inline-inline-child.html.ini
  tests/wpt/metadata/fetch/content-type/response.window.js.ini
  tests/wpt/metadata/fetch/nosniff/parsing-nosniff.window.js.ini
  tests/wpt/metadata/fetch/security/embedded-credentials.tentative.sub.html.ini
  tests/wpt/metadata/html/browsers/history/the-history-interface/traverse_the_history_2.html.ini
  tests/wpt/metadata/html/browsers/history/the-history-interface/traverse_the_history_3.html.ini
  tests/wpt/metadata/html/browsers/the-window-object/apis-for-creating-and-navigating-browsing-contexts-by-name/creating_browsing_context_test_01.html.ini
  tests/wpt/metadata/html/interaction/focus/the-autofocus-attribute/skip-document-with-fragment.html.ini
  tests/wpt/metadata/html/semantics/embedded-content/the-iframe-element/iframe_sandbox_popups_escaping-3.html.ini
  tests/wpt/metadata/performance-timeline/webtiming-resolution.any.js.ini
  tests/wpt/metadata/resource-timing/crossorigin-sandwich-TAO.sub.html.ini
  tests/wpt/metadata/workers/semantics/multiple-workers/005.html.ini
  tests/wpt/web-platform-tests/css/css-multicol/change-intrinsic-width.html
  tests/wpt/web-platform-tests/css/cssom-view/getClientRects-inline-inline-child.html
  tests/wpt/web-platform-tests/html/semantics/forms/constraints/form-validation-validity-valid.html
  tests/wpt/web-platform-tests/html/semantics/forms/constraints/form-validation-validity-valueMissing.html
  tests/wpt/web-platform-tests/html/semantics/forms/constraints/support/validator.js
  tests/wpt/web-platform-tests/resources/chromium/nfc-mock.js
  tests/wpt/web-platform-tests/tools/wptrunner/wptrunner/browsers/firefox_android.py
  tests/wpt/web-platform-tests/tools/wptrunner/wptrunner/executors/executormarionette.py
  tests/wpt/web-platform-tests/tools/wptrunner/wptrunner/executors/test-wait.js
  tests/wpt/web-platform-tests/tools/wptrunner/wptrunner/font.py
  tests/wpt/web-platform-tests/tools/wptrunner/wptrunner/wptrunner.py
  tests/wpt/web-platform-tests/web-nfc/NDEFReader_scan.https.html
  tests/wpt/web-platform-tests/web-nfc/NDEFWriter_push.https.html
Labels: S-awaiting-merge

#25434 Put correct version number in rustup version-requirement string
  python/servo/command_base.py
Labels: S-awaiting-merge

#25424 Make labelable element .labels a live list in tree order
  components/script/dom/htmlbuttonelement.rs
  components/script/dom/htmlelement.rs
  components/script/dom/htmlinputelement.rs
  components/script/dom/htmllabelelement.rs
  components/script/dom/htmlmeterelement.rs
  components/script/dom/htmloutputelement.rs
  components/script/dom/htmlprogresselement.rs
  components/script/dom/htmlselectelement.rs
  components/script/dom/htmltextareaelement.rs
  components/script/dom/macros.rs
  components/script/dom/nodelist.rs
  components/script/dom/webidls/HTMLInputElement.webidl
  tests/wpt/metadata/html/semantics/forms/the-label-element/label-attributes.sub.html.ini
  tests/wpt/metadata/html/semantics/forms/the-label-element/labelable-elements.html.ini
Labels: S-awaiting-merge

#25368 servo-tidy.toml cleanup
  servo-tidy.toml
Labels: S-awaiting-merge

#25412 implement HTMLOutputElement.value
  components/script/dom/htmlformelement.rs
  components/script/dom/htmloutputelement.rs
  components/script/dom/node.rs
  components/script/dom/webidls/HTMLOutputElement.webidl
  tests/wpt/metadata/custom-elements/reactions/HTMLOutputElement.html.ini
  tests/wpt/metadata/html/dom/idlharness.https.html.ini
  tests/wpt/metadata/html/semantics/forms/resetting-a-form/reset-form.html.ini
  tests/wpt/metadata/html/semantics/forms/the-output-element/mutations.window.js.ini
  tests/wpt/metadata/html/semantics/forms/the-output-element/output.html.ini
Labels: S-awaiting-merge

#25310 Attr is a Node, with consequences for many Node methods
  components/script/dom/attr.rs
  components/script/dom/document.rs
  components/script/dom/element.rs
  components/script/dom/node.rs
  components/script/dom/range.rs
  components/script/dom/servoparser/html.rs
  components/script/dom/webidls/Attr.webidl
  tests/wpt/metadata/dom/idlharness.window.js.ini
  tests/wpt/metadata/dom/nodes/Document-importNode.html.ini
Labels: S-awaiting-merge

#25344 Set more ANGLE shader translation properties for WebGL 2
  components/canvas/webgl_limits.rs
  components/canvas/webgl_thread.rs
  components/canvas_traits/webgl.rs
  components/script/dom/webglshader.rs
  tests/wpt/webgl/meta/conformance2/programs/gl-get-frag-data-location.html.ini
  tests/wpt/webgl/meta/conformance2/uniforms/incompatible-texture-type-for-sampler.html.ini
Labels: S-awaiting-merge

#25444 Fix canvas arc path WPT test failures
  components/canvas/canvas_data.rs
  tests/wpt/metadata/2dcontext/path-objects/2d.path.arcTo.ensuresubpath.2.html.ini
  tests/wpt/metadata/offscreen-canvas/path-objects/2d.path.arcTo.ensuresubpath.2.html.ini
  tests/wpt/metadata/offscreen-canvas/path-objects/2d.path.arcTo.ensuresubpath.2.worker.js.ini
Labels: S-awaiting-merge

#25449 Implement HTMLSelectElement.add() and indexed setter
  components/script/dom/bindings/codegen/CodegenRust.py
  components/script/dom/htmlselectelement.rs
  components/script/dom/webidls/HTMLSelectElement.webidl
  tests/wpt/metadata/custom-elements/reactions/HTMLSelectElement.html.ini
  tests/wpt/metadata/html/semantics/forms/the-select-element/select-add.html.ini
  tests/wpt/mozilla/meta/MANIFEST.json
  tests/wpt/mozilla/tests/mozilla/union.html
Labels: S-awaiting-merge

#25453 Group WPT chunks together in Treeherder
  etc/taskcluster/decision_task.py
  etc/taskcluster/decisionlib.py
Labels: S-awaiting-merge

#25300 Mach: Improve Visual Studio detection for non-standard-path installations
  python/servo/command_base.py
Labels: S-awaiting-merge

#25404 Fix HSTS
  components/config/prefs.rs
  components/net/fetch/methods.rs
  components/net/hsts.rs
  components/net/http_loader.rs
  components/net/tests/fetch.rs
  components/net/tests/http_loader.rs
  components/net/websocket_loader.rs
  resources/prefs.json
Labels: S-awaiting-merge

#25451 Add accountable-refcell as optional build time feature
  Cargo.lock
  components/malloc_size_of/Cargo.toml
  components/malloc_size_of/lib.rs
  components/script/Cargo.toml
  components/script/body.rs
  components/script/dom/attr.rs
  components/script/dom/audiobuffer.rs
  components/script/dom/bindings/cell.rs
  components/script/dom/bluetooth.rs
  components/script/dom/characterdata.rs
  components/script/dom/document.rs
  components/script/dom/dommatrixreadonly.rs
  components/script/dom/element.rs
  components/script/dom/htmlcanvaselement.rs
  components/script/dom/htmlimageelement.rs
  components/script/dom/mediastream.rs
  components/script/dom/node.rs
  components/script/dom/offscreencanvas.rs
  components/script/dom/request.rs
  components/script/dom/response.rs
  components/script/dom/webglprogram.rs
  components/script/dom/webglvertexarrayobjectoes.rs
  components/script/dom/workerglobalscope.rs
  components/script_plugins/lib.rs
  components/servo/Cargo.toml
  etc/taskcluster/decision_task.py
  ports/glutin/Cargo.toml
  ports/libsimpleservo/api/Cargo.toml
  ports/libsimpleservo/capi/Cargo.toml
Labels: S-awaiting-merge

#25456 Past names expire when form owner is reset
  components/script/dom/htmlformelement.rs
  tests/wpt/metadata/html/semantics/forms/the-form-element/form-nameditem.html.ini
Labels: S-awaiting-merge

#25458 Add documentation for WindowsSdkDir to README
  README.md
Labels: A-documentation, P-windows, S-awaiting-merge

#25467 Use dom and new_inherited in (extendable)messageevent
  components/script/dom/extendablemessageevent.rs
  components/script/dom/messageevent.rs
Labels: S-awaiting-merge

#25229 Add initial support for WebGL2 uniform buffer functions
  Cargo.lock
  components/canvas/Cargo.toml
  components/canvas/webgl_limits.rs
  components/canvas/webgl_thread.rs
  components/canvas_traits/webgl.rs
  components/script/dom/bindings/trace.rs
  components/script/dom/webgl2renderingcontext.rs
  components/script/dom/webglbuffer.rs
  components/script/dom/webglprogram.rs
  components/script/dom/webglrenderingcontext.rs
  components/script/dom/webidls/WebGL2RenderingContext.webidl
  tests/wpt/webgl/meta/conformance2/buffers/bound-buffer-size-change-test.html.ini
  tests/wpt/webgl/meta/conformance2/buffers/buffer-overflow-test.html.ini
  tests/wpt/webgl/meta/conformance2/buffers/buffer-type-restrictions.html.ini
  tests/wpt/webgl/meta/conformance2/buffers/delete-buffer.html.ini
  tests/wpt/webgl/meta/conformance2/buffers/one-large-uniform-buffer.html.ini
  tests/wpt/webgl/meta/conformance2/buffers/uniform-buffers-second-compile.html.ini
  tests/wpt/webgl/meta/conformance2/buffers/uniform-buffers-state-restoration.html.ini
  tests/wpt/webgl/meta/conformance2/buffers/uniform-buffers.html.ini
  tests/wpt/webgl/meta/conformance2/context/methods-2.html.ini
  tests/wpt/webgl/meta/conformance2/rendering/uniform-block-buffer-size.html.ini
  tests/wpt/webgl/meta/conformance2/state/gl-enum-tests.html.ini
  tests/wpt/webgl/meta/conformance2/transform_feedback/same-buffer-two-binding-points.html.ini
  tests/wpt/webgl/meta/conformance2/transform_feedback/switching-objects.html.ini
  tests/wpt/webgl/meta/conformance2/transform_feedback/too-small-buffers.html.ini
  tests/wpt/webgl/meta/conformance2/transform_feedback/transform_feedback.html.ini
  tests/wpt/webgl/meta/conformance2/transform_feedback/two-unreferenced-varyings.html.ini
  tests/wpt/webgl/meta/conformance2/transform_feedback/unwritten-output-defaults-to-zero.html.ini
  tests/wpt/webgl/meta/conformance2/uniforms/dependent-buffer-change.html.ini
  tests/wpt/webgl/meta/conformance2/uniforms/draw-with-uniform-blocks.html.ini
  tests/wpt/webgl/meta/conformance2/uniforms/query-uniform-blocks-after-shader-detach.html.ini
  tests/wpt/webgl/meta/conformance2/uniforms/simple-buffer-change.html.ini
  tests/wpt/webgl/meta/conformance2/uniforms/uniform-blocks-with-arrays.html.ini
Labels: S-awaiting-merge

#25446 Make getOwnPropertyDescriptor hold the correct value for indexed/named properties
  components/script/dom/bindings/codegen/CodegenRust.py
  components/script/dom/webidls/HTMLFormElement.webidl
  components/script/dom/webidls/Window.webidl
  components/script/dom/windowproxy.rs
  tests/wpt/metadata/WebIDL/ecmascript-binding/legacy-platform-object.html.ini
  tests/wpt/metadata/dom/collections/HTMLCollection-supported-property-indices.html.ini
  tests/wpt/metadata/html/dom/elements/global-attributes/dataset-binding.window.js.ini
  tests/wpt/metadata/html/semantics/forms/the-form-element/form-nameditem.html.ini
Labels: S-awaiting-merge

#25413 Implement HTMLOptionElement.index
  components/script/dom/htmloptionelement.rs
  components/script/dom/htmlselectelement.rs
  components/script/dom/webidls/HTMLOptionElement.webidl
  tests/wpt/metadata/html/dom/idlharness.https.html.ini
  tests/wpt/metadata/html/semantics/forms/the-option-element/option-index.html.ini
Labels: S-awaiting-merge

#25435 RadioNodeList liveness
  components/script/dom/htmlformcontrolscollection.rs
  components/script/dom/htmlformelement.rs
  components/script/dom/nodelist.rs
  components/script/dom/radionodelist.rs
  tests/wpt/metadata/html/semantics/forms/the-form-element/form-elements-nameditem-01.html.ini
  tests/wpt/metadata/html/semantics/forms/the-form-element/form-nameditem.html.ini
Labels: S-awaiting-merge

#25502 Sync WPT with upstream (13-01-2020)
  tests/wpt/metadata/css/cssom-view/CaretPosition-001.html.ini
  tests/wpt/metadata/css/cssom-view/elementsFromPoint-iframes.html.ini
  tests/wpt/metadata/fetch/content-type/response.window.js.ini
  tests/wpt/metadata/fetch/nosniff/parsing-nosniff.window.js.ini
  tests/wpt/metadata/html/browsers/history/the-history-interface/traverse_the_history_2.html.ini
  tests/wpt/metadata/html/browsers/history/the-history-interface/traverse_the_history_5.html.ini
  tests/wpt/metadata/html/browsers/the-window-object/apis-for-creating-and-navigating-browsing-contexts-by-name/creating_browsing_context_test_01.html.ini
  tests/wpt/metadata/html/interaction/focus/the-autofocus-attribute/supported-elements.html.ini
  tests/wpt/metadata/html/semantics/embedded-content/the-iframe-element/iframe_sandbox_popups_nonescaping-3.html.ini
  tests/wpt/metadata/html/semantics/forms/form-submission-0/SubmitEvent.window.js.ini
  tests/wpt/metadata/resource-timing/crossorigin-sandwich-TAO.sub.html.ini
  tests/wpt/metadata/webmessaging/without-ports/017.html.ini
  tests/wpt/metadata/workers/semantics/multiple-workers/005.html.ini
  tests/wpt/web-platform-tests/html/semantics/forms/form-submission-0/SubmitEvent.window.js
Labels: S-awaiting-merge

#25503 Allow dumping the fragment tree in layout_2020
  components/layout_2020/flow/root.rs
  components/layout_2020/fragments.rs
  components/layout_2020/geom.rs
  components/layout_thread_2020/lib.rs
Labels: S-awaiting-merge

#25509 Update ANGLE for UWP build.
  python/servo/build_commands.py
  support/hololens/ServoApp/ServoApp.vcxproj
  support/hololens/ServoApp/packages.config
Labels: S-awaiting-merge

#25510 Implement queueMicrotask
  components/script/dom/globalscope.rs
  components/script/dom/webidls/WindowOrWorkerGlobalScope.webidl
  components/script/dom/window.rs
  components/script/dom/workerglobalscope.rs
  components/script/microtask.rs
  tests/wpt/metadata/html/browsers/the-window-object/window-properties.https.html.ini
  tests/wpt/metadata/html/dom/idlharness.https.html.ini
  tests/wpt/metadata/html/dom/idlharness.worker.js.ini
  tests/wpt/metadata/html/webappapis/microtask-queuing/queue-microtask-exceptions.any.js.ini
  tests/wpt/metadata/html/webappapis/microtask-queuing/queue-microtask.any.js.ini
  tests/wpt/metadata/html/webappapis/microtask-queuing/queue-microtask.window.js.ini
Labels: S-awaiting-merge

#25507 Update wgpu-core
  Cargo.lock
  components/webgpu/lib.rs
  servo-tidy.toml
Labels: S-awaiting-merge

#25521 Add support for WebGL2 `RASTERIZER_DISCARD` enum.
  components/script/dom/webgl2renderingcontext.rs
  tests/wpt/webgl/meta/conformance2/transform_feedback/same-buffer-two-binding-points.html.ini
  tests/wpt/webgl/meta/conformance2/transform_feedback/transform_feedback.html.ini
  tests/wpt/webgl/meta/conformance2/transform_feedback/unwritten-output-defaults-to-zero.html.ini
Labels: S-awaiting-merge

#25495 CI: build Linux amd64 --media-stack=dummy
  etc/taskcluster/decision_task.py
Labels: S-awaiting-merge

#25506 Change code of conduct contact
  CONTRIBUTING.md
Labels: S-awaiting-merge

#25525 Mitigation for #25498
  Cargo.lock
  ports/glutin/Cargo.toml
  ports/glutin/browser.rs
Labels: S-awaiting-merge

#25519 Add support for WebGL2 unsigned uniform operations
  Cargo.lock
  components/canvas/Cargo.toml
  components/canvas/webgl_thread.rs
  components/canvas_traits/webgl.rs
  components/script/dom/webgl2renderingcontext.rs
  components/script/dom/webglrenderingcontext.rs
  components/script/dom/webidls/WebGL2RenderingContext.webidl
  tests/wpt/webgl/meta/conformance2/context/methods-2.html.ini
  tests/wpt/webgl/meta/conformance2/glsl3/unary-minus-operator-in-dynamic-loop.html.ini
  tests/wpt/webgl/meta/conformance2/uniforms/gl-uniform-arrays-sub-source.html.ini
Labels: S-awaiting-merge

#25534 Put target element, form owner, and element document on scope chain of compiled events
  components/script/dom/eventtarget.rs
  tests/wpt/mozilla/meta/MANIFEST.json
  tests/wpt/mozilla/tests/mozilla/compile-event-handler-lexical-scopes-simple.html
Labels: S-awaiting-merge

#25529 Slightly increase timeout for linux tidy+unit task.
  etc/taskcluster/decision_task.py
Labels: S-awaiting-merge

#25485 Allow deletions from overflowed textinput
  components/script/textinput.rs
  tests/unit/script/textinput.rs
Labels: S-awaiting-merge

#25526 Initial implementation of GPUBindGroupLayout for WebGPU
  Cargo.lock
  components/script/dom/bindings/trace.rs
  components/script/dom/gpubindgrouplayout.rs
  components/script/dom/gpudevice.rs
  components/script/dom/gpushaderstage.rs
  components/script/dom/identityhub.rs
  components/script/dom/mod.rs
  components/script/dom/navigator.rs
  components/script/dom/webidls/GPUBindGroupLayout.webidl
  components/script/dom/webidls/GPUDevice.webidl
  components/script/dom/webidls/GPUShaderStage.webidl
  components/webgpu/lib.rs
  servo-tidy.toml
Labels: S-awaiting-merge

#25536 Upgrade to rustc 1.42.0-nightly (3291ae339 2020-01-15)
  components/config_plugins/lib.rs
  components/deny_public_fields/lib.rs
  components/domobject_derive/lib.rs
  components/layout/lib.rs
  components/layout_2020/lib.rs
  components/script_plugins/lib.rs
  rust-toolchain
Labels: S-awaiting-merge

#25538 Add support for WebGL2 uniform array operations
  components/script/dom/webgl2renderingcontext.rs
  components/script/dom/webglrenderingcontext.rs
  components/script/dom/webidls/WebGL2RenderingContext.webidl
  components/script/dom/webidls/WebGLRenderingContext.webidl
  tests/wpt/webgl/meta/conformance2/uniforms/gl-uniform-arrays-sub-source.html.ini
Labels: S-awaiting-merge

#25543 Add support for WebGL2 uniform matrix operations
  Cargo.lock
  components/canvas/Cargo.toml
  components/canvas/webgl_thread.rs
  components/canvas_traits/webgl.rs
  components/script/dom/webgl2renderingcontext.rs
  components/script/dom/webglrenderingcontext.rs
  components/script/dom/webidls/WebGL2RenderingContext.webidl
  components/script/dom/webidls/WebGLRenderingContext.webidl
  tests/wpt/webgl/meta/conformance2/context/methods-2.html.ini
  tests/wpt/webgl/meta/conformance2/uniforms/gl-uniform-arrays-sub-source.html.ini
Labels: S-awaiting-merge

#25545 Add WebGL2 specific version strings
  components/script/dom/webgl2renderingcontext.rs
  tests/wpt/webgl/meta/conformance2/state/gl-getstring.html.ini
Labels: S-awaiting-merge

#25551 Fix canvas wpt test `path-objects/2d.path.rect.zero.4.html`
  components/canvas/canvas_data.rs
  tests/wpt/metadata/2dcontext/path-objects/2d.path.rect.zero.4.html.ini
  tests/wpt/metadata/offscreen-canvas/path-objects/2d.path.rect.zero.4.html.ini
  tests/wpt/metadata/offscreen-canvas/path-objects/2d.path.rect.zero.4.worker.js.ini
Labels: S-awaiting-merge

#25552 Return the highest priority error from the descendant instead of return the very first one
  components/script/script_module.rs
  tests/wpt/metadata/html/semantics/scripting-1/the-script-element/module/error-type-1.html.ini
Labels: S-awaiting-merge

#25555 Add default arguments so that ./mach test --all works
  python/servo/testing_commands.py
Labels: S-awaiting-merge

#25556 Update the WebGL2 test expectations
  tests/wpt/webgl/meta/conformance2/attribs/gl-vertex-attrib-i-render.html.ini
  tests/wpt/webgl/meta/conformance2/attribs/gl-vertex-attrib.html.ini
  tests/wpt/webgl/meta/conformance2/buffers/bound-buffer-size-change-test.html.ini
  tests/wpt/webgl/meta/conformance2/buffers/buffer-overflow-test.html.ini
  tests/wpt/webgl/meta/conformance2/buffers/delete-buffer.html.ini
  tests/wpt/webgl/meta/conformance2/buffers/get-buffer-sub-data-validity.html.ini
  tests/wpt/webgl/meta/conformance2/canvas/to-data-url-with-pack-params.html.ini
  tests/wpt/webgl/meta/conformance2/context/constants-and-properties-2.html.ini
  tests/wpt/webgl/meta/conformance2/glsl3/float-parsing.html.ini
  tests/wpt/webgl/meta/conformance2/glsl3/shader-with-mis-matching-uniform-block.html.ini
  tests/wpt/webgl/meta/conformance2/glsl3/switch-case.html.ini
  tests/wpt/webgl/meta/conformance2/glsl3/texture-offset-non-constant-offset.html.ini
  tests/wpt/webgl/meta/conformance2/glsl3/tricky-loop-conditions.html.ini
  tests/wpt/webgl/meta/conformance2/glsl3/uniform-block-layout-match.html.ini
  tests/wpt/webgl/meta/conformance2/glsl3/varying-struct-inline-definition.html.ini
  tests/wpt/webgl/meta/conformance2/glsl3/vector-dynamic-indexing-swizzled-lvalue.html.ini
  tests/wpt/webgl/meta/conformance2/misc/expando-loss-2.html.ini
  tests/wpt/webgl/meta/conformance2/misc/getextension-while-pbo-bound-stability.html.ini
  tests/wpt/webgl/meta/conformance2/misc/instanceof-test.html.ini
  tests/wpt/webgl/meta/conformance2/misc/object-deletion-behaviour-2.html.ini
  tests/wpt/webgl/meta/conformance2/query/occlusion-query.html.ini
  tests/wpt/webgl/meta/conformance2/rendering/canvas-resizing-with-pbo-bound.html.ini
  tests/wpt/webgl/meta/conformance2/rendering/out-of-bounds-index-buffers-after-copying.html.ini
  tests/wpt/webgl/meta/conformance2/rendering/uniform-block-buffer-size.html.ini
  tests/wpt/webgl/meta/conformance2/state/gl-get-calls.html.ini
  tests/wpt/webgl/meta/conformance2/transform_feedback/two-unreferenced-varyings.html.ini
  tests/wpt/webgl/meta/conformance2/uniforms/incompatible-texture-type-for-sampler.html.ini
  tests/wpt/webgl/meta/conformance2/vertex_arrays/vertex-array-object.html.ini
Labels: S-awaiting-merge

#25569 Initial implementation of GPUPipelineLayout for WebGPU
  components/script/dom/bindings/trace.rs
  components/script/dom/gpubindgrouplayout.rs
  components/script/dom/gpudevice.rs
  components/script/dom/gpupipelinelayout.rs
  components/script/dom/identityhub.rs
  components/script/dom/mod.rs
  components/script/dom/navigator.rs
  components/script/dom/webidls/GPUDevice.webidl
  components/script/dom/webidls/GPUPipelineLayout.webidl
  components/webgpu/lib.rs
Labels: S-awaiting-merge

#25431 use create_html_element for HTMLAudioElement and HTMLImageElement
  components/script/dom/htmlaudioelement.rs
  components/script/dom/htmlimageelement.rs
Labels: S-awaiting-merge

#25580 Support worker for WebGPU
  components/script/dom/globalscope.rs
  components/script/dom/gpu.rs
  components/script/dom/gpuadapter.rs
  components/script/dom/gpudevice.rs
  components/script/dom/navigator.rs
Labels: S-awaiting-merge

#25490 Simplify and fix iteration over radio button group
  components/script/dom/htmlinputelement.rs
Labels: S-awaiting-merge

#25586 Update windows llvm to 8.0.1.
  python/servo/packages.py
Labels: S-awaiting-merge

#25578 Let custom element registry know about picture tag
  components/script/dom/bindings/htmlconstructor.rs
  components/script/dom/customelementregistry.rs
  tests/wpt/metadata/custom-elements/builtin-coverage.html.ini
Labels: S-awaiting-merge

#25574 Use Euclid data types for physical structs in layout_2020
  components/layout_2020/display_list.rs
  components/layout_2020/dom_traversal.rs
  components/layout_2020/flow/root.rs
  components/layout_2020/fragments.rs
  components/layout_2020/geom.rs
  components/layout_2020/replaced.rs
  components/layout_2020/style_ext.rs
  components/style/values/computed/length.rs
Labels: A-layout/2020, S-awaiting-merge

#25561 Make File objects roundtrip through FormData
  components/script/dom/formdata.rs
  tests/wpt/metadata/xhr/formdata-foreach.html.ini
Labels: S-awaiting-merge

#25592 change branch of spirv_cross
  Cargo.lock
  Cargo.toml
Labels: S-awaiting-merge

#25597 Rename compartment to realm
  components/config/prefs.rs
  components/script/body.rs
  components/script/devtools.rs
  components/script/dom/audiobuffer.rs
  components/script/dom/audiocontext.rs
  components/script/dom/baseaudiocontext.rs
  components/script/dom/bindings/callback.rs
  components/script/dom/bindings/codegen/Bindings.conf
  components/script/dom/bindings/codegen/CodegenRust.py
  components/script/dom/bindings/codegen/Configuration.py
  components/script/dom/bindings/structuredclone.rs
  components/script/dom/bluetooth.rs
  components/script/dom/bluetoothdevice.rs
  components/script/dom/bluetoothremotegattcharacteristic.rs
  components/script/dom/bluetoothremotegattdescriptor.rs
  components/script/dom/bluetoothremotegattserver.rs
  components/script/dom/customelementregistry.rs
  components/script/dom/dedicatedworkerglobalscope.rs
  components/script/dom/document.rs
  components/script/dom/eventsource.rs
  components/script/dom/eventtarget.rs
  components/script/dom/filereader.rs
  components/script/dom/gpu.rs
  components/script/dom/gpuadapter.rs
  components/script/dom/htmlmediaelement.rs
  components/script/dom/mediadevices.rs
  components/script/dom/mediasession.rs
  components/script/dom/navigationpreloadmanager.rs
  components/script/dom/navigator.rs
  components/script/dom/offlineaudiocontext.rs
  components/script/dom/permissions.rs
  components/script/dom/promise.rs
  components/script/dom/rtcpeerconnection.rs
  components/script/dom/serviceworkercontainer.rs
  components/script/dom/serviceworkerglobalscope.rs
  components/script/dom/testbinding.rs
  components/script/dom/testworklet.rs
  components/script/dom/vrdisplay.rs
  components/script/dom/window.rs
  components/script/dom/windowproxy.rs
  components/script/dom/worker.rs
  components/script/dom/workerglobalscope.rs
  components/script/dom/worklet.rs
  components/script/dom/xr.rs
  components/script/dom/xrinputsource.rs
  components/script/dom/xrinputsourceschangeevent.rs
  components/script/dom/xrsession.rs
  components/script/dom/xrviewerpose.rs
  components/script/fetch.rs
  components/script/lib.rs
  components/script/realms.rs
  components/script/script_module.rs
  components/script/script_thread.rs
  resources/prefs.json
Labels: S-awaiting-merge

#25515 Add microtask checkpoints to script elements and custom elements
  components/script/dom/customelementregistry.rs
  components/script/dom/htmlimageelement.rs
  components/script/dom/servoparser/mod.rs
  components/script/microtask.rs
  tests/wpt/metadata/custom-elements/microtasks-and-constructors.html.ini
  tests/wpt/metadata/dom/nodes/MutationObserver-document.html.ini
Labels: S-awaiting-merge

#25598 Expire cookies on lookup
  components/net/cookie_storage.rs
  components/net/http_loader.rs
  components/net/resource_thread.rs
  components/net/websocket_loader.rs
  tests/wpt/metadata/fetch/api/cors/cors-cookies-redirect.any.js.ini
  tests/wpt/metadata/fetch/api/cors/cors-cookies.any.js.ini
  tests/wpt/metadata/fetch/api/credentials/cookies.any.js.ini
Labels: S-awaiting-merge

#25576 Implement HTMLMenuElement
  components/script/dom/bindings/htmlconstructor.rs
  components/script/dom/create.rs
  components/script/dom/customelementregistry.rs
  components/script/dom/htmlmenuelement.rs
  components/script/dom/mod.rs
  components/script/dom/webidls/HTMLMenuElement.webidl
  tests/wpt/metadata/custom-elements/builtin-coverage.html.ini
  tests/wpt/metadata/html/dom/idlharness.https.html.ini
  tests/wpt/metadata/html/dom/reflection-misc.html.ini
  tests/wpt/metadata/html/semantics/interfaces.html.ini
  tests/wpt/mozilla/meta/MANIFEST.json
  tests/wpt/mozilla/tests/mozilla/interfaces.html
Labels: S-awaiting-merge, S-fails-tidy

#25599 Enable cookies tests
  tests/wpt/include.ini
  tests/wpt/metadata/cookies/http-state/charset-tests.html.ini
  tests/wpt/metadata/cookies/http-state/chromium-tests.html.ini
  tests/wpt/metadata/cookies/http-state/domain-tests.html.ini
  tests/wpt/metadata/cookies/http-state/general-tests.html.ini
  tests/wpt/metadata/cookies/http-state/ordering-tests.html.ini
  tests/wpt/metadata/cookies/http-state/path-tests.html.ini
  tests/wpt/metadata/cookies/navigated-away.html.ini
  tests/wpt/metadata/cookies/samesite-none-secure/cookies-without-samesite-must-be-secure.https.tentative.html.ini
  tests/wpt/metadata/cookies/samesite/about-blank-nested.https.html.ini
  tests/wpt/metadata/cookies/samesite/about-blank-toplevel.https.html.ini
  tests/wpt/metadata/cookies/samesite/fetch.https.html.ini
  tests/wpt/metadata/cookies/samesite/form-get-blank-reload.https.html.ini
  tests/wpt/metadata/cookies/samesite/form-get-blank.https.html.ini
  tests/wpt/metadata/cookies/samesite/form-post-blank-reload.https.html.ini
  tests/wpt/metadata/cookies/samesite/form-post-blank.https.html.ini
  tests/wpt/metadata/cookies/samesite/iframe-reload.https.html.ini
  tests/wpt/metadata/cookies/samesite/iframe.https.html.ini
  tests/wpt/metadata/cookies/samesite/img.https.html.ini
  tests/wpt/metadata/cookies/samesite/sandbox-iframe-nested.https.html.ini
  tests/wpt/metadata/cookies/samesite/sandbox-iframe-subresource.https.html.ini
  tests/wpt/metadata/cookies/samesite/setcookie-lax.https.html.ini
  tests/wpt/metadata/cookies/samesite/setcookie-navigation.https.html.ini
  tests/wpt/metadata/cookies/samesite/window-open-reload.https.html.ini
  tests/wpt/metadata/cookies/samesite/window-open.https.html.ini
Labels: S-awaiting-merge

#25575 Prevent infinite recursion when upgrading custom elements
  components/script/dom/customelementregistry.rs
  components/script/dom/element.rs
  tests/wpt/metadata/custom-elements/upgrading.html.ini
Labels: S-awaiting-merge

#25615 mach: fix error on Python 3 when specifying a target
  python/servo/command_base.py
Labels: S-awaiting-merge

#25617 mach: fix `bootstrap-android` on Python 3
  python/servo/util.py
Labels: S-awaiting-merge

#25620 Sync WPT with upstream (27-01-2020)
  tests/wpt/metadata/css/cssom-view/elementFromPoint-001.html.ini
  tests/wpt/metadata/fetch/content-type/response.window.js.ini
  tests/wpt/metadata/fetch/nosniff/parsing-nosniff.window.js.ini
  tests/wpt/metadata/fetch/security/embedded-credentials.tentative.sub.html.ini
  tests/wpt/metadata/html/browsers/history/the-history-interface/traverse_the_history_1.html.ini
  tests/wpt/metadata/html/browsers/history/the-history-interface/traverse_the_history_2.html.ini
  tests/wpt/metadata/html/browsers/history/the-history-interface/traverse_the_history_5.html.ini
  tests/wpt/metadata/html/browsers/windows/embedded-opener-remove-frame.html.ini
  tests/wpt/metadata/html/semantics/embedded-content/the-iframe-element/iframe_sandbox_popups_escaping-3.html.ini
  tests/wpt/metadata/html/semantics/embedded-content/the-iframe-element/iframe_sandbox_popups_nonescaping-3.html.ini
  tests/wpt/metadata/performance-timeline/webtiming-resolution.any.js.ini
  tests/wpt/metadata/resource-timing/crossorigin-sandwich-TAO.sub.html.ini
  tests/wpt/metadata/workers/semantics/multiple-workers/005.html.ini
  tests/wpt/web-platform-tests/workers/constructors/SharedWorker/Infinity
  tests/wpt/web-platform-tests/workers/constructors/SharedWorker/Infinity-arguments.html
  tests/wpt/web-platform-tests/workers/constructors/SharedWorker/NaN
  tests/wpt/web-platform-tests/workers/constructors/SharedWorker/NaN-arguments.html
Labels: S-awaiting-merge

#25610 do less on abort if not done
  components/script/dom/xmlhttprequest.rs
  tests/wpt/metadata/xhr/abort-during-open.any.js.ini
  tests/wpt/metadata/xhr/abort-event-abort.any.js.ini
  tests/wpt/metadata/xhr/send-data-unexpected-tostring.htm.ini
Labels: S-awaiting-merge

#25622 Add missing CanvasRenderingContext2D global composition operation "clear"
  components/canvas/raqote_backend.rs
  components/canvas_traits/canvas.rs
  tests/wpt/metadata/2dcontext/compositing/2d.composite.operation.clear.html.ini
  tests/wpt/metadata/offscreen-canvas/compositing/2d.composite.operation.clear.html.ini
  tests/wpt/metadata/offscreen-canvas/compositing/2d.composite.operation.clear.worker.js.ini
Labels: S-awaiting-merge

#25524 Implement Blob methods (text/arraybuffer)
  components/script/body.rs
  components/script/dom/blob.rs
  components/script/dom/globalscope.rs
  components/script/dom/webidls/Blob.webidl
  tests/wpt/metadata/FileAPI/blob/Blob-array-buffer.any.js.ini
  tests/wpt/metadata/FileAPI/blob/Blob-text.any.js.ini
  tests/wpt/metadata/FileAPI/idlharness.html.ini
  tests/wpt/metadata/FileAPI/idlharness.worker.js.ini
Labels: S-awaiting-merge

#25625 Make error events only pass the extra error-event arguments to global listeners
  components/script/dom/eventtarget.rs
  tests/wpt/metadata/html/webappapis/scripting/events/event-handler-processing-algorithm-error/document-synthetic-errorevent.html.ini
  tests/wpt/metadata/html/webappapis/scripting/events/event-handler-processing-algorithm-error/script-element.html.ini
Labels: S-awaiting-merge

#25635 Implement URLMismatchError
  components/script/dom/domexception.rs
  tests/wpt/metadata/WebIDL/ecmascript-binding/es-exceptions/DOMException-constructor-behavior.any.js.ini
Labels: S-awaiting-merge

#25633 Remove unnecessary LocalName::from(constant) calls
  components/script/dom/htmlimageelement.rs
  components/script/dom/servoparser/prefetch.rs
Labels: S-awaiting-merge

#25634 Accept UTF8 cookie header values
  components/net/http_loader.rs
  components/net/websocket_loader.rs
  tests/wpt/metadata/cookies/http-state/charset-tests.html.ini
Labels: S-awaiting-merge

#25640 move ConstellationMsg to compositing
  Cargo.lock
  components/compositing/Cargo.toml
  components/compositing/compositor.rs
  components/compositing/compositor_thread.rs
  components/compositing/lib.rs
  components/compositing/windowing.rs
  components/constellation/constellation.rs
  components/script/dom/event.rs
  components/script_traits/lib.rs
  components/servo/lib.rs
  components/webdriver_server/Cargo.toml
  components/webdriver_server/actions.rs
  components/webdriver_server/lib.rs
  components/webvr/Cargo.toml
  components/webvr/webvr_thread.rs
Labels: S-awaiting-merge

#25648 Remove code duplication from IdentityHub
  components/script/dom/identityhub.rs
Labels: S-awaiting-merge

#25637 Initial implementation of GPUBindGroup for WebGPU
  Cargo.lock
  components/script/dom/bindings/trace.rs
  components/script/dom/globalscope.rs
  components/script/dom/gpubindgroup.rs
  components/script/dom/gpubuffer.rs
  components/script/dom/gpudevice.rs
  components/script/dom/identityhub.rs
  components/script/dom/mod.rs
  components/script/dom/webidls/GPUBindGroup.webidl
  components/script/dom/webidls/GPUDevice.webidl
  components/webgpu/lib.rs
Labels: S-awaiting-merge

#25642 Send request's integrity metadata via RequestBuilder
  components/script/fetch.rs
  tests/wpt/metadata/fetch/api/basic/integrity.sub.any.js.ini
Labels: S-awaiting-merge

#25653 Make nulling out an inline event handler remove it from the list order
  components/script/dom/eventtarget.rs
  tests/wpt/metadata/html/webappapis/scripting/events/event-handler-removal.window.js.ini
Labels: S-awaiting-merge

#25654 fix DOMTokenList
  components/script/dom/domtokenlist.rs
  tests/wpt/metadata/dom/nodes/Element-classlist.html.ini
Labels: S-awaiting-merge

#25662 Try to avoid panicking during I/O in the signal and panic handlers.
  ports/glutin/backtrace.rs
  ports/glutin/main2.rs
Labels: S-awaiting-merge
