Repository servo/servo, pull requests merged in 2020-07, with the labels that each got.

#27126 Implement GPUBuffer.getMappedRange()
  components/constellation/constellation.rs
  components/script/dom/gpubuffer.rs
  components/script/dom/gpudevice.rs
  components/script/dom/webidls/GPUBuffer.webidl
Labels: S-awaiting-merge

#27141 Fix typo
  components/selectors/README.md
Labels: S-awaiting-merge

#27100 Implement HTMLFormElement.requestSubmit()
  components/script/dom/htmlbuttonelement.rs
  components/script/dom/htmlformelement.rs
  components/script/dom/htmlinputelement.rs
  components/script/dom/webidls/HTMLFormElement.webidl
  tests/wpt/metadata-layout-2020/html/dom/idlharness.https.html.ini
  tests/wpt/metadata/html/dom/idlharness.https.html.ini
  tests/wpt/metadata/html/semantics/forms/form-submission-0/form-submission-algorithm.html.ini
  tests/wpt/metadata/html/semantics/forms/the-form-element/form-requestsubmit.html.ini
Labels: S-awaiting-merge

#27151 Fix Gstreamer `undefined symbol: gst_webrtc_data_channel_state_get_type` error
  python/servo/post_build_commands.py
Labels: S-awaiting-merge

#27157 Enable stdout logging for all UWP builds
  support/hololens/ServoApp/ServoControl/Servo.cpp
Labels: S-awaiting-merge

#27149 UWP: support virtual keyboard
  components/embedder_traits/lib.rs
  components/script/dom/document.rs
  ports/libmlservo/src/lib.rs
  ports/libsimpleservo/api/src/lib.rs
  ports/libsimpleservo/capi/src/lib.rs
  ports/libsimpleservo/jniapi/src/lib.rs
  ports/winit/browser.rs
  support/hololens/ServoApp/ServoControl/Servo.cpp
  support/hololens/ServoApp/ServoControl/Servo.h
  support/hololens/ServoApp/ServoControl/ServoControl.cpp
  support/hololens/ServoApp/ServoControl/ServoControl.h
Labels: S-awaiting-merge

#27143 Implement MediaStreamAudioDestinationNode, MediaStreamAudioSourceNode, MediaStreamTrackAudioSourceNode
  Cargo.lock
  components/script/dom/audiocontext.rs
  components/script/dom/mediastream.rs
  components/script/dom/mediastreamaudiodestinationnode.rs
  components/script/dom/mediastreamaudiosourcenode.rs
  components/script/dom/mediastreamtrackaudiosourcenode.rs
  components/script/dom/mod.rs
  components/script/dom/webidls/AudioContext.webidl
  components/script/dom/webidls/MediaStream.webidl
  components/script/dom/webidls/MediaStreamAudioDestinationNode.webidl
  components/script/dom/webidls/MediaStreamAudioSourceNode.webidl
  components/script/dom/webidls/MediaStreamTrack.webidl
  components/script/dom/webidls/MediaStreamTrackAudioSourceNode.webidl
  tests/html/media_stream_audio_nodes_loopback.html
  tests/wpt/metadata/webaudio/idlharness.https.window.js.ini
  tests/wpt/metadata/webaudio/the-audio-api/the-audionode-interface/audionode-connect-method-chaining.html.ini
  tests/wpt/metadata/webaudio/the-audio-api/the-mediastreamaudiodestinationnode-interface/ctor-mediastreamaudiodestination.html.ini
  tests/wpt/metadata/webaudio/the-audio-api/the-mediastreamaudiosourcenode-interface/mediastreamaudiosourcenode-ctor.html.ini
  tests/wpt/metadata/webaudio/the-audio-api/the-mediastreamaudiosourcenode-interface/mediastreamaudiosourcenode-routing.html.ini
  tests/wpt/mozilla/meta/MANIFEST.json
  tests/wpt/mozilla/tests/mozilla/interfaces.html
Labels: S-awaiting-merge

#27154 WebGPU update presentation data asynchronously
  components/script/dom/gpubuffer.rs
  components/script/dom/gpucanvascontext.rs
  components/webgpu/lib.rs
Labels: S-awaiting-merge

#27169 Mach test cargo target dir
  tests/wpt/run.py
Labels: S-awaiting-merge

#27163 Return Option for Window's layout channel
  components/script/dom/document.rs
  components/script/dom/window.rs
  components/script/script_thread.rs
  tests/wpt/mozilla/meta/MANIFEST.json
  tests/wpt/mozilla/tests/mozilla/detached_layout.html
Labels: S-awaiting-merge

#27173 Implement GPUQueue write methods and update wgpu-core
  Cargo.lock
  components/script/dom/gpuadapter.rs
  components/script/dom/gpudevice.rs
  components/script/dom/gpuqueue.rs
  components/script/dom/gputexture.rs
  components/script/dom/webidls/GPUBuffer.webidl
  components/script/dom/webidls/GPUQueue.webidl
  components/script/dom/webidls/GPUTexture.webidl
  components/webgpu/lib.rs
Labels: S-awaiting-merge

#27174 Do not fire `invalid` event on form elements
  components/script/dom/htmlformelement.rs
  tests/wpt/metadata/html/semantics/forms/form-submission-0/historical.window.js.ini
Labels: S-awaiting-merge

#27177 UWP: allow servo's initial URL to be set before Servo starts
  support/hololens/ServoApp/DefaultUrl.h
  support/hololens/ServoApp/ServoControl/Servo.cpp
  support/hololens/ServoApp/ServoControl/Servo.h
  support/hololens/ServoApp/ServoControl/ServoControl.cpp
  support/hololens/ServoApp/ServoControl/ServoControl.h
Labels: S-awaiting-merge

#27179 Update to 7/6 rustc.
  components/compositing/lib.rs
  components/script_plugins/lib.rs
  rust-toolchain
Labels: S-awaiting-merge

#26998 Use a stronger atomic guarantee when cancelling tasks
  components/script/dom/window.rs
Labels: S-awaiting-merge

#27183 Add `.servobuild` configuration for the choice of media stack
  python/servo/command_base.py
  servobuild.example
Labels: S-awaiting-merge

#27168 Add stub isContextLost API.
  components/script/dom/webgl2renderingcontext.rs
  components/script/dom/webglrenderingcontext.rs
  components/script/dom/webidls/WebGLRenderingContext.webidl
  tests/wpt/webgl/meta/conformance/context/context-lost.html.ini
  tests/wpt/webgl/meta/conformance/context/methods.html.ini
  tests/wpt/webgl/meta/conformance/more/conformance/methods.html.ini
  tests/wpt/webgl/meta/conformance2/context/methods-2.html.ini
Labels: S-awaiting-merge

#27180 Remove segfaults in WebGPU threads
  components/script/dom/gpucanvascontext.rs
  components/webgpu/lib.rs
Labels: S-awaiting-merge

#27188 Delete Servo.ico
  resources/Servo.ico
Labels: S-awaiting-merge

#27184 Bail out from font loading if no default font can be loaded.
  components/canvas/canvas_data.rs
Labels: S-awaiting-merge

#27088 Implement Console grouping APIs.
  components/script/dom/console.rs
  components/script/dom/globalscope.rs
  components/script/dom/webidls/Console.webidl
  python/tidy/servo_tidy/tidy.py
Labels: S-awaiting-merge

#27186 Update webrender to crash-backtrace branch.
  Cargo.lock
  Cargo.toml
Labels: S-awaiting-merge

#27192 Net: in the absense of a request body, assume streaming it cannot fail
  components/net/http_loader.rs
Labels: S-awaiting-merge

#27193 improve reliability of hang monitor tests
  components/background_hang_monitor/background_hang_monitor.rs
  components/background_hang_monitor/tests/hang_monitor_tests.rs
Labels: S-awaiting-merge

#27198 Add debug output for intermittently failing test.
  components/net/tests/http_loader.rs
Labels: S-awaiting-merge

#27142 Delay initializing servo GL until as late as possible
  ports/gstplugin/servowebsrc.rs
Labels: P-gst-plugin, S-awaiting-merge

#27201 Update servo-media-audio for HRTF panic fix.
  Cargo.lock
Labels: S-awaiting-merge

#27208 Update bindgen and unicase.
  Cargo.lock
Labels: S-awaiting-merge

#27209 Update x11-clipboard.
  Cargo.lock
  etc/taskcluster/docker/build.dockerfile
  etc/taskcluster/docker/run.dockerfile
Labels: S-awaiting-merge

#27164 Replace ws-rs with async-tungstenite.
  Cargo.lock
  Cargo.toml
  components/net/Cargo.toml
  components/net/resource_thread.rs
  components/net/websocket_loader.rs
  servo-tidy.toml
  tests/wpt/metadata/websockets/cookies/third-party-cookie-accepted.https.html.ini
  tests/wpt/metadata/websockets/interfaces/WebSocket/close/close-connecting.html.ini
Labels: S-awaiting-merge

#27214 Update content-security-policy.
  Cargo.lock
Labels: S-awaiting-merge

#27224 Add support for webxr cubemap and spherical 360 rendering
  Cargo.lock
  components/config/prefs.rs
  components/script/dom/xrviewerpose.rs
  ports/winit/headed_window.rs
  resources/prefs.json
Labels: A-xr-zomg, S-awaiting-merge

#27152 Mediadevices.enumeratedevices
  Cargo.lock
  components/script/dom/mediadeviceinfo.rs
  components/script/dom/mediadevices.rs
  components/script/dom/mod.rs
  components/script/dom/webidls/MediaDeviceInfo.webidl
  components/script/dom/webidls/MediaDevices.webidl
Labels: S-awaiting-merge

#27235 Add a sessionavailable event that allows content to enter an XR session without a user gesture
  components/atoms/static_atoms.txt
  components/config/prefs.rs
  components/script/dom/document.rs
  components/script/dom/xrsystem.rs
  resources/prefs.json
  tests/wpt/mozilla/meta/MANIFEST.json
  tests/wpt/mozilla/meta/webxr/sessionavailable.html.ini
  tests/wpt/mozilla/tests/webxr/sessionavailable.html
Labels: A-xr-zomg, S-awaiting-merge, S-needs-tests

#27232 Support depth and stencil in webxr
  Cargo.lock
  components/canvas/webgl_thread.rs
  components/script/dom/xrwebgllayer.rs
Labels: A-xr-zomg, S-awaiting-merge

#27229 devtools: TabDescription actor
  components/devtools/actor.rs
  components/devtools/actors/browsing_context.rs
  components/devtools/actors/root.rs
  components/devtools/actors/tab.rs
  components/devtools/lib.rs
  support/hololens/ServoApp/Devtools/Client.cpp
Labels: S-awaiting-merge

#27250 Unfocus input when virtual keyboard is dismissed
  components/compositing/lib.rs
  components/compositing/windowing.rs
  components/constellation/constellation.rs
  components/script/dom/document.rs
  components/script/script_thread.rs
  components/script_traits/lib.rs
  components/servo/lib.rs
  ports/libsimpleservo/api/src/lib.rs
  ports/libsimpleservo/capi/src/lib.rs
  support/hololens/ServoApp/ServoControl/Servo.h
  support/hololens/ServoApp/ServoControl/ServoControl.cpp
Labels: S-awaiting-merge

#27255 Implemented HTMLFormElement.relList
  components/script/dom/htmlformelement.rs
  components/script/dom/webidls/HTMLFormElement.webidl
  tests/wpt/metadata/WebIDL/ecmascript-binding/put-forwards.html.ini
  tests/wpt/metadata/html/dom/idlharness.https.html.ini
Labels: S-awaiting-merge

#27264 Implement Navigator.languages
  components/script/dom/navigator.rs
  components/script/dom/webidls/Navigator.webidl
  components/script/dom/workernavigator.rs
  tests/wpt/metadata/html/dom/idlharness.https.html.ini
  tests/wpt/metadata/html/dom/idlharness.worker.js.ini
  tests/wpt/metadata/html/webappapis/system-state-and-capabilities/__dir__.ini
  tests/wpt/metadata/html/webappapis/system-state-and-capabilities/the-navigator-object/historical.https.window.js.ini
  tests/wpt/metadata/html/webappapis/system-state-and-capabilities/the-navigator-object/navigator.any.js.ini
  tests/wpt/metadata/html/webappapis/system-state-and-capabilities/the-navigator-object/navigator_user_agent.https.html.ini
  tests/wpt/metadata/html/webappapis/system-state-and-capabilities/the-navigator-object/protocol.https.html.ini
Labels: S-awaiting-merge

#27266 Hide Window extension methods by default and add helper Window.js_backtrace method
  components/config/prefs.rs
  components/script/Cargo.toml
  components/script/dom/webidls/Window.webidl
  components/script/dom/window.rs
  resources/prefs.json
  resources/user-agent-js/00.example.js
  tests/wpt/mozilla/meta-layout-2020/mozilla/media_query_list_gc.html.ini
  tests/wpt/mozilla/meta-layout-2020/mozilla/prototypes.html.ini
  tests/wpt/mozilla/meta-layout-2020/mozilla/trace_null.html.ini
  tests/wpt/mozilla/meta-layout-2020/mozilla/transitionend_safety.html.ini
  tests/wpt/mozilla/meta-layout-2020/mozilla/weakref.html.ini
  tests/wpt/mozilla/meta/mozilla/media_query_list_gc.html.ini
  tests/wpt/mozilla/meta/mozilla/prototypes.html.ini
  tests/wpt/mozilla/meta/mozilla/trace_null.html.ini
  tests/wpt/mozilla/meta/mozilla/transitionend_safety.html.ini
  tests/wpt/mozilla/meta/mozilla/weakref.html.ini
Labels: S-awaiting-merge

#27265 Add stubs for HTMLCanvasElement.captureStream and WebRTC transceiver APIs
  components/config/prefs.rs
  components/script/dom/htmlcanvaselement.rs
  components/script/dom/mod.rs
  components/script/dom/rtcpeerconnection.rs
  components/script/dom/rtcrtpsender.rs
  components/script/dom/rtcrtptransceiver.rs
  components/script/dom/webidls/HTMLCanvasElement.webidl
  components/script/dom/webidls/RTCPeerConnection.webidl
  components/script/dom/webidls/RTCRtpSender.webidl
  components/script/dom/webidls/RTCRtpTransceiver.webidl
  resources/prefs.json
Labels: S-awaiting-merge

#27287 Make it possible to run fxr:// url in non-kiosk mode
  support/hololens/ServoApp/App.cpp
  support/hololens/ServoApp/BrowserPage.cpp
  support/hololens/ServoApp/BrowserPage.h
  support/hololens/ServoApp/Package.appxmanifest
Labels: S-awaiting-merge

#27300 Remove explicit Host header from websocket connection.
  components/net/websocket_loader.rs
Labels: S-awaiting-merge

#27282 Use `Rc` instead of cloning the `DOMString`
  components/script/dom/htmlscriptelement.rs
  components/script/script_module.rs
Labels: S-awaiting-merge

#27302 Make gstreamer packaging explicit
  components/servo/build.rs
  components/servo/lib.rs
  etc/taskcluster/decision_task.py
  python/servo/build_commands.py
  python/servo/gstreamer.py
  python/servo/package_commands.py
Labels: S-awaiting-merge

#27285 Implement WebGPU ErrorScopes
  Cargo.lock
  components/script/dom/bindings/codegen/Bindings.conf
  components/script/dom/bindings/trace.rs
  components/script/dom/globalscope.rs
  components/script/dom/gpuadapter.rs
  components/script/dom/gpucommandencoder.rs
  components/script/dom/gpudevice.rs
  components/script/dom/gpudevicelostinfo.rs
  components/script/dom/gpuoutofmemoryerror.rs
  components/script/dom/gpuvalidationerror.rs
  components/script/dom/mod.rs
  components/script/dom/webidls/GPUDeviceLostInfo.webidl
  components/script/dom/webidls/GPUOutOfMemoryError.webidl
  components/script/dom/webidls/GPUValidationError.webidl
  components/script/script_thread.rs
  components/webgpu/Cargo.toml
  components/webgpu/identity.rs
  components/webgpu/lib.rs
Labels: S-awaiting-merge

#27295 Gstreamer plugin support for streaming from webxr
  Cargo.lock
  components/compositing/compositor.rs
  ports/gstplugin/Cargo.toml
  ports/gstplugin/README.md
  ports/gstplugin/servowebsrc.rs
  ports/winit/headed_window.rs
  ports/winit/headless_window.rs
Labels: A-xr-zomg, P-gst-plugin, S-awaiting-merge

#27303 Use `asynch` instead of `r#async`
  components/script/dom/htmlscriptelement.rs
  components/script/dom/xmlhttprequest.rs
  components/script/script_module.rs
Labels: S-awaiting-merge

#27310 Remove emacs backup files, add them to .gitignore
  .gitignore
  components/webrender_surfman/#Cargo.toml#
  components/webrender_surfman/.#Cargo.toml
Labels: S-awaiting-merge

#27026 Introduce dynamic module
  Cargo.lock
  components/script/devtools.rs
  components/script/dom/bindings/codegen/Bindings.conf
  components/script/dom/bindings/trace.rs
  components/script/dom/dynamicmoduleowner.rs
  components/script/dom/globalscope.rs
  components/script/dom/htmlscriptelement.rs
  components/script/dom/mod.rs
  components/script/dom/servoparser/prefetch.rs
  components/script/dom/userscripts.rs
  components/script/dom/webidls/DynamicModuleOwner.webidl
  components/script/dom/workletglobalscope.rs
  components/script/script_module.rs
  components/script/script_thread.rs
  components/script/timers.rs
  components/script/webdriver_handlers.rs
  tests/wpt/include.ini
  tests/wpt/metadata/html/semantics/scripting-1/the-script-element/module/dynamic-import/dynamic-imports-fetch-error.sub.html.ini
  tests/wpt/metadata/html/semantics/scripting-1/the-script-element/module/dynamic-import/dynamic-imports-script-error.html.ini
  tests/wpt/metadata/html/semantics/scripting-1/the-script-element/module/dynamic-import/dynamic-imports.html.ini
  tests/wpt/metadata/html/semantics/scripting-1/the-script-element/module/dynamic-import/inline-event-handler.html.ini
  tests/wpt/metadata/html/semantics/scripting-1/the-script-element/module/dynamic-import/propagate-nonce-external-classic.html.ini
  tests/wpt/metadata/html/semantics/scripting-1/the-script-element/module/dynamic-import/propagate-nonce-external-module.html.ini
  tests/wpt/metadata/html/semantics/scripting-1/the-script-element/module/dynamic-import/propagate-nonce-inline-classic.html.ini
  tests/wpt/metadata/html/semantics/scripting-1/the-script-element/module/dynamic-import/propagate-nonce-inline-module.html.ini
  tests/wpt/metadata/html/semantics/scripting-1/the-script-element/module/dynamic-import/string-compilation-base-url-external-classic.html.ini
  tests/wpt/metadata/html/semantics/scripting-1/the-script-element/module/dynamic-import/string-compilation-base-url-external-module.html.ini
  tests/wpt/metadata/html/semantics/scripting-1/the-script-element/module/dynamic-import/string-compilation-base-url-inline-classic.html.ini
  tests/wpt/metadata/html/semantics/scripting-1/the-script-element/module/dynamic-import/string-compilation-base-url-inline-module.html.ini
  tests/wpt/metadata/html/semantics/scripting-1/the-script-element/module/dynamic-import/string-compilation-classic.html.ini
  tests/wpt/metadata/html/semantics/scripting-1/the-script-element/module/dynamic-import/string-compilation-module.html.ini
  tests/wpt/metadata/html/semantics/scripting-1/the-script-element/module/dynamic-import/string-compilation-nonce-classic.html.ini
  tests/wpt/metadata/html/semantics/scripting-1/the-script-element/module/dynamic-import/string-compilation-nonce-module.html.ini
  tests/wpt/metadata/html/semantics/scripting-1/the-script-element/module/dynamic-import/string-compilation-of-promise-result.html.ini
  tests/wpt/metadata/html/semantics/scripting-1/the-script-element/module/dynamic-import/string-compilation-other-document.html.ini
  tests/wpt/metadata/html/webappapis/dynamic-markup-insertion/document-write/module-dynamic-import.html.ini
Labels: S-awaiting-merge

#27279 Update hololens documentation.
  docs/hololens.md
Labels: S-awaiting-merge

#27316 Save / restore state when updating opaque framebuffer bindings
  Cargo.lock
  components/script/dom/xrwebgllayer.rs
Labels: A-content/webgl, A-xr-zomg, S-awaiting-merge

#27338 Update webxr.
  Cargo.lock
Labels: S-awaiting-merge

#27329 Update GPUObjectBase webidl and cleanup valid flags
  Cargo.lock
  components/script/dom/gpubindgroup.rs
  components/script/dom/gpubindgrouplayout.rs
  components/script/dom/gpubuffer.rs
  components/script/dom/gpucommandbuffer.rs
  components/script/dom/gpucommandencoder.rs
  components/script/dom/gpucomputepassencoder.rs
  components/script/dom/gpucomputepipeline.rs
  components/script/dom/gpudevice.rs
  components/script/dom/gpupipelinelayout.rs
  components/script/dom/gpuqueue.rs
  components/script/dom/gpurenderpassencoder.rs
  components/script/dom/gpurenderpipeline.rs
  components/script/dom/gpusampler.rs
  components/script/dom/gpushadermodule.rs
  components/script/dom/gpuswapchain.rs
  components/script/dom/gputexture.rs
  components/script/dom/gputextureview.rs
  components/script/dom/webidls/GPUObjectBase.webidl
  components/webgpu/lib.rs
Labels: S-awaiting-merge

#27216 Implement core float layout for layout 2020
  Cargo.lock
  components/layout_2020/Cargo.toml
  components/layout_2020/flow/float.rs
  components/layout_2020/flow/mod.rs
  components/layout_2020/geom.rs
  components/layout_2020/lib.rs
  components/layout_2020/tests/floats.rs
  python/servo/testing_commands.py
  servo-tidy.toml
  tests/unit/style/parsing/mod.rs
Labels: S-awaiting-merge

#27313 Update XRWebGLLayer to match specification.
  components/script/dom/webidls/XRWebGLLayer.webidl
  components/script/dom/xrsession.rs
  components/script/dom/xrwebgllayer.rs
  tests/wpt/include.ini
  tests/wpt/metadata/webxr/ar-module/xrDevice_requestSession_immersive-ar.https.html.ini
  tests/wpt/metadata/webxr/ar-module/xrSession_environmentBlendMode.https.html.ini
  tests/wpt/metadata/webxr/dom-overlay/ar_dom_overlay.https.html.ini
  tests/wpt/metadata/webxr/events_input_source_recreation.https.html.ini
  tests/wpt/metadata/webxr/events_session_select.https.html.ini
  tests/wpt/metadata/webxr/events_session_select_subframe.https.html.ini
  tests/wpt/metadata/webxr/events_session_squeeze.https.html.ini
  tests/wpt/metadata/webxr/gamepads-module/xrInputSource_gamepad_input_registered.https.html.ini
  tests/wpt/metadata/webxr/getInputPose_handedness.https.html.ini
  tests/wpt/metadata/webxr/getInputPose_pointer.https.html.ini
  tests/wpt/metadata/webxr/hit-test/ar_hittest_subscription_refSpaces.https.html.ini
  tests/wpt/metadata/webxr/hit-test/ar_hittest_subscription_states_regular.https.html.ini
  tests/wpt/metadata/webxr/hit-test/ar_hittest_subscription_transientInputSources.https.html.ini
  tests/wpt/metadata/webxr/idlharness.https.window.js.ini
  tests/wpt/metadata/webxr/navigator_xr_sameObject.https.html.ini
  tests/wpt/metadata/webxr/render_state_vertical_fov_immersive.https.html.ini
  tests/wpt/metadata/webxr/render_state_vertical_fov_inline.https.html.ini
  tests/wpt/metadata/webxr/xrBoundedReferenceSpace_updates.https.html.ini
  tests/wpt/metadata/webxr/xrDevice_disconnect_ends.https.html.ini
  tests/wpt/metadata/webxr/xrDevice_requestSession_immersive.https.html.ini
  tests/wpt/metadata/webxr/xrDevice_requestSession_optionalFeatures.https.html.ini
  tests/wpt/metadata/webxr/xrFrame_getPose.https.html.ini
  tests/wpt/metadata/webxr/xrFrame_getViewerPose_getPose.https.html.ini
  tests/wpt/metadata/webxr/xrFrame_lifetime.https.html.ini
  tests/wpt/metadata/webxr/xrFrame_session_sameObject.https.html.ini
  tests/wpt/metadata/webxr/xrInputSource_add_remove.https.html.ini
  tests/wpt/metadata/webxr/xrInputSource_profiles.https.html.ini
  tests/wpt/metadata/webxr/xrInputSource_sameObject.https.html.ini
  tests/wpt/metadata/webxr/xrPose_transform_sameObject.https.html.ini
  tests/wpt/metadata/webxr/xrReferenceSpace_originOffset.https.html.ini
  tests/wpt/metadata/webxr/xrReferenceSpace_originOffsetBounded.https.html.ini
  tests/wpt/metadata/webxr/xrReferenceSpace_originOffset_viewer.https.html.ini
  tests/wpt/metadata/webxr/xrReferenceSpace_relationships.https.html.ini
  tests/wpt/metadata/webxr/xrRigidTransform_constructor.https.html.ini
  tests/wpt/metadata/webxr/xrRigidTransform_inverse.https.html.ini
  tests/wpt/metadata/webxr/xrRigidTransform_sameObject.https.html.ini
  tests/wpt/metadata/webxr/xrSession_cancelAnimationFrame.https.html.ini
  tests/wpt/metadata/webxr/xrSession_cancelAnimationFrame_invalidhandle.https.html.ini
  tests/wpt/metadata/webxr/xrSession_end.https.html.ini
  tests/wpt/metadata/webxr/xrSession_requestAnimationFrame_callback_calls.https.html.ini
  tests/wpt/metadata/webxr/xrSession_requestAnimationFrame_data_valid.https.html.ini
  tests/wpt/metadata/webxr/xrSession_requestAnimationFrame_getViewerPose.https.html.ini
  tests/wpt/metadata/webxr/xrSession_requestAnimationFrame_timestamp.https.html.ini
  tests/wpt/metadata/webxr/xrSession_requestReferenceSpace_features.https.html.ini
  tests/wpt/metadata/webxr/xrSession_sameObject.https.html.ini
  tests/wpt/metadata/webxr/xrSession_viewer_referenceSpace.https.html.ini
  tests/wpt/metadata/webxr/xrView_eyes.https.html.ini
  tests/wpt/metadata/webxr/xrView_match.https.html.ini
  tests/wpt/metadata/webxr/xrView_sameObject.https.html.ini
  tests/wpt/metadata/webxr/xrViewerPose_views_sameObject.https.html.ini
  tests/wpt/metadata/webxr/xrViewport_valid.https.html.ini
  tests/wpt/metadata/webxr/xrWebGLLayer_framebuffer_draw.https.html.ini
  tests/wpt/metadata/webxr/xrWebGLLayer_framebuffer_sameObject.https.html.ini
  tests/wpt/metadata/webxr/xrWebGLLayer_opaque_framebuffer.https.html.ini
  tests/wpt/metadata/webxr/xrWebGLLayer_viewports.https.html.ini
Labels: S-awaiting-merge

#27334 Handle flex item cross sizing and minmax for flexbox in 2020
  components/layout_2020/flexbox/layout.rs
  tests/wpt/metadata-layout-2020/css/css-flexbox/align-content-002.htm.ini
  tests/wpt/metadata-layout-2020/css/css-flexbox/align-content_flex-start.html.ini
  tests/wpt/metadata-layout-2020/css/css-flexbox/align-items-002.htm.ini
  tests/wpt/metadata-layout-2020/css/css-flexbox/align-self-001.html.ini
  tests/wpt/metadata-layout-2020/css/css-flexbox/align-self-007.html.ini
  tests/wpt/metadata-layout-2020/css/css-flexbox/align-self-013.html.ini
  tests/wpt/metadata-layout-2020/css/css-flexbox/dynamic-change-simplified-layout-002.html.ini
  tests/wpt/metadata-layout-2020/css/css-flexbox/fit-content-item-002.html.ini
  tests/wpt/metadata-layout-2020/css/css-flexbox/fit-content-item-003.html.ini
  tests/wpt/metadata-layout-2020/css/css-flexbox/fit-content-item-004.html.ini
  tests/wpt/metadata-layout-2020/css/css-flexbox/flex-001.htm.ini
  tests/wpt/metadata-layout-2020/css/css-flexbox/flex-002.htm.ini
  tests/wpt/metadata-layout-2020/css/css-flexbox/flex-003.htm.ini
  tests/wpt/metadata-layout-2020/css/css-flexbox/flex-004.htm.ini
  tests/wpt/metadata-layout-2020/css/css-flexbox/flex-basis-001.html.ini
  tests/wpt/metadata-layout-2020/css/css-flexbox/flex-basis-002.html.ini
  tests/wpt/metadata-layout-2020/css/css-flexbox/flex-basis-003.html.ini
  tests/wpt/metadata-layout-2020/css/css-flexbox/flex-basis-004.html.ini
  tests/wpt/metadata-layout-2020/css/css-flexbox/flex-basis-007.html.ini
  tests/wpt/metadata-layout-2020/css/css-flexbox/flex-basis-008.html.ini
  tests/wpt/metadata-layout-2020/css/css-flexbox/flex-box-wrap.html.ini
  tests/wpt/metadata-layout-2020/css/css-flexbox/flex-container-margin.html.ini
  tests/wpt/metadata-layout-2020/css/css-flexbox/flex-flow-002.html.ini
  tests/wpt/metadata-layout-2020/css/css-flexbox/flex-flow-003.html.ini
  tests/wpt/metadata-layout-2020/css/css-flexbox/flex-flow-005.html.ini
  tests/wpt/metadata-layout-2020/css/css-flexbox/flex-flow-006.html.ini
  tests/wpt/metadata-layout-2020/css/css-flexbox/flex-grow-002.html.ini
  tests/wpt/metadata-layout-2020/css/css-flexbox/flex-grow-004.html.ini
  tests/wpt/metadata-layout-2020/css/css-flexbox/flex-grow-006.html.ini
  tests/wpt/metadata-layout-2020/css/css-flexbox/flex-grow-007.html.ini
  tests/wpt/metadata-layout-2020/css/css-flexbox/flex-shrink-001.html.ini
  tests/wpt/metadata-layout-2020/css/css-flexbox/flex-shrink-002.html.ini
  tests/wpt/metadata-layout-2020/css/css-flexbox/flex-shrink-003.html.ini
  tests/wpt/metadata-layout-2020/css/css-flexbox/flex-shrink-004.html.ini
  tests/wpt/metadata-layout-2020/css/css-flexbox/flex-shrink-005.html.ini
  tests/wpt/metadata-layout-2020/css/css-flexbox/flex-shrink-006.html.ini
  tests/wpt/metadata-layout-2020/css/css-flexbox/flex-shrink-007.html.ini
  tests/wpt/metadata-layout-2020/css/css-flexbox/flex-shrink-008.html.ini
  tests/wpt/metadata-layout-2020/css/css-flexbox/flex-wrap-006.html.ini
  tests/wpt/metadata-layout-2020/css/css-flexbox/flexbox-flex-wrap-flexing.html.ini
  tests/wpt/metadata-layout-2020/css/css-flexbox/flexbox_align-content-flexstart.html.ini
  tests/wpt/metadata-layout-2020/css/css-flexbox/flexbox_box-clear.html.ini
  tests/wpt/metadata-layout-2020/css/css-flexbox/flexbox_fbfc.html.ini
  tests/wpt/metadata-layout-2020/css/css-flexbox/flexible-box-float.html.ini
  tests/wpt/metadata-layout-2020/css/css-flexbox/layout-algorithm_algo-cross-line-001.html.ini
  tests/wpt/metadata-layout-2020/css/css-flexbox/order-painting.html.ini
  tests/wpt/metadata-layout-2020/css/css-flexbox/overflow-area-001.html.ini
  tests/wpt/metadata-layout-2020/css/css-flexbox/overflow-area-002.html.ini
  tests/wpt/metadata-layout-2020/css/css-flexbox/table-as-item-change-cell.html.ini
Labels: S-tests-failed

#27304 UWP: non random port for devtools, and support for custom UWP prefs
  Cargo.lock
  components/config/opts.rs
  components/config/prefs.rs
  components/devtools/Cargo.toml
  components/servo/lib.rs
  ports/libsimpleservo/api/Cargo.toml
  ports/libsimpleservo/api/build.rs
  ports/libsimpleservo/api/src/lib.rs
  ports/libsimpleservo/capi/src/lib.rs
  resources/package-prefs.json
  resources/prefs.json
  support/hololens/ServoApp/DefaultUrl.h
  support/hololens/ServoApp/ServoControl/Servo.cpp
  support/hololens/ServoApp/ServoControl/Servo.h
  support/hololens/ServoApp/ServoControl/ServoControl.cpp
Labels: S-awaiting-merge

#27343 Update mozjs
  Cargo.lock
Labels: S-awaiting-merge

#27348 Implement GPUCommandEncoder.copy commands
  components/script/dom/gpucommandencoder.rs
  components/script/dom/gpudevice.rs
  components/script/dom/gpuqueue.rs
  components/script/dom/webidls/GPUCommandEncoder.webidl
  components/script/dom/webidls/GPUTexture.webidl
  components/webgpu/lib.rs
Labels: S-awaiting-merge

#27333 Include gstreamer plugins in macOS nightly package.
  etc/ci/macos_package_smoketest.sh
  etc/taskcluster/decision_task.py
  python/servo/package_commands.py
Labels: S-awaiting-merge

#26710 Compile external scripts off the main thread
  components/config/prefs.rs
  components/script/devtools.rs
  components/script/dom/bindings/trace.rs
  components/script/dom/globalscope.rs
  components/script/dom/htmlscriptelement.rs
  components/script/dom/userscripts.rs
  resources/prefs.json
  tests/wpt/metadata/custom-elements/customized-built-in-constructor-exceptions.html.ini
Labels: S-awaiting-merge

#27368 Use backtrace fork with UWP-specific fix.
  Cargo.lock
  Cargo.toml
Labels: S-awaiting-merge

#27365 Fixes for off-thread compilation of scripts
  components/script/dom/globalscope.rs
  components/script/dom/htmlscriptelement.rs
Labels: S-awaiting-merge

#27362 Fix nightly smoketest.
  etc/taskcluster/decision_task.py
Labels: S-awaiting-merge

#27325 Fire sessionavailable
  support/hololens/ServoApp/ServoControl/Servo.cpp
  support/hololens/ServoApp/ServoControl/Servo.h
  support/hololens/ServoApp/ServoControl/ServoControl.cpp
Labels: S-awaiting-merge

#27372 Add libxcb dependencies to README and bootstrap.py
  README.md
  python/servo/bootstrap.py
Labels: S-awaiting-merge

#27382 Fix nightly smoketest
  etc/taskcluster/decision_task.py
Labels: S-awaiting-merge

#27373 Updated webxr
  Cargo.lock
Labels: S-awaiting-merge

#27376 Use the size of the containing block, not the size of the block formatting context, to place floats in layout 2020.
  components/layout_2020/flow/float.rs
  components/layout_2020/flow/mod.rs
  components/layout_2020/tests/floats.rs
Labels: S-awaiting-merge

#27377 Handle apostrophes for whatwg URL tidy check
  python/tidy/servo_tidy/tidy.py
Labels: S-awaiting-merge

#27386 Added debian gstreamer packages to README
  README.md
Labels: A-content/media, A-documentation, S-awaiting-merge

#27396 Avoid crashing when no homepage preference is set.
  support/hololens/ServoApp/DefaultUrl.h
  support/hololens/ServoApp/ServoControl/Servo.cpp
Labels: S-awaiting-merge

#27385 Add Layout 2020 support for `display: list-item`
  components/layout_2020/dom_traversal.rs
  components/layout_2020/flow/construct.rs
  components/layout_2020/formatting_contexts.rs
  components/layout_2020/lib.rs
  components/layout_2020/lists.rs
  components/layout_2020/style_ext.rs
  components/style/properties/longhands/list.mako.rs
  components/style/properties/shorthands/list.mako.rs
  components/style/values/generics/counters.rs
  components/style/values/specified/box.rs
  components/style/values/specified/counters.rs
  tests/wpt/metadata-layout-2020/css/CSS2/generated-content/content-counter-001.xht.ini
  tests/wpt/metadata-layout-2020/css/CSS2/generated-content/multiple-content-values-001.xht.ini
  tests/wpt/metadata-layout-2020/css/CSS2/linebox/inline-negative-margin-001.html.ini
  tests/wpt/metadata-layout-2020/css/CSS2/lists/list-style-019.xht.ini
  tests/wpt/metadata-layout-2020/css/CSS2/margin-padding-clear/padding-left-applies-to-010.xht.ini
  tests/wpt/metadata-layout-2020/css/CSS2/syntax/characters-0080-009F-001.xht.ini
  tests/wpt/metadata-layout-2020/css/cssom/cssom-setProperty-shorthand.html.ini
  tests/wpt/metadata-layout-2020/css/cssom/serialize-values.html.ini
  tests/wpt/mozilla/meta-layout-2020/css/get-computed-style-for-url.html.ini
  tests/wpt/mozilla/meta-layout-2020/css/list_style_image_sizing_a.html.ini
  tests/wpt/mozilla/meta-layout-2020/css/list_style_position_a.html.ini
  tests/wpt/mozilla/meta-layout-2020/css/list_style_type_a.html.ini
Labels: A-layout/2020, S-awaiting-merge

#27391 Fix nightly smoketest again.
  etc/taskcluster/decision_task.py
Labels: S-awaiting-merge

#27393 Remove unit test that triggers frequent intermittent failure.
  components/net/tests/http_loader.rs
Labels: S-awaiting-merge

#27335 Update to 7/20 nightly rustc.
  components/script_plugins/lib.rs
  rust-toolchain
Labels: S-awaiting-merge

#27405 Update user agent strings
  components/servo/lib.rs
Labels: S-awaiting-merge

#27403 Add more gstreamer plugins to nightly builds.
  etc/taskcluster/decision_task.py
  python/servo/build_commands.py
  python/servo/gstreamer.py
Labels: S-awaiting-merge

#27418 Move secondary view support into a pref
  Cargo.lock
  components/config/prefs.rs
  components/script/dom/xrsystem.rs
  ports/libsimpleservo/api/src/lib.rs
  resources/prefs.json
Labels: S-awaiting-merge

#27417 Make reload button clear the network cache.
  components/compositing/lib.rs
  components/compositing/windowing.rs
  components/constellation/constellation.rs
  components/net/http_cache.rs
  components/net/resource_thread.rs
  components/net_traits/lib.rs
  components/servo/lib.rs
  ports/libsimpleservo/api/src/lib.rs
  ports/libsimpleservo/capi/src/lib.rs
  support/hololens/ServoApp/ServoControl/Servo.h
Labels: S-tests-failed

#27420 Removed unnecessary conversion from UTF-8 to UTF-16
  components/script/dom/htmlscriptelement.rs
  components/script/script_module.rs
Labels: S-awaiting-merge

#27426 Update webxr
  Cargo.lock
Labels: S-awaiting-merge

#27428 Fixed usage of wrong delete
  support/hololens/ServoApp/strutils.h
Labels: S-awaiting-merge

#27443 console.clear implemented
  components/devtools/actors/console.rs
  components/devtools_traits/lib.rs
  components/script/dom/console.rs
  components/script/dom/webidls/Console.webidl
Labels: S-awaiting-merge

#27445 Update packaged UWP gstreamer plugins.
  support/hololens/ServoApp/ServoApp.vcxproj
  support/hololens/ServoApp/ServoApp.vcxproj.filters
Labels: S-awaiting-merge

#27429 Add a pref to indicate user intent to enter webxr
  components/config/prefs.rs
  components/script/dom/xrsystem.rs
  ports/gstplugin/servowebsrc.rs
  resources/prefs.json
Labels: A-xr-zomg, S-awaiting-merge

#27448 Don't delete GL textures created by WebXR
  components/script/dom/webgltexture.rs
  components/script/dom/xrwebgllayer.rs
Labels: A-content/webgl, A-xr-zomg, S-awaiting-merge

#27449 Gstreamer plugin README edits
  ports/gstplugin/README.md
Labels: S-awaiting-merge

#27447 Refactor and improve GPUErrorScopes
  Cargo.lock
  components/script/dom/bindings/trace.rs
  components/script/dom/globalscope.rs
  components/script/dom/gpucommandencoder.rs
  components/script/dom/gpudevice.rs
  components/script/dom/gpurenderbundleencoder.rs
  components/script/dom/gputexture.rs
  components/script/dom/webidls/GPUTextureView.webidl
  components/webgpu/identity.rs
  components/webgpu/lib.rs
  servo-tidy.toml
Labels: S-awaiting-merge

#27456 Get the gstreamer plugin to stream Hubs rooms
  ports/gstplugin/README.md
  ports/gstplugin/servowebsrc.rs
Labels: A-xr-zomg, P-gst-plugin, S-awaiting-merge

#26607 Use ExtendableMessageEvent for messageerror in service workers #25241
  components/script/dom/extendablemessageevent.rs
  components/script/dom/serviceworkerglobalscope.rs
  components/script/dom/webidls/ExtendableMessageEvent.webidl
Labels: S-awaiting-merge

#27413 Fire mouseenter and mouseleave events
  components/compositing/compositor.rs
  components/script/dom/document.rs
  components/script/dom/node.rs
  components/script/dom/range.rs
  components/script_traits/lib.rs
  tests/html/test_mouse_events_order_1.html
  tests/html/test_mouse_events_order_2.html
  tests/html/test_mouse_events_order_3.html
Labels: S-awaiting-merge

#27207 Update various dependencies
  Cargo.lock
  Cargo.toml
  components/canvas/Cargo.toml
  components/compositing/Cargo.toml
  components/gfx/Cargo.toml
  components/gfx/text/shaping/harfbuzz.rs
  components/layout/Cargo.toml
  components/layout/text.rs
  components/layout_2020/Cargo.toml
  components/servo/Cargo.toml
  python/tidy/servo_tidy/tidy.py
  servo-tidy.toml
  tests/wpt/metadata/css/css-paint-api/background-image-tiled.https.html.ini
Labels: S-awaiting-merge

#27466 Do not instanciate random ServoControls
  support/hololens/ServoApp/BrowserPage.cpp
  support/hololens/ServoApp/BrowserPage.xaml
Labels: S-awaiting-merge
