Repository servo/servo, pull requests merged in 2020-03, with the labels that each got.

#25862 Have transforms and filters be CBs for all descendants in layout_2020
  components/layout_2020/display_list/mod.rs
  components/layout_2020/display_list/stacking_context.rs
  components/layout_2020/flow/mod.rs
  components/layout_2020/flow/root.rs
  components/layout_2020/positioned.rs
  components/layout_2020/style_ext.rs
  tests/wpt/metadata-layout-2020/css/css-transforms/preserve3d-button.html.ini
  tests/wpt/metadata-layout-2020/css/css-transforms/transform-abspos-001.html.ini
  tests/wpt/metadata-layout-2020/css/css-transforms/transform-abspos-002.html.ini
  tests/wpt/metadata-layout-2020/css/css-transforms/transform-abspos-003.html.ini
  tests/wpt/metadata-layout-2020/css/css-transforms/transform-abspos-004.html.ini
  tests/wpt/metadata-layout-2020/css/css-transforms/transform-abspos-006.html.ini
  tests/wpt/metadata-layout-2020/css/css-transforms/transform-abspos-007.html.ini
  tests/wpt/metadata-layout-2020/css/filter-effects/filtered-inline-is-container.html.ini
  tests/wpt/mozilla/meta-layout-2020/css/transform_stacking_context_a.html.ini
  tests/wpt/mozilla/meta-layout-2020/css/translate_clip_nested.html.ini
Labels: A-layout/2020, S-awaiting-merge

#25781 Introduce a new type MaybeUnreflectedDom<T> (fixes #25701)
  components/domobject_derive/lib.rs
  components/script/dom/bindings/codegen/CodegenRust.py
  components/script/dom/bindings/reflector.rs
  components/script/dom/bindings/root.rs
  components/script/dom/bindings/trace.rs
  components/script/dom/promise.rs
  components/script/dom/windowproxy.rs
  components/script/lib.rs
Labels: S-awaiting-merge

#25877 Disable Android CI builds
  etc/taskcluster/decision_task.py
Labels: S-awaiting-merge

#25876 Upgrade mime crate to use the essence function
  Cargo.lock
  components/script/script_module.rs
Labels: S-awaiting-merge

#25879 Remove broken thumbprint.
  support/hololens/ServoApp/ServoApp.vcxproj
Labels: S-awaiting-merge

#25867 Make CanvasRenderingContext2D.fillRect() draw patterns correctly
  components/canvas/canvas_data.rs
  components/canvas/raqote_backend.rs
  tests/wpt/metadata/2dcontext/fill-and-stroke-styles/2d.pattern.paint.norepeat.coord3.html.ini
  tests/wpt/metadata/2dcontext/fill-and-stroke-styles/2d.pattern.paint.repeatx.coord1.html.ini
  tests/wpt/metadata/2dcontext/fill-and-stroke-styles/2d.pattern.paint.repeaty.coord1.html.ini
Labels: S-awaiting-merge

#25798 Add support for WebGL2 framebuffer invalidation
  Cargo.lock
  components/canvas/Cargo.toml
  components/canvas/webgl_thread.rs
  components/canvas_traits/webgl.rs
  components/script/dom/webgl2renderingcontext.rs
  components/script/dom/webidls/WebGL2RenderingContext.webidl
  tests/wpt/webgl/meta/conformance2/context/methods-2.html.ini
  tests/wpt/webgl/meta/conformance2/extensions/webgl_multiview.html.ini
  tests/wpt/webgl/meta/conformance2/state/gl-get-calls.html.ini
  tests/wpt/webgl/meta/conformance2/state/gl-object-get-calls.html.ini
Labels: S-awaiting-merge

#25886 Sync WPT with upstream (03-03-2020)
  tests/wpt/metadata/FileAPI/url/url-in-tags-revoke.window.js.ini
  tests/wpt/metadata/css/CSS2/floats/hit-test-floats-002.html.ini
  tests/wpt/metadata/css/CSS2/floats/hit-test-floats-004.html.ini
  tests/wpt/metadata/css/CSS2/floats/hit-test-floats-005.html.ini
  tests/wpt/metadata/css/css-transforms/transform-scale-hittest.html.ini
  tests/wpt/metadata/css/cssom-view/MediaQueryList-addListener-removeListener.html.ini
  tests/wpt/metadata/css/cssom-view/elementsFromPoint-iframes.html.ini
  tests/wpt/metadata/css/cssom-view/elementsFromPoint-invalid-cases.html.ini
  tests/wpt/metadata/fetch/content-type/response.window.js.ini
  tests/wpt/metadata/fetch/content-type/script.window.js.ini
  tests/wpt/metadata/fetch/nosniff/parsing-nosniff.window.js.ini
  tests/wpt/metadata/html/browsers/history/the-history-interface/traverse_the_history_1.html.ini
  tests/wpt/metadata/html/browsers/history/the-history-interface/traverse_the_history_3.html.ini
  tests/wpt/metadata/html/browsers/history/the-history-interface/traverse_the_history_5.html.ini
  tests/wpt/metadata/html/semantics/embedded-content/the-iframe-element/iframe_sandbox_popups_nonescaping-3.html.ini
  tests/wpt/metadata/html/semantics/embedded-content/the-img-element/image-loading-lazy-crossorigin-change.sub.html.ini
  tests/wpt/metadata/webaudio/the-audio-api/the-analysernode-interface/realtimeanalyser-fft-scaling.html.ini
  tests/wpt/metadata/webaudio/the-audio-api/the-audiobuffersourcenode-interface/audiobuffersource-multi-channels.html.ini
  tests/wpt/metadata/webaudio/the-audio-api/the-audiobuffersourcenode-interface/sub-sample-buffer-stitching.html.ini
  tests/wpt/metadata/webmessaging/without-ports/017.html.ini
  tests/wpt/metadata/workers/semantics/multiple-workers/005.html.ini
  tests/wpt/web-platform-tests/css/css-grid/placement/grid-placement-using-named-grid-lines-003.html
  tests/wpt/web-platform-tests/html/rendering/non-replaced-elements/the-page/iframe-scrolling-attribute-ref.html
  tests/wpt/web-platform-tests/html/rendering/non-replaced-elements/the-page/iframe-scrolling-attribute.html
  tests/wpt/web-platform-tests/html/semantics/embedded-content/the-img-element/image-loading-lazy-crossorigin-change.sub.html
  tests/wpt/web-platform-tests/html/semantics/embedded-content/the-img-element/original-crossorigin-applied.sub.html
  tests/wpt/web-platform-tests/payment-handler/app-respond-with-minimal-ui.js
  tests/wpt/web-platform-tests/payment-request/rejects_if_not_active-manual.https.html
  tests/wpt/web-platform-tests/portals/about-blank-cannot-host.html
  tests/wpt/web-platform-tests/portals/portal-activate-data.html
  tests/wpt/web-platform-tests/portals/portals-activate-inside-iframe.html
  tests/wpt/web-platform-tests/resources/testharness.js
  tests/wpt/web-platform-tests/scroll-animations/scroll-timeline-phases.tentative.html
  tests/wpt/web-platform-tests/svg/styling/presentation-attributes-special-cases.html
  tests/wpt/web-platform-tests/svg/styling/presentation-attributes.js
  tests/wpt/web-platform-tests/tools/ci/pr_preview.py
  tests/wpt/web-platform-tests/tools/ci/tests/test_pr_preview.py
  tests/wpt/web-platform-tests/tools/wptrunner/wptrunner/formatters/chromium.py
  tests/wpt/web-platform-tests/tools/wptrunner/wptrunner/formatters/tests/test_chromium.py
  tests/wpt/web-platform-tests/url/resources/urltestdata.json
  tests/wpt/web-platform-tests/wake-lock/wakelock-active-document.https.window.js
  tests/wpt/web-platform-tests/web-animations/interfaces/DocumentTimeline/document-timeline-phases.tentative.html
  tests/wpt/web-platform-tests/webauthn/helpers.js
Labels: S-awaiting-merge

#25814 Add support for WebGL2 FramebufferTextureLayer
  Cargo.lock
  components/canvas/Cargo.toml
  components/canvas/webgl_limits.rs
  components/canvas/webgl_thread.rs
  components/canvas_traits/webgl.rs
  components/script/dom/webgl2renderingcontext.rs
  components/script/dom/webglframebuffer.rs
  components/script/dom/webidls/WebGL2RenderingContext.webidl
  tests/wpt/webgl/meta/conformance2/context/methods-2.html.ini
Labels: S-awaiting-merge, S-blocked-on-external

#25890 Sync WPT with upstream (04-03-2020)
  tests/wpt/metadata/FileAPI/url/url-in-tags-revoke.window.js.ini
  tests/wpt/metadata/css/CSS2/floats/hit-test-floats-002.html.ini
  tests/wpt/metadata/css/CSS2/floats/hit-test-floats-003.html.ini
  tests/wpt/metadata/css/CSS2/floats/hit-test-floats-004.html.ini
  tests/wpt/metadata/css/css-transitions/CSSTransition-effect.tentative.html.ini
  tests/wpt/metadata/css/css-transitions/KeyframeEffect-setKeyframes.tentative.html.ini
  tests/wpt/metadata/css/css-ui/outline-with-padding-001.html.ini
  tests/wpt/metadata/css/css-values/update-subpixel-rem-unit.html.ini
  tests/wpt/metadata/css/cssom-view/MediaQueryList-addListener-removeListener.html.ini
  tests/wpt/metadata/css/cssom-view/elementFromPoint-001.html.ini
  tests/wpt/metadata/css/cssom-view/elementsFromPoint-iframes.html.ini
  tests/wpt/metadata/css/cssom-view/elementsFromPoint-invalid-cases.html.ini
  tests/wpt/metadata/css/cssom/CSSStyleSheet-constructable-duplicate.html.ini
  tests/wpt/metadata/fetch/content-type/response.window.js.ini
  tests/wpt/metadata/fetch/content-type/script.window.js.ini
  tests/wpt/metadata/fetch/nosniff/parsing-nosniff.window.js.ini
  tests/wpt/metadata/html/browsers/history/the-history-interface/traverse_the_history_4.html.ini
  tests/wpt/metadata/html/browsers/history/the-history-interface/traverse_the_history_5.html.ini
  tests/wpt/metadata/html/interaction/focus/the-autofocus-attribute/skip-document-with-fragment.html.ini
  tests/wpt/metadata/html/rendering/replaced-elements/attributes-for-embedded-content-and-images/img-alt-crash-001.html.ini
  tests/wpt/metadata/webaudio/the-audio-api/the-audiobuffersourcenode-interface/audiobuffersource-multi-channels.html.ini
  tests/wpt/metadata/webaudio/the-audio-api/the-audiobuffersourcenode-interface/sub-sample-buffer-stitching.html.ini
  tests/wpt/metadata/workers/semantics/multiple-workers/005.html.ini
  tests/wpt/web-platform-tests/conformance-checkers/html/elements/input/autocomplete-address-novalid.html
  tests/wpt/web-platform-tests/conformance-checkers/html/elements/input/autocomplete-empty-novalid.html
  tests/wpt/web-platform-tests/conformance-checkers/html/elements/input/autocomplete-section-novalid.html
  tests/wpt/web-platform-tests/conformance-checkers/html/elements/input/autocomplete-text-isvalid.html
  tests/wpt/web-platform-tests/conformance-checkers/html/elements/input/autocomplete-token-novalid.html
  tests/wpt/web-platform-tests/conformance-checkers/html/elements/input/autocomplete-work-novalid.html
  tests/wpt/web-platform-tests/conformance-checkers/messages.json
  tests/wpt/web-platform-tests/conformance-checkers/select/autocomplete-address-novalid.html
  tests/wpt/web-platform-tests/conformance-checkers/select/autocomplete-empty-novalid.html
  tests/wpt/web-platform-tests/conformance-checkers/select/autocomplete-isvalid.html
  tests/wpt/web-platform-tests/conformance-checkers/select/autocomplete-section-novalid.html
  tests/wpt/web-platform-tests/conformance-checkers/select/autocomplete-token-novalid.html
  tests/wpt/web-platform-tests/conformance-checkers/select/autocomplete-work-novalid.html
  tests/wpt/web-platform-tests/conformance-checkers/textarea/autocomplete-address-novalid.html
  tests/wpt/web-platform-tests/conformance-checkers/textarea/autocomplete-empty-novalid.html
  tests/wpt/web-platform-tests/conformance-checkers/textarea/autocomplete-isvalid.html
  tests/wpt/web-platform-tests/conformance-checkers/textarea/autocomplete-section-novalid.html
  tests/wpt/web-platform-tests/conformance-checkers/textarea/autocomplete-token-novalid.html
  tests/wpt/web-platform-tests/conformance-checkers/textarea/autocomplete-work-novalid.html
  tests/wpt/web-platform-tests/css/css-transitions/CSSTransition-effect.tentative.html
  tests/wpt/web-platform-tests/css/css-transitions/KeyframeEffect-setKeyframes.tentative.html
  tests/wpt/web-platform-tests/css/css-ui/outline-with-padding-001.html
  tests/wpt/web-platform-tests/css/css-ui/reference/outline-with-padding-001-ref.html
  tests/wpt/web-platform-tests/css/css-values/update-subpixel-rem-unit.html
  tests/wpt/web-platform-tests/css/cssom/CSSStyleSheet-constructable-duplicate.html
  tests/wpt/web-platform-tests/html/rendering/replaced-elements/attributes-for-embedded-content-and-images/img-alt-crash-001.html
  tests/wpt/web-platform-tests/html/rendering/unmapped-attributes.html
  tests/wpt/web-platform-tests/tools/wpt/virtualenv.py
  tests/wpt/web-platform-tests/tools/wptrunner/wptrunner/wptcommandline.py
  tests/wpt/web-platform-tests/workers/modules/dedicated-worker-import-failure.html
  tests/wpt/web-platform-tests/workers/modules/dedicated-worker-parse-error-failure.html
  tests/wpt/web-platform-tests/workers/modules/resources/static-import-syntax-error.js
  tests/wpt/web-platform-tests/workers/modules/resources/syntax-error.js
Labels: S-awaiting-merge

#25898 Update to 3/4 nightly rustc.
  components/script/dom/baseaudiocontext.rs
  components/script/dom/broadcastchannel.rs
  components/script/dom/messageport.rs
  components/script/dom/rtcpeerconnection.rs
  components/script/dom/xrsession.rs
  components/script_plugins/lib.rs
  rust-toolchain
Labels: S-awaiting-merge

#25896 Remove unnecessary .clone() calls
  components/layout_thread/lib.rs
Labels: S-awaiting-merge

#25899 Disable devtools for HoloLens.
  support/hololens/ServoApp/ServoControl/Servo.cpp
Labels: S-awaiting-merge

#25902 Sync WPT with upstream (05-03-2020)
  tests/wpt/metadata/css/CSS2/floats/hit-test-floats-002.html.ini
  tests/wpt/metadata/css/CSS2/floats/hit-test-floats-004.html.ini
  tests/wpt/metadata/css/CSS2/floats/hit-test-floats-005.html.ini
  tests/wpt/metadata/css/css-animations/AnimationEffect-updateTiming.tentative.html.ini
  tests/wpt/metadata/css/css-animations/CSSAnimation-effect.tentative.html.ini
  tests/wpt/metadata/css/css-animations/CSSAnimation-pausing.tentative.html.ini
  tests/wpt/metadata/css/css-animations/KeyframeEffect-getKeyframes.tentative.html.ini
  tests/wpt/metadata/css/css-animations/KeyframeEffect-setKeyframes.tentative.html.ini
  tests/wpt/metadata/css/css-transitions/no-transition-from-ua-to-blocking-stylesheet.html.ini
  tests/wpt/metadata/css/css-values/round-function.html.ini
  tests/wpt/metadata/css/cssom-view/CaretPosition-001.html.ini
  tests/wpt/metadata/css/cssom-view/MediaQueryList-addListener-removeListener.html.ini
  tests/wpt/metadata/fetch/content-type/response.window.js.ini
  tests/wpt/metadata/fetch/content-type/script.window.js.ini
  tests/wpt/metadata/fetch/nosniff/parsing-nosniff.window.js.ini
  tests/wpt/metadata/html/browsers/history/the-history-interface/traverse_the_history_1.html.ini
  tests/wpt/metadata/html/browsers/history/the-history-interface/traverse_the_history_3.html.ini
  tests/wpt/metadata/html/interaction/focus/the-autofocus-attribute/skip-document-with-fragment.html.ini
  tests/wpt/metadata/webaudio/the-audio-api/the-audiobuffersourcenode-interface/audiobuffersource-multi-channels.html.ini
  tests/wpt/metadata/webaudio/the-audio-api/the-audiobuffersourcenode-interface/sub-sample-buffer-stitching.html.ini
  tests/wpt/metadata/webaudio/the-audio-api/the-audioworklet-interface/suspended-context-messageport.https.html.ini
  tests/wpt/web-platform-tests/IndexedDB/support.js
  tests/wpt/web-platform-tests/IndexedDB/transaction-scheduling-across-connections.any.js
  tests/wpt/web-platform-tests/IndexedDB/transaction-scheduling-across-databases.any.js
  tests/wpt/web-platform-tests/IndexedDB/transaction-scheduling-mixed-scopes.any.js
  tests/wpt/web-platform-tests/IndexedDB/transaction-scheduling-ordering.any.js
  tests/wpt/web-platform-tests/IndexedDB/transaction-scheduling-ro-waits-for-rw.any.js
  tests/wpt/web-platform-tests/IndexedDB/transaction-scheduling-rw-scopes.any.js
  tests/wpt/web-platform-tests/IndexedDB/transaction-scheduling-within-database.any.js
  tests/wpt/web-platform-tests/content-security-policy/nonce-hiding/nonces.html
  tests/wpt/web-platform-tests/css/css-animations/AnimationEffect-updateTiming.tentative.html
  tests/wpt/web-platform-tests/css/css-animations/CSSAnimation-effect.tentative.html
  tests/wpt/web-platform-tests/css/css-animations/CSSAnimation-pausing.tentative.html
  tests/wpt/web-platform-tests/css/css-animations/KeyframeEffect-getKeyframes.tentative.html
  tests/wpt/web-platform-tests/css/css-animations/KeyframeEffect-setKeyframes.tentative.html
  tests/wpt/web-platform-tests/css/css-animations/support/testcommon.js
  tests/wpt/web-platform-tests/css/css-values/round-function.html
  tests/wpt/web-platform-tests/css/support/numeric-testcommon.js
  tests/wpt/web-platform-tests/html/cross-origin-embedder-policy/dedicated-worker-cache-storage.https.html
  tests/wpt/web-platform-tests/html/cross-origin-embedder-policy/resources/dedicated-worker.js
  tests/wpt/web-platform-tests/html/cross-origin-embedder-policy/resources/universal-worker.js
  tests/wpt/web-platform-tests/html/cross-origin-embedder-policy/service-worker-cache-storage.https.html
  tests/wpt/web-platform-tests/interfaces/construct-stylesheets.idl
  tests/wpt/web-platform-tests/native-file-system/script-tests/FileSystemBaseHandle-IndexedDB.js
  tests/wpt/web-platform-tests/resources/chromium/nfc-mock.js
  tests/wpt/web-platform-tests/tools/wpt/revlist.py
  tests/wpt/web-platform-tests/web-nfc/resources/nfc-helpers.js
  tests/wpt/web-platform-tests/webaudio/the-audio-api/the-audioworklet-interface/suspended-context-messageport.https.html
  tests/wpt/web-platform-tests/webauthn/createcredential-badargs-authnrselection.https.html
  tests/wpt/web-platform-tests/webauthn/createcredential-badargs-rp.https.html
  tests/wpt/web-platform-tests/webauthn/createcredential-excludecredentials.https.html
  tests/wpt/web-platform-tests/webauthn/createcredential-extensions.https.html
  tests/wpt/web-platform-tests/webauthn/createcredential-pubkeycredparams.https.html
Labels: S-awaiting-merge

#25903 Improved the WebGL2 framebuffer render validation
  components/script/dom/webglframebuffer.rs
  tests/wpt/webgl/meta/conformance2/reading/read-pixels-from-rgb8-into-pbo-bug.html.ini
  tests/wpt/webgl/meta/conformance2/rendering/framebuffer-texture-changing-base-level.html.ini
Labels: S-awaiting-merge

#25678 Update SpiderMonkey
  Cargo.lock
  components/compositing/Cargo.toml
  components/config/prefs.rs
  components/script/Cargo.toml
  components/script/dom/bindings/codegen/CodegenRust.py
  components/script/dom/bindings/error.rs
  components/script/dom/bindings/interface.rs
  components/script/dom/bindings/namespace.rs
  components/script/dom/bindings/proxyhandler.rs
  components/script/dom/bindings/record.rs
  components/script/dom/bindings/structuredclone.rs
  components/script/dom/bindings/utils.rs
  components/script/dom/eventtarget.rs
  components/script/dom/globalscope.rs
  components/script/dom/promise.rs
  components/script/dom/webgl2renderingcontext.rs
  components/script/lib.rs
  components/script/script_module.rs
  components/script/script_runtime.rs
  components/script/webdriver_handlers.rs
  components/servo/Cargo.toml
  components/style/Cargo.toml
  components/webvr/Cargo.toml
  ports/glutin/Cargo.toml
  ports/libmlservo/Cargo.toml
  ports/libsimpleservo/capi/Cargo.toml
  resources/prefs.json
  tests/wpt/metadata/html/infrastructure/safe-passing-of-structured-data/structured_clone_bigint.html.ini
  tests/wpt/metadata/html/semantics/scripting-1/the-script-element/css-module/css-module-worker-test.html.ini
  tests/wpt/metadata/html/semantics/scripting-1/the-script-element/module/inactive-context-import.html.ini
  tests/wpt/mozilla/meta-layout-2020/mozilla/localeCompare.html.ini
  tests/wpt/mozilla/meta/MANIFEST.json
  tests/wpt/mozilla/meta/mozilla/localeCompare.html.ini
  tests/wpt/mozilla/tests/mozilla/interfaces.js
Labels: S-awaiting-merge

#25911 Revert 3/4 nightly rustc upgrade
  components/script/dom/baseaudiocontext.rs
  components/script/dom/broadcastchannel.rs
  components/script/dom/messageport.rs
  components/script/dom/rtcpeerconnection.rs
  components/script/dom/xrsession.rs
  components/script_plugins/lib.rs
  rust-toolchain
Labels: S-awaiting-merge

#25918 Don't compare vtable pointers anymore
  components/script/dom/bindings/codegen/CodegenRust.py
  components/script/dom/bindings/root.rs
  components/script/dom/bindings/trace.rs
Labels: S-awaiting-merge

#25915 Add support for WebGL2 GetFragDataLocation
  Cargo.lock
  components/canvas/Cargo.toml
  components/canvas/webgl_thread.rs
  components/canvas_traits/webgl.rs
  components/script/dom/webgl2renderingcontext.rs
  components/script/dom/webglprogram.rs
  components/script/dom/webidls/WebGL2RenderingContext.webidl
  tests/wpt/webgl/meta/conformance2/context/methods-2.html.ini
  tests/wpt/webgl/meta/conformance2/programs/gl-get-frag-data-location.html.ini
Labels: S-awaiting-merge

#25914 Stop embedder calls and fake rAF when window not visible
  components/compositing/compositor.rs
  components/script/dom/document.rs
  components/script/dom/window.rs
Labels: S-awaiting-merge

#25925 Properly sign UWP package
  etc/taskcluster/decision_task.py
  python/servo/package_commands.py
  support/hololens/ServoApp/Package.appxmanifest
  support/hololens/ServoApp/ServoApp.vcxproj
  support/hololens/ServoApp/ServoApp.vcxproj.filters
  support/hololens/ServoApp/ServoApp_TemporaryKey.pfx
  support/hololens/package.msbuild
Labels: S-awaiting-merge

#25855 Remove GL->d3d blit in HoloLens immersive mode
  Cargo.lock
  components/canvas/Cargo.toml
  components/canvas/lib.rs
  components/canvas/webgl_mode/inprocess.rs
  components/canvas/webgl_thread.rs
  components/canvas_traits/webgl.rs
  components/canvas_traits/webgl_channel/mod.rs
  components/canvas_traits/webgl_channel/mpsc.rs
  components/compositing/Cargo.toml
  components/compositing/windowing.rs
  components/script/dom/webglframebuffer.rs
  components/script/dom/webglrenderingcontext.rs
  components/script/dom/xrsession.rs
  components/servo/lib.rs
  ports/glutin/embedder.rs
  ports/libsimpleservo/api/src/lib.rs
  tests/wpt/webgl/meta/conformance2/uniforms/incompatible-texture-type-for-sampler.html.ini
Labels: S-awaiting-merge, S-blocked-on-external

#25837 Remove XR canvas dirtying step.
  Cargo.lock
  components/script/dom/xrsession.rs
Labels: S-awaiting-merge, S-blocked-on-external

#25930 Add support for WebGL2 GetIndexedParameter
  components/script/dom/webgl2renderingcontext.rs
  components/script/dom/webidls/WebGL2RenderingContext.webidl
  tests/wpt/webgl/meta/conformance2/buffers/bound-buffer-size-change-test.html.ini
  tests/wpt/webgl/meta/conformance2/buffers/buffer-overflow-test.html.ini
  tests/wpt/webgl/meta/conformance2/context/methods-2.html.ini
  tests/wpt/webgl/meta/conformance2/transform_feedback/switching-objects.html.ini
  tests/wpt/webgl/meta/conformance2/transform_feedback/transform_feedback.html.ini
Labels: S-awaiting-merge

#25942 Update surfman-chains multi branch
  Cargo.lock
  ports/gstplugin/servowebsrc.rs
Labels: A-build, S-awaiting-merge

#25943 Add cert scope to UWP nightly build task.
  etc/taskcluster/decision_task.py
Labels: S-awaiting-merge

#25939 Update to 3/4 nightly rustc.
  components/script/dom/baseaudiocontext.rs
  components/script/dom/broadcastchannel.rs
  components/script/dom/messageport.rs
  components/script/dom/rtcpeerconnection.rs
  components/script/dom/xrsession.rs
  components/script_plugins/lib.rs
  rust-toolchain
Labels: S-awaiting-merge

#25946 Update mozjs for macOS 10.15 build fix.
  Cargo.lock
  components/script/Cargo.toml
Labels: S-awaiting-merge

#25948 Accept only connected attributes for checkbox and radio activation behavior
  components/script/dom/htmlinputelement.rs
  tests/wpt/metadata/dom/events/Event-dispatch-detached-input-and-change.html.ini
Labels: S-awaiting-merge

#25904 Add support for some more WebGL2 renderbuffer functions
  components/canvas/webgl_thread.rs
  components/canvas_traits/webgl.rs
  components/script/dom/webgl2renderingcontext.rs
  components/script/dom/webglrenderbuffer.rs
  components/script/dom/webglrenderingcontext.rs
  components/script/dom/webidls/WebGL2RenderingContext.webidl
  tests/wpt/webgl/meta/conformance2/context/methods-2.html.ini
  tests/wpt/webgl/meta/conformance2/renderbuffers/invalidate-framebuffer.html.ini
  tests/wpt/webgl/meta/conformance2/renderbuffers/multisampled-depth-renderbuffer-initialization.html.ini
  tests/wpt/webgl/meta/conformance2/renderbuffers/multisampled-renderbuffer-initialization.html.ini
  tests/wpt/webgl/meta/conformance2/renderbuffers/multisampled-stencil-renderbuffer-initialization.html.ini
  tests/wpt/webgl/meta/conformance2/rendering/blitframebuffer-multisampled-readbuffer.html.ini
  tests/wpt/webgl/meta/conformance2/rendering/blitframebuffer-resolve-to-back-buffer.html.ini
  tests/wpt/webgl/meta/conformance2/rendering/line-rendering-quality.html.ini
  tests/wpt/webgl/meta/conformance2/rendering/rgb-format-support.html.ini
  tests/wpt/webgl/meta/conformance2/state/gl-object-get-calls.html.ini
Labels: S-awaiting-merge, S-blocked-on-external

#25945 layout_2020: Paint hoisted positioned fragments in tree order
  Cargo.lock
  components/layout_2020/Cargo.toml
  components/layout_2020/display_list/mod.rs
  components/layout_2020/display_list/stacking_context.rs
  components/layout_2020/flow/inline.rs
  components/layout_2020/flow/mod.rs
  components/layout_2020/flow/root.rs
  components/layout_2020/fragments.rs
  components/layout_2020/lib.rs
  components/layout_2020/positioned.rs
  components/layout_2020/style_ext.rs
  tests/wpt/metadata-layout-2020/css/CSS2/backgrounds/background-intrinsic-010.xht.ini
  tests/wpt/metadata-layout-2020/css/CSS2/borders/border-005.xht.ini
  tests/wpt/metadata-layout-2020/css/CSS2/borders/border-006.xht.ini
  tests/wpt/metadata-layout-2020/css/CSS2/borders/border-008.xht.ini
  tests/wpt/metadata-layout-2020/css/CSS2/csswg-issues/submitted/css2.1/anonymous-boxes-001.xht.ini
  tests/wpt/metadata-layout-2020/css/CSS2/floats/hit-test-floats-005.html.ini
  tests/wpt/metadata-layout-2020/css/CSS2/margin-padding-clear/margin-bottom-103.xht.ini
  tests/wpt/metadata-layout-2020/css/CSS2/margin-padding-clear/margin-bottom-104.xht.ini
  tests/wpt/metadata-layout-2020/css/CSS2/positioning/abspos-028.xht.ini
  tests/wpt/metadata-layout-2020/css/CSS2/positioning/top-019.xht.ini
  tests/wpt/metadata-layout-2020/css/CSS2/positioning/top-020.xht.ini
  tests/wpt/metadata-layout-2020/css/CSS2/positioning/top-031.xht.ini
  tests/wpt/metadata-layout-2020/css/CSS2/positioning/top-032.xht.ini
  tests/wpt/metadata-layout-2020/css/CSS2/positioning/top-043.xht.ini
  tests/wpt/metadata-layout-2020/css/CSS2/positioning/top-044.xht.ini
  tests/wpt/metadata-layout-2020/css/CSS2/positioning/top-055.xht.ini
  tests/wpt/metadata-layout-2020/css/CSS2/positioning/top-056.xht.ini
  tests/wpt/metadata-layout-2020/css/CSS2/positioning/top-067.xht.ini
  tests/wpt/metadata-layout-2020/css/CSS2/positioning/top-068.xht.ini
  tests/wpt/metadata-layout-2020/css/CSS2/positioning/top-079.xht.ini
  tests/wpt/metadata-layout-2020/css/CSS2/positioning/top-080.xht.ini
  tests/wpt/metadata-layout-2020/css/CSS2/positioning/top-103.xht.ini
  tests/wpt/metadata-layout-2020/css/CSS2/positioning/top-104.xht.ini
  tests/wpt/metadata-layout-2020/css/CSS2/positioning/top-113.xht.ini
  tests/wpt/metadata-layout-2020/css/CSS2/visudet/line-height-202.html.ini
  tests/wpt/metadata-layout-2020/css/CSS2/visudet/line-height-203.html.ini
  tests/wpt/metadata-layout-2020/css/CSS2/visudet/line-height-204.html.ini
  tests/wpt/metadata-layout-2020/css/css-transforms/preserve3d-button.html.ini
  tests/wpt/mozilla/meta-layout-2020/css/absolute_z_index_auto_paint_order_a.html.ini
  tests/wpt/mozilla/meta-layout-2020/css/opacity_stacking_context_a.html.ini
Labels: A-layout/2020, A-layout/block, S-awaiting-merge

#25941 Add support for launching devtools server on random port
  components/config/opts.rs
  components/devtools/lib.rs
  components/embedder_traits/lib.rs
  ports/glutin/browser.rs
  ports/libmlservo/src/lib.rs
  ports/libsimpleservo/api/src/lib.rs
  ports/libsimpleservo/capi/src/lib.rs
  ports/libsimpleservo/jniapi/src/lib.rs
  support/hololens/ServoApp/ServoControl/Servo.cpp
  support/hololens/ServoApp/ServoControl/Servo.h
Labels: S-awaiting-merge

#25905 Add support for WebGL2 read and draw buffer settings
  components/canvas/webgl_thread.rs
  components/canvas_traits/webgl.rs
  components/script/dom/webgl2renderingcontext.rs
  components/script/dom/webglframebuffer.rs
  components/script/dom/webglrenderingcontext.rs
  components/script/dom/webidls/WebGL2RenderingContext.webidl
  tests/wpt/webgl/meta/conformance2/context/methods-2.html.ini
  tests/wpt/webgl/meta/conformance2/renderbuffers/readbuffer.html.ini
  tests/wpt/webgl/meta/conformance2/rendering/blitframebuffer-srgb-and-linear-drawbuffers.html.ini
  tests/wpt/webgl/meta/conformance2/rendering/clear-func-buffer-type-match.html.ini
  tests/wpt/webgl/meta/conformance2/rendering/draw-buffers.html.ini
  tests/wpt/webgl/meta/conformance2/rendering/framebuffer-completeness-unaffected.html.ini
  tests/wpt/webgl/meta/conformance2/rendering/fs-color-type-mismatch-color-buffer-type.html.ini
  tests/wpt/webgl/meta/conformance2/rendering/read-draw-when-missing-image.html.ini
  tests/wpt/webgl/meta/conformance2/rendering/rendering-sampling-feedback-loop.html.ini
  tests/wpt/webgl/meta/conformance2/state/gl-get-calls.html.ini
  tests/wpt/webgl/meta/conformance2/state/gl-object-get-calls.html.ini
Labels: S-awaiting-merge

#25967 Re-enabling devtools on UWP
  support/hololens/ServoApp/BrowserPage.cpp
  support/hololens/ServoApp/ServoControl/Servo.cpp
  support/hololens/ServoApp/ServoControl/Servo.h
  support/hololens/ServoApp/ServoControl/ServoControl.cpp
  support/hololens/ServoApp/ServoControl/ServoControl.h
  support/hololens/ServoApp/pch.h
Labels: S-awaiting-merge

#25970 Update rustc to 3/16 nightly.
  components/script_plugins/lib.rs
  rust-toolchain
Labels: S-awaiting-merge

#25972 Disable running windows binaries on CI.
  etc/taskcluster/decision_task.py
Labels: S-awaiting-merge

#25975 Do not try to read pixels from an FBO without read buffer
  components/script/dom/webgl2renderingcontext.rs
  tests/wpt/webgl/meta/conformance2/renderbuffers/readbuffer.html.ini
Labels: S-awaiting-merge

#25964 Update the WebIDL parser
  components/script/dom/bindings/codegen/CodegenRust.py
  components/script/dom/bindings/codegen/parser/WebIDL.py
  components/script/dom/bindings/codegen/parser/ext-attribute-no-value-error.patch
  components/script/dom/bindings/codegen/parser/tests/test_attributes_on_types.py
  components/script/dom/bindings/codegen/parser/tests/test_constructor.py
  components/script/dom/bindings/codegen/parser/tests/test_date.py
  components/script/dom/bindings/codegen/parser/tests/test_distinguishability.py
  components/script/dom/bindings/codegen/parser/tests/test_extended_attributes.py
  components/script/dom/bindings/codegen/parser/tests/test_nullable_equivalency.py
  components/script/dom/bindings/codegen/parser/tests/test_toJSON.py
  components/script/dom/bindings/codegen/parser/update.sh
Labels: S-awaiting-merge

#25957 Start using `AtomicRefCell` in layout 2020 as preparation for incremental layout
  Cargo.lock
  components/layout_2020/Cargo.toml
  components/layout_2020/cell.rs
  components/layout_2020/dom_traversal.rs
  components/layout_2020/element_data.rs
  components/layout_2020/flow/construct.rs
  components/layout_2020/flow/inline.rs
  components/layout_2020/flow/mod.rs
  components/layout_2020/flow/root.rs
  components/layout_2020/formatting_contexts.rs
  components/layout_2020/lib.rs
  components/layout_2020/positioned.rs
Labels: S-awaiting-merge

#25983 Update x11-dl to pickup the fix for x11 startup crash (recurrence of #21530)
  Cargo.lock
Labels: S-awaiting-merge

#25984 layout_2020: Refactor PositioningContext to be simpler and smaller
  components/layout_2020/positioned.rs
Labels: A-layout/2020, S-awaiting-merge

#25985 layout_2020: Add support for hoisting positioned fragments in inline boxes
  components/layout_2020/flow/inline.rs
  components/layout_2020/positioned.rs
  components/layout_2020/style_ext.rs
  tests/wpt/metadata-layout-2020/css/CSS2/positioning/abspos-inline-008.xht.ini
  tests/wpt/metadata-layout-2020/css/CSS2/positioning/toogle-abspos-on-relpos-inline-child.html.ini
  tests/wpt/metadata-layout-2020/css/css-transforms/preserve3d-button.html.ini
  tests/wpt/metadata-layout-2020/css/filter-effects/filtered-inline-is-container.html.ini
  tests/wpt/mozilla/meta-layout-2020/css/absolute_inline_containing_block_a.html.ini
Labels: A-layout/2020, S-awaiting-merge

#25960 Don't run 2dcontext tests in layout-2020.
  tests/wpt/include-layout-2020.ini
Labels: S-awaiting-merge

#25782 Add a simple implementation of CanvasRenderingContext2d.fillText
  Cargo.lock
  components/canvas/Cargo.toml
  components/canvas/canvas_data.rs
  components/canvas/raqote_backend.rs
  tests/wpt/metadata/2dcontext/fill-and-stroke-styles/2d.gradient.radial.inside3.html.ini
  tests/wpt/metadata/2dcontext/line-styles/2d.line.cap.closed.html.ini
  tests/wpt/metadata/2dcontext/text-styles/canvas_text_font_001.htm.ini
  tests/wpt/metadata/offscreen-canvas/fill-and-stroke-styles/2d.gradient.radial.inside3.html.ini
  tests/wpt/metadata/offscreen-canvas/fill-and-stroke-styles/2d.gradient.radial.inside3.worker.js.ini
  tests/wpt/metadata/offscreen-canvas/line-styles/2d.line.cap.closed.html.ini
  tests/wpt/metadata/offscreen-canvas/line-styles/2d.line.cap.closed.worker.js.ini
Labels: S-awaiting-merge

#25988 layout_2020: Fix a documentation comment
  components/layout_2020/fragments.rs
Labels: A-layout/2020, S-awaiting-merge

#25839 Remove requirement to install pkg-config on Windows.
  README.md
Labels: S-awaiting-merge

#25989 Reuse layout-2013 WPT results with layout-2020 when syncing.
  etc/ci/update-wpt-checkout
Labels: S-awaiting-merge

#25996 added pop!_os support for ./mach bootstrap
  python/servo/bootstrap.py
Labels: S-awaiting-merge

#25994 Replace IRC channel with Matrix link
  docs/HACKING_QUICKSTART.md
Labels: S-awaiting-merge

#25992 Index tasks by git tree hash instead of parent commits hashes
  etc/taskcluster/decision_task.py
  etc/taskcluster/decisionlib.py
  etc/taskcluster/mock.py
Labels: S-awaiting-merge

#25980 Enable windows unit tests
  etc/taskcluster/decision_task.py
  python/servo/build_commands.py
Labels: S-awaiting-merge

#26006 Add missing same-origin referrer policy
  components/script/dom/request.rs
  components/script/dom/webidls/Request.webidl
  tests/wpt/metadata/fetch/api/redirect/redirect-referrer.any.js.ini
  tests/wpt/metadata/fetch/api/request/request-init-001.sub.html.ini
Labels: S-awaiting-merge

#26002 Add Layout 2020 reftests regression report
  .gitignore
  etc/layout-2020-regressions/gen.py
  etc/layout-2020-regressions/prism.css
  etc/layout-2020-regressions/prism.js
  etc/taskcluster/decision_task.py
  etc/taskcluster/decisionlib.py
Labels: S-awaiting-merge

#26012 layout_2020: Use the containing block more when calculating scrolling overflow
  components/layout_2020/display_list/stacking_context.rs
  components/layout_2020/flow/root.rs
  components/layout_2020/fragments.rs
Labels: A-layout/2020, S-awaiting-merge

#26016 Force alert message to its own line.
  components/script/dom/window.rs
Labels: S-awaiting-merge

#25365 Launch vcvarsall.bat for the recognized VS Installation Directory from python instead of making mach.bat try that on hardcoded paths.
  mach.bat
  python/servo/build_commands.py
Labels: S-awaiting-merge

#26017 Removed createTouch and createTouchList
  components/script/dom/document.rs
  components/script/dom/webidls/Document.webidl
  tests/wpt/metadata/touch-events/historical.html.ini
Labels: S-awaiting-merge

#25913 Update curl package for Windows CI.
  etc/taskcluster/decisionlib.py
Labels: S-awaiting-merge

#26021 Revert fillText()
  Cargo.lock
  components/canvas/Cargo.toml
  components/canvas/canvas_data.rs
  components/canvas/raqote_backend.rs
  tests/wpt/metadata/2dcontext/fill-and-stroke-styles/2d.gradient.radial.inside3.html.ini
  tests/wpt/metadata/2dcontext/line-styles/2d.line.cap.closed.html.ini
  tests/wpt/metadata/2dcontext/text-styles/canvas_text_font_001.htm.ini
  tests/wpt/metadata/offscreen-canvas/fill-and-stroke-styles/2d.gradient.radial.inside3.html.ini
  tests/wpt/metadata/offscreen-canvas/fill-and-stroke-styles/2d.gradient.radial.inside3.worker.js.ini
  tests/wpt/metadata/offscreen-canvas/line-styles/2d.line.cap.closed.html.ini
  tests/wpt/metadata/offscreen-canvas/line-styles/2d.line.cap.closed.worker.js.ini
Labels: S-awaiting-merge

#26011 UWP: include submodule logs
  ports/libsimpleservo/capi/src/vslogger.rs
  support/hololens/ServoApp/ServoControl/Servo.cpp
Labels: S-awaiting-merge

#26030 UWP: Add a devtools button
  support/hololens/ServoApp/Assets/UI/devtools.png
  support/hololens/ServoApp/BrowserPage.cpp
  support/hololens/ServoApp/BrowserPage.h
  support/hololens/ServoApp/BrowserPage.xaml
  support/hololens/ServoApp/ServoApp.vcxproj
  support/hololens/ServoApp/ServoApp.vcxproj.filters
  support/hololens/ServoApp/ServoControl/ServoControl.cpp
  support/hololens/ServoApp/ServoControl/ServoControl.h
  support/hololens/ServoApp/ServoControl/ServoControl.idl
Labels: S-awaiting-merge

#26005 Update content-security-policy.
  Cargo.lock
  components/malloc_size_of/Cargo.toml
  components/net/Cargo.toml
  components/net/fetch/methods.rs
  components/net_traits/Cargo.toml
  components/script/Cargo.toml
  components/script/dom/htmlscriptelement.rs
Labels: S-awaiting-merge

#26035 Make tests/jquery/run_jquery.py Python3 compatible
  tests/jquery/run_jquery.py
Labels: S-awaiting-merge

#26029 Set user interactions for tasks
  components/script/dom/promise.rs
  components/script/microtask.rs
  components/script/script_runtime.rs
  components/script/timers.rs
Labels: S-awaiting-merge

#26037 layout_2020: Use ArcRefCell in the fragment tree
  components/layout_2020/display_list/stacking_context.rs
  components/layout_2020/flow/root.rs
  components/layout_2020/fragments.rs
  components/layout_2020/positioned.rs
Labels: A-layout/2020, S-awaiting-merge

#26042 Update webxr and webxr-api.
  Cargo.lock
Labels: S-awaiting-merge

#25998 Avoid a panic when closing webgl pages using VAOs
  components/script/dom/vertexarrayobject.rs
  components/script/dom/webgl2renderingcontext.rs
  components/script/dom/webglbuffer.rs
  components/script/dom/webglrenderingcontext.rs
Labels: S-awaiting-merge

#26046 layout_2020: Use ArcRefCell to track hoisted fragments
  components/layout_2020/display_list/stacking_context.rs
  components/layout_2020/flow/inline.rs
  components/layout_2020/flow/mod.rs
  components/layout_2020/flow/root.rs
  components/layout_2020/fragments.rs
  components/layout_2020/positioned.rs
  tests/wpt/mozilla/meta-layout-2020/css/absolute_hypothetical_with_intervening_inline_block_a.html.ini
  tests/wpt/mozilla/meta-layout-2020/css/list_item_marker_around_float.html.ini
Labels: A-layout/2020, S-awaiting-merge

#26048 Give a lifetime parameter to LayoutDom
  components/layout/construct.rs
  components/layout/fragment.rs
  components/layout/query.rs
  components/layout/table_cell.rs
  components/layout/traversal.rs
  components/layout/wrapper.rs
  components/layout_2020/dom_traversal.rs
  components/layout_2020/flow/root.rs
  components/layout_2020/query.rs
  components/layout_2020/traversal.rs
  components/layout_2020/wrapper.rs
  components/layout_thread/dom_wrapper.rs
  components/layout_thread/lib.rs
  components/layout_thread_2020/dom_wrapper.rs
  components/layout_thread_2020/lib.rs
  components/script/dom/attr.rs
  components/script/dom/bindings/root.rs
  components/script/dom/bindings/trace.rs
  components/script/dom/canvasrenderingcontext2d.rs
  components/script/dom/characterdata.rs
  components/script/dom/document.rs
  components/script/dom/element.rs
  components/script/dom/htmlbodyelement.rs
  components/script/dom/htmlcanvaselement.rs
  components/script/dom/htmlfontelement.rs
  components/script/dom/htmlhrelement.rs
  components/script/dom/htmliframeelement.rs
  components/script/dom/htmlimageelement.rs
  components/script/dom/htmlinputelement.rs
  components/script/dom/htmlmediaelement.rs
  components/script/dom/htmltablecellelement.rs
  components/script/dom/htmltableelement.rs
  components/script/dom/htmltablerowelement.rs
  components/script/dom/htmltablesectionelement.rs
  components/script/dom/htmltextareaelement.rs
  components/script/dom/node.rs
  components/script/dom/shadowroot.rs
  components/script/dom/svgsvgelement.rs
  components/script/dom/webgl2renderingcontext.rs
  components/script/dom/webglrenderingcontext.rs
  components/script/dom/window.rs
  components/script/lib.rs
  components/script_layout_interface/message.rs
  components/script_layout_interface/wrapper_traits.rs
Labels: S-awaiting-merge

#26049 layout_2020: Stop throwing away hoisted boxes in nested absolutes
  components/layout_2020/display_list/stacking_context.rs
  components/layout_2020/lib.rs
  components/layout_2020/positioned.rs
Labels: A-layout/2020, S-awaiting-merge

#26043 Context menu API
  Cargo.lock
  components/embedder_traits/lib.rs
  ports/glutin/browser.rs
  ports/libsimpleservo/api/Cargo.toml
  ports/libsimpleservo/api/src/lib.rs
  ports/libsimpleservo/capi/src/lib.rs
  support/hololens/ServoApp/ServoControl/Servo.cpp
  support/hololens/ServoApp/ServoControl/Servo.h
  support/hololens/ServoApp/ServoControl/ServoControl.cpp
  support/hololens/ServoApp/ServoControl/ServoControl.h
Labels: S-awaiting-merge

#26056 Enable Atomics.wait in a dedicated worker agent
  components/script/script_runtime.rs
  tests/wpt/metadata/html/webappapis/scripting/processing-model-2/integration-with-the-javascript-agent-formalism/requires-success.any.js.ini
Labels: S-awaiting-merge

#26058 Make many improvements to the layout/script comms story
  components/layout_thread/dom_wrapper.rs
  components/layout_thread_2020/dom_wrapper.rs
  components/script/dom/attr.rs
  components/script/dom/bindings/root.rs
  components/script/dom/canvasrenderingcontext2d.rs
  components/script/dom/characterdata.rs
  components/script/dom/document.rs
  components/script/dom/element.rs
  components/script/dom/htmlbodyelement.rs
  components/script/dom/htmlcanvaselement.rs
  components/script/dom/htmlfontelement.rs
  components/script/dom/htmlhrelement.rs
  components/script/dom/htmliframeelement.rs
  components/script/dom/htmlimageelement.rs
  components/script/dom/htmlmediaelement.rs
  components/script/dom/htmltablecellelement.rs
  components/script/dom/htmltableelement.rs
  components/script/dom/htmltablerowelement.rs
  components/script/dom/htmltablesectionelement.rs
  components/script/dom/node.rs
  components/script/dom/shadowroot.rs
  components/script/dom/svgsvgelement.rs
  components/script/dom/webgl2renderingcontext.rs
  components/script/dom/webglrenderingcontext.rs
Labels: S-awaiting-merge

#26025 Add support for DrawRangeElements in WebGL2
  components/canvas/webgl_thread.rs
  components/canvas_traits/webgl.rs
  components/script/dom/webgl2renderingcontext.rs
  components/script/dom/webglprogram.rs
  components/script/dom/webglrenderingcontext.rs
  components/script/dom/webidls/WebGL2RenderingContext.webidl
  tests/wpt/webgl/meta/conformance2/rendering/uniform-block-buffer-size.html.ini
  tests/wpt/webgl/meta/conformance2/transform_feedback/simultaneous_binding.html.ini
Labels: S-awaiting-merge

#26036 Add ipc router shutdown
  Cargo.lock
  components/constellation/constellation.rs
  components/script/script_thread.rs
Labels: S-awaiting-merge

#26009 Implementation for ImageBitmap
  components/script/dom/imagebitmap.rs
  components/script/dom/mod.rs
  components/script/dom/webidls/ImageBitmap.webidl
  tests/wpt/metadata/html/dom/idlharness.https.html.ini
  tests/wpt/metadata/workers/semantics/interface-objects/001.worker.js.ini
  tests/wpt/mozilla/meta/MANIFEST.json
  tests/wpt/mozilla/tests/mozilla/interfaces.html
  tests/wpt/mozilla/tests/mozilla/interfaces.worker.js
Labels: S-awaiting-merge

#26041 Update dwrote to 0.11.
  Cargo.lock
  components/gfx/Cargo.toml
  components/gfx/platform/windows/font.rs
  servo-tidy.toml
Labels: S-awaiting-merge

#26062 Update mozjs.
  Cargo.lock
  components/script/Cargo.toml
  components/servo/Cargo.toml
  ports/glutin/Cargo.toml
  ports/libsimpleservo/api/Cargo.toml
  ports/libsimpleservo/capi/Cargo.toml
Labels: S-awaiting-merge

#26063 Fix failing assertion -- failure to pop reference frame
  components/layout/display_list/items.rs
  components/layout/display_list/webrender_helpers.rs
  tests/wpt/metadata/css/compositing/mix-blend-mode/mix-blend-mode-sibling-with-3D-transform.html.ini
Labels: S-awaiting-merge

#26054 Fix tojson unconditionally serializes
  components/script/dom/bindings/codegen/CodegenRust.py
  components/script/dom/bindings/guard.rs
  tests/wpt/metadata/hr-time/idlharness.any.js.ini
Labels: S-awaiting-merge

#26067 Make it possible to add a title to context menu
  .gitignore
  components/embedder_traits/lib.rs
  ports/glutin/browser.rs
  ports/libsimpleservo/api/src/lib.rs
  ports/libsimpleservo/capi/src/lib.rs
  support/hololens/ServoApp/ServoControl/Servo.cpp
  support/hololens/ServoApp/ServoControl/Servo.h
  support/hololens/ServoApp/ServoControl/ServoControl.cpp
  support/hololens/ServoApp/ServoControl/ServoControl.h
Labels: S-awaiting-merge

#26038 Use rust-mozjs exposed function to generate SourceText
  components/script/dom/eventtarget.rs
  components/script/dom/globalscope.rs
  components/script/script_module.rs
Labels: S-awaiting-merge

#26070 Make LayoutNodeHelpers::text_content return a cow
  components/layout/wrapper.rs
  components/layout_2020/dom_traversal.rs
  components/layout_2020/flow/construct.rs
  components/layout_thread/dom_wrapper.rs
  components/layout_thread_2020/dom_wrapper.rs
  components/script/dom/attr.rs
  components/script/dom/characterdata.rs
  components/script/dom/element.rs
  components/script/dom/htmlinputelement.rs
  components/script/dom/htmltextareaelement.rs
  components/script/dom/node.rs
  components/script_layout_interface/wrapper_traits.rs
Labels: S-awaiting-merge

#26072 Ensure reference frame is popped in layout 2020
  components/layout_2020/display_list/stacking_context.rs
Labels: S-awaiting-merge
