Repository servo/servo, pull requests merged in 2020-08, with the labels that each got.

#27470 Added a recipe for streaming to twitch
  ports/gstplugin/README.md
Labels: A-documentation, P-gst-plugin, S-awaiting-merge

#27487 WebXR Layers update WebIDL
  components/script/dom/webglframebuffer.rs
  components/script/dom/webidls/XRLayer.webidl
  components/script/dom/webidls/XRLayerEvent.webidl
  components/script/dom/webidls/XRMediaBinding.webidl
  components/script/dom/webidls/XRRenderState.webidl
  components/script/dom/webidls/XRSubImage.webidl
  components/script/dom/webidls/XRWebGLBinding.webidl
  components/script/dom/webidls/XRWebGLLayer.webidl
  components/script/dom/xrlayer.rs
  components/script/dom/xrrenderstate.rs
  components/script/dom/xrsession.rs
  components/script/dom/xrwebglbinding.rs
  components/script/dom/xrwebgllayer.rs
  tests/wpt/metadata/webxr/idlharness.https.window.js.ini
  tests/wpt/mozilla/meta/MANIFEST.json
  tests/wpt/mozilla/tests/mozilla/interfaces.html
  tests/wpt/mozilla/tests/webxr/layers.html
Labels: A-content/script, A-xr-zomg, S-awaiting-merge

#27438 UWP Crash reporter
  components/config/prefs.rs
  ports/libsimpleservo/api/src/lib.rs
  ports/libsimpleservo/capi/src/lib.rs
  ports/libsimpleservo/capi/src/prefs.rs
  resources/prefs.json
  support/hololens/ServoApp/BrowserPage.cpp
  support/hololens/ServoApp/BrowserPage.h
  support/hololens/ServoApp/BrowserPage.xaml
  support/hololens/ServoApp/Devtools/Client.cpp
  support/hololens/ServoApp/ServoControl/Servo.cpp
  support/hololens/ServoApp/ServoControl/Servo.h
  support/hololens/ServoApp/ServoControl/ServoControl.cpp
  support/hololens/ServoApp/ServoControl/ServoControl.h
  support/hololens/ServoApp/ServoControl/ServoControl.idl
  support/hololens/ServoApp/Strings/en-US/Resources.resw
Labels: S-awaiting-merge

#27481 Support Linux Mint 20.04 for mach bootstrap
  python/servo/bootstrap.py
Labels: S-awaiting-merge

#27480 WebGPU-Report errors in Promise or void returning operations
  Cargo.lock
  components/constellation/constellation.rs
  components/malloc_size_of/lib.rs
  components/script/dom/bindings/trace.rs
  components/script/dom/globalscope.rs
  components/script/dom/gpu.rs
  components/script/dom/gpuadapter.rs
  components/script/dom/gpubuffer.rs
  components/script/dom/gpucanvascontext.rs
  components/script/dom/gpucommandencoder.rs
  components/script/dom/gpucomputepassencoder.rs
  components/script/dom/gpudevice.rs
  components/script/dom/gpuqueue.rs
  components/script/dom/gpurenderbundleencoder.rs
  components/script/dom/gpurenderpassencoder.rs
  components/script/dom/gpuswapchain.rs
  components/script/dom/gputexture.rs
  components/script/dom/webidls/GPU.webidl
  components/script/dom/webidls/GPUAdapter.webidl
  components/script/dom/webidls/GPUBuffer.webidl
  components/webgpu/identity.rs
  components/webgpu/lib.rs
Labels: S-awaiting-merge

#27500 Revert webrender upgrade
  Cargo.lock
  Cargo.toml
  components/canvas/Cargo.toml
  components/compositing/Cargo.toml
  components/gfx/Cargo.toml
  components/gfx/text/shaping/harfbuzz.rs
  components/layout/Cargo.toml
  components/layout/text.rs
  components/layout_2020/Cargo.toml
  components/servo/Cargo.toml
  servo-tidy.toml
  tests/wpt/metadata/css/css-paint-api/background-image-tiled.https.html.ini
Labels: S-awaiting-merge

#27491 UWP: only show promoted preferences
  support/hololens/ServoApp/BrowserPage.cpp
  support/hololens/ServoApp/BrowserPage.h
  support/hololens/ServoApp/BrowserPage.xaml
  support/hololens/ServoApp/Resources/PromotedPrefs.resw
  support/hololens/ServoApp/Resources/Strings/en-US/Resources.resw
  support/hololens/ServoApp/Resources/Strings/fr-FR/Resources.resw
  support/hololens/ServoApp/ServoApp.vcxproj
  support/hololens/ServoApp/ServoApp.vcxproj.filters
  support/hololens/ServoApp/pch.h
Labels: S-awaiting-merge

#27506 Keep C++ pref value in memory longer
  support/hololens/ServoApp/ServoControl/Servo.cpp
Labels: S-awaiting-merge

#27513 Add XRLayerEvent
  components/script/dom/mod.rs
  components/script/dom/webidls/XRLayerEvent.webidl
  components/script/dom/xrlayerevent.rs
  tests/wpt/mozilla/meta/MANIFEST.json
  tests/wpt/mozilla/meta/webxr/layerevents.html.ini
  tests/wpt/mozilla/tests/webxr/layerevents.html
Labels: A-content/script, A-xr-zomg, S-awaiting-merge

#27512 Handle devtools clients disconnecting better
  components/devtools/actor.rs
  components/devtools/actors/browsing_context.rs
  components/devtools/actors/console.rs
  components/devtools/actors/device.rs
  components/devtools/actors/emulation.rs
  components/devtools/actors/framerate.rs
  components/devtools/actors/inspector.rs
  components/devtools/actors/memory.rs
  components/devtools/actors/network_event.rs
  components/devtools/actors/object.rs
  components/devtools/actors/performance.rs
  components/devtools/actors/preference.rs
  components/devtools/actors/process.rs
  components/devtools/actors/profiler.rs
  components/devtools/actors/root.rs
  components/devtools/actors/stylesheets.rs
  components/devtools/actors/tab.rs
  components/devtools/actors/thread.rs
  components/devtools/actors/timeline.rs
  components/devtools/actors/worker.rs
  components/devtools/lib.rs
  components/devtools/protocol.rs
Labels: S-awaiting-merge

#27425 Support preserveDrawingBuffer
  Cargo.lock
  components/canvas/Cargo.toml
  components/canvas/webgl_thread.rs
  components/webrender_surfman/Cargo.toml
  components/webrender_surfman/lib.rs
  ports/gstplugin/Cargo.toml
Labels: S-awaiting-merge

#27530 Fix crashes on video playback in UWP
  components/script/dom/mediasession.rs
  support/hololens/ServoApp/BrowserPage.cpp
  support/hololens/ServoApp/ServoApp.vcxproj
  support/hololens/ServoApp/ServoControl/Servo.cpp
  support/hololens/ServoApp/ServoControl/Servo.h
  support/hololens/ServoApp/ServoControl/ServoControl.cpp
  support/hololens/ServoApp/ServoControl/ServoControl.h
  support/hololens/ServoApp/ServoControl/ServoControl.idl
Labels: S-awaiting-merge

#27538 Make textures that come from webxr invalid outside an rAF
  components/script/dom/webglframebuffer.rs
  components/script/dom/webglrenderingcontext.rs
  components/script/dom/webgltexture.rs
  components/script/dom/xrwebgllayer.rs
Labels: A-content/script, A-xr-spec-complete, S-awaiting-merge

#27522 Use override value for home button when available.
  support/hololens/ServoApp/ServoControl/Servo.cpp
Labels: S-awaiting-merge

#27537 Use gstreamer on UWP targets
  components/servo/lib.rs
  python/servo/command_base.py
  support/hololens/ServoApp/ServoControl/Servo.cpp
Labels: S-awaiting-merge

#27543 UWP: better pref label
  support/hololens/ServoApp/Resources/PromotedPrefs.resw
Labels: S-awaiting-merge

#27536 Major fixes in error reporting in GPUCommandEncoder and ErrorScope Model
  Cargo.lock
  components/script/dom/gpucommandencoder.rs
  components/script/dom/gpucomputepassencoder.rs
  components/script/dom/gpudevice.rs
  components/script/dom/gpurenderpassencoder.rs
  components/script/dom/gputexture.rs
  components/webgpu/lib.rs
  tests/wpt/webgpu/meta/webgpu/cts.html.ini
Labels: S-awaiting-merge

#27534 Move action buttons above invalid certificate details.
  resources/badcert.html
Labels: S-awaiting-merge

#27549 Update WebGPU CTS to main branch
  components/script/dom/gpucommandbuffer.rs
  components/webgpu/lib.rs
  tests/wpt/webgpu/meta/MANIFEST.json
  tests/wpt/webgpu/meta/webgpu/cts.html.ini
  tests/wpt/webgpu/tests/webgpu/common/framework/fixture.js
  tests/wpt/webgpu/tests/webgpu/common/framework/glsl.js
  tests/wpt/webgpu/tests/webgpu/common/framework/params_builder.js
  tests/wpt/webgpu/tests/webgpu/common/framework/query/encode_selectively.js
  tests/wpt/webgpu/tests/webgpu/common/framework/query/json_param_value.js
  tests/wpt/webgpu/tests/webgpu/common/framework/query/parseQuery.js
  tests/wpt/webgpu/tests/webgpu/common/framework/query/stringify_params.js
  tests/wpt/webgpu/tests/webgpu/common/framework/version.js
  tests/wpt/webgpu/tests/webgpu/cts.html
  tests/wpt/webgpu/tests/webgpu/third_party/glslang_js/lib/glslang.js
  tests/wpt/webgpu/tests/webgpu/third_party/glslang_js/lib/glslang.wasm
  tests/wpt/webgpu/tests/webgpu/webgpu/api/operation/buffers/create_mapped.spec.js
  tests/wpt/webgpu/tests/webgpu/webgpu/api/operation/buffers/map.spec.js
  tests/wpt/webgpu/tests/webgpu/webgpu/api/operation/buffers/map_detach.spec.js
  tests/wpt/webgpu/tests/webgpu/webgpu/api/operation/buffers/map_oom.spec.js
  tests/wpt/webgpu/tests/webgpu/webgpu/api/operation/buffers/mapping_test.js
  tests/wpt/webgpu/tests/webgpu/webgpu/api/operation/command_buffer/compute/basic.spec.js
  tests/wpt/webgpu/tests/webgpu/webgpu/api/operation/command_buffer/copies.spec.js
  tests/wpt/webgpu/tests/webgpu/webgpu/api/operation/command_buffer/render/rendering.spec.js
  tests/wpt/webgpu/tests/webgpu/webgpu/api/operation/command_buffer/render/storeop.spec.js
  tests/wpt/webgpu/tests/webgpu/webgpu/api/operation/render_pass/storeOp.spec.js
  tests/wpt/webgpu/tests/webgpu/webgpu/api/operation/render_pipeline/culling_tests.spec.js
  tests/wpt/webgpu/tests/webgpu/webgpu/api/operation/resource_init/depth_stencil_attachment_clear.spec.js
  tests/wpt/webgpu/tests/webgpu/webgpu/api/operation/resource_init/sampled_texture_clear.spec.js
  tests/wpt/webgpu/tests/webgpu/webgpu/api/validation/createBindGroupLayout.spec.js
  tests/wpt/webgpu/tests/webgpu/webgpu/api/validation/createRenderPipeline.spec.js
  tests/wpt/webgpu/tests/webgpu/webgpu/api/validation/encoding/cmds/index_access.spec.js
  tests/wpt/webgpu/tests/webgpu/webgpu/api/validation/fences.spec.js
  tests/wpt/webgpu/tests/webgpu/webgpu/api/validation/queue_submit.spec.js
  tests/wpt/webgpu/tests/webgpu/webgpu/api/validation/render_pass.spec.js
  tests/wpt/webgpu/tests/webgpu/webgpu/api/validation/render_pass/resolve.spec.js
  tests/wpt/webgpu/tests/webgpu/webgpu/api/validation/render_pass/storeOp.spec.js
  tests/wpt/webgpu/tests/webgpu/webgpu/api/validation/resource_usages/textureUsageInRender.spec.js
  tests/wpt/webgpu/tests/webgpu/webgpu/api/validation/setVertexBuffer.spec.js
  tests/wpt/webgpu/tests/webgpu/webgpu/api/validation/vertex_state.spec.js
  tests/wpt/webgpu/tests/webgpu/webgpu/capability_info.js
  tests/wpt/webgpu/tests/webgpu/webgpu/examples.spec.js
  tests/wpt/webgpu/tests/webgpu/webgpu/gpu_test.js
  tests/wpt/webgpu/tests/webgpu/webgpu/listing.js
  tests/wpt/webgpu/tests/webgpu/webgpu/shader/execution/robust_access.spec.js
  tests/wpt/webgpu/tests/webgpu/webgpu/shader/execution/robust_access_vertex.spec.js
  tests/wpt/webgpu/tests/webgpu/webgpu/util/texture/layout.js
  tests/wpt/webgpu/tests/webgpu/webgpu/web-platform/copyImageBitmapToTexture.spec.js
  tests/wpt/webgpu/tests/webgpu/webgpu/web-platform/reftests/canvas_complex.js
Labels: S-awaiting-merge

#27556 UWP Bookmarks
  ports/libsimpleservo/api/src/lib.rs
  ports/libsimpleservo/capi/src/lib.rs
  support/hololens/ServoApp/Bookmarks.cpp
  support/hololens/ServoApp/Bookmarks.h
  support/hololens/ServoApp/BrowserPage.cpp
  support/hololens/ServoApp/BrowserPage.h
  support/hololens/ServoApp/BrowserPage.idl
  support/hololens/ServoApp/BrowserPage.xaml
  support/hololens/ServoApp/Resources/Strings/en-US/Resources.resw
  support/hololens/ServoApp/ServoApp.vcxproj
  support/hololens/ServoApp/ServoApp.vcxproj.filters
  support/hololens/ServoApp/ServoControl/ServoControl.h
Labels: S-awaiting-merge

#27548 Canvas text and macOS font fixes
  Cargo.lock
  components/canvas/Cargo.toml
  components/canvas/canvas_data.rs
  components/canvas/raqote_backend.rs
  components/gfx/platform/macos/font_template.rs
Labels: S-awaiting-merge

#27505 Do not load srcdoc iframes synchronously
  components/constellation/constellation.rs
  components/script/dom/htmliframeelement.rs
  components/script/script_thread.rs
  tests/wpt/metadata/cookies/cookie-enabled-noncookie-frame.html.ini
  tests/wpt/metadata/custom-elements/perform-microtask-checkpoint-before-construction.html.ini
  tests/wpt/metadata/html/browsers/sandboxing/sandbox-disallow-scripts-via-unsandboxed-popup.tentative.html.ini
  tests/wpt/metadata/html/interaction/focus/the-autofocus-attribute/skip-not-fully-active.html.ini
  tests/wpt/metadata/referrer-policy/generic/sandboxed-iframe-with-opaque-origin.html.ini
Labels: S-awaiting-merge

#27558 Fix missing canvas text on UWP
  Cargo.lock
  Cargo.toml
  components/canvas/Cargo.toml
  components/compositing/Cargo.toml
  components/gfx/Cargo.toml
  components/gfx/text/shaping/harfbuzz.rs
  components/layout/Cargo.toml
  components/layout/text.rs
  components/layout_2020/Cargo.toml
  components/servo/Cargo.toml
  servo-tidy.toml
Labels: S-awaiting-merge

#27559 Update FxR version number.
  support/hololens/ServoApp/Package.appxmanifest
Labels: S-awaiting-merge

#27562 Notify devtools of session history traversals
  components/constellation/constellation.rs
  components/constellation/pipeline.rs
  components/script/dom/document.rs
  components/script_traits/script_msg.rs
Labels: S-awaiting-merge

#27564 Disable as many broken devtools panels as possible.
  components/devtools/actors/browsing_context.rs
  components/devtools/actors/root.rs
Labels: S-awaiting-merge

#27570 Implement GPUUncapturedErrorEvent
  Cargo.lock
  components/atoms/static_atoms.txt
  components/script/dom/gpudevice.rs
  components/script/dom/gpuuncapturederrorevent.rs
  components/script/dom/mod.rs
  components/script/dom/webidls/GPUUncapturedErrorEvent.webidl
  tests/wpt/webgpu/meta/webgpu/cts.html.ini
Labels: S-awaiting-merge

#27569 Add time and app version to crash report
  support/hololens/ServoApp/ServoApp.vcxproj
  support/hololens/ServoApp/ServoApp.vcxproj.filters
  support/hololens/ServoApp/ServoControl/Crash.cpp
  support/hololens/ServoApp/ServoControl/Crash.h
  support/hololens/ServoApp/ServoControl/Servo.cpp
Labels: S-awaiting-merge

#27590 Update wgpu and WebGPU CTS to include copy validation tests
  Cargo.lock
  components/script/dom/gpudevice.rs
  components/script/dom/gpurenderbundleencoder.rs
  components/script/dom/gputexture.rs
  components/webgpu/lib.rs
  tests/wpt/webgpu/meta/MANIFEST.json
  tests/wpt/webgpu/meta/webgpu/cts.html.ini
  tests/wpt/webgpu/tests/webgpu/common/framework/gpu/device_pool.js
  tests/wpt/webgpu/tests/webgpu/common/framework/query/json_param_value.js
  tests/wpt/webgpu/tests/webgpu/common/framework/version.js
  tests/wpt/webgpu/tests/webgpu/cts.html
  tests/wpt/webgpu/tests/webgpu/webgpu/api/operation/render_pass/storeOp.spec.js
  tests/wpt/webgpu/tests/webgpu/webgpu/api/operation/resource_init/texture_zero_init_test.js
  tests/wpt/webgpu/tests/webgpu/webgpu/api/validation/copyBufferToBuffer.spec.js
  tests/wpt/webgpu/tests/webgpu/webgpu/api/validation/copy_between_linear_data_and_texture/copyBetweenLinearDataAndTexture.js
  tests/wpt/webgpu/tests/webgpu/webgpu/api/validation/copy_between_linear_data_and_texture/copyBetweenLinearDataAndTexture_dataRelated.spec.js
  tests/wpt/webgpu/tests/webgpu/webgpu/api/validation/copy_between_linear_data_and_texture/copyBetweenLinearDataAndTexture_textureRelated.spec.js
  tests/wpt/webgpu/tests/webgpu/webgpu/api/validation/createBindGroupLayout.spec.js
  tests/wpt/webgpu/tests/webgpu/webgpu/api/validation/createTexture.spec.js
  tests/wpt/webgpu/tests/webgpu/webgpu/api/validation/error_scope.spec.js
  tests/wpt/webgpu/tests/webgpu/webgpu/api/validation/fences.spec.js
  tests/wpt/webgpu/tests/webgpu/webgpu/api/validation/resource_usages/textureUsageInRender.spec.js
  tests/wpt/webgpu/tests/webgpu/webgpu/api/validation/validation_test.js
  tests/wpt/webgpu/tests/webgpu/webgpu/capability_info.js
  tests/wpt/webgpu/tests/webgpu/webgpu/gpu_test.js
  tests/wpt/webgpu/tests/webgpu/webgpu/idl/constants/flags.spec.js
  tests/wpt/webgpu/tests/webgpu/webgpu/idl/idl_test.js
  tests/wpt/webgpu/tests/webgpu/webgpu/listing.js
  tests/wpt/webgpu/tests/webgpu/webgpu/util/math.js
  tests/wpt/webgpu/tests/webgpu/webgpu/util/texture/layout.js
  tests/wpt/webgpu/tests/webgpu/webgpu/util/texture/texelData.js
  tests/wpt/webgpu/tests/webgpu/webgpu/web-platform/copyImageBitmapToTexture.spec.js
  tests/wpt/webgpu/tests/webgpu/webgpu/web-platform/reftests/gpu_ref_test.js
Labels: S-awaiting-merge

#27603 Implement GPUPipelineBase for implicit pipeline layouts
  Cargo.lock
  components/script/dom/gpucomputepipeline.rs
  components/script/dom/gpudevice.rs
  components/script/dom/gpupipelinelayout.rs
  components/script/dom/gpurenderbundleencoder.rs
  components/script/dom/gpurenderpipeline.rs
  components/script/dom/gputexture.rs
  components/script/dom/webidls/GPUComputePipeline.webidl
  components/script/dom/webidls/GPURenderPipeline.webidl
  components/webgpu/lib.rs
Labels: S-awaiting-merge

#27607 Defer Encoding errors to GPUCommandEncoder.finish()
  Cargo.lock
  components/script/dom/gpucommandencoder.rs
  components/script/dom/gpucomputepassencoder.rs
  components/script/dom/gpudevice.rs
  components/script/dom/gpurenderpassencoder.rs
  components/script/dom/gpuswapchain.rs
  components/webgpu/Cargo.toml
  components/webgpu/lib.rs
  servo-tidy.toml
  tests/wpt/webgpu/meta/webgpu/cts.html.ini
Labels: S-awaiting-merge

#27614 Minor fixes and update cts
  Cargo.lock
  components/script/dom/gpubuffer.rs
  components/script/dom/gputexture.rs
  components/webgpu/lib.rs
  tests/wpt/webgpu/meta/MANIFEST.json
  tests/wpt/webgpu/meta/webgpu/cts.html.ini
  tests/wpt/webgpu/tests/webgpu/common/framework/params_utils.js
  tests/wpt/webgpu/tests/webgpu/common/framework/query/encode_selectively.js
  tests/wpt/webgpu/tests/webgpu/common/framework/query/parseQuery.js
  tests/wpt/webgpu/tests/webgpu/common/framework/version.js
  tests/wpt/webgpu/tests/webgpu/cts.html
  tests/wpt/webgpu/tests/webgpu/webgpu/api/operation/copyBetweenLinearDataAndTexture.spec.js
  tests/wpt/webgpu/tests/webgpu/webgpu/api/validation/resource_usages/textureUsageInRender.spec.js
  tests/wpt/webgpu/tests/webgpu/webgpu/api/validation/setScissorRect.spec.js
  tests/wpt/webgpu/tests/webgpu/webgpu/gpu_test.js
  tests/wpt/webgpu/tests/webgpu/webgpu/listing.js
  tests/wpt/webgpu/tests/webgpu/webgpu/util/texture/layout.js
Labels: S-awaiting-merge

#27618 Update mozjs 0.14.1
  Cargo.lock
  components/script/dom/bindings/codegen/CodegenRust.py
  components/script/dom/eventtarget.rs
  components/script/dom/globalscope.rs
  components/script/dom/htmlscriptelement.rs
  components/script/script_module.rs
  components/script/webdriver_handlers.rs
Labels: S-awaiting-merge
