Repository servo/servo, pull requests merged in 2020-02, with the labels that each got.

#25665 Reduce log spam in some cases
  components/canvas/canvas_paint_thread.rs
Labels: S-awaiting-merge

#25664 Correctly install 'nigthtly' (without a date) if it’s not installed already
  python/servo/command_base.py
Labels: S-tests-failed

#25645 Add support for overflow:scroll and overflow:hidden to layout_2020
  components/layout_2020/display_list/mod.rs
  components/layout_2020/fragments.rs
  components/style/properties/longhands/box.mako.rs
  components/style/properties/shorthands/box.mako.rs
  tests/wpt/metadata-layout-2020/css/css-backgrounds/background-repeat/background-repeat-repeat-x.xht.ini
  tests/wpt/metadata-layout-2020/css/css-backgrounds/background-repeat/background-repeat-repeat-y.xht.ini
  tests/wpt/metadata-layout-2020/css/css-backgrounds/background-size/background-size-contain.xht.ini
  tests/wpt/metadata-layout-2020/css/css-backgrounds/background-size/background-size-cover.xht.ini
  tests/wpt/mozilla/meta-layout-2020/css/acid2_ref.html.ini
  tests/wpt/mozilla/meta-layout-2020/css/border_radius_clip_a.html.ini
  tests/wpt/mozilla/meta-layout-2020/css/css-position-3/position-sticky-bottom.html.ini
  tests/wpt/mozilla/meta-layout-2020/css/css-position-3/position-sticky-top.html.ini
  tests/wpt/mozilla/meta-layout-2020/css/overflow_auto.html.ini
  tests/wpt/mozilla/meta-layout-2020/css/overflow_position_abs_simple_a.html.ini
  tests/wpt/mozilla/meta-layout-2020/css/overflow_scroll.html.ini
  tests/wpt/mozilla/meta-layout-2020/css/overflow_simple_a.html.ini
  tests/wpt/mozilla/meta-layout-2020/css/overflow_xy_a.html.ini
  tests/wpt/mozilla/meta-layout-2020/css/text_overflow_ellipsis.html.ini
  tests/wpt/mozilla/meta-layout-2020/css/text_overflow_string.html.ini
Labels: A-layout/2020, S-awaiting-merge

#25669 Update user agent info
  components/config/opts.rs
Labels: S-awaiting-merge

#25696 Remove outdated comment about #4105
  components/script/dom/node.rs
Labels: S-awaiting-merge

#25694 Remove dependency of constellation on canvas
  Cargo.lock
  components/canvas/canvas_paint_thread.rs
  components/canvas/lib.rs
  components/canvas_traits/Cargo.toml
  components/canvas_traits/lib.rs
  components/constellation/Cargo.toml
  components/constellation/constellation.rs
  components/servo/lib.rs
Labels: S-awaiting-merge

#25707 fix zip extraction for python 3
  python/servo/util.py
Labels: S-awaiting-merge

#25716 Revert ANGLE upgrade.
  python/servo/build_commands.py
  support/hololens/ServoApp/ServoApp.vcxproj
  support/hololens/ServoApp/packages.config
Labels: S-awaiting-merge

#25659 Expose DOMHighResTimeStamps at lower res
  components/script/dom/event.rs
  components/script/dom/performance.rs
  components/script/dom/performanceentry.rs
  components/script/dom/performanceresourcetiming.rs
  components/script/dom/vrframedata.rs
  components/script/dom/xrsession.rs
  tests/wpt/metadata/dom/events/Event-timestamp-safe-resolution.html.ini
  tests/wpt/metadata/performance-timeline/webtiming-resolution.any.js.ini
  tests/wpt/mozilla/meta/MANIFEST.json
  tests/wpt/mozilla/tests/mozilla/window_performance.html
Labels: S-awaiting-merge

#25695 Let EventSource fail fast on bad schemes
  components/script/dom/eventsource.rs
  tests/wpt/metadata/eventsource/dedicated-worker/eventsource-constructor-non-same-origin.htm.ini
  tests/wpt/metadata/eventsource/eventsource-constructor-non-same-origin.htm.ini
Labels: S-awaiting-merge

#25719 Make HTMLFormControlsCollection rooted at the form's root, not rooted at the form itself
  components/script/dom/htmlformcontrolscollection.rs
  tests/wpt/metadata/html/semantics/forms/the-form-element/form-elements-filter.html.ini
Labels: S-awaiting-merge

#25691 Improve the name the NodeGeometryQuery
  components/layout/query.rs
  components/layout_thread/lib.rs
  components/layout_thread_2020/lib.rs
  components/script/dom/window.rs
  components/script_layout_interface/message.rs
Labels: A-layout/query, S-awaiting-merge

#25715 Improve position:fixed support in layout_2020
  components/layout_2020/display_list/mod.rs
  tests/wpt/mozilla/meta/MANIFEST.json
  tests/wpt/mozilla/tests/css/position_fixed_scroll.html
  tests/wpt/mozilla/tests/css/position_fixed_scroll_ref.html
Labels: A-gfx/displaylist, A-layout/2020, S-awaiting-merge

#25677 Initial implementation of GPUShaderModule
  components/script/dom/bindings/trace.rs
  components/script/dom/globalscope.rs
  components/script/dom/gpudevice.rs
  components/script/dom/gpushadermodule.rs
  components/script/dom/identityhub.rs
  components/script/dom/mod.rs
  components/script/dom/webidls/GPUDevice.webidl
  components/script/dom/webidls/GPUShaderModule.webidl
  components/webgpu/lib.rs
Labels: S-awaiting-merge

#25687 Filter file: and about: responses opaquely
  components/net/fetch/methods.rs
  components/net/tests/fetch.rs
  tests/wpt/metadata/fetch/api/basic/scheme-about.any.js.ini
  tests/wpt/metadata/workers/constructors/Worker/same-origin.html.ini
  tests/wpt/metadata/xhr/send-non-same-origin.htm.ini
Labels: S-awaiting-merge

#25644 Give error and resize special getter/setters for body/frameset reflection
  components/script/dom/htmlelement.rs
  components/script/dom/macros.rs
  tests/wpt/metadata/html/webappapis/scripting/events/event-handler-attributes-body-window.html.ini
  tests/wpt/metadata/html/webappapis/scripting/events/event-handler-attributes-frameset-window.html.ini
  tests/wpt/metadata/html/webappapis/scripting/events/event-handler-attributes-windowless-body.html.ini
Labels: S-awaiting-merge

#25223 Changed error type on qname, per spec
  components/script/dom/bindings/xmlname.rs
  tests/wpt/metadata/dom/nodes/DOMImplementation-createDocument.html.ini
  tests/wpt/metadata/dom/nodes/DOMImplementation-createDocumentType.html.ini
  tests/wpt/metadata/dom/nodes/Document-createElementNS.html.ini
  tests/wpt/metadata/dom/nodes/attributes.html.ini
Labels: S-awaiting-merge

#25747 Give attribute-change callbacks a realm so they can to_jsval
  components/script/dom/customelementregistry.rs
  tests/wpt/metadata/custom-elements/parser/parser-sets-attributes-and-children.html.ini
Labels: S-awaiting-merge

#25629 Implement "translate" attribute
  components/script/dom/element.rs
  components/script/dom/htmlelement.rs
  components/script/dom/webidls/HTMLElement.webidl
  tests/wpt/metadata/custom-elements/reactions/HTMLElement.html.ini
  tests/wpt/metadata/html/dom/elements/global-attributes/the-translate-attribute-007.html.ini
  tests/wpt/metadata/html/dom/elements/global-attributes/the-translate-attribute-008.html.ini
  tests/wpt/metadata/html/dom/elements/global-attributes/the-translate-attribute-009.html.ini
  tests/wpt/metadata/html/dom/elements/global-attributes/the-translate-attribute-010.html.ini
  tests/wpt/metadata/html/dom/elements/global-attributes/the-translate-attribute-011.html.ini
  tests/wpt/metadata/html/dom/elements/global-attributes/the-translate-attribute-012.html.ini
  tests/wpt/metadata/html/dom/idlharness.https.html.ini
Labels: S-awaiting-merge

#25734 Implement CanvasRenderingContext2D.getTransform()
  components/canvas/canvas_data.rs
  components/canvas/canvas_paint_thread.rs
  components/canvas_traits/canvas.rs
  components/script/canvas_state.rs
  components/script/dom/canvasrenderingcontext2d.rs
  components/script/dom/offscreencanvasrenderingcontext2d.rs
  components/script/dom/paintrenderingcontext2d.rs
  components/script/dom/webidls/CanvasRenderingContext2D.webidl
  components/script/dom/webidls/DOMMatrix.webidl
  components/script/dom/webidls/DOMMatrixReadOnly.webidl
  components/script/dom/webidls/DOMPoint.webidl
  components/script/dom/webidls/DOMPointReadOnly.webidl
  tests/wpt/metadata/2dcontext/transformations/2d.transformation.getTransform.html.ini
  tests/wpt/metadata/css/geometry/DOMMatrix2DInit-validate-fixup.html.ini
  tests/wpt/metadata/html/dom/idlharness.https.html.ini
  tests/wpt/metadata/offscreen-canvas/transformations/2d.transformation.getTransform.html.ini
Labels: S-awaiting-merge

#25488 Event dispatch rewritten to align to spec, activate on clicks better
  components/atoms/static_atoms.txt
  components/script/dom/activation.rs
  components/script/dom/document.rs
  components/script/dom/element.rs
  components/script/dom/event.rs
  components/script/dom/eventtarget.rs
  components/script/dom/htmlanchorelement.rs
  components/script/dom/htmlareaelement.rs
  components/script/dom/htmlbuttonelement.rs
  components/script/dom/htmlelement.rs
  components/script/dom/htmlinputelement.rs
  components/script/dom/htmllabelelement.rs
  components/script/dom/node.rs
  components/script/dom/window.rs
  tests/wpt/metadata/dom/events/Event-dispatch-click.html.ini
  tests/wpt/metadata/dom/events/Event-dispatch-handlers-changed.html.ini
  tests/wpt/metadata/dom/events/Event-dispatch-order-at-target.html.ini
  tests/wpt/metadata/dom/events/EventTarget-dispatchEvent.html.ini
  tests/wpt/metadata/html/semantics/forms/the-button-element/button-click-submits.html.ini
  tests/wpt/metadata/html/semantics/forms/the-input-element/checkbox-click-events.html.ini
  tests/wpt/metadata/html/semantics/forms/the-input-element/checkbox-detached-change-event.html.ini
  tests/wpt/metadata/html/semantics/forms/the-input-element/checkbox.html.ini
  tests/wpt/metadata/html/semantics/forms/the-input-element/radio-detached-change-event.html.ini
  tests/wpt/metadata/html/semantics/forms/the-input-element/radio-input-cancel.html.ini
  tests/wpt/metadata/html/semantics/forms/the-label-element/proxy-click-to-associated-element.html.ini
  tests/wpt/metadata/html/webappapis/scripting/event-loops/task_microtask_ordering.html.ini
  tests/wpt/metadata/uievents/legacy-domevents-tests/approved/dispatchEvent.click.checkbox.html.ini
  tests/wpt/mozilla/meta/MANIFEST.json
  tests/wpt/mozilla/tests/mozilla/event_dispatch_order.html
Labels: S-awaiting-merge

#25759 Install virtualenv through APT, in Docker images
  etc/taskcluster/docker/base.dockerfile
Labels: S-awaiting-merge

#25755 Use CE reaction queue when inserting an element from non-fragment parser
  components/script/dom/servoparser/async_html.rs
  components/script/dom/servoparser/mod.rs
  tests/wpt/metadata/custom-elements/parser/parser-sets-attributes-and-children.html.ini
Labels: S-awaiting-merge

#25674 Selection DOM interface (but not actual UI selections)
  components/atoms/static_atoms.txt
  components/script/dom/document.rs
  components/script/dom/macros.rs
  components/script/dom/mod.rs
  components/script/dom/range.rs
  components/script/dom/selection.rs
  components/script/dom/webidls/Document.webidl
  components/script/dom/webidls/EventHandler.webidl
  components/script/dom/webidls/Selection.webidl
  components/script/dom/webidls/Window.webidl
  components/script/dom/window.rs
  tests/wpt/include.ini
  tests/wpt/metadata/custom-elements/reactions/Selection.html.ini
  tests/wpt/metadata/dom/ranges/Range-mutations-appendChild.html.ini
  tests/wpt/metadata/dom/ranges/Range-mutations-appendData.html.ini
  tests/wpt/metadata/dom/ranges/Range-mutations-dataChange.html.ini
  tests/wpt/metadata/dom/ranges/Range-mutations-deleteData.html.ini
  tests/wpt/metadata/dom/ranges/Range-mutations-insertBefore.html.ini
  tests/wpt/metadata/dom/ranges/Range-mutations-insertData.html.ini
  tests/wpt/metadata/dom/ranges/Range-mutations-removeChild.html.ini
  tests/wpt/metadata/dom/ranges/Range-mutations-replaceChild.html.ini
  tests/wpt/metadata/dom/ranges/Range-mutations-replaceData.html.ini
  tests/wpt/metadata/dom/ranges/Range-mutations-splitText.html.ini
  tests/wpt/metadata/html/browsers/the-window-object/window-properties.https.html.ini
  tests/wpt/metadata/selection/script-and-style-elements.html.ini
  tests/wpt/mozilla/meta/MANIFEST.json
  tests/wpt/mozilla/tests/mozilla/interfaces.html
  tests/wpt/mozilla/tests/mozilla/selectionchange/selectionchange_noop.html
  tests/wpt/mozilla/tests/mozilla/selectionchange/selectionchange_range.html
  tests/wpt/mozilla/tests/mozilla/selectionchange/selectionchange_selection.html
Labels: S-awaiting-merge

#25744 Initial implementation of GPUQueue
  components/script/dom/bindings/trace.rs
  components/script/dom/gpuadapter.rs
  components/script/dom/gpubuffer.rs
  components/script/dom/gpucommandbuffer.rs
  components/script/dom/gpucommandencoder.rs
  components/script/dom/gpudevice.rs
  components/script/dom/gpuqueue.rs
  components/script/dom/mod.rs
  components/script/dom/webidls/GPUDevice.webidl
  components/script/dom/webidls/GPUQueue.webidl
  components/webgpu/lib.rs
Labels: S-awaiting-merge

#25697 PerformanceObserver.supportedEntryTypes
  components/script/dom/extendablemessageevent.rs
  components/script/dom/globalscope.rs
  components/script/dom/messageevent.rs
  components/script/dom/performanceobserver.rs
  components/script/dom/webidls/PerformanceObserver.webidl
  tests/wpt/metadata/navigation-timing/supported_navigation_type.window.js.ini
  tests/wpt/metadata/performance-timeline/idlharness.any.js.ini
  tests/wpt/metadata/performance-timeline/supportedEntryTypes.any.js.ini
  tests/wpt/metadata/resource-timing/supported_resource_type.any.js.ini
Labels: S-awaiting-merge

#25724 Use rayon for file operations off the main resource thread
  components/net/fetch/methods.rs
  components/net/filemanager_thread.rs
  components/net/resource_thread.rs
  components/net/tests/fetch.rs
  components/net/tests/filemanager_thread.rs
  components/net/tests/http_loader.rs
  components/net/tests/main.rs
Labels: S-awaiting-merge

#25768 Handle access-control header wildcards
  components/net/fetch/methods.rs
  components/net_traits/response.rs
  tests/wpt/metadata/fetch/api/cors/cors-expose-star.sub.any.js.ini
Labels: S-awaiting-merge

#25770 supportsSession() -> isSessionSupported()
  components/script/dom/webidls/XR.webidl
  components/script/dom/xr.rs
  tests/wpt/metadata/webxr/ar-module/xrDevice_isSessionSupported_immersive-ar.https.html.ini
  tests/wpt/metadata/webxr/idlharness.https.window.js.ini
  tests/wpt/metadata/webxr/xrDevice_isSessionSupported_immersive.https.html.ini
  tests/wpt/metadata/webxr/xrDevice_isSessionSupported_immersive_unsupported.https.html.ini
  tests/wpt/metadata/webxr/xrDevice_isSessionSupported_inline.https.html.ini
Labels: S-awaiting-merge

#25773 Always trigger an input sources change event on session creation
  components/script/dom/xr.rs
  components/script/dom/xrinputsourcearray.rs
  components/script/dom/xrsession.rs
Labels: S-awaiting-merge

#25786 Split stacking context fragments into sections in layout_2020
  components/layout_2020/display_list/stacking_context.rs
  components/layout_2020/flow/root.rs
  tests/wpt/metadata-layout-2020/css/CSS2/zindex/stack-floats-003.xht.ini
  tests/wpt/metadata-layout-2020/css/CSS2/zindex/stack-floats-004.xht.ini
Labels: A-layout/2020, S-awaiting-merge

#25780 Update webxr
  Cargo.lock
Labels: S-awaiting-merge

#25752 Add support for WebGL2 `MAX_COLOR_ATTACHMENTS` and `MAX_DRAW_BUFFERS`
  components/script/dom/webgl2renderingcontext.rs
  tests/wpt/webgl/meta/conformance2/renderbuffers/framebuffer-test.html.ini
  tests/wpt/webgl/meta/conformance2/rendering/draw-buffers.html.ini
  tests/wpt/webgl/meta/conformance2/state/gl-object-get-calls.html.ini
Labels: S-awaiting-merge

#25369 Always pass InRealm to GlobalScope::from_context to avoid getting a null global
  components/script/dom/bindings/callback.rs
  components/script/dom/bindings/codegen/Bindings.conf
  components/script/dom/bindings/error.rs
  components/script/dom/bindings/structuredclone.rs
  components/script/dom/create.rs
  components/script/dom/customelementregistry.rs
  components/script/dom/dedicatedworkerglobalscope.rs
  components/script/dom/eventtarget.rs
  components/script/dom/globalscope.rs
  components/script/dom/serviceworkerglobalscope.rs
  components/script/dom/testbinding.rs
  components/script/dom/window.rs
  components/script/dom/windowproxy.rs
  components/script/dom/workerglobalscope.rs
  components/script/script_module.rs
  components/script/script_runtime.rs
Labels: S-awaiting-merge

#25793 Implement GPUComputePassEncoder functions
  Cargo.lock
  components/script/dom/bindings/trace.rs
  components/script/dom/gpubindgroup.rs
  components/script/dom/gpucommandencoder.rs
  components/script/dom/gpucomputepassencoder.rs
  components/script/dom/gpucomputepipeline.rs
  components/script/dom/webidls/GPUComputePassEncoder.webidl
  components/script/dom/webidls/GPUProgrammablePassEncoder.webidl
  components/webgpu/lib.rs
  servo-tidy.toml
Labels: S-awaiting-merge

#25761 Instruct intallation of python-virtualenv
  README.md
  python/servo/bootstrap.py
Labels: S-awaiting-merge

#25809 Thread vslatestinstalled feature to the top
  ports/libsimpleservo/api/Cargo.toml
  ports/libsimpleservo/capi/Cargo.toml
Labels: S-awaiting-merge

#25799 Hide window
  components/compositing/lib.rs
  components/compositing/windowing.rs
  components/constellation/constellation.rs
  components/servo/lib.rs
  ports/libsimpleservo/api/src/lib.rs
  ports/libsimpleservo/capi/src/lib.rs
  support/hololens/ServoApp/BrowserPage.cpp
  support/hololens/ServoApp/ServoApp.vcxproj
  support/hololens/ServoApp/ServoControl/Servo.h
  support/hololens/ServoApp/ServoControl/ServoControl.cpp
  support/hololens/ServoApp/ServoControl/ServoControl.h
  support/hololens/ServoApp/ServoControl/ServoControl.idl
Labels: S-awaiting-merge

#25806 Update ipc-channel and crossbeam-channel
  Cargo.lock
  components/background_hang_monitor/Cargo.toml
  components/bluetooth/Cargo.toml
  components/bluetooth/lib.rs
  components/bluetooth_traits/Cargo.toml
  components/canvas/Cargo.toml
  components/canvas_traits/Cargo.toml
  components/compositing/Cargo.toml
  components/constellation/Cargo.toml
  components/constellation/constellation.rs
  components/constellation/pipeline.rs
  components/debugger/Cargo.toml
  components/devtools/Cargo.toml
  components/devtools_traits/Cargo.toml
  components/embedder_traits/Cargo.toml
  components/gfx/Cargo.toml
  components/layout/Cargo.toml
  components/layout_2020/Cargo.toml
  components/layout_thread/Cargo.toml
  components/layout_thread_2020/Cargo.toml
  components/layout_traits/Cargo.toml
  components/malloc_size_of/Cargo.toml
  components/media/Cargo.toml
  components/metrics/Cargo.toml
  components/msg/Cargo.toml
  components/net/Cargo.toml
  components/net/filemanager_thread.rs
  components/net_traits/Cargo.toml
  components/profile/Cargo.toml
  components/profile_traits/Cargo.toml
  components/profile_traits/ipc.rs
  components/script/Cargo.toml
  components/script_layout_interface/Cargo.toml
  components/script_traits/Cargo.toml
  components/servo/Cargo.toml
  components/style/Cargo.toml
  components/webdriver_server/Cargo.toml
  components/webgpu/Cargo.toml
  components/webvr/Cargo.toml
  components/webvr_traits/Cargo.toml
  ports/glutin/Cargo.toml
  ports/gstplugin/Cargo.toml
  ports/gstplugin/servowebsrc.rs
  ports/libmlservo/Cargo.toml
  ports/libsimpleservo/jniapi/Cargo.toml
  servo-tidy.toml
  tests/unit/metrics/Cargo.toml
  tests/unit/profile/Cargo.toml
  tests/wpt/metadata/webaudio/the-audio-api/the-audiobuffersourcenode-interface/audiobuffersource-multi-channels.html.ini
  tests/wpt/metadata/webaudio/the-audio-api/the-audioparam-interface/setTargetAtTime-after-event-within-block.html.ini
  tests/wpt/metadata/webaudio/the-audio-api/the-audioparam-interface/setValueAtTime-within-block.html.ini
Labels: S-awaiting-merge

#25819 Synchronize ANGLE linking path with VS project.
  python/servo/build_commands.py
Labels: S-awaiting-merge

#25816 Expect dom syntax error in window postmessage sameorigin test
  tests/wpt/mozilla/meta/MANIFEST.json
  tests/wpt/mozilla/meta/mozilla/window-postmessage-sameorigin.html.ini
  tests/wpt/mozilla/tests/mozilla/window-postmessage-sameorigin.html
Labels: S-awaiting-merge

#25784 Add support for WebGL2 framebuffer attachments
  components/script/dom/webgl2renderingcontext.rs
  components/script/dom/webglframebuffer.rs
  components/script/dom/webglrenderbuffer.rs
  components/script/dom/webglrenderingcontext.rs
  tests/wpt/webgl/meta/conformance2/context/methods-2.html.ini
  tests/wpt/webgl/meta/conformance2/renderbuffers/framebuffer-object-attachment.html.ini
  tests/wpt/webgl/meta/conformance2/renderbuffers/framebuffer-test.html.ini
  tests/wpt/webgl/meta/conformance2/rendering/draw-buffers.html.ini
  tests/wpt/webgl/meta/conformance2/rendering/framebuffer-texture-changing-base-level.html.ini
  tests/wpt/webgl/meta/conformance2/rendering/framebuffer-texture-level1.html.ini
  tests/wpt/webgl/meta/conformance2/state/gl-object-get-calls.html.ini
Labels: S-awaiting-merge

#25822 Delay reftest screenshot while WR frame is rendering
  components/compositing/compositor.rs
  components/compositing/compositor_thread.rs
  components/constellation/constellation.rs
  components/servo/lib.rs
Labels: S-awaiting-merge

#25785 Add support for WebGL2 getFramebufferAttachmentParameter
  components/script/dom/webgl2renderingcontext.rs
  tests/wpt/webgl/meta/conformance2/renderbuffers/framebuffer-object-attachment.html.ini
  tests/wpt/webgl/meta/conformance2/renderbuffers/framebuffer-test.html.ini
Labels: S-awaiting-merge

#25825 Disable complex-glsl-does-not-crash.html
  tests/wpt/webgl/meta/conformance/glsl/bugs/complex-glsl-does-not-crash.html.ini
Labels: S-awaiting-merge

#25821 Use new and new_inherited in messagechannel
  components/script/dom/messagechannel.rs
  components/script/dom/webidls/MessageChannel.webidl
Labels: S-awaiting-merge

#25826 Make Background Hang Monitor Optional
  components/config/opts.rs
  components/constellation/constellation.rs
  components/constellation/pipeline.rs
  components/layout_thread/lib.rs
  components/layout_thread_2020/lib.rs
  components/layout_traits/lib.rs
  components/script/script_thread.rs
  components/script_layout_interface/message.rs
  components/script_traits/lib.rs
Labels: S-awaiting-merge

#25810 Add profiling to WebXR
  Cargo.lock
  components/canvas/Cargo.toml
  components/canvas/webgl_thread.rs
  components/canvas_traits/Cargo.toml
  components/canvas_traits/webgl.rs
  components/script/Cargo.toml
  components/script/dom/document.rs
  components/script/dom/xrsession.rs
  components/servo/Cargo.toml
  ports/glutin/Cargo.toml
  ports/libsimpleservo/api/Cargo.toml
  ports/libsimpleservo/capi/Cargo.toml
Labels: S-awaiting-merge

#25771 Leak message ports in Dom, until they are closed
  components/script/dom/globalscope.rs
  tests/wpt/metadata/fetch/security/embedded-credentials.tentative.sub.html.ini
Labels: S-awaiting-merge

#25830 Fix invalid metadata ini contents.
  tests/wpt/metadata/webaudio/the-audio-api/the-audiobuffersourcenode-interface/audiobuffersource-multi-channels.html.ini
Labels: S-awaiting-merge

#25803 Layout viewer for layout 2020
  .gitignore
  Cargo.lock
  components/layout_2020/Cargo.toml
  components/layout_2020/flow/float.rs
  components/layout_2020/flow/inline.rs
  components/layout_2020/flow/mod.rs
  components/layout_2020/flow/root.rs
  components/layout_2020/formatting_contexts.rs
  components/layout_2020/fragments.rs
  components/layout_2020/geom.rs
  components/layout_2020/layout_debug.rs
  components/layout_2020/lib.rs
  components/layout_2020/positioned.rs
  components/layout_2020/query.rs
  components/layout_2020/replaced.rs
  components/layout_2020/sizing.rs
  components/layout_thread_2020/lib.rs
  etc/layout_viewer/css/main.css
  etc/layout_viewer/viewer_2020.html
Labels: S-awaiting-merge

#25738 refactor: rename XR to XRSystem
  components/script/dom/bindings/codegen/Bindings.conf
  components/script/dom/mod.rs
  components/script/dom/navigator.rs
  components/script/dom/webidls/XRSystem.webidl
  components/script/dom/xrsession.rs
  components/script/dom/xrsystem.rs
  tests/wpt/metadata/webxr/idlharness.https.window.js.ini
  tests/wpt/mozilla/meta/MANIFEST.json
  tests/wpt/mozilla/tests/mozilla/interfaces.html
Labels: S-awaiting-merge

#25789 Add support for WebGL2 clear buffer operations
  Cargo.lock
  components/canvas/Cargo.toml
  components/canvas/webgl_thread.rs
  components/canvas_traits/webgl.rs
  components/script/dom/webgl2renderingcontext.rs
  components/script/dom/webidls/WebGL2RenderingContext.webidl
  tests/wpt/webgl/meta/conformance2/context/methods-2.html.ini
  tests/wpt/webgl/meta/conformance2/rendering/clear-srgb-color-buffer.html.ini
  tests/wpt/webgl/meta/conformance2/rendering/clearbuffer-sub-source.html.ini
  tests/wpt/webgl/meta/conformance2/rendering/clearbufferfv-with-alpha-false.html.ini
Labels: S-awaiting-merge

#25668 Stop iframes from including their ancestors
  components/script/dom/htmliframeelement.rs
Labels: S-awaiting-merge

#25832 Fix `mach run --headless`
  python/servo/post_build_commands.py
Labels: S-awaiting-merge

#25345 Avoid accessing global objects from DOM destructors
  components/script/dom/audiocontext.rs
  components/script/dom/document.rs
  components/script/dom/htmlmediaelement.rs
  components/script/dom/mediasession.rs
  components/script/dom/navigator.rs
  components/script/dom/node.rs
  components/script/dom/offlineaudiocontext.rs
  components/script/dom/vrdisplay.rs
  components/script/dom/vrdisplaycapabilities.rs
  components/script/dom/vreyeparameters.rs
  components/script/dom/vrfieldofview.rs
  components/script/dom/vrstageparameters.rs
  components/script/dom/window.rs
  components/script/dom/xrsystem.rs
  components/script/script_thread.rs
Labels: S-awaiting-merge

#25834 Fix invalid WPT metadata.
  tests/wpt/metadata/webaudio/the-audio-api/the-audiobuffersourcenode-interface/audiobuffersource-multi-channels.html.ini
Labels: S-awaiting-merge

#25740 Per fetch file token for blob url
  components/net/fetch/methods.rs
  components/net/filemanager_thread.rs
  components/net/resource_thread.rs
  components/net/tests/fetch.rs
  components/net/tests/filemanager_thread.rs
  components/net/tests/main.rs
  components/net_traits/filemanager_thread.rs
  components/script/dom/globalscope.rs
  tests/wpt/metadata/FileAPI/url/url-in-tags-revoke.window.js.ini
  tests/wpt/metadata/FileAPI/url/url-with-fetch.any.js.ini
Labels: S-awaiting-merge

#25831 Implement mapReadAsync function of GPUBuffer
  components/script/dom/bindings/codegen/Bindings.conf
  components/script/dom/gpubuffer.rs
  components/script/dom/gpudevice.rs
  components/script/dom/webidls/GPUBuffer.webidl
  components/webgpu/lib.rs
Labels: S-awaiting-merge

#25841 Remove azure canvas backend
  Cargo.lock
  components/canvas/Cargo.toml
  components/canvas/azure_backend.rs
  components/canvas/build.rs
  components/canvas/canvas_data.rs
  components/canvas/lib.rs
  components/gfx/platform/freetype/font_template.rs
  components/servo/Cargo.toml
  docs/ORGANIZATION.md
  ports/glutin/Cargo.toml
  ports/libmlservo/Cargo.toml
  ports/libsimpleservo/api/Cargo.toml
  ports/libsimpleservo/capi/Cargo.toml
  ports/libsimpleservo/jniapi/Cargo.toml
  python/servo/command_base.py
  python/tidy/servo_tidy/licenseck.py
  python/tidy/servo_tidy_tests/rust_tidy.rs
Labels: S-awaiting-merge

#25801 Refactor CanvasRenderingContext2D.arc() and .ellipse()
  Cargo.lock
  components/canvas/Cargo.toml
  components/canvas/raqote_backend.rs
  tests/wpt/metadata/2dcontext/line-styles/2d.line.cap.round.html.ini
  tests/wpt/metadata/2dcontext/path-objects/2d.path.arc.twopie.1.html.ini
  tests/wpt/metadata/2dcontext/path-objects/2d.path.arc.twopie.3.html.ini
  tests/wpt/metadata/2dcontext/path-objects/2d.path.arcTo.scale.html.ini
  tests/wpt/metadata/2dcontext/path-objects/2d.path.arcTo.shape.curve2.html.ini
  tests/wpt/metadata/2dcontext/path-objects/2d.path.arcTo.transformation.html.ini
  tests/wpt/metadata/offscreen-canvas/line-styles/2d.line.cap.round.html.ini
  tests/wpt/metadata/offscreen-canvas/line-styles/2d.line.cap.round.worker.js.ini
  tests/wpt/metadata/offscreen-canvas/path-objects/2d.path.arc.twopie.1.html.ini
  tests/wpt/metadata/offscreen-canvas/path-objects/2d.path.arc.twopie.1.worker.js.ini
  tests/wpt/metadata/offscreen-canvas/path-objects/2d.path.arc.twopie.3.html.ini
  tests/wpt/metadata/offscreen-canvas/path-objects/2d.path.arc.twopie.3.worker.js.ini
  tests/wpt/metadata/offscreen-canvas/path-objects/2d.path.arcTo.scale.html.ini
  tests/wpt/metadata/offscreen-canvas/path-objects/2d.path.arcTo.scale.worker.js.ini
  tests/wpt/metadata/offscreen-canvas/path-objects/2d.path.arcTo.shape.curve2.html.ini
  tests/wpt/metadata/offscreen-canvas/path-objects/2d.path.arcTo.shape.curve2.worker.js.ini
  tests/wpt/metadata/offscreen-canvas/path-objects/2d.path.arcTo.transformation.html.ini
  tests/wpt/metadata/offscreen-canvas/path-objects/2d.path.arcTo.transformation.worker.js.ini
Labels: S-awaiting-merge

#25843 Update webxr for openxr VR support.
  Cargo.lock
Labels: S-awaiting-merge

#25850 Fixing some style related issues in WebGPU.
  components/constellation/constellation.rs
  components/script/dom/globalscope.rs
  components/script/dom/gpu.rs
  components/script/dom/gpuadapter.rs
  components/script/dom/gpubuffer.rs
  components/script/dom/gpucommandencoder.rs
  components/script/dom/gpucomputepassencoder.rs
  components/script/dom/gpudevice.rs
  components/script/dom/gpuqueue.rs
  components/webgpu/lib.rs
Labels: S-awaiting-merge

#25428 make Document.getElementsByName a live collection
  components/script/dom/document.rs
  components/script/dom/nodelist.rs
  tests/wpt/metadata/html/dom/documents/dom-tree-accessors/document.getElementsByName/document.getElementsByName-liveness.html.ini
Labels: S-awaiting-merge

#25864 Rename AbsolutelyPositionedBox::layout to AbsolutelyPositionedBox::to_hoisted
  components/layout_2020/flow/inline.rs
  components/layout_2020/flow/mod.rs
  components/layout_2020/positioned.rs
Labels: A-layout/2020, S-awaiting-merge

#25866 Generate ::before and ::after content from url() for layout2020
  components/layout_2020/dom_traversal.rs
  components/layout_2020/replaced.rs
  components/style/values/specified/counters.rs
  tests/wpt/metadata-layout-2020/css/CSS2/generated-content/content-004.xht.ini
  tests/wpt/metadata-layout-2020/css/css-content/pseudo-element-inline-box.html.ini
Labels: S-awaiting-merge

#25869 Move tinyfiledialog call from script to embedder
  Cargo.lock
  components/embedder_traits/lib.rs
  components/script/Cargo.toml
  components/script/dom/globalscope.rs
  components/script/dom/permissions.rs
  components/script/dom/window.rs
  ports/glutin/browser.rs
  ports/libsimpleservo/api/src/lib.rs
  tests/wpt/metadata/permissions/idlharness.any.js.ini
Labels: S-awaiting-merge
