Repository servo/servo, pull requests merged in 2020-04, with the labels that each got.

#26076 Reduce unnecessary layout queries in babylon.js content
  components/script/dom/document.rs
  components/script/dom/element.rs
  components/script/dom/raredata.rs
  components/script/dom/window.rs
  components/script/script_thread.rs
Labels: S-awaiting-merge

#26051 Hook up new openxr context menu gesture to embedder context menu machinery
  Cargo.lock
  components/compositing/windowing.rs
  components/servo/lib.rs
  ports/glutin/embedder.rs
  ports/libsimpleservo/api/src/lib.rs
Labels: S-awaiting-merge

#26077 webgl: Don't dirty canvas element while in immersive mode.
  components/script/dom/navigator.rs
  components/script/dom/webglrenderingcontext.rs
  components/script/dom/window.rs
Labels: S-awaiting-merge

#26081 Add support for Debian in mach bootstrap
  python/servo/bootstrap.py
Labels: S-awaiting-merge

#26083 More layout cleanups from the introduction of a lifetime in LayoutDom<T>
  components/layout_thread/dom_wrapper.rs
  components/layout_thread_2020/dom_wrapper.rs
  components/script/dom/bindings/root.rs
  components/script/dom/canvasrenderingcontext2d.rs
  components/script/dom/document.rs
  components/script/dom/element.rs
  components/script/dom/htmlbodyelement.rs
  components/script/dom/htmlcanvaselement.rs
  components/script/dom/htmlfontelement.rs
  components/script/dom/htmlhrelement.rs
  components/script/dom/htmliframeelement.rs
  components/script/dom/htmlimageelement.rs
  components/script/dom/htmlinputelement.rs
  components/script/dom/htmltablecellelement.rs
  components/script/dom/htmltableelement.rs
  components/script/dom/htmltablerowelement.rs
  components/script/dom/htmltablesectionelement.rs
  components/script/dom/htmltextareaelement.rs
  components/script/dom/macros.rs
  components/script/dom/node.rs
  components/script/dom/shadowroot.rs
  components/script/dom/svgsvgelement.rs
  components/script/lib.rs
Labels: S-awaiting-merge

#26074 Avoid infinitely looping CSS transitions.
  components/layout/animation.rs
  components/style/animation.rs
  components/style/matching.rs
  tests/wpt/mozilla/meta-layout-2020/css/transitionend_event.html.ini
  tests/wpt/mozilla/meta/MANIFEST.json
  tests/wpt/mozilla/tests/css/transitionend_event.html
Labels: S-awaiting-merge

#26085 Use a valid debug option in the example command in the Debugging guide.
  docs/HACKING_QUICKSTART.md
Labels: S-awaiting-merge

#26086 Support SpiderMonkey jitspew.
  Cargo.lock
  components/script/Cargo.toml
  components/servo/Cargo.toml
  ports/glutin/Cargo.toml
  ports/libsimpleservo/api/Cargo.toml
  ports/libsimpleservo/capi/Cargo.toml
Labels: S-awaiting-merge

#26093 Update webxr.
  Cargo.lock
Labels: S-awaiting-merge

#26102 Add support for requersting RDP access from generic-worker
  etc/taskcluster/decision_task.py
  etc/taskcluster/decisionlib.py
Labels: S-awaiting-merge

#26106 Check the BHM option before starting it in multi-process mode.
  components/servo/lib.rs
Labels: S-awaiting-merge

#26105 Make DOM own the style and layout data, in an UnsafeCell
  components/layout/data.rs
  components/layout/query.rs
  components/layout/wrapper.rs
  components/layout_2020/dom_traversal.rs
  components/layout_2020/wrapper.rs
  components/layout_thread/dom_wrapper.rs
  components/layout_thread/lib.rs
  components/layout_thread_2020/dom_wrapper.rs
  components/layout_thread_2020/lib.rs
  components/msg/constellation_msg.rs
  components/script/dom/node.rs
  components/script/dom/window.rs
  components/script/script_thread.rs
  components/script_layout_interface/lib.rs
  components/script_layout_interface/message.rs
  components/script_layout_interface/wrapper_traits.rs
  components/style/dom.rs
  components/style/gecko/wrapper.rs
  components/style/invalidation/element/state_and_attributes.rs
  components/style/traversal.rs
  tests/unit/script/size_of.rs
Labels: S-awaiting-merge

#26110 Kill ServoLayoutElement::note_dirty_descendant
  components/layout_thread/dom_wrapper.rs
  components/layout_thread/lib.rs
  components/layout_thread_2020/dom_wrapper.rs
  components/layout_thread_2020/lib.rs
  components/script/dom/document.rs
Labels: S-awaiting-merge

#26087 Fix ServiceWorker in multiprocess
  components/constellation/constellation.rs
  components/constellation/lib.rs
  components/constellation/pipeline.rs
  components/constellation/sandboxing.rs
  components/constellation/serviceworker.rs
  components/net/resource_thread.rs
  components/net_traits/lib.rs
  components/script/init.rs
  components/script/lib.rs
  components/script/serviceworker_manager.rs
  components/script_traits/lib.rs
  components/script_traits/script_msg.rs
  components/servo/lib.rs
Labels: S-awaiting-merge

#26113 Drive-by refactoring of some unsafe code in stylo
  components/style/driver.rs
  components/style/scoped_tls.rs
  components/style/values/computed/font.rs
  components/style/values/specified/font.rs
  components/style/values/specified/svg.rs
Labels: S-awaiting-merge

#26103 Extract user_agent from global opts and allow embedder to provide user agent string
  components/compositing/windowing.rs
  components/config/opts.rs
  components/constellation/constellation.rs
  components/constellation/pipeline.rs
  components/servo/lib.rs
  ports/glutin/app.rs
  ports/glutin/main2.rs
  ports/gstplugin/servowebsrc.rs
  ports/libsimpleservo/api/src/lib.rs
Labels: S-awaiting-merge

#26116 Add InRealm argument to Callback trait
  components/script/dom/promise.rs
  components/script/dom/promisenativehandler.rs
  components/script/dom/testbinding.rs
  components/script/script_module.rs
Labels: S-awaiting-merge

#26124 Add troubleshooting for rustup picking the wrong default toolchain
  README.md
Labels: A-build, A-documentation, P-windows, S-awaiting-merge

#26126 Fix misspelled "get_suported_extensions" function
  components/script/dom/webgl_extensions/extensions.rs
  components/script/dom/webglrenderingcontext.rs
Labels: S-awaiting-merge

#26127 Update README instructions for Fedora, remove Ubuntu 14.04 workarounds
  README.md
Labels: S-awaiting-merge

#26104 Update parse_length to match spec
  components/style/attr.rs
  tests/unit/style/attr.rs
  tests/wpt/metadata/html/rendering/dimension-attributes.html.ini
  tests/wpt/metadata/html/rendering/non-replaced-elements/the-hr-element-0/width.html.ini
Labels: S-awaiting-merge

#26120 Remove postorder traversal from layout 2020 during styling
  components/layout/data.rs
  components/layout/query.rs
  components/layout/traversal.rs
  components/layout/wrapper.rs
  components/layout_2020/data.rs
  components/layout_2020/dom_traversal.rs
  components/layout_2020/lib.rs
  components/layout_2020/query.rs
  components/layout_2020/traversal.rs
  components/layout_2020/wrapper.rs
  components/layout_thread/dom_wrapper.rs
  components/layout_thread/lib.rs
  components/layout_thread_2020/dom_wrapper.rs
  components/layout_thread_2020/lib.rs
  components/script/devtools.rs
  components/script/dom/bindings/trace.rs
  components/script/dom/element.rs
  components/script/dom/node.rs
  components/script/dom/window.rs
  components/script_layout_interface/lib.rs
  components/script_layout_interface/message.rs
  components/script_layout_interface/rpc.rs
  components/script_layout_interface/wrapper_traits.rs
Labels: S-awaiting-merge

#26130 Update euclid
  Cargo.lock
  components/canvas/canvas_data.rs
  components/script/canvas_state.rs
  components/script/dom/canvasrenderingcontext2d.rs
  components/script/dom/htmlcanvaselement.rs
  components/script/dom/imagedata.rs
  components/script/dom/paintrenderingcontext2d.rs
  components/script/dom/webgl2renderingcontext.rs
  components/script/euclidext.rs
  tests/wpt/metadata/2dcontext/path-objects/2d.path.stroke.scale2.html.ini
  tests/wpt/metadata/2dcontext/path-objects/2d.path.stroke.skew.html.ini
  tests/wpt/metadata/offscreen-canvas/path-objects/2d.path.stroke.scale2.html.ini
  tests/wpt/metadata/offscreen-canvas/path-objects/2d.path.stroke.scale2.worker.js.ini
  tests/wpt/metadata/offscreen-canvas/path-objects/2d.path.stroke.skew.html.ini
  tests/wpt/metadata/offscreen-canvas/path-objects/2d.path.stroke.skew.worker.js.ini
Labels: S-awaiting-merge

#26135 Add initial support for VertexAttribI4* and VertexAttribIPointer
  components/canvas/webgl_thread.rs
  components/canvas_traits/webgl.rs
  components/script/dom/vertexarrayobject.rs
  components/script/dom/webgl2renderingcontext.rs
  components/script/dom/webglprogram.rs
  components/script/dom/webglrenderingcontext.rs
  components/script/dom/webglvertexarrayobject.rs
  components/script/dom/webglvertexarrayobjectoes.rs
  components/script/dom/webidls/WebGL2RenderingContext.webidl
  tests/wpt/webgl/meta/conformance2/attribs/gl-vertex-attrib-i-render.html.ini
  tests/wpt/webgl/meta/conformance2/attribs/gl-vertex-attrib.html.ini
  tests/wpt/webgl/meta/conformance2/attribs/gl-vertexattribipointer-offsets.html.ini
  tests/wpt/webgl/meta/conformance2/attribs/gl-vertexattribipointer.html.ini
  tests/wpt/webgl/meta/conformance2/buffers/get-buffer-sub-data-validity.html.ini
  tests/wpt/webgl/meta/conformance2/rendering/attrib-type-match.html.ini
  tests/wpt/webgl/meta/conformance2/rendering/element-index-uint.html.ini
  tests/wpt/webgl/meta/conformance2/state/gl-object-get-calls.html.ini
  tests/wpt/webgl/meta/conformance2/vertex_arrays/vertex-array-object.html.ini
Labels: S-awaiting-merge

#26133 Update raqote
  Cargo.lock
  tests/wpt/metadata/2dcontext/fill-and-stroke-styles/2d.gradient.radial.inside3.html.ini
  tests/wpt/metadata/2dcontext/line-styles/2d.line.cap.closed.html.ini
  tests/wpt/metadata/css/css-paint-api/overdraw.https.html.ini
  tests/wpt/metadata/offscreen-canvas/fill-and-stroke-styles/2d.gradient.radial.inside3.html.ini
  tests/wpt/metadata/offscreen-canvas/fill-and-stroke-styles/2d.gradient.radial.inside3.worker.js.ini
  tests/wpt/metadata/offscreen-canvas/line-styles/2d.line.cap.closed.html.ini
  tests/wpt/metadata/offscreen-canvas/line-styles/2d.line.cap.closed.worker.js.ini
Labels: S-awaiting-merge

#26141 implement mach clean-uwp
  python/servo/build_commands.py
Labels: S-awaiting-merge

#26146 Support WebGL2 contexts in immersive mode
  components/script/dom/webglframebuffer.rs
  components/script/dom/webidls/XRWebGLLayer.webidl
  components/script/dom/xrwebgllayer.rs
Labels: S-awaiting-merge

#26152 Fix missing Babylon.js content
  Cargo.lock
Labels: S-awaiting-merge

#26155 Update user agent strings
  components/servo/lib.rs
Labels: S-awaiting-merge

#26154 Do not filter out platform objects when doing dictionary conversions in overload resolution
  components/script/dom/bindings/codegen/CodegenRust.py
  components/script/dom/testbinding.rs
  components/script/dom/webidls/TestBinding.webidl
  tests/wpt/mozilla/meta-layout-2020/mozilla/overload_dict.html.ini
  tests/wpt/mozilla/meta/MANIFEST.json
  tests/wpt/mozilla/meta/mozilla/overload_dict.html.ini
  tests/wpt/mozilla/tests/mozilla/overload_dict.html
Labels: S-awaiting-merge

#26071 Upgrade to rustc 1.44.0-nightly (42abbd887 2020-04-07)
  Xargo.toml
  components/canvas_traits/webgl_channel/mod.rs
  components/media/media_channel/mod.rs
  components/net/http_loader.rs
  components/net/tests/main.rs
  components/script/script_thread.rs
  components/script_plugins/lib.rs
  ports/glutin/events_loop.rs
  ports/libsimpleservo/capi/src/lib.rs
  python/tidy/servo_tidy/tidy.py
  python/tidy/servo_tidy_tests/script_thread.rs
  python/tidy/servo_tidy_tests/test_tidy.py
  rust-toolchain
Labels: S-awaiting-merge

#26163 Remove assertion for negative value from get_uniform_location
  components/canvas/webgl_thread.rs
Labels: S-awaiting-merge

#26170 Add FromJSValConvertible for enums
  components/script/dom/bindings/codegen/CodegenRust.py
Labels: S-awaiting-merge

#26174 Add 'python3-devel' to the DNF bootstrap packages list
  README.md
  python/servo/bootstrap.py
Labels: S-awaiting-merge

#26111 Update checking origin trustworthy align to spec
  components/script/dom/urlhelper.rs
  tests/wpt/mozilla/meta-layout-2020/mozilla/service-workers/service-worker-registration.https.html.ini
  tests/wpt/mozilla/meta/MANIFEST.json
  tests/wpt/mozilla/tests/mozilla/service-workers/service-worker-registration.https.html
Labels: S-awaiting-merge

#26167 Remove some no-longer-necessary dependencies
  README.md
  etc/taskcluster/docker/build.dockerfile
  ports/glutin/main2.rs
  ports/glutin/skia_symbols.rs
  python/servo/bootstrap.py
  python/servo/command_base.py
Labels: S-awaiting-merge

#26168 Added first-cut implementation of XR layers
  components/config/prefs.rs
  components/script/dom/mod.rs
  components/script/dom/webidls/XRLayer.webidl
  components/script/dom/webidls/XRMediaBinding.webidl
  components/script/dom/webidls/XRRenderState.webidl
  components/script/dom/webidls/XRSubImage.webidl
  components/script/dom/webidls/XRWebGLBinding.webidl
  components/script/dom/webidls/XRWebGLSubImage.webidl
  components/script/dom/xrlayer.rs
  components/script/dom/xrmediabinding.rs
  components/script/dom/xrrenderstate.rs
  components/script/dom/xrsession.rs
  components/script/dom/xrsubimage.rs
  components/script/dom/xrwebglbinding.rs
  components/script/dom/xrwebglsubimage.rs
  resources/prefs.json
  tests/wpt/mozilla/meta/MANIFEST.json
  tests/wpt/mozilla/meta/webxr/layers.html.ini
  tests/wpt/mozilla/tests/webxr/layers.html
Labels: A-xr-zomg, S-awaiting-merge

#26164 Dirty canvas when exiting immersive sessions
  components/script/dom/webglrenderingcontext.rs
  components/script/dom/xrsession.rs
  components/script/dom/xrsystem.rs
Labels: S-awaiting-merge

#26181 style: Refactor some animations code
  components/style/animation.rs
  components/style/matching.rs
Labels: S-awaiting-merge

#26147 Avoid GL errors with LineWidth commands
  components/canvas/webgl_thread.rs
Labels: S-awaiting-merge

#26183 Use hash_map::Entry to save a map lookup
  components/constellation/constellation.rs
Labels: S-awaiting-merge

#26188 add some missing dependencies to bootstrap.py
  python/servo/bootstrap.py
Labels: S-awaiting-merge

#26143 Fix webgl transform feedback
  components/script/dom/webgl2renderingcontext.rs
  tests/wpt/webgl/meta/conformance2/transform_feedback/simultaneous_binding.html.ini
  tests/wpt/webgl/meta/conformance2/transform_feedback/switching-objects.html.ini
  tests/wpt/webgl/meta/conformance2/transform_feedback/transform_feedback.html.ini
  tests/wpt/webgl/meta/conformance2/transform_feedback/two-unreferenced-varyings.html.ini
  tests/wpt/webgl/meta/conformance2/transform_feedback/unwritten-output-defaults-to-zero.html.ini
Labels: S-awaiting-merge

#26166 Remove DomRefCell wrapper for CanvasState
  components/script/canvas_state.rs
  components/script/dom/canvasrenderingcontext2d.rs
  components/script/dom/offscreencanvasrenderingcontext2d.rs
Labels: S-awaiting-merge

#26185 handle detached array in XRView
  components/script/dom/xrview.rs
Labels: S-awaiting-merge

#26191 Automatically enable WebGL 2 for specific domains.
  components/script/dom/htmlcanvaselement.rs
  components/script/dom/webgl2renderingcontext.rs
  components/script/dom/webidls/WebGL2RenderingContext.webidl
Labels: S-awaiting-merge

#26197 Use preview OpenXR runtime
  support/hololens/ServoApp/Package.appxmanifest
  support/hololens/ServoApp/ServoControl/Servo.cpp
Labels: S-awaiting-merge

#26190 Remove use of soon-to-be-deprecated unstable feature
  components/layout_2020/flow/inline.rs
  components/layout_2020/flow/mod.rs
  components/layout_2020/lib.rs
  components/layout_2020/positioned.rs
  components/script/dom/bindings/codegen/CodegenRust.py
  components/script/dom/bindings/root.rs
  components/script/lib.rs
  components/script_layout_interface/lib.rs
  ports/glutin/main.rs
Labels: S-awaiting-merge

#26193 Upgrade clang to 9.0 on Windows.
  python/servo/packages.py
  python/servo/testing_commands.py
Labels: S-awaiting-merge

#26198 Report error when vcvarsall fails
  python/servo/build_commands.py
Labels: S-awaiting-merge

#26205 Don't shutdown the app when it's suspended.
  support/hololens/ServoApp/App.cpp
Labels: S-awaiting-merge

#26206 Add VCINSTALLDIR to the 'do not run within vcvarsall' check
  python/servo/build_commands.py
Labels: S-awaiting-merge

#26200 style: Add an iterator for transition properties
  components/style/animation.rs
  components/style/gecko/wrapper.rs
  components/style/properties/helpers/animated_properties.mako.rs
  components/style/properties/properties.mako.rs
  tests/wpt/metadata/css/css-transitions/events-005.html.ini
  tests/wpt/metadata/css/css-transitions/properties-value-002.html.ini
Labels: A-stylo, S-awaiting-merge

#26196 Dump all UWP logging output to a file
  ports/libsimpleservo/capi/src/lib.rs
  ports/libsimpleservo/capi/src/vslogger.rs
  support/hololens/ServoApp/ServoControl/Servo.cpp
  support/hololens/ServoApp/ServoControl/Servo.h
Labels: S-awaiting-merge

#23661 Refactor ImageCache::find_image_or_metadata -> ImageCache::{get_image, track_image}
  components/layout/context.rs
  components/layout_2020/context.rs
  components/net/image_cache.rs
  components/net_traits/image_cache.rs
  components/script/canvas_state.rs
  components/script/dom/htmlcanvaselement.rs
  components/script/dom/htmlimageelement.rs
  components/script/dom/htmlvideoelement.rs
  components/script/image_listener.rs
Labels: S-awaiting-merge

#26201 Refactor style rule tree, without actually fixing its !Send behaviour yet
  components/style/rule_tree/core.rs
  components/style/rule_tree/level.rs
  components/style/rule_tree/map.rs
  components/style/rule_tree/mod.rs
  components/style/rule_tree/source.rs
  components/style/rule_tree/unsafe_box.rs
Labels: S-awaiting-merge

#26207 Publish new UWP package
  etc/taskcluster/decision_task.py
  python/servo/package_commands.py
  support/hololens/ServoApp/Package.appxmanifest
Labels: S-awaiting-merge

#26218 style: Sync changes from mozilla-central.
  components/malloc_size_of/lib.rs
  components/selectors/builder.rs
  components/selectors/matching.rs
  components/selectors/parser.rs
  components/selectors/visitor.rs
  components/style/gecko/selector_parser.rs
  components/style/invalidation/element/invalidation_map.rs
  components/style/rule_tree/mod.rs
  components/style/rule_tree/source.rs
  components/style/selector_map.rs
  components/style/servo/selector_parser.rs
  components/style/stylist.rs
Labels: S-awaiting-merge

#26217 Disable RUST_BACKTRACE in unit tests on macOS.
  python/servo/testing_commands.py
Labels: S-awaiting-merge

#26214 Eliminate `AnimationFrame`
  components/layout/animation.rs
  components/style/animation.rs
  components/style/matching.rs
Labels: S-awaiting-merge

#26220 Always upgrade existing weak child references in the rule tree
  components/style/rule_tree/core.rs
Labels: S-awaiting-merge

#26223 Dedupe the dirs dependency
  Cargo.lock
  components/config/Cargo.toml
  servo-tidy.toml
Labels: S-awaiting-merge

#26221 [python/servo/bootstrap.py] Add missing comma
  python/servo/bootstrap.py
Labels: S-awaiting-merge

#26171 Implement hit testing API
  Cargo.lock
  components/script/dom/bindings/trace.rs
  components/script/dom/fakexrdevice.rs
  components/script/dom/mod.rs
  components/script/dom/webidls/FakeXRDevice.webidl
  components/script/dom/webidls/XRFrame.webidl
  components/script/dom/webidls/XRHitTestResult.webidl
  components/script/dom/webidls/XRHitTestSource.webidl
  components/script/dom/webidls/XRRay.webidl
  components/script/dom/webidls/XRSession.webidl
  components/script/dom/webidls/XRTest.webidl
  components/script/dom/xrframe.rs
  components/script/dom/xrhittestresult.rs
  components/script/dom/xrhittestsource.rs
  components/script/dom/xrray.rs
  components/script/dom/xrreferencespace.rs
  components/script/dom/xrsession.rs
  components/script/dom/xrspace.rs
  components/script/dom/xrtest.rs
  tests/wpt/metadata/webxr/ar-module/xrDevice_isSessionSupported_immersive-ar.https.html.ini
  tests/wpt/metadata/webxr/ar-module/xrDevice_requestSession_immersive-ar.https.html.ini
  tests/wpt/metadata/webxr/dom-overlay/ar_dom_overlay.https.html.ini
  tests/wpt/metadata/webxr/dom-overlay/ar_dom_overlay_hit_test.https.html.ini
  tests/wpt/metadata/webxr/hit-test/ar_hittest_subscription_inputSources.https.html.ini
  tests/wpt/metadata/webxr/hit-test/ar_hittest_subscription_refSpaces.https.html.ini
  tests/wpt/metadata/webxr/hit-test/ar_hittest_subscription_states_regular.https.html.ini
  tests/wpt/metadata/webxr/hit-test/ar_hittest_subscription_transientInputSources.https.html.ini
  tests/wpt/metadata/webxr/hit-test/xrRay_constructor.https.html.ini
  tests/wpt/metadata/webxr/hit-test/xrRay_matrix.https.html.ini
  tests/wpt/mozilla/meta/MANIFEST.json
  tests/wpt/mozilla/tests/mozilla/interfaces.html
  tests/wpt/mozilla/tests/webxr/create_session.html
  tests/wpt/mozilla/tests/webxr/layers.html
  tests/wpt/mozilla/tests/webxr/obtain_frame.html
Labels: S-awaiting-merge

#26227 Make the rule tree actually threadsafe
  components/layout_thread/lib.rs
  components/layout_thread_2020/lib.rs
  components/style/rule_tree/core.rs
  components/style/rule_tree/map.rs
  components/style/rule_tree/unsafe_box.rs
Labels: S-awaiting-merge

#25944 Update UWP toolchain version
  support/hololens/ServoApp/ServoApp.vcxproj
Labels: S-awaiting-merge

#26237 OSMesa is no longer a build dependency
  README.md
  components/config/opts.rs
  components/servo/lib.rs
  etc/taskcluster/docker/run.dockerfile
  python/servo/bootstrap.py
Labels: S-awaiting-merge

#26239 Remove glutin from the dependency graph
  Cargo.lock
  ports/libsimpleservo/api/Cargo.toml
  servo-tidy.toml
Labels: S-awaiting-merge

#26238 Only enable RUST_BACKTRACE in non-mac build environment on CI.
  etc/taskcluster/decision_task.py
Labels: S-awaiting-merge

#26241 Add a minimal alternative to `cargo graph`
  etc/crates-graph.py
Labels: S-awaiting-merge

#26260 Fix InvalidateSubFramebuffer error handling
  components/script/dom/webgl2renderingcontext.rs
  tests/wpt/webgl/meta/conformance2/renderbuffers/invalidate-framebuffer.html.ini
Labels: S-awaiting-merge

#26253 Add a dummy implementation of contentEditable
  components/script/dom/htmlelement.rs
  components/script/dom/webidls/ElementContentEditable.webidl
  tests/wpt/metadata/html/dom/idlharness.https.html.ini
Labels: A-content/script, S-awaiting-merge

#26268 Update mozjs for better Window builds.
  Cargo.lock
Labels: S-awaiting-merge

#26276 style: Sync changes from mozilla-central.
  components/style/animation.rs
  components/style/rule_tree/core.rs
  components/style/rule_tree/mod.rs
Labels: S-awaiting-merge

#26291 Update WebGL IDL
  components/script/dom/webgl2renderingcontext.rs
  components/script/dom/webglrenderingcontext.rs
  components/script/dom/webidls/WebGL2RenderingContext.webidl
  components/script/dom/webidls/WebGLRenderingContext.webidl
Labels: S-awaiting-merge

#26289 Replaced failible boolean with an enum
  components/script/dom/vertexarrayobject.rs
  components/script/dom/webgl2renderingcontext.rs
  components/script/dom/webglbuffer.rs
  components/script/dom/webglframebuffer.rs
  components/script/dom/webglprogram.rs
  components/script/dom/webglquery.rs
  components/script/dom/webglrenderbuffer.rs
  components/script/dom/webglrenderingcontext.rs
  components/script/dom/webglsampler.rs
  components/script/dom/webglshader.rs
  components/script/dom/webglsync.rs
  components/script/dom/webgltexture.rs
  components/script/dom/webgltransformfeedback.rs
  components/script/dom/webglvertexarrayobject.rs
  components/script/dom/webglvertexarrayobjectoes.rs
Labels: S-awaiting-merge

#26294 Update mozjs and mozjs-sys
  Cargo.lock
Labels: S-awaiting-merge

#26231 Implement various checks on the Location setters
  components/script/dom/location.rs
  tests/wpt/metadata/fullscreen/api/document-exit-fullscreen-active-document.html.ini
  tests/wpt/metadata/html/browsers/browsing-the-web/navigating-across-documents/005.html.ini
  tests/wpt/metadata/html/browsers/browsing-the-web/unloading-documents/beforeunload-synchronous.html.ini
  tests/wpt/metadata/html/browsers/history/the-location-interface/location-protocol-setter-non-broken-weird.html.ini
  tests/wpt/metadata/html/browsers/history/the-location-interface/location-protocol-setter-non-broken.html.ini
  tests/wpt/metadata/html/browsers/history/the-location-interface/location-protocol-setter.html.ini
  tests/wpt/metadata/html/browsers/history/the-location-interface/no-browsing-context.window.js.ini
  tests/wpt/metadata/url/failure.html.ini
Labels: S-awaiting-merge

#26285 Add ElementAnimationState and PossibleElementAnimationState
  Cargo.lock
  components/layout/animation.rs
  components/layout_thread/lib.rs
  components/layout_thread_2020/lib.rs
  components/style/Cargo.toml
  components/style/animation.rs
  components/style/context.rs
  components/style/lib.rs
  components/style/matching.rs
Labels: S-awaiting-merge

#26292 Update backtrace dependency.
  Cargo.lock
  Cargo.toml
Labels: S-awaiting-merge

#26312 Provide feedback when OpenXR can't start
  Cargo.lock
  components/script/dom/xrsystem.rs
  ports/libsimpleservo/api/src/lib.rs
  support/hololens/ServoApp/ServoControl/Servo.cpp
  support/hololens/ServoApp/ServoControl/ServoControl.cpp
Labels: S-awaiting-merge

#26308 Add support for transitionrun events
  components/atoms/static_atoms.txt
  components/layout/animation.rs
  components/layout_thread/lib.rs
  components/script/dom/event.rs
  components/script/dom/macros.rs
  components/script/dom/webidls/EventHandler.webidl
  components/script/script_thread.rs
  components/script_traits/lib.rs
  tests/wpt/metadata/css/css-transitions/before-load-001.html.ini
  tests/wpt/metadata/css/css-transitions/idlharness.html.ini
  tests/wpt/metadata/css/css-transitions/non-rendered-element-001.html.ini
Labels: A-layout/animations, S-awaiting-merge

#26319 Some Cargo.toml cleanups
  components/constellation/Cargo.toml
  components/script/Cargo.toml
  ports/glutin/Cargo.toml
  ports/libsimpleservo/capi/Cargo.toml
Labels: S-awaiting-merge

#26320 Some more Cargo.toml cleanups
  components/net/Cargo.toml
  components/script/Cargo.toml
  ports/gstplugin/Cargo.toml
  ports/libmlservo/Cargo.toml
Labels: S-awaiting-merge

#26321 Update Ubuntu base docker image for Taskcluster
  etc/taskcluster/docker/base.dockerfile
Labels: S-awaiting-merge

#26293 Update serde_json.
  Cargo.lock
  components/webdriver_server/lib.rs
Labels: S-awaiting-merge

#26316 Add experimental hand tracking support
  Cargo.lock
  components/config/prefs.rs
  components/script/dom/bindings/trace.rs
  components/script/dom/fakexrdevice.rs
  components/script/dom/mod.rs
  components/script/dom/webidls/XRFrame.webidl
  components/script/dom/webidls/XRHand.webidl
  components/script/dom/webidls/XRInputSource.webidl
  components/script/dom/webidls/XRJointPose.webidl
  components/script/dom/webidls/XRJointSpace.webidl
  components/script/dom/xrframe.rs
  components/script/dom/xrhand.rs
  components/script/dom/xrinputsource.rs
  components/script/dom/xrjointpose.rs
  components/script/dom/xrjointspace.rs
  components/script/dom/xrspace.rs
  python/tidy/servo_tidy/tidy.py
  resources/prefs.json
Labels: S-awaiting-merge

#26339 Add support for WebGL2 buffer types in GetBufferParameter
  components/script/dom/webgl2renderingcontext.rs
  components/script/dom/webglrenderingcontext.rs
  tests/wpt/webgl/meta/conformance2/state/gl-object-get-calls.html.ini
Labels: S-awaiting-merge

#26343 Update link
  components/style/README.md
Labels: S-awaiting-merge

#26325 Improve devtools experience when navigating
  Cargo.lock
  components/devtools/Cargo.toml
  components/devtools/actors/browsing_context.rs
  components/devtools/actors/console.rs
  components/devtools/actors/inspector.rs
  components/devtools/actors/root.rs
  components/devtools/actors/worker.rs
  components/devtools/lib.rs
  components/devtools_traits/lib.rs
  components/script/dom/dedicatedworkerglobalscope.rs
  components/script/dom/document.rs
  components/script/dom/serviceworkerregistration.rs
  components/script/dom/window.rs
  components/script/dom/worker.rs
  components/script/dom/workerglobalscope.rs
  components/script/script_thread.rs
  components/script/serviceworker_manager.rs
Labels: S-awaiting-merge

#26346 Improve devtools output for console APIs
  Cargo.lock
  Cargo.toml
  components/script/devtools.rs
  components/script/dom/console.rs
Labels: S-awaiting-merge

#26230 Update Winrt and xrloader and ANGLE NuGet packages.
  support/hololens/ServoApp/ServoApp.vcxproj
  support/hololens/ServoApp/ServoApp.vcxproj.filters
  support/hololens/ServoApp/packages.config
Labels: S-awaiting-merge

#26352 Add a pref for webxr glwindow anaglyphic red-cyan stereo
  Cargo.lock
  components/config/prefs.rs
  ports/glutin/app.rs
  ports/glutin/headed_window.rs
  resources/prefs.json
Labels: A-xr-zomg, S-awaiting-merge

#26354 Add support for some more WebGL2 limit parameters
  Cargo.lock
  components/canvas/Cargo.toml
  components/canvas/webgl_limits.rs
  components/canvas_traits/webgl.rs
  components/script/dom/webgl2renderingcontext.rs
  tests/wpt/webgl/meta/conformance2/state/gl-get-calls.html.ini
Labels: S-awaiting-merge

#26333 Add support for even more WebGL2 GetParameter enums
  components/canvas_traits/webgl.rs
  tests/wpt/webgl/meta/conformance2/state/gl-get-calls.html.ini
Labels: S-awaiting-merge

#26363 Split animation cancellation from update_style_for_animation
  components/layout/animation.rs
  components/style/animation.rs
  components/style/matching.rs
Labels: A-layout/animations, S-awaiting-merge

#26359 Update Ubuntu version up to 20.04
  python/servo/bootstrap.py
Labels: S-awaiting-merge
