Repository servo/servo, pull requests merged in 2020-05, with the labels that each got.

#26362 Add support for animationend event
  components/layout/animation.rs
  components/layout/context.rs
  components/layout_thread/lib.rs
  components/script/dom/animationevent.rs
  components/script/dom/macros.rs
  components/script/dom/mod.rs
  components/script/dom/webidls/AnimationEvent.webidl
  components/script/dom/webidls/EventHandler.webidl
  components/script/dom/window.rs
  components/script/script_thread.rs
  components/script_layout_interface/message.rs
  components/script_traits/lib.rs
  components/style/animation.rs
  tests/wpt/metadata/css/css-animations/Element-getAnimations.tentative.html.ini
  tests/wpt/metadata/css/css-animations/animationevent-interface.html.ini
  tests/wpt/metadata/css/css-animations/animationevent-types.html.ini
  tests/wpt/metadata/css/css-animations/idlharness.html.ini
  tests/wpt/metadata/css/css-variables/variable-animation-substitute-into-keyframe-shorthand.html.ini
  tests/wpt/metadata/css/css-variables/variable-animation-substitute-into-keyframe-transform.html.ini
  tests/wpt/metadata/css/css-variables/variable-animation-substitute-into-keyframe.html.ini
  tests/wpt/metadata/css/css-variables/variable-animation-substitute-within-keyframe-fallback.html.ini
  tests/wpt/metadata/css/css-variables/variable-animation-substitute-within-keyframe-multiple.html.ini
  tests/wpt/metadata/css/css-variables/variable-animation-substitute-within-keyframe.html.ini
  tests/wpt/metadata/dom/events/webkit-animation-end-event.html.ini
  tests/wpt/metadata/dom/events/webkit-transition-end-event.html.ini
  tests/wpt/mozilla/meta/MANIFEST.json
  tests/wpt/mozilla/tests/mozilla/interfaces.html
Labels: S-awaiting-merge

#26336 Add support for WebGL2 MIN_PROGRAM_TEXEL_OFFSET
  components/canvas/webgl_limits.rs
  components/canvas_traits/webgl.rs
  components/script/dom/webgl2renderingcontext.rs
  tests/wpt/webgl/meta/conformance2/state/gl-get-calls.html.ini
Labels: S-awaiting-merge

#26215 Fix combination of border and border-radius being drawn incorrectly
  components/layout/display_list/builder.rs
  tests/wpt/mozilla/meta-layout-2020/css/border-radius-image.html.ini
  tests/wpt/mozilla/meta/MANIFEST.json
  tests/wpt/mozilla/meta/css/border-radius-image.html.ini
  tests/wpt/mozilla/tests/css/border-radius-image-ref.html
  tests/wpt/mozilla/tests/css/border-radius-image.html
Labels: S-awaiting-merge

#26401 fixed BaseAudioContext.DecodeAudioData progress callback
  components/script/dom/baseaudiocontext.rs
Labels: S-awaiting-merge

#26396 Update ORGANIZATION.md
  docs/ORGANIZATION.md
Labels: S-awaiting-merge

#26398 Add a fast path in Element::SetInnerHTML when the value is small and trivial text
  components/script/dom/element.rs
  components/script/dom/htmlframesetelement.rs
  components/script/dom/htmlheadelement.rs
  components/script/dom/htmlhtmlelement.rs
  components/script/dom/htmlselectelement.rs
  components/script/dom/htmltablecaptionelement.rs
  components/script/dom/htmltablecellelement.rs
  components/script/dom/htmltablecolelement.rs
  components/script/dom/htmltableelement.rs
  components/script/dom/htmltablerowelement.rs
  components/script/dom/htmltablesectionelement.rs
  components/script/dom/htmltemplateelement.rs
  components/script/dom/node.rs
Labels: S-awaiting-merge

#26413 Use PYTHON2 variable for script's codegen.
  components/script/build.rs
Labels: S-awaiting-merge

#26415 Update some URLs
  components/script/dom/htmlcanvaselement.rs
Labels: S-awaiting-merge

#26418 Fix Fedora installation guide
  README.md
Labels: S-awaiting-merge

#26399 Update doc links and code snippet for trace implementation in JS-Servos-only-GC.md
  components/script/docs/JS-Servos-only-GC.md
Labels: S-awaiting-merge

#26423 Workarounds for webxr glwindow on macos
  Cargo.lock
  Cargo.toml
  components/config/prefs.rs
  ports/glutin/headed_window.rs
  resources/prefs.json
Labels: A-xr-zomg, S-awaiting-merge

#25357 Fix a few things regarding redirects
  components/net/http_loader.rs
  components/net_traits/lib.rs
  components/net_traits/response.rs
  components/script/dom/response.rs
  components/script/fetch.rs
  tests/wpt/metadata/fetch/api/basic/request-headers.any.js.ini
  tests/wpt/metadata/fetch/api/redirect/redirect-method.any.js.ini
  tests/wpt/metadata/xhr/send-redirect-post-upload.htm.ini
  tests/wpt/metadata/xhr/send-redirect-to-cors.htm.ini
Labels: S-awaiting-merge

#26438 Separate values in Headers with ", ", not ","
  components/script/dom/headers.rs
  tests/wpt/metadata/fetch/api/headers/headers-combine.html.ini
Labels: S-awaiting-merge

#26452 Split animations and transitions into separate lists
  components/layout/animation.rs
  components/layout_thread/lib.rs
  components/style/animation.rs
  components/style/context.rs
  components/style/matching.rs
Labels: S-awaiting-merge

#26455 Properly set the url on the Response object when the response is an opaqueredirect
  components/net/image_cache.rs
  components/net_traits/lib.rs
  components/net_traits/response.rs
  components/script/dom/eventsource.rs
  components/script/dom/xmlhttprequest.rs
  components/script/fetch.rs
  components/script/stylesheet_loader.rs
  tests/wpt/metadata/fetch/api/redirect/redirect-mode.any.js.ini
Labels: S-awaiting-merge

#26446 Update webxr
  Cargo.lock
  ports/libsimpleservo/api/src/lib.rs
  servo-tidy.toml
Labels: S-awaiting-merge

#26437 Generalize the 2020 regression report to show local unexpected failures
  .gitignore
  etc/taskcluster/decision_task.py
  etc/taskcluster/decisionlib.py
  servo-tidy.toml
  tests/wpt/reftests-report/gen.py
  tests/wpt/reftests-report/prism.css
  tests/wpt/reftests-report/prism.js
Labels: S-awaiting-merge

#26450 Add referrerpolicy to list of relevant mutations
  components/net_traits/lib.rs
  components/script/dom/htmlimageelement.rs
  components/script/dom/webidls/HTMLImageElement.webidl
  tests/wpt/metadata/custom-elements/reactions/HTMLImageElement.html.ini
  tests/wpt/metadata/html/dom/idlharness.https.html.ini
  tests/wpt/metadata/html/semantics/embedded-content/the-img-element/relevant-mutations.html.ini
Labels: S-awaiting-merge

#26465 Bump rust-url from 2.1.0 to 2.1.1
  Cargo.lock
  tests/wpt/metadata/html/browsers/history/the-location-interface/location-protocol-setter-non-broken-weird.html.ini
  tests/wpt/metadata/html/browsers/history/the-location-interface/location-protocol-setter-non-broken.html.ini
  tests/wpt/metadata/html/browsers/history/the-location-interface/location-protocol-setter.html.ini
  tests/wpt/metadata/html/browsers/history/the-location-interface/location_hash.html.ini
  tests/wpt/metadata/url/a-element-xhtml.xhtml.ini
  tests/wpt/metadata/url/a-element.html.ini
  tests/wpt/metadata/url/failure.html.ini
  tests/wpt/metadata/url/url-constructor.html.ini
  tests/wpt/metadata/url/url-setters-stripping.any.js.ini
  tests/wpt/metadata/url/url-setters.html.ini
Labels: S-awaiting-merge

#26475 Initiate redirect fetching iff the request has a location
  components/constellation/network_listener.rs
  tests/wpt/metadata/cookies/http-state/domain-tests.html.ini
  tests/wpt/metadata/cookies/http-state/ordering-tests.html.ini
  tests/wpt/metadata/cookies/http-state/path-tests.html.ini
Labels: S-awaiting-merge

#26481 Remove a TODO from the implementation of getComputedStyle
  components/script/dom/cssstyledeclaration.rs
Labels: S-awaiting-merge

#26483 Implement EXT_frag_depth
  components/canvas_traits/webgl.rs
  components/script/dom/webgl_extensions/ext/extfragdepth.rs
  components/script/dom/webgl_extensions/ext/mod.rs
  components/script/dom/webgl_extensions/extensions.rs
  components/script/dom/webglrenderingcontext.rs
  components/script/dom/webglshader.rs
  components/script/dom/webidls/EXTFragDepth.webidl
Labels: S-awaiting-merge

#26485 layout_2020: Add support for transform-style
  components/layout_2020/display_list/stacking_context.rs
  components/layout_2020/flow/root.rs
  tests/wpt/metadata-layout-2020/css/css-transforms/css-transform-3d-transform-style.html.ini
  tests/wpt/metadata-layout-2020/css/css-transforms/transform3d-sorting-005.html.ini
Labels: S-awaiting-merge

#26464 Move most animation processing to script
  Cargo.lock
  components/constellation/constellation.rs
  components/layout/animation.rs
  components/layout/context.rs
  components/layout/lib.rs
  components/layout_thread/lib.rs
  components/layout_thread_2020/lib.rs
  components/msg/constellation_msg.rs
  components/script/Cargo.toml
  components/script/animation_timeline.rs
  components/script/animations.rs
  components/script/dom/bindings/trace.rs
  components/script/dom/document.rs
  components/script/dom/window.rs
  components/script/lib.rs
  components/script/script_thread.rs
  components/script_layout_interface/Cargo.toml
  components/script_layout_interface/message.rs
  components/script_traits/lib.rs
  components/script_traits/script_msg.rs
  components/style/animation.rs
Labels: S-awaiting-merge

#26487 Fix radial gradients for html canvas element
  Cargo.lock
  tests/wpt/metadata-layout-2020/html/canvas/element/drawing-images-to-the-canvas/drawimage_canvas.html.ini
  tests/wpt/metadata-layout-2020/html/canvas/element/fill-and-stroke-styles/2d.gradient.radial.cone.beside.html.ini
  tests/wpt/metadata-layout-2020/html/canvas/element/fill-and-stroke-styles/2d.gradient.radial.touch1.html.ini
  tests/wpt/metadata-layout-2020/html/canvas/element/fill-and-stroke-styles/2d.gradient.radial.touch2.html.ini
  tests/wpt/metadata-layout-2020/html/canvas/element/fill-and-stroke-styles/2d.gradient.radial.touch3.html.ini
  tests/wpt/metadata-layout-2020/html/canvas/offscreen/fill-and-stroke-styles/2d.gradient.radial.cone.beside.html.ini
  tests/wpt/metadata-layout-2020/html/canvas/offscreen/fill-and-stroke-styles/2d.gradient.radial.cone.beside.worker.js.ini
  tests/wpt/metadata-layout-2020/html/canvas/offscreen/fill-and-stroke-styles/2d.gradient.radial.touch1.html.ini
  tests/wpt/metadata-layout-2020/html/canvas/offscreen/fill-and-stroke-styles/2d.gradient.radial.touch1.worker.js.ini
  tests/wpt/metadata-layout-2020/html/canvas/offscreen/fill-and-stroke-styles/2d.gradient.radial.touch2.html.ini
  tests/wpt/metadata-layout-2020/html/canvas/offscreen/fill-and-stroke-styles/2d.gradient.radial.touch2.worker.js.ini
  tests/wpt/metadata-layout-2020/html/canvas/offscreen/fill-and-stroke-styles/2d.gradient.radial.touch3.html.ini
  tests/wpt/metadata-layout-2020/html/canvas/offscreen/fill-and-stroke-styles/2d.gradient.radial.touch3.worker.js.ini
  tests/wpt/metadata/html/canvas/element/drawing-images-to-the-canvas/drawimage_canvas.html.ini
  tests/wpt/metadata/html/canvas/element/fill-and-stroke-styles/2d.gradient.radial.cone.beside.html.ini
  tests/wpt/metadata/html/canvas/element/fill-and-stroke-styles/2d.gradient.radial.touch1.html.ini
  tests/wpt/metadata/html/canvas/element/fill-and-stroke-styles/2d.gradient.radial.touch2.html.ini
  tests/wpt/metadata/html/canvas/element/fill-and-stroke-styles/2d.gradient.radial.touch3.html.ini
  tests/wpt/metadata/html/canvas/offscreen/fill-and-stroke-styles/2d.gradient.radial.cone.beside.html.ini
  tests/wpt/metadata/html/canvas/offscreen/fill-and-stroke-styles/2d.gradient.radial.cone.beside.worker.js.ini
  tests/wpt/metadata/html/canvas/offscreen/fill-and-stroke-styles/2d.gradient.radial.touch1.html.ini
  tests/wpt/metadata/html/canvas/offscreen/fill-and-stroke-styles/2d.gradient.radial.touch1.worker.js.ini
  tests/wpt/metadata/html/canvas/offscreen/fill-and-stroke-styles/2d.gradient.radial.touch2.html.ini
  tests/wpt/metadata/html/canvas/offscreen/fill-and-stroke-styles/2d.gradient.radial.touch2.worker.js.ini
  tests/wpt/metadata/html/canvas/offscreen/fill-and-stroke-styles/2d.gradient.radial.touch3.html.ini
  tests/wpt/metadata/html/canvas/offscreen/fill-and-stroke-styles/2d.gradient.radial.touch3.worker.js.ini
Labels: S-awaiting-merge

#26335 Update webrender.
  Cargo.lock
  components/canvas/Cargo.toml
  components/canvas/canvas_data.rs
  components/canvas/canvas_paint_thread.rs
  components/canvas/webgl_mode/inprocess.rs
  components/canvas/webgl_thread.rs
  components/canvas_traits/lib.rs
  components/compositing/Cargo.toml
  components/constellation/constellation.rs
  components/gfx/Cargo.toml
  components/gfx/font_cache_thread.rs
  components/layout/display_list/builder.rs
  components/layout/display_list/items.rs
  components/layout/display_list/mod.rs
  components/layout/display_list/webrender_helpers.rs
  components/layout/sequential.rs
  components/layout_2020/display_list/mod.rs
  components/layout_2020/display_list/stacking_context.rs
  components/net/image_cache.rs
  components/net_traits/lib.rs
  components/script/dom/htmlmediaelement.rs
  components/script_traits/lib.rs
  components/servo/Cargo.toml
  components/servo/lib.rs
  components/webgpu/Cargo.toml
  tests/wpt/metadata/css/css-images/gradient-move-stops.html.ini
  tests/wpt/metadata/css/css-transforms/transform-input-012.html.ini
  tests/wpt/metadata/html/rendering/non-replaced-elements/the-fieldset-and-legend-elements/fieldset-transform-translatez.html.ini
Labels: S-awaiting-merge

#26476 Use an appropriate graphics adapter when openxr is present.
  Cargo.lock
  ports/libsimpleservo/api/src/lib.rs
Labels: S-awaiting-merge

#26430 Implement referrer policy
  components/net/http_loader.rs
Labels: S-awaiting-merge

#26495 Fix reftest report regression.
  tests/wpt/reftests-report/gen.py
Labels: S-awaiting-merge

#26458 Update webxr with secondary view support
  Cargo.lock
  components/script/dom/xrviewerpose.rs
  components/script/dom/xrwebgllayer.rs
Labels: S-awaiting-merge

#26496 Remove AnimatedProperty
  components/script/animations.rs
  components/style/animation.rs
  components/style/properties/helpers/animated_properties.mako.rs
  tests/wpt/metadata/css/CSS2/linebox/animations/line-height-interpolation.html.ini
  tests/wpt/metadata/css/compositing/mix-blend-mode/mix-blend-mode-animation.html.ini
  tests/wpt/metadata/css/css-backgrounds/animations/border-width-interpolation.html.ini
  tests/wpt/metadata/css/css-transforms/animation/rotate-interpolation.html.ini
  tests/wpt/metadata/css/css-transforms/animation/scale-interpolation.html.ini
  tests/wpt/metadata/css/css-transforms/animation/translate-interpolation.html.ini
  tests/wpt/metadata/css/css-ui/animation/outline-width-interpolation.html.ini
Labels: S-awaiting-merge

#26501 Dedupe dwrote
  Cargo.lock
  components/canvas/Cargo.toml
  components/canvas_traits/Cargo.toml
  servo-tidy.toml
Labels: S-awaiting-merge

#26491 Handle cancelAnimationFrame() when called within a requestAnimationFr…
  components/script/dom/xrsession.rs
  tests/wpt/metadata/webxr/xrSession_cancelAnimationFrame.https.html.ini
Labels: S-awaiting-merge

#26434 Allow BabylonJS playground to load
  components/script/dom/document.rs
  components/script/dom/event.rs
  components/script/dom/eventtarget.rs
  components/script/dom/webidls/Document.webidl
  components/script/dom/webidls/Window.webidl
  components/script/dom/window.rs
  tests/wpt/metadata/dom/events/event-global.html.ini
  tests/wpt/metadata/dom/idlharness.window.js.ini
  tests/wpt/metadata/html/dom/idlharness.https.html.ini
Labels: S-awaiting-merge

#26503 Fix an issue with the rooting of animating nodes
  components/script/script_thread.rs
Labels: S-awaiting-merge

#26513 Reject incompatible webgl texture pixel data
  components/canvas_traits/webgl.rs
  components/script/dom/webgl_extensions/extensions.rs
  components/script/dom/webglrenderingcontext.rs
Labels: S-awaiting-merge

#26510 Add integrity hash for nightly builds
  python/servo/package_commands.py
Labels: S-awaiting-merge

#26516 Some Cargo.toml cleanups
  components/background_hang_monitor/Cargo.toml
  components/bluetooth/Cargo.toml
  components/bluetooth_traits/Cargo.toml
  components/compositing/Cargo.toml
  ports/glutin/Cargo.toml
  ports/libsimpleservo/api/Cargo.toml
  ports/libsimpleservo/capi/Cargo.toml
  ports/libsimpleservo/jniapi/Cargo.toml
Labels: S-awaiting-merge

#26524 Fix file extension for Linux nightly
  python/servo/package_commands.py
Labels: S-awaiting-merge

#26525 Share single gpu_id_hub among all threads in a process
  components/script/dom/bindings/trace.rs
  components/script/dom/dedicatedworkerglobalscope.rs
  components/script/dom/dissimilaroriginwindow.rs
  components/script/dom/globalscope.rs
  components/script/dom/gpu.rs
  components/script/dom/gpuadapter.rs
  components/script/dom/gpudevice.rs
  components/script/dom/serviceworkerglobalscope.rs
  components/script/dom/window.rs
  components/script/dom/worker.rs
  components/script/dom/workerglobalscope.rs
  components/script/dom/workletglobalscope.rs
  components/script/script_thread.rs
Labels: S-awaiting-merge

#26527 layout_2020: Fix WebRender display list dumping
  components/layout_thread_2020/lib.rs
Labels: S-awaiting-merge

#26526 More Cargo.toml cleanups
  components/config/Cargo.toml
  components/config_plugins/Cargo.toml
  components/devtools/Cargo.toml
  components/devtools_traits/Cargo.toml
  components/domobject_derive/Cargo.toml
  components/embedder_traits/Cargo.toml
  components/fallible/Cargo.toml
  components/gfx/Cargo.toml
  components/gfx_traits/Cargo.toml
  components/hashglobe/Cargo.toml
  components/layout/Cargo.toml
  components/layout_2020/Cargo.toml
  components/layout_thread/Cargo.toml
  components/layout_thread_2020/Cargo.toml
  components/layout_traits/Cargo.toml
Labels: S-awaiting-merge

#26414 Correctly paint the CSS canvas’ background
  components/layout_2020/display_list/background.rs
  components/layout_2020/display_list/mod.rs
  components/layout_2020/display_list/stacking_context.rs
  components/layout_2020/dom_traversal.rs
  components/layout_2020/element_data.rs
  components/layout_2020/flow/mod.rs
  components/layout_2020/flow/root.rs
  components/layout_2020/layout_debug.rs
  components/layout_2020/lib.rs
  components/layout_2020/query.rs
  components/layout_2020/style_ext.rs
  components/layout_thread_2020/lib.rs
  components/script/dom/node.rs
  components/script_layout_interface/lib.rs
  components/style/values/specified/box.rs
  tests/wpt/metadata-layout-2020/css/CSS2/abspos/abspos-containing-block-initial-004a.xht.ini
  tests/wpt/metadata-layout-2020/css/CSS2/abspos/abspos-containing-block-initial-004b.xht.ini
  tests/wpt/metadata-layout-2020/css/CSS2/abspos/abspos-containing-block-initial-004c.xht.ini
  tests/wpt/metadata-layout-2020/css/CSS2/abspos/abspos-containing-block-initial-004d.xht.ini
  tests/wpt/metadata-layout-2020/css/CSS2/abspos/abspos-containing-block-initial-004e.xht.ini
  tests/wpt/metadata-layout-2020/css/CSS2/abspos/abspos-containing-block-initial-004f.xht.ini
  tests/wpt/metadata-layout-2020/css/CSS2/abspos/abspos-containing-block-initial-005a.xht.ini
  tests/wpt/metadata-layout-2020/css/CSS2/abspos/abspos-containing-block-initial-005b.xht.ini
  tests/wpt/metadata-layout-2020/css/CSS2/abspos/abspos-containing-block-initial-005c.xht.ini
  tests/wpt/metadata-layout-2020/css/CSS2/abspos/abspos-containing-block-initial-005d.xht.ini
  tests/wpt/metadata-layout-2020/css/CSS2/backgrounds/background-body-001.xht.ini
  tests/wpt/metadata-layout-2020/css/CSS2/backgrounds/background-root-001.xht.ini
  tests/wpt/metadata-layout-2020/css/CSS2/backgrounds/background-root-002.xht.ini
  tests/wpt/metadata-layout-2020/css/CSS2/backgrounds/background-root-005.xht.ini
  tests/wpt/metadata-layout-2020/css/CSS2/backgrounds/background-root-007.xht.ini
  tests/wpt/metadata-layout-2020/css/CSS2/backgrounds/background-root-008.xht.ini
  tests/wpt/metadata-layout-2020/css/CSS2/backgrounds/background-root-009.xht.ini
  tests/wpt/metadata-layout-2020/css/CSS2/backgrounds/background-root-010.xht.ini
  tests/wpt/metadata-layout-2020/css/CSS2/backgrounds/background-root-012b.xht.ini
  tests/wpt/metadata-layout-2020/css/CSS2/backgrounds/background-root-015.xht.ini
  tests/wpt/metadata-layout-2020/css/CSS2/backgrounds/background-root-016.xht.ini
  tests/wpt/metadata-layout-2020/css/CSS2/backgrounds/background-root-018.xht.ini
  tests/wpt/metadata-layout-2020/css/CSS2/backgrounds/background-root-019.xht.ini
  tests/wpt/metadata-layout-2020/css/CSS2/backgrounds/background-root-024.xht.ini
  tests/wpt/metadata-layout-2020/css/CSS2/box-display/root-box-003.xht.ini
  tests/wpt/metadata-layout-2020/css/CSS2/css1/c45-bg-canvas-000.xht.ini
  tests/wpt/metadata-layout-2020/css/CSS2/margin-padding-clear/margin-collapse-021.xht.ini
  tests/wpt/metadata-layout-2020/css/CSS2/visudet/height-percentage-003a.xht.ini
  tests/wpt/metadata-layout-2020/css/css-backgrounds/background-attachment-margin-root-001.html.ini
  tests/wpt/metadata-layout-2020/css/css-backgrounds/background-color-body-propagation-001.html.ini
  tests/wpt/metadata-layout-2020/css/css-backgrounds/background-color-body-propagation-003.html.ini
  tests/wpt/metadata-layout-2020/css/css-backgrounds/background-margin-root.html.ini
  tests/wpt/metadata-layout-2020/css/css-backgrounds/background-margin-transformed-root.html.ini
  tests/wpt/metadata-layout-2020/css/css-backgrounds/background-margin-will-change-root.html.ini
  tests/wpt/metadata-layout-2020/css/css-color/t421-rgb-func-whitespace-b.xht.ini
  tests/wpt/metadata-layout-2020/css/css-color/t422-rgba-func-whitespace-b.xht.ini
  tests/wpt/metadata-layout-2020/css/css-color/t423-transparent-2-a.xht.ini
  tests/wpt/mozilla/meta-layout-2020/css/root_height_a.html.ini
  tests/wpt/mozilla/meta/MANIFEST.json
  tests/wpt/mozilla/tests/mozilla/scroll_root.html
  tests/wpt/mozilla/tests/mozilla/scroll_root_ref.html
Labels: A-layout/2020, S-awaiting-merge

#26541 Validate copybuffertobuffer() + some spec update
  components/script/dom/bindings/trace.rs
  components/script/dom/gpubindgrouplayout.rs
  components/script/dom/gpubuffer.rs
  components/script/dom/gpucommandencoder.rs
  components/script/dom/gpucomputepassencoder.rs
  components/script/dom/gpudevice.rs
  components/script/dom/webidls/GPUBindGroup.webidl
  components/script/dom/webidls/GPUBindGroupLayout.webidl
  components/script/dom/webidls/GPUBuffer.webidl
  components/script/dom/webidls/GPUCommandEncoder.webidl
  components/script/dom/webidls/GPUComputePassEncoder.webidl
Labels: S-awaiting-merge

#26537 layout_2020: Implement support for backface-visibility
  components/layout_2020/display_list/background.rs
  components/layout_2020/display_list/mod.rs
  components/layout_2020/display_list/stacking_context.rs
  components/layout_2020/style_ext.rs
  tests/wpt/metadata-layout-2020/css/css-transforms/composited-under-rotateY-180deg-clip-perspective.html.ini
  tests/wpt/metadata-layout-2020/css/css-transforms/composited-under-rotateY-180deg-clip.html.ini
  tests/wpt/metadata-layout-2020/css/css-transforms/composited-under-rotateY-180deg.html.ini
  tests/wpt/metadata-layout-2020/css/css-transforms/rotateY-180deg-with-overflow-scroll.html.ini
  tests/wpt/metadata-layout-2020/css/css-transforms/transform3d-backface-visibility-001.html.ini
  tests/wpt/metadata-layout-2020/css/css-transforms/transform3d-backface-visibility-002.html.ini
  tests/wpt/metadata-layout-2020/css/css-transforms/transform3d-backface-visibility-003.html.ini
  tests/wpt/metadata-layout-2020/css/css-transforms/transform3d-backface-visibility-004.html.ini
  tests/wpt/metadata-layout-2020/css/css-transforms/transform3d-backface-visibility-006.html.ini
  tests/wpt/metadata-layout-2020/css/css-transforms/transform3d-backface-visibility-007.html.ini
Labels: A-layout/2020, S-awaiting-merge

#26544 Introduce import.meta hook for module script
  components/script/script_module.rs
  tests/wpt/include.ini
  tests/wpt/metadata/html/semantics/scripting-1/the-script-element/module/import-meta/import-meta-url.html.ini
Labels: S-awaiting-merge

#26519 Implement `animation-fill-mode`
  components/style/animation.rs
  components/style/matching.rs
  components/style/properties/longhands/box.mako.rs
  tests/wpt/metadata/css/css-animations/animation-delay-010.html.ini
  tests/wpt/metadata/css/css-variables/variable-animation-substitute-into-keyframe-shorthand.html.ini
  tests/wpt/metadata/css/css-variables/variable-animation-substitute-into-keyframe.html.ini
  tests/wpt/metadata/css/css-variables/variable-animation-substitute-within-keyframe-fallback.html.ini
  tests/wpt/metadata/css/css-variables/variable-animation-substitute-within-keyframe-multiple.html.ini
  tests/wpt/metadata/css/css-variables/variable-animation-substitute-within-keyframe.html.ini
  tests/wpt/metadata/css/cssom/getComputedStyle-animations-replaced-into-ib-split.html.ini
  tests/wpt/mozilla/meta-layout-2020/css/animations/__dir__.ini
  tests/wpt/mozilla/meta-layout-2020/css/animations/animation-fill-mode.html.ini
  tests/wpt/mozilla/meta-layout-2020/css/animations/basic-transition.html.ini
  tests/wpt/mozilla/meta-layout-2020/css/animations/transition-raf.html.ini
  tests/wpt/mozilla/meta/MANIFEST.json
  tests/wpt/mozilla/tests/css/animations/animation-fill-mode.html
Labels: S-awaiting-merge

#26551 Update to handle per-view eye transforms
  Cargo.lock
  components/script/dom/bindings/trace.rs
  components/script/dom/xrframe.rs
  components/script/dom/xrreferencespace.rs
  components/script/dom/xrsession.rs
  components/script/dom/xrview.rs
  components/script/dom/xrviewerpose.rs
  components/script/dom/xrwebgllayer.rs
  tests/wpt/metadata/webxr/xrSession_input_events_end.https.html.ini
Labels: S-awaiting-merge

#26484 Implement concept of dirty root
  components/layout/traversal.rs
  components/layout/wrapper.rs
  components/layout_2020/dom_traversal.rs
  components/layout_thread/lib.rs
  components/layout_thread_2020/dom_wrapper.rs
  components/layout_thread_2020/lib.rs
  components/script/dom/bindings/cell.rs
  components/script/dom/document.rs
  components/script/dom/element.rs
  components/script/dom/node.rs
  components/script/dom/range.rs
  components/script/dom/shadowroot.rs
  components/script/dom/window.rs
  components/script_layout_interface/message.rs
  components/style/driver.rs
  tests/unit/script/size_of.rs
Labels: S-awaiting-merge

#26499 Add creator URL, creator base URL and creator origin to browsing context
  components/script/dom/blob.rs
  components/script/dom/document.rs
  components/script/dom/htmlanchorelement.rs
  components/script/dom/location.rs
  components/script/dom/url.rs
  components/script/dom/windowproxy.rs
  components/script/script_thread.rs
  tests/wpt/metadata/FileAPI/url/sandboxed-iframe.html.ini
  tests/wpt/metadata/FileAPI/url/url-format.any.js.ini
  tests/wpt/metadata/css/css-values/viewport-units-after-font-load.html.ini
  tests/wpt/metadata/fetch/security/dangling-markup-mitigation.tentative.html.ini
  tests/wpt/metadata/html/browsers/browsing-the-web/navigating-across-documents/010.html.ini
  tests/wpt/metadata/html/infrastructure/urls/terminology-0/document-base-url.html.ini
  tests/wpt/metadata/html/semantics/document-metadata/the-base-element/base_about_blank.html.ini
  tests/wpt/metadata/html/semantics/document-metadata/the-base-element/base_srcdoc.html.ini
  tests/wpt/metadata/html/semantics/embedded-content/the-iframe-element/iframe_sandbox_anchor_download_allow_downloads.sub.tentative.html.ini
  tests/wpt/metadata/html/semantics/embedded-content/the-iframe-element/iframe_sandbox_anchor_download_block_downloads.sub.tentative.html.ini
  tests/wpt/metadata/html/semantics/embedded-content/the-iframe-element/iframe_sandbox_navigation_download_allow_downloads.sub.tentative.html.ini
  tests/wpt/metadata/html/semantics/embedded-content/the-iframe-element/iframe_sandbox_navigation_download_block_downloads.sub.tentative.html.ini
  tests/wpt/metadata/html/semantics/embedded-content/the-img-element/move-element-and-scroll.html.ini
  tests/wpt/metadata/html/semantics/embedded-content/the-img-element/sizes/sizes-dynamic-001-ref.html.ini
  tests/wpt/metadata/html/semantics/embedded-content/the-img-element/sizes/sizes-dynamic-001.html.ini
  tests/wpt/metadata/html/webappapis/dynamic-markup-insertion/opening-the-input-stream/abort-while-navigating.window.js.ini
  tests/wpt/metadata/referrer-policy/generic/sandboxed-iframe-with-opaque-origin.html.ini
  tests/wpt/metadata/xhr/open-url-about-blank-window.htm.ini
  tests/wpt/metadata/xhr/open-url-javascript-window-2.htm.ini
Labels: S-awaiting-merge

#26546 check http_state in determine_request_referrer
  components/net/fetch/methods.rs
  components/net/http_loader.rs
  components/net/tests/data_loader.rs
  components/net/tests/fetch.rs
  components/net/tests/http_cache.rs
  components/net/tests/http_loader.rs
  components/net_traits/request.rs
  components/script/dom/dedicatedworkerglobalscope.rs
  components/script/dom/document.rs
  components/script/dom/globalscope.rs
  components/script/dom/request.rs
  components/script/dom/urlhelper.rs
  components/script/fetch.rs
  components/script/serviceworkerjob.rs
  components/url/lib.rs
Labels: S-awaiting-merge

#26574 Remove deprecated crate wincolor
  Cargo.lock
Labels: S-awaiting-merge

#26540 Add support for faster reversing of interrupted transitions
  components/style/animation.rs
  tests/wpt/mozilla/meta/MANIFEST.json
  tests/wpt/mozilla/tests/css/animations/faster-reversing-of-transitions.html
Labels: S-awaiting-merge

#26317 ServiceWorker: restructure Job Queue, Register flow, to better match spec
  components/constellation/constellation.rs
  components/msg/constellation_msg.rs
  components/script/dom/bindings/trace.rs
  components/script/dom/client.rs
  components/script/dom/globalscope.rs
  components/script/dom/navigationpreloadmanager.rs
  components/script/dom/serviceworker.rs
  components/script/dom/serviceworkercontainer.rs
  components/script/dom/serviceworkerglobalscope.rs
  components/script/dom/serviceworkerregistration.rs
  components/script/dom/workerglobalscope.rs
  components/script/lib.rs
  components/script/script_thread.rs
  components/script/serviceworker_manager.rs
  components/script/serviceworkerjob.rs
  components/script_traits/lib.rs
  components/script_traits/script_msg.rs
  tests/wpt/mozilla/meta-layout-2020/mozilla/service-workers/service-worker-registration.https.html.ini
  tests/wpt/mozilla/meta/MANIFEST.json
  tests/wpt/mozilla/meta/mozilla/service-workers/service-worker-registration.https.html.ini
  tests/wpt/mozilla/tests/mozilla/service-workers/service-worker-registration.https.html
Labels: S-awaiting-merge

#26520 Add support for WebGL2 TexImage2D
  components/script/dom/webgl2renderingcontext.rs
  components/script/dom/webglrenderingcontext.rs
  components/script/dom/webidls/WebGL2RenderingContext.webidl
  tests/wpt/webgl/meta/conformance2/misc/views-with-offsets.html.ini
Labels: S-awaiting-merge

#26594 Implement animationiteration event
  components/script/animations.rs
  components/script/dom/document.rs
  components/script/dom/macros.rs
  components/script/dom/webidls/EventHandler.webidl
  components/script/dom/window.rs
  components/script/script_thread.rs
  components/style/animation.rs
  tests/wpt/metadata-layout-2020/css/css-animations/animationevent-types.html.ini
  tests/wpt/metadata-layout-2020/css/css-animations/idlharness.html.ini
  tests/wpt/metadata/css/css-animations/animationevent-types.html.ini
  tests/wpt/metadata/css/css-animations/idlharness.html.ini
  tests/wpt/metadata/dom/events/webkit-animation-iteration-event.html.ini
Labels: S-awaiting-merge

#26564 Upgrade wgpu version to "0.5.0" and add server-side code for id recycling for WebGPU
  Cargo.lock
  Cargo.toml
  components/canvas/canvas_data.rs
  components/script/dom/gpu.rs
  components/script/dom/gpuadapter.rs
  components/script/dom/gpubuffer.rs
  components/script/dom/gpucommandencoder.rs
  components/script/dom/gpucomputepassencoder.rs
  components/script/dom/gpudevice.rs
  components/script/dom/identityhub.rs
  components/script/dom/response.rs
  components/script/dom/webidls/GPUBindGroupLayout.webidl
  components/script/dom/webidls/GPUBuffer.webidl
  components/style/values/generics/calc.rs
  components/webgpu/Cargo.toml
  components/webgpu/identity.rs
  components/webgpu/lib.rs
  rust-toolchain
  servo-tidy.toml
Labels: S-awaiting-merge

#26619 Implement client-side logic for WebGPU id recycling
  components/constellation/constellation.rs
  components/msg/constellation_msg.rs
  components/profile/time.rs
  components/profile_traits/time.rs
  components/script/dom/identityhub.rs
  components/script/dom/workletglobalscope.rs
  components/script/script_runtime.rs
  components/script/script_thread.rs
  components/script_traits/lib.rs
  components/webgpu/lib.rs
Labels: S-awaiting-merge

#26624 Use temporary files instead of pipes for JS unminification.
  Cargo.lock
  components/script/Cargo.toml
  components/script/dom/htmlscriptelement.rs
Labels: S-awaiting-merge

#26606 Added macro to create functions in PipelineNamespace
  components/msg/constellation_msg.rs
Labels: S-awaiting-merge

#26622 Remove duplicate Host header from initial websocket request.
  components/net/websocket_loader.rs
Labels: S-awaiting-merge

#26623 Add a preference to control ImageBitmap while it's incomplete.
  components/config/prefs.rs
  components/script/dom/webidls/ImageBitmap.webidl
  components/script/dom/webidls/WindowOrWorkerGlobalScope.webidl
  resources/prefs.json
  tests/wpt/metadata/__dir__.ini
  tests/wpt/mozilla/meta/MANIFEST.json
  tests/wpt/mozilla/tests/mozilla/interfaces.html
  tests/wpt/mozilla/tests/mozilla/interfaces.worker.js
  tests/wpt/webgl/meta/conformance/__dir__.ini
  tests/wpt/webgl/meta/conformance2/__dir__.ini
Labels: S-awaiting-merge

#26609 Improve ending of transitions
  components/script/animations.rs
  components/style/animation.rs
  tests/wpt/metadata-layout-2020/css/css-transitions/properties-value-inherit-001.html.ini
  tests/wpt/metadata-layout-2020/css/css-transitions/properties-value-inherit-003.html.ini
  tests/wpt/mozilla/meta/MANIFEST.json
  tests/wpt/mozilla/tests/css/animations/faster-reversing-of-transitions.html
Labels: S-awaiting-merge

#26630 Add GPUSampler to WebGPU implementation
  components/script/dom/bindings/trace.rs
  components/script/dom/gpudevice.rs
  components/script/dom/gpusampler.rs
  components/script/dom/identityhub.rs
  components/script/dom/mod.rs
  components/script/dom/webidls/GPUDevice.webidl
  components/script/dom/webidls/GPUSampler.webidl
  components/script/script_thread.rs
  components/webgpu/lib.rs
Labels: S-awaiting-merge

#26421 Remove influxDB support for profile
  Cargo.lock
  components/config/opts.rs
  components/profile/Cargo.toml
  components/profile/time.rs
Labels: S-awaiting-merge

#26643 More Cargo.toml updates
  components/malloc_size_of/Cargo.toml
  components/media/Cargo.toml
  components/metrics/Cargo.toml
  components/msg/Cargo.toml
Labels: S-awaiting-merge

#26641 Fix undefined behavior in `energymon::init`
  components/profile_traits/energy.rs
Labels: S-awaiting-merge

#26646 Avoid parking_lot bustage with recent rustc nightlies.
  Cargo.lock
  components/layout/Cargo.toml
  components/layout_2020/Cargo.toml
  components/layout_thread/Cargo.toml
  components/layout_thread_2020/Cargo.toml
  components/msg/Cargo.toml
  components/script/Cargo.toml
  components/script_layout_interface/Cargo.toml
  components/style/Cargo.toml
  servo-tidy.toml
Labels: S-awaiting-merge

#26587 Fix output of test-tidy with duplicated packages.
  python/tidy/servo_tidy/tidy.py
  python/tidy/servo_tidy_tests/duplicated_package.lock
  python/tidy/servo_tidy_tests/test_tidy.py
Labels: S-awaiting-merge

#26642 Use dynamic dispatch in `mozjs::panic::wrap_panic`
  Cargo.lock
  components/script/dom/bindings/codegen/CodegenRust.py
  components/script/script_runtime.rs
Labels: S-awaiting-merge

#26660 Make WebGPU resource creation async and prevent panic during shutdown if WebGPU is enabled.
  components/script/dom/gpubuffer.rs
  components/script/dom/gpucommandencoder.rs
  components/script/dom/gpudevice.rs
  components/script/script_thread.rs
  components/webgpu/identity.rs
  components/webgpu/lib.rs
Labels: S-awaiting-merge

#26659 Add support for remaining animation and transition events
  components/atoms/static_atoms.txt
  components/script/animations.rs
  components/script/dom/document.rs
  components/script/dom/window.rs
  components/script/script_thread.rs
  components/style/animation.rs
  tests/wpt/metadata-layout-2020/css/css-animations/animationevent-types.html.ini
  tests/wpt/metadata/css/css-animations/Element-getAnimations.tentative.html.ini
  tests/wpt/metadata/css/css-animations/animationevent-pseudoelement.html.ini
  tests/wpt/metadata/css/css-animations/animationevent-types.html.ini
  tests/wpt/metadata/css/css-transitions/events-006.html.ini
  tests/wpt/metadata/css/css-variables/variable-animation-from-to.html.ini
  tests/wpt/metadata/css/css-variables/variable-animation-over-transition.html.ini
  tests/wpt/metadata/css/css-variables/variable-animation-substitute-into-keyframe-shorthand.html.ini
  tests/wpt/metadata/css/css-variables/variable-animation-substitute-into-keyframe-transform.html.ini
  tests/wpt/metadata/css/css-variables/variable-animation-substitute-into-keyframe.html.ini
  tests/wpt/metadata/css/css-variables/variable-animation-substitute-within-keyframe-fallback.html.ini
  tests/wpt/metadata/css/css-variables/variable-animation-substitute-within-keyframe-multiple.html.ini
  tests/wpt/metadata/css/css-variables/variable-animation-substitute-within-keyframe.html.ini
  tests/wpt/metadata/css/css-variables/variable-animation-to-only.html.ini
  tests/wpt/metadata/css/css-variables/variable-transitions-from-no-value.html.ini
  tests/wpt/metadata/css/css-variables/variable-transitions-to-no-value.html.ini
  tests/wpt/metadata/css/css-variables/variable-transitions-transition-property-variable-before-value.html.ini
  tests/wpt/metadata/css/css-variables/variable-transitions-value-before-transition-property-variable.html.ini
  tests/wpt/mozilla/meta-layout-2020/css/animations/animation-events.html.ini
  tests/wpt/mozilla/meta-layout-2020/css/animations/transition-events.html.ini
  tests/wpt/mozilla/meta/MANIFEST.json
  tests/wpt/mozilla/meta/css/animations/animation-events.html.ini
  tests/wpt/mozilla/meta/css/animations/transition-events.html.ini
  tests/wpt/mozilla/tests/css/animations/animation-events.html
  tests/wpt/mozilla/tests/css/animations/transition-events.html
Labels: S-awaiting-merge

#26662 Partial preparations for upgrading to Rust nightly-2020-05-26
  Cargo.lock
  components/derive_common/cg.rs
  python/servo/command_base.py
Labels: S-awaiting-merge

#26668 Set `currentScript` to `null` for module scripts
  components/script/dom/htmlscriptelement.rs
  tests/wpt/metadata/html/semantics/scripting-1/the-script-element/module/load-error-events-inline.html.ini
Labels: S-awaiting-merge

#26684 Rename glutin port to winit
  Cargo.toml
  docs/HACKING_QUICKSTART.md
  docs/ORGANIZATION.md
  etc/ci/check_no_panic.sh
  ports/gstplugin/resources.rs
  ports/winit/Cargo.toml
  ports/winit/app.rs
  ports/winit/backtrace.rs
  ports/winit/browser.rs
  ports/winit/build.rs
  ports/winit/embedder.rs
  ports/winit/events_loop.rs
  ports/winit/headed_window.rs
  ports/winit/headless_window.rs
  ports/winit/keyutils.rs
  ports/winit/main.rs
  ports/winit/main2.rs
  ports/winit/platform/macos/Info.plist
  ports/winit/platform/macos/count_threads.c
  ports/winit/platform/macos/mod.rs
  ports/winit/platform/windows/servo.exe.manifest
  ports/winit/resources.rs
  ports/winit/window_trait.rs
  python/servo/command_base.py
Labels: S-awaiting-merge

#26122 Support building on Void Linux
  python/servo/bootstrap.py
Labels: S-awaiting-merge

#26698 Remove some unused dependency declarations
  Cargo.lock
  components/canvas/Cargo.toml
  components/constellation/Cargo.toml
  components/layout/Cargo.toml
  components/layout_2020/Cargo.toml
  components/layout_thread/Cargo.toml
  components/layout_thread_2020/Cargo.toml
  components/layout_traits/Cargo.toml
  components/msg/Cargo.toml
  components/net/lib.rs
  components/profile/Cargo.toml
  components/profile_traits/Cargo.toml
  components/script/Cargo.toml
  components/script_traits/Cargo.toml
  components/style/Cargo.toml
  components/webdriver_server/Cargo.toml
  components/webgpu/Cargo.toml
  components/webrender_traits/Cargo.toml
  ports/gstplugin/Cargo.toml
  ports/winit/Cargo.toml
Labels: S-awaiting-merge

#26718 Improve precision of sequence types for WebIDL codegen.
  components/script/dom/bindings/codegen/CodegenRust.py
Labels: S-awaiting-merge

#26442 Fix the webidl for Headers
  components/script/dom/headers.rs
  components/script/dom/request.rs
  components/script/dom/response.rs
  components/script/dom/webidls/Headers.webidl
  tests/wpt/metadata/fetch/api/headers/headers-basic.html.ini
  tests/wpt/metadata/fetch/range/general.any.js.ini
Labels: S-awaiting-merge

#26678 Net: shutdown async runtime on exit
  components/net/http_loader.rs
  components/net/resource_thread.rs
Labels: S-awaiting-merge

#26721 More Cargo.toml updates
  components/net_traits/Cargo.toml
  components/pixels/Cargo.toml
  components/profile/Cargo.toml
  components/profile_traits/Cargo.toml
  components/range/Cargo.toml
  components/script_layout_interface/Cargo.toml
  components/script_traits/Cargo.toml
  components/selectors/Cargo.toml
  components/servo/Cargo.toml
  components/servo_arc/Cargo.toml
Labels: S-awaiting-merge

#26727 More Cargo.toml updates
  Cargo.toml
  components/style/Cargo.toml
  components/style_traits/Cargo.toml
  components/url/Cargo.toml
  components/webdriver_server/Cargo.toml
  components/webgpu/Cargo.toml
  components/webrender_traits/Cargo.toml
Labels: S-awaiting-merge
