Repository servo/servo, pull requests merged in 2023-05, with the labels that each got.

#28587 Make `Location` operate on the correct objects
  components/script/dom/location.rs
  tests/wpt/metadata-layout-2020/html/browsers/browsing-the-web/navigating-across-documents/javascript-url-security-check-failure.sub.html.ini
  tests/wpt/metadata-layout-2020/html/browsers/browsing-the-web/navigating-across-documents/multiple-globals/context-for-location-assign.html.ini
  tests/wpt/metadata-layout-2020/html/browsers/browsing-the-web/navigating-across-documents/multiple-globals/context-for-location-href.html.ini
  tests/wpt/metadata-layout-2020/html/browsers/browsing-the-web/navigating-across-documents/multiple-globals/context-for-location.html.ini
  tests/wpt/metadata/html/browsers/browsing-the-web/navigating-across-documents/javascript-url-security-check-failure.sub.html.ini
  tests/wpt/metadata/html/browsers/browsing-the-web/navigating-across-documents/multiple-globals/context-for-location-assign.html.ini
  tests/wpt/metadata/html/browsers/browsing-the-web/navigating-across-documents/multiple-globals/context-for-location-href.html.ini
  tests/wpt/metadata/html/browsers/browsing-the-web/navigating-across-documents/multiple-globals/context-for-location.html.ini
  tests/wpt/metadata/html/browsers/browsing-the-web/navigating-across-documents/source/navigate-child-function-parent.html.ini
  tests/wpt/metadata/html/browsers/history/the-location-interface/no-browsing-context.window.js.ini
Labels: S-awaiting-review

#29750 layout_2020: fix target main size not get clamped in flexbox
  components/layout_2020/flexbox/layout.rs
  tests/wpt/metadata-layout-2020/css/css-flexbox/flex-grow-008.html.ini
  tests/wpt/metadata-layout-2020/css/css-flexbox/flexbox_justifycontent-center.html.ini
  tests/wpt/metadata-layout-2020/css/css-flexbox/flexbox_justifycontent-flex-end.html.ini
  tests/wpt/metadata-layout-2020/css/css-flexbox/flexbox_justifycontent-flex-start.html.ini
  tests/wpt/metadata-layout-2020/css/css-flexbox/flexbox_justifycontent-spacearound-only.html.ini
  tests/wpt/metadata-layout-2020/css/css-flexbox/flexbox_justifycontent-spacearound.html.ini
  tests/wpt/metadata-layout-2020/css/css-flexbox/flexbox_justifycontent-spacebetween-only.html.ini
  tests/wpt/metadata-layout-2020/css/css-flexbox/flexbox_justifycontent-spacebetween.html.ini
  tests/wpt/metadata-layout-2020/css/css-flexbox/image-as-flexitem-size-005.html.ini
  tests/wpt/metadata-layout-2020/css/css-flexbox/image-as-flexitem-size-005v.html.ini
  tests/wpt/metadata-layout-2020/css/css-flexbox/percentage-heights-012.html.ini
Labels: A-layout/2020

#29790 Remove outdated note on README (fix #29786)
  README.md
Labels: A-documentation
