Repository servo/servo, pull requests merged in 2025-10, with the labels that each got.

#39591 layout: Clone static position rectangles when caching in `IndependentFormattingContext`
  components/layout/flow/mod.rs
  components/layout/fragment_tree/hoisted_shared_fragment.rs
  components/layout/positioned.rs
Labels: S-awaiting-review, S-awaiting-merge

#39594 xpath: Remove XML QName validation
  Cargo.lock
  components/xpath/Cargo.toml
  components/xpath/src/eval.rs
  components/xpath/src/lib.rs
  tests/wpt/meta/domxpath/resolver-callback-interface.html.ini
Labels: S-awaiting-merge

#39612 Upgrade Stylo to 2025-10-01
  Cargo.lock
  Cargo.toml
  components/layout/Cargo.toml
  components/layout/layout_impl.rs
  components/script/Cargo.toml
  components/script/animations.rs
Labels: S-awaiting-merge, dependencies

#39584 script: Stubs for geolocation interfaces
  components/config/prefs.rs
  components/script/dom/geolocation/geolocation.rs
  components/script/dom/geolocation/geolocationcoordinates.rs
  components/script/dom/geolocation/geolocationposition.rs
  components/script/dom/geolocation/geolocationpositionerror.rs
  components/script/dom/geolocation/mod.rs
  components/script/dom/mod.rs
  components/script/dom/navigator.rs
  components/script/script_runtime.rs
  components/script/script_thread.rs
  components/script/task_manager.rs
  components/script/task_source.rs
  components/script_bindings/webidls/Geolocation.webidl
  components/script_bindings/webidls/GeolocationCoordinates.webidl
  components/script_bindings/webidls/GeolocationPosition.webidl
  components/script_bindings/webidls/GeolocationPositionError.webidl
  components/shared/background_hang_monitor/lib.rs
  components/shared/profile/time.rs
  python/tidy/tidy.py
  tests/wpt/include.ini
  tests/wpt/meta/geolocation/__dir__.ini
  tests/wpt/meta/geolocation/getCurrentPosition_TypeError.https.html.ini
  tests/wpt/meta/geolocation/idlharness.https.window.js.ini
  tests/wpt/meta/geolocation/non-secure-contexts.http.html.ini
  tests/wpt/meta/geolocation/permission.https.html.ini
  tests/wpt/meta/geolocation/tojson.https.window.js.ini
  tests/wpt/meta/geolocation/watchPosition_TypeError.https.html.ini
  tests/wpt/meta/geolocation/watchposition-timeout.https.window.js.ini
Labels: S-awaiting-review, S-awaiting-merge

#39615 cargo: Update various non-breaking dependencies
  Cargo.lock
Labels: S-awaiting-merge

#39632 webdriver: Clean-up `actions.rs`
  components/webdriver_server/actions.rs
Labels: S-awaiting-merge

#39627 script: Share `Epoch` between canvas and layout and update the renderer separately
  components/compositing/compositor.rs
  components/compositing/tracing.rs
  components/layout/display_list/stacking_context.rs
  components/layout/layout_impl.rs
  components/script/dom/document.rs
  components/script/dom/window.rs
  components/shared/compositing/display_list.rs
  components/shared/compositing/lib.rs
  components/shared/layout/lib.rs
Labels: S-awaiting-review, S-awaiting-merge

#38991 script: Skip running layout when only updating images or canvas
  components/script/dom/canvas/2d/canvasrenderingcontext2d.rs
  components/script/dom/canvas/2d/offscreencanvasrenderingcontext2d.rs
  components/script/dom/canvas/canvas_context.rs
  components/script/dom/canvas/imagebitmaprenderingcontext.rs
  components/script/dom/document.rs
  components/script/dom/html/htmlcanvaselement.rs
  components/script/dom/webgpu/gpucanvascontext.rs
  components/script/image_animation.rs
  components/shared/layout/lib.rs
Labels: S-awaiting-review, S-awaiting-merge, A-content/canvas, A-content/webgpu

#39651 Update js-sys and associated dependencies
  Cargo.lock
Labels: S-awaiting-merge

#39629 net: Share SVG font database between all image caches in the same process
  components/net/image_cache.rs
Labels: S-awaiting-merge

#39656 wpt: Capture test output when running WPT in WebDriver mode
  python/wpt/grouping_formatter.py
Labels: S-awaiting-merge

#39645 script: implement url matches about:blank
  components/script/dom/document.rs
  components/url/Cargo.toml
  components/url/lib.rs
  components/url/tests/main.rs
  python/servo/testing_commands.py
Labels: S-awaiting-review, S-awaiting-merge

#39688 layout: Unify line height resolution
  components/layout/flow/inline/line.rs
  components/layout/flow/inline/mod.rs
Labels: A-layout/inline, S-awaiting-merge, A-layout/2020

#39690 layout: Remove some unneeded type annotations
  components/layout/flow/mod.rs
  components/layout/table/layout.rs
Labels: S-awaiting-merge, A-layout/2020

#39686 script: Allow loading of `<iframe srcdoc>` with a `sandbox` attribute
  components/script/dom/document.rs
  components/script/script_thread.rs
  tests/wpt/meta/IndexedDB/idbfactory-databases-opaque-origin.html.ini
  tests/wpt/meta/IndexedDB/idbfactory-deleteDatabase-opaque-origin.html.ini
  tests/wpt/meta/IndexedDB/idbfactory-open-opaque-origin.html.ini
  tests/wpt/meta/content-security-policy/base-uri/base-uri_iframe_sandbox.sub.html.ini
  tests/wpt/meta/content-security-policy/meta/sandbox-iframe.html.ini
  tests/wpt/meta/cookies/cookie-enabled-noncookie-frame.html.ini
  tests/wpt/meta/cookiestore/cookieStore_opaque_origin.https.html.ini
  tests/wpt/meta/html/browsers/sandboxing/sandbox-disallow-popups.html.ini
  tests/wpt/meta/html/infrastructure/urls/terminology-0/document-base-url-about-srcdoc.https.window.js.ini
  tests/wpt/meta/html/infrastructure/urls/terminology-0/document-base-url-changes-about-srcdoc.https.window.js.ini
  tests/wpt/meta/secure-contexts/basic-popup-and-iframe-tests.html.ini
  tests/wpt/meta/secure-contexts/basic-popup-and-iframe-tests.https.html.ini
Labels: S-awaiting-review, S-awaiting-merge

#39704 script: Remove `WebdriverTimeout` callback
  components/script/dom/window.rs
  components/script_bindings/webidls/Window.webidl
  components/shared/embedder/webdriver.rs
  components/webdriver_server/lib.rs
Labels: S-awaiting-merge

#39681 fonts: Use OS/2 table to determine if font face is already bold when synthesizing bold face for FreeType platform
  components/fonts/font.rs
  components/fonts/platform/freetype/font.rs
Labels: S-awaiting-review, S-awaiting-merge

#39709 libservo: Make `FormControl` responses completely asynchronous
  components/constellation/constellation.rs
  components/constellation/tracing.rs
  components/layout/display_list/stacking_context.rs
  components/script/dom/document.rs
  components/script/dom/document_embedder_controls.rs
  components/script/dom/html/htmlinputelement.rs
  components/script/dom/html/htmlselectelement.rs
  components/script/dom/mod.rs
  components/script/messaging.rs
  components/script/script_thread.rs
  components/servo/lib.rs
  components/servo/webview_delegate.rs
  components/shared/base/lib.rs
  components/shared/constellation/lib.rs
  components/shared/embedder/lib.rs
  components/shared/script/lib.rs
  components/webgpu/canvas_context.rs
  ports/servoshell/desktop/dialog.rs
Labels: S-awaiting-merge
