Repository servo/servo, pull requests merged in 2025-09, with the labels that each got.

#39041 layout: Ensure IFC for abspos with inline-level original display
  components/layout/flow/construct.rs
  components/layout/flow/root.rs
  components/script/layout_dom/element.rs
  tests/wpt/meta/css/css-position/position-absolute-dynamic-static-position-floats-001.html.ini
  tests/wpt/meta/css/css-position/position-absolute-dynamic-static-position-floats-002.html.ini
  tests/wpt/meta/css/css-position/position-absolute-dynamic-static-position-floats-003.html.ini
  tests/wpt/meta/css/css-position/position-absolute-dynamic-static-position-floats-004.html.ini
  tests/wpt/meta/css/css-position/static-position/inline-level-absolute-in-block-level-context-001.html.ini
  tests/wpt/meta/css/css-position/static-position/inline-level-absolute-in-block-level-context-002.html.ini
  tests/wpt/meta/css/css-position/static-position/inline-level-absolute-in-block-level-context-003.html.ini
  tests/wpt/meta/css/css-position/static-position/inline-level-absolute-in-block-level-context-005.html.ini
  tests/wpt/meta/css/css-position/static-position/inline-level-absolute-in-block-level-context-006.html.ini
  tests/wpt/meta/css/css-position/static-position/inline-level-absolute-in-block-level-context-008.html.ini
  tests/wpt/meta/css/css-position/static-position/inline-level-absolute-in-block-level-context-009.html.ini
  tests/wpt/meta/css/css-position/static-position/inline-level-absolute-in-block-level-context-010.html.ini
  tests/wpt/meta/css/css-position/static-position/inline-level-absolute-in-block-level-context-011.html.ini
  tests/wpt/meta/css/css-position/static-position/inline-level-absolute-in-block-level-context-012.html.ini
Labels: A-layout/2020

#39008 indexeddb: Finish implementation of key_type_to_jsval
  components/script/indexed_db.rs
  tests/wpt/meta/IndexedDB/crashtests/create-index.any.js.ini
  tests/wpt/meta/IndexedDB/idbfactory_open.any.js.ini
Labels: A-content/indexeddb

#39150 Upgrade Stylo to 2025-09-02
  Cargo.lock
  Cargo.toml
  components/layout/query.rs
  tests/wpt/meta/css/css-transforms/parsing/rotate-parsing-computed.html.ini
  tests/wpt/meta/css/css-transforms/parsing/rotate-parsing-valid.html.ini
Labels: dependencies

#38847 script: Re-implement evaluate_key_path_on_value in IndexedDB
  components/script/dom/idbobjectstore.rs
  components/script/indexed_db.rs
  tests/wpt/meta/IndexedDB/crashtests/create-index.any.js.ini
  tests/wpt/meta/IndexedDB/idbdatabase_deleteObjectStore.any.js.ini
  tests/wpt/meta/IndexedDB/idbobjectstore_add.any.js.ini
  tests/wpt/meta/IndexedDB/idbobjectstore_getAll-options.tentative.any.js.ini
  tests/wpt/meta/IndexedDB/idbobjectstore_getAll.any.js.ini
  tests/wpt/meta/IndexedDB/idbobjectstore_getAllKeys-options.tentative.any.js.ini
  tests/wpt/meta/IndexedDB/idbobjectstore_getAllKeys.any.js.ini
  tests/wpt/meta/IndexedDB/idbobjectstore_getAllRecords.tentative.any.js.ini
  tests/wpt/meta/IndexedDB/idbobjectstore_put.any.js.ini
  tests/wpt/meta/IndexedDB/key_valid.any.js.ini
  tests/wpt/meta/IndexedDB/keygenerator.any.js.ini
  tests/wpt/meta/IndexedDB/keypath.any.js.ini
  tests/wpt/meta/IndexedDB/nested-cloning-large-multiple.any.js.ini
  tests/wpt/meta/IndexedDB/nested-cloning-large.any.js.ini
  tests/wpt/meta/IndexedDB/nested-cloning-small.any.js.ini
  tests/wpt/meta/IndexedDB/transaction-deactivation-timing.any.js.ini
  tests/wpt/meta/IndexedDB/transaction-requestqueue.any.js.ini
Labels: A-content/indexeddb

#38885 indexeddb: Implement getAll and getAllKeys
  components/net/indexeddb/engines/sqlite.rs
  components/net/tests/sqlite.rs
  components/script/dom/idbobjectstore.rs
  components/script/dom/idbrequest.rs
  components/script_bindings/webidls/IDBObjectStore.webidl
  components/shared/net/indexeddb_thread.rs
  tests/wpt/meta/IndexedDB/idbobjectstore-cross-realm-methods.html.ini
  tests/wpt/meta/IndexedDB/idbobjectstore-query-exception-order.any.js.ini
  tests/wpt/meta/IndexedDB/idlharness.any.js.ini
Labels: S-awaiting-review, A-content/indexeddb

#39172 layout: Simplify `effective_overflow()` a little
  components/layout/flow/root.rs
  components/layout/style_ext.rs
Labels: A-layout/2020

#38839 script: Initial stubs for Credential Management API
  components/config/prefs.rs
  components/script/dom/credentialmanagement/credential.rs
  components/script/dom/credentialmanagement/credentialscontainer.rs
  components/script/dom/credentialmanagement/mod.rs
  components/script/dom/credentialmanagement/passwordcredential.rs
  components/script/dom/mod.rs
  components/script/dom/navigator.rs
  components/script_bindings/webidls/Credential.webidl
  components/script_bindings/webidls/CredentialsContainer.webidl
  components/script_bindings/webidls/PasswordCredential.webidl
  python/tidy/tidy.py
Labels: S-awaiting-review

#39223 script: Propagate CanGc argument through DictionaryFromJSVal trait
  components/script/dom/subtlecrypto.rs
Labels: S-awaiting-merge

#38846 ohos: Adding support for running WPT on OHOS devices using WebDriver
  ports/servoshell/egl/app_state.rs
  python/servo/testing_commands.py
  python/wpt/ohos_test_parser.js
  python/wpt/ohos_webdriver_test.py
Labels: S-awaiting-review

#39166 Replace Hash Algorithm in HashMap/Set with FxHashMap/Set for simple types
  Cargo.lock
  components/net/Cargo.toml
  components/net/http_loader.rs
  components/net/image_cache.rs
  components/net/indexeddb/idb_thread.rs
  components/net/resource_thread.rs
  components/net/storage_thread.rs
  components/net/tests/main.rs
  components/script/document_collection.rs
  components/script/dom/abstractworkerglobalscope.rs
  components/script/dom/bindings/serializable.rs
  components/script/dom/bindings/structuredclone.rs
  components/script/dom/bindings/trace.rs
  components/script/dom/bindings/transferable.rs
  components/script/dom/blob.rs
  components/script/dom/canvas/imagebitmap.rs
  components/script/dom/canvas/offscreencanvas.rs
  components/script/dom/document.rs
  components/script/dom/domexception.rs
  components/script/dom/dommatrix.rs
  components/script/dom/dommatrixreadonly.rs
  components/script/dom/dompoint.rs
  components/script/dom/dompointreadonly.rs
  components/script/dom/domquad.rs
  components/script/dom/domrect.rs
  components/script/dom/domrectreadonly.rs
  components/script/dom/globalscope.rs
  components/script/dom/html/htmlcanvaselement.rs
  components/script/dom/mediasession.rs
  components/script/dom/messageport.rs
  components/script/dom/quotaexceedederror.rs
  components/script/dom/readablestream.rs
  components/script/dom/servoparser/async_html.rs
  components/script/dom/transformstream.rs
  components/script/dom/webrtc/rtcpeerconnection.rs
  components/script/dom/window.rs
  components/script/dom/worklet.rs
  components/script/dom/writablestream.rs
  components/script/messaging.rs
  components/script/script_thread.rs
  components/script/task_manager.rs
  components/script/task_queue.rs
  components/script/timers.rs
  components/shared/constellation/Cargo.toml
  components/shared/constellation/structured_data/mod.rs
  components/shared/constellation/structured_data/serializable.rs
Labels: S-awaiting-review

#39204 libservo: Make Servo (and servoshell) more resilient against extreme sizes
  components/servo/lib.rs
  components/servo/tests/common/mod.rs
  components/servo/tests/webview.rs
  components/servo/webview.rs
  components/servo/webview_delegate.rs
  ports/servoshell/desktop/headed_window.rs
  ports/servoshell/desktop/headless_window.rs
  ports/servoshell/desktop/window_trait.rs
  tests/wpt/meta/css/cssom-view/resizeTo-negative.html.ini
Labels: S-awaiting-review

#39231 script: Fix building with `webgl_backtrace` feature
  components/script/dom/webgl/webglrenderingcontext.rs
Labels: S-awaiting-merge

#39193 script: Make `root_from_handle_value` a safe function by accepting `SafeJSContext`
  components/script/dom/trustedtypepolicyfactory.rs
  components/script/indexed_db.rs
  components/script_bindings/codegen/codegen.py
  components/script_bindings/conversions.rs
Labels: S-awaiting-review

#39241 webdriver: Focus WebView asynchronously
  components/constellation/constellation.rs
  components/servo/lib.rs
  components/servo/webview.rs
  components/servo/webview_delegate.rs
  components/shared/constellation/lib.rs
  components/shared/embedder/lib.rs
  components/shared/embedder/webdriver.rs
  components/webdriver_server/lib.rs
  ports/servoshell/desktop/app.rs
  ports/servoshell/desktop/app_state.rs
  ports/servoshell/egl/app_state.rs
  tests/wpt/meta/webdriver/tests/classic/send_alert_text/send.py.ini
Labels: S-awaiting-review

#39233 Removed FnvHash and transformed the rest to FxHashmap
  Cargo.lock
  Cargo.toml
  components/compositing/Cargo.toml
  components/compositing/compositor.rs
  components/compositing/touch.rs
  components/compositing/webview_manager.rs
  components/compositing/webview_renderer.rs
  components/constellation/Cargo.toml
  components/constellation/broadcastchannel.rs
  components/constellation/browsingcontext.rs
  components/constellation/constellation.rs
  components/constellation/constellation_webview.rs
  components/constellation/webview_manager.rs
  components/devtools/Cargo.toml
  components/devtools/id.rs
  components/devtools/lib.rs
  components/fonts/Cargo.toml
  components/fonts/font_context.rs
  components/layout/Cargo.toml
  components/layout/context.rs
  components/layout/display_list/hit_test.rs
  components/layout/layout_impl.rs
  components/net/filemanager_thread.rs
  components/net/image_cache.rs
  components/script/Cargo.toml
  components/script/dom/bindings/refcounted.rs
  components/script/dom/customelementregistry.rs
  components/script/dom/document.rs
  components/script/dom/documentfragment.rs
  components/script/dom/documentorshadowroot.rs
  components/script/dom/eventtarget.rs
  components/script/dom/globalscope.rs
  components/script/dom/html/htmlformelement.rs
  components/script/dom/servoparser/async_html.rs
  components/script/dom/stylepropertymapreadonly.rs
  components/script/dom/webgl/extensions/extensions.rs
  components/script/dom/webgl/webglprogram.rs
  components/script/dom/webxr/xrsession.rs
  components/script/iframe_collection.rs
  components/script/script_thread.rs
  components/shared/compositing/Cargo.toml
  components/shared/compositing/display_list.rs
  components/shared/constellation/Cargo.toml
  components/shared/constellation/from_script_message.rs
  components/shared/constellation/lib.rs
  components/shared/embedder/Cargo.toml
  components/shared/embedder/webdriver.rs
  components/shared/layout/Cargo.toml
  components/shared/layout/lib.rs
  components/shared/net/Cargo.toml
  components/shared/net/lib.rs
  components/shared/script/Cargo.toml
  components/shared/script/lib.rs
  components/webdriver_server/Cargo.toml
  components/webdriver_server/actions.rs
Labels: S-awaiting-review

#36530 Enable the zstd decoder
  Cargo.lock
  components/net/Cargo.toml
  components/net/decoder.rs
  components/net/http_loader.rs
  components/net/tests/fetch.rs
  components/net/tests/http_loader.rs
  tests/wpt/meta/fetch/content-encoding/zstd/big-zstd-body.https.any.js.ini
  tests/wpt/meta/fetch/content-encoding/zstd/zstd-body.https.any.js.ini
  tests/wpt/meta/fetch/content-encoding/zstd/zstd-navigation.https.window.js.ini
Labels: S-awaiting-review

#39230 layout: Take `text-indent` into account in min/max-content inline sizes
  components/layout/flow/inline/mod.rs
  tests/wpt/meta/css/CSS2/text/text-indent-applies-to-003.xht.ini
  tests/wpt/meta/css/CSS2/text/text-indent-intrinsic-001.xht.ini
  tests/wpt/meta/css/CSS2/text/text-indent-intrinsic-002.xht.ini
  tests/wpt/meta/css/CSS2/text/text-indent-intrinsic-003.xht.ini
  tests/wpt/meta/css/CSS2/text/text-indent-intrinsic-004.xht.ini
  tests/wpt/meta/css/css-text/text-indent/text-indent-min-max-content-001.html.ini
  tests/wpt/meta/css/css-values/calc-text-indent-intrinsic-1.html.ini
Labels: S-awaiting-review, S-awaiting-merge, A-layout/2020

#39282 Enable abort controller preference for fetch/api/abort
  tests/wpt/meta/fetch/api/abort/__dir__.ini
  tests/wpt/meta/fetch/api/abort/destroyed-context.html.ini
  tests/wpt/meta/fetch/api/abort/general.any.js.ini
  tests/wpt/meta/fetch/api/abort/keepalive.html.ini
  tests/wpt/meta/fetch/api/abort/request.any.js.ini
Labels: S-awaiting-review, S-awaiting-merge

#39281 Remove the `dom_trusted_types_enabled` preference
  components/config/prefs.rs
  components/script_bindings/webidls/TrustedHTML.webidl
  components/script_bindings/webidls/TrustedScript.webidl
  components/script_bindings/webidls/TrustedScriptURL.webidl
  components/script_bindings/webidls/TrustedTypePolicy.webidl
  components/script_bindings/webidls/TrustedTypePolicyFactory.webidl
  components/script_bindings/webidls/WindowOrWorkerGlobalScope.webidl
  ports/servoshell/prefs.rs
Labels: S-awaiting-review, S-awaiting-merge

#39283 Add spec steps and comments for fetch abort steps
  components/script/dom/abortcontroller.rs
  components/script/dom/abortsignal.rs
  components/script/dom/window.rs
  components/script/dom/workerglobalscope.rs
  components/script/fetch.rs
  components/script_bindings/webidls/Fetch.webidl
  components/script_bindings/webidls/WindowOrWorkerGlobalScope.webidl
Labels: S-awaiting-merge

#39289 servoshell: Add `ParseResolutionError` to parse elegantly
  ports/servoshell/prefs.rs
Labels: S-awaiting-merge

#39287 Fix Response:bodyUsed behavior to return false if the body is null
  components/script/dom/response.rs
  tests/wpt/meta/fetch/api/response/response-consume-empty.any.js.ini
Labels: S-awaiting-merge

#39308 script: Make `EventTarget::fire` return `bool` according to spec
  components/script/dom/eventtarget.rs
  components/script/dom/html/htmlformelement.rs
  components/script/dom/validation.rs
Labels: S-awaiting-merge

#39310 Get the Rc to the custom_reaction_stack outside the loop instead of using the thread_local inside.
  components/script/dom/customelementregistry.rs
  components/script/dom/node.rs
Labels: S-awaiting-merge

#39320 net: use `log::error!` to handle DevTools startup failures gracefully
  components/net/http_loader.rs
Labels: S-awaiting-merge

#39325 script: use `Element::create` instead of DOM struct constructors
  components/script/dom/domimplementation.rs
  components/script/dom/element.rs
  components/script/dom/html/htmldetailselement.rs
  components/script/dom/html/htmlelement.rs
  components/script/dom/html/htmlinputelement.rs
  components/script/dom/html/htmlmediaelement.rs
  components/script/dom/html/htmlmeterelement.rs
  components/script/dom/html/htmloptionscollection.rs
  components/script/dom/html/htmlprogresselement.rs
  components/script/dom/html/htmltableelement.rs
  components/script/dom/html/htmltablerowelement.rs
  components/script/dom/html/htmltablesectionelement.rs
  components/script/dom/servoparser/mod.rs
Labels: S-awaiting-merge

#39332 libservo: Remove the `Opts::trace_layout`
  components/config/opts.rs
  ports/servoshell/prefs.rs
Labels: S-awaiting-merge

#39290 Add signal to request
  components/script/dom/abortsignal.rs
  components/script/dom/request.rs
  components/script_bindings/codegen/Bindings.conf
  components/script_bindings/webidls/AbortSignal.webidl
  components/script_bindings/webidls/Request.webidl
  tests/wpt/meta/dom/abort/abort-signal-any-crash.html.ini
  tests/wpt/meta/dom/abort/abort-signal-any.any.js.ini
  tests/wpt/meta/dom/idlharness.any.js.ini
  tests/wpt/meta/dom/idlharness.window.js.ini
  tests/wpt/meta/fetch/api/abort/general.any.js.ini
  tests/wpt/meta/fetch/api/idlharness.any.js.ini
Labels: S-awaiting-review, S-awaiting-merge

#39331 libservo: Remove `Opts::webrender_stats` and `-Z wr-stats`
  components/config/opts.rs
  components/servo/lib.rs
  ports/servoshell/prefs.rs
Labels: S-awaiting-review, S-awaiting-merge

#39316 servoshell: Update the debug options (`-Z`) help to reflect current set of options
  components/config/opts.rs
  ports/servoshell/prefs.rs
Labels: S-awaiting-review, S-awaiting-merge

#39354 profile: Remove integration with Instruments.app "Points of Interest"
  Cargo.lock
  components/config/opts.rs
  components/shared/profile/Cargo.toml
  components/shared/profile/time.rs
  deny.toml
  ports/servoshell/prefs.rs
Labels: S-awaiting-merge

#39366 webdriver: Remove TODO comments of focusing steps
  components/script/webdriver_handlers.rs
Labels: S-awaiting-merge

#39365 mach: Configure `uv` using `pyproject.toml`
  pyproject.toml
  uv.toml
Labels: S-awaiting-merge

#39351 script: Replace DomRefCell<bool> with Cell<bool> for Response::redirected
  components/script/dom/response.rs
Labels: S-awaiting-merge

#39373 Update to Stylo with icu range dependency
  Cargo.lock
Labels: S-awaiting-merge

#39375 layout: Avoid recomputing automatic inline size
  components/layout/flow/mod.rs
Labels: S-awaiting-merge, A-layout/2020

#39372 layout: Avoid ClipId, ExternalScrollId and ScrollTreeNodeId references
  components/compositing/webview_renderer.rs
  components/layout/display_list/clip.rs
  components/layout/display_list/hit_test.rs
  components/layout/display_list/mod.rs
  components/layout/display_list/stacking_context.rs
  components/layout/query.rs
  components/shared/compositing/display_list.rs
  components/shared/compositing/tests/compositor.rs
Labels: S-awaiting-merge, A-layout/2020

#39392 script: Allow reusing results from xpath queries
  components/script/dom/xpathexpression.rs
  components/script/dom/xpathresult.rs
  tests/wpt/mozilla/meta/MANIFEST.json
  tests/wpt/mozilla/tests/mozilla/xpath-result-out-parameter.html
Labels: S-awaiting-merge

#39353 html: Check the <source> MIME type on the source set updating
  components/script/dom/html/htmlimageelement.rs
  tests/wpt/meta/html/semantics/embedded-content/the-img-element/update-the-source-set.html.ini
  tests/wpt/meta/resource-timing/initiator-type/picture.html.ini
Labels: S-awaiting-merge

#39404 Use more workspace dependencies
  Cargo.toml
  components/background_hang_monitor/Cargo.toml
  components/shared/compositing/Cargo.toml
  components/shared/script/Cargo.toml
  ports/servoshell/Cargo.toml
Labels: S-awaiting-merge

#38288 Implement indexeddb array conversion
  components/script/dom/idbobjectstore.rs
  components/script/indexed_db.rs
  tests/wpt/meta/IndexedDB/idb-partitioned-coverage.sub.html.ini
  tests/wpt/meta/IndexedDB/idbcursor-continuePrimaryKey-exceptions.any.js.ini
  tests/wpt/meta/IndexedDB/idbfactory_cmp.any.js.ini
  tests/wpt/meta/IndexedDB/idbkeyrange-includes.any.js.ini
  tests/wpt/meta/IndexedDB/idbkeyrange_incorrect.any.js.ini
  tests/wpt/meta/IndexedDB/idbobjectstore_getAll.any.js.ini
  tests/wpt/meta/IndexedDB/idbobjectstore_openKeyCursor.any.js.ini
  tests/wpt/meta/IndexedDB/key-conversion-exceptions.any.js.ini
  tests/wpt/meta/IndexedDB/key_invalid.any.js.ini
  tests/wpt/meta/IndexedDB/keyorder.any.js.ini
  tests/wpt/meta/IndexedDB/keypath-exceptions.any.js.ini
Labels: S-awaiting-review, S-awaiting-merge, A-content/indexeddb

#39327 Enable credential management wpt tests
  tests/wpt/include.ini
  tests/wpt/meta/__dir__.ini
  tests/wpt/meta/credential-management/credentialscontainer-create-basics.https.html.ini
  tests/wpt/meta/credential-management/credentialscontainer-frame-basics.https.html.ini
  tests/wpt/meta/credential-management/credentialscontainer-get-basics.https.html.ini
  tests/wpt/meta/credential-management/credentialscontainer-prevent-silent-access.https.html.ini
  tests/wpt/meta/credential-management/federatedcredential-framed-get.sub.https.html.ini
  tests/wpt/meta/credential-management/idlharness.https.window.js.ini
  tests/wpt/meta/credential-management/otpcredential-get-basics.https.html.ini
  tests/wpt/meta/credential-management/otpcredential-iframe.https.html.ini
  tests/wpt/meta/credential-management/otpcredential-store.https.html.ini
  tests/wpt/meta/credential-management/passwordcredential-framed-get.sub.https.html.ini
Labels: S-awaiting-review, S-awaiting-merge

#39396 script: Have HyperlinkElementTraits::update_href take a &ServoUrl
  components/script/dom/html/htmlhyperlinkelementutils.rs
Labels: S-awaiting-review, S-awaiting-merge

#39410 Allow whitespace around path expressions in xpath
  components/script/xpath/parser.rs
  tests/wpt/meta/domxpath/lexical-structure.html.ini
Labels: S-awaiting-merge

#39412 Remove `test-content` subcommand from mach
  python/servo/testing_commands.py
Labels: A-mach, S-awaiting-merge

#39391 webdriver: Improve documentations for `actions.rs` and update TODOs
  components/webdriver_server/actions.rs
  components/webdriver_server/lib.rs
  ports/servoshell/desktop/app.rs
Labels: S-awaiting-merge

#39374 Abort fetch controller when signal is aborted
  components/script/dom/abortsignal.rs
  components/script/fetch.rs
  tests/wpt/meta/fetch/api/abort/general.any.js.ini
  tests/wpt/meta/fetch/api/abort/keepalive.html.ini
Labels: S-awaiting-review, S-awaiting-merge

#39406 Add AbortSignal support for event listeners
  components/script/dom/abortsignal.rs
  components/script/dom/event.rs
  components/script/dom/eventtarget.rs
  components/script/dom/mediaquerylist.rs
  components/script_bindings/codegen/Bindings.conf
  components/script_bindings/codegen/codegen.py
  components/script_bindings/webidls/EventTarget.webidl
  tests/wpt/meta/dom/events/AddEventListenerOptions-signal.any.js.ini
  tests/wpt/meta/dom/events/__dir__.ini
Labels: S-awaiting-merge

#39435 codeowners: remove /layout and add /layout/taffy and /fonts for nicoburns
  .github/CODEOWNERS
Labels: S-awaiting-merge

#39437 Convert Android resources to lossless .webp
  support/android/apk/servoapp/src/main/res/drawable/cancel.png
  support/android/apk/servoapp/src/main/res/drawable/cancel.webp
  support/android/apk/servoapp/src/main/res/drawable/history_back.png
  support/android/apk/servoapp/src/main/res/drawable/history_back.webp
  support/android/apk/servoapp/src/main/res/drawable/history_forward.png
  support/android/apk/servoapp/src/main/res/drawable/history_forward.webp
  support/android/apk/servoapp/src/main/res/drawable/media_session_icon.png
  support/android/apk/servoapp/src/main/res/drawable/media_session_icon.webp
  support/android/apk/servoapp/src/main/res/drawable/media_session_next.png
  support/android/apk/servoapp/src/main/res/drawable/media_session_next.webp
  support/android/apk/servoapp/src/main/res/drawable/media_session_pause.png
  support/android/apk/servoapp/src/main/res/drawable/media_session_pause.webp
  support/android/apk/servoapp/src/main/res/drawable/media_session_play.png
  support/android/apk/servoapp/src/main/res/drawable/media_session_play.webp
  support/android/apk/servoapp/src/main/res/drawable/media_session_prev.png
  support/android/apk/servoapp/src/main/res/drawable/media_session_prev.webp
  support/android/apk/servoapp/src/main/res/drawable/media_session_stop.png
  support/android/apk/servoapp/src/main/res/drawable/media_session_stop.webp
  support/android/apk/servoapp/src/main/res/drawable/refresh.png
  support/android/apk/servoapp/src/main/res/drawable/refresh.webp
  support/android/apk/servoapp/src/main/res/mipmap/servo.png
  support/android/apk/servoapp/src/main/res/mipmap/servo.webp
Labels: S-awaiting-merge

#39465 Ensure test_multiprocess_preference_observer waits for reload to complete.
  components/servo/tests/common/mod.rs
  components/servo/tests/multiprocess.rs
Labels: S-awaiting-merge

#39459 Never disconnect shadow roots from their hosts
  components/script/dom/document.rs
  components/script/dom/element.rs
  components/script/dom/html/htmlmediaelement.rs
  components/script/dom/shadowroot.rs
  tests/wpt/mozilla/meta/MANIFEST.json
  tests/wpt/mozilla/tests/shadow-dom/move-element-with-ua-shadow-tree-crash.html
Labels: S-awaiting-merge

#39466 html: Add the reflected 'sizes' IDL attribute for <image>
  components/script/dom/html/htmlimageelement.rs
  components/script_bindings/webidls/HTMLImageElement.webidl
  tests/wpt/meta/custom-elements/reactions/customized-builtins/HTMLImageElement.html.ini
  tests/wpt/meta/html/dom/idlharness.https.html.ini
  tests/wpt/meta/html/semantics/embedded-content/the-img-element/relevant-mutations.html.ini
Labels: S-awaiting-merge

#39472 servoshell: Scale WebDriver mouse button coordinates by HiDPI scale factor
  ports/servoshell/desktop/app.rs
Labels: S-awaiting-merge

#39296 script: implement `ClipboardItem` `getType` and `supports`
  components/script/dom/clipboarditem.rs
  components/script_bindings/codegen/Bindings.conf
  components/script_bindings/webidls/Clipboard.webidl
  tests/wpt/meta/clipboard-apis/clipboard-item.https.html.ini
  tests/wpt/meta/clipboard-apis/idlharness.https.window.js.ini
Labels: S-awaiting-merge

#39481 Script: Change the rest of script to not rely on Deref<str> for DOMString
  components/script/body.rs
  components/script/dom/bindings/domname.rs
  components/script/dom/blob.rs
  components/script/dom/characterdata.rs
  components/script/dom/clipboarditem.rs
  components/script/dom/compositionevent.rs
  components/script/dom/console.rs
  components/script/dom/css.rs
  components/script/dom/csskeyframesrule.rs
  components/script/dom/cssrulelist.rs
  components/script/dom/cssstyledeclaration.rs
  components/script/dom/cssstylerule.rs
  components/script/dom/cssstylesheet.rs
  components/script/dom/customelementregistry.rs
  components/script/dom/datatransfer.rs
  components/script/dom/document.rs
  components/script/dom/domexception.rs
  components/script/dom/domtokenlist.rs
  components/script/dom/servoparser/html.rs
  components/script/dom/servoparser/mod.rs
  components/script/dom/stylepropertymapreadonly.rs
  components/script/dom/testbinding.rs
  components/script/dom/text.rs
  components/script/dom/trustedhtml.rs
  components/script/dom/trustedscript.rs
  components/script/dom/trustedscripturl.rs
  components/script/dom/trustedtypepolicyfactory.rs
  components/script/dom/url.rs
  components/script/dom/webgl/extensions/extensions.rs
  components/script/dom/webgl/webglprogram.rs
  components/script/dom/webgl/webglshader.rs
  components/script/dom/webgpu/gpuadapter.rs
  components/script/dom/webrtc/rtcdatachannel.rs
  components/script/dom/websocket.rs
  components/script/dom/window.rs
  components/script/dom/windowproxy.rs
  components/script/dom/worker.rs
  components/script/dom/workerglobalscope.rs
  components/script/dom/xmlhttprequest.rs
  components/script/dom/xpathevaluator.rs
  components/script/drag_data_store.rs
  components/script/indexed_db.rs
  components/script/links.rs
  components/script/script_module.rs
  components/script/textinput.rs
  components/script/timers.rs
  components/script_bindings/conversions.rs
  components/script_bindings/proxyhandler.rs
  components/script_bindings/record.rs
  components/script_bindings/str.rs
Labels: S-awaiting-merge

#39467 Allow hyper_serde to only depend on serde_core for potentially faster compile times.
  .github/dependabot.yml
  Cargo.lock
  Cargo.toml
  components/hyper_serde/Cargo.toml
  components/hyper_serde/lib.rs
Labels: S-awaiting-review, S-awaiting-merge

#39490 Move Request constructor to impl
  components/script/dom/request.rs
Labels: S-awaiting-merge

#39492 stylo: Add support for `-webkit-fill-available` sizing keyword
  Cargo.lock
  components/layout/flow/mod.rs
  components/layout/sizing.rs
  components/layout/taffy/stylo_taffy/convert.rs
  tests/wpt/meta/css/css-sizing/stretch/cache-miss-001.html.ini
  tests/wpt/meta/css/css-sizing/stretch/cache-miss-002.html.ini
  tests/wpt/meta/css/css-sizing/stretch/stretch-alias-block-size-001.tentative.html.ini
  tests/wpt/meta/css/css-sizing/stretch/stretch-alias-inline-size-001.tentative.html.ini
  tests/wpt/meta/css/css-sizing/stretch/stretch-alias-max-block-size-001.tentative.html.ini
  tests/wpt/meta/css/css-sizing/stretch/stretch-alias-max-inline-size-001.tentative.html.ini
  tests/wpt/meta/css/css-sizing/stretch/stretch-alias-min-block-size-001.tentative.html.ini
  tests/wpt/meta/css/css-sizing/stretch/stretch-alias-min-inline-size-001.tentative.html.ini
  tests/wpt/meta/css/css-tables/tentative/table-width-redistribution.html.ini
Labels: S-awaiting-merge, A-stylo

#39500 servoshell: Do not hide window in macOS when taking screenshot
  ports/servoshell/desktop/cli.rs
  ports/servoshell/desktop/events_loop.rs
Labels: S-awaiting-merge

#39421 Add abort signal preference to experimental web features
  ports/servoshell/prefs.rs
  tests/wpt/meta/IndexedDB/back-forward-cache-open-connection.window.js.ini
  tests/wpt/meta/IndexedDB/back-forward-cache-open-transaction.window.js.ini
  tests/wpt/meta/credential-management/credentialscontainer-get-basics.https.html.ini
  tests/wpt/meta/dom/abort/__dir__.ini
  tests/wpt/meta/dom/events/__dir__.ini
  tests/wpt/meta/dom/idlharness.any.js.ini
  tests/wpt/meta/dom/idlharness.window.js.ini
  tests/wpt/meta/dom/interface-objects.html.ini
  tests/wpt/meta/fetch/api/abort/__dir__.ini
  tests/wpt/meta/fetch/fetch-later/quota/cross-origin-iframe/multiple-iframes.https.window.js.ini
  tests/wpt/meta/fetch/fetch-later/send-on-deactivate.https.window.js.ini
  tests/wpt/meta/html/browsers/browsing-the-web/back-forward-cache/broadcastchannel/broadcastchannel.window.js.ini
  tests/wpt/meta/html/browsers/browsing-the-web/back-forward-cache/broadcastchannel/dedicatedworker.tentative.window.js.ini
  tests/wpt/meta/html/browsers/browsing-the-web/back-forward-cache/broadcastchannel/evict-on-message.tentative.window.js.ini
  tests/wpt/meta/html/browsers/browsing-the-web/history-traversal/document-state.https.html.ini
  tests/wpt/meta/html/browsers/browsing-the-web/remote-context-helper-tests/navigateToNew.window.js.ini
  tests/wpt/meta/html/browsers/browsing-the-web/remote-context-helper-tests/navigation-bfcache.window.js.ini
  tests/wpt/meta/html/browsers/browsing-the-web/remote-context-helper-tests/navigation-helpers.window.js.ini
  tests/wpt/meta/html/browsers/browsing-the-web/remote-context-helper-tests/navigation-same-document.window.js.ini
  tests/wpt/meta/html/browsers/browsing-the-web/unloading-documents/unload/unload-main-frame-cross-origin.window.js.ini
  tests/wpt/meta/html/browsers/browsing-the-web/unloading-documents/unload/unload-main-frame-same-origin.window.js.ini
  tests/wpt/meta/html/browsers/history/the-history-interface/history-state-after-bfcache.window.js.ini
  tests/wpt/meta/html/browsers/windows/auxiliary-browsing-contexts/no-proactive-swap-when-other-contexts-in-group.html.ini
  tests/wpt/meta/html/semantics/links/links-created-by-a-and-area-elements/rel-opener-prevents-browsing-context-group-change.tentative.html.ini
  tests/wpt/meta/performance-timeline/not-restored-reasons/performance-navigation-timing-attributes.tentative.window.js.ini
  tests/wpt/meta/performance-timeline/not-restored-reasons/performance-navigation-timing-bfcache-reasons-stay.tentative.window.js.ini
  tests/wpt/meta/performance-timeline/not-restored-reasons/performance-navigation-timing-bfcache.tentative.window.js.ini
  tests/wpt/meta/performance-timeline/not-restored-reasons/performance-navigation-timing-cross-origin-bfcache.tentative.window.js.ini
  tests/wpt/meta/performance-timeline/not-restored-reasons/performance-navigation-timing-fetch.tentative.window.js.ini
  tests/wpt/meta/performance-timeline/not-restored-reasons/performance-navigation-timing-navigation-failure.tentative.window.js.ini
  tests/wpt/meta/performance-timeline/not-restored-reasons/performance-navigation-timing-not-bfcached.tentative.window.js.ini
  tests/wpt/meta/performance-timeline/not-restored-reasons/performance-navigation-timing-redirect-on-history.tentative.window.js.ini
  tests/wpt/meta/performance-timeline/not-restored-reasons/performance-navigation-timing-reload.tentative.window.js.ini
  tests/wpt/meta/performance-timeline/not-restored-reasons/performance-navigation-timing-same-origin-bfcache.tentative.window.js.ini
  tests/wpt/meta/streams/__dir__.ini
  tests/wpt/meta/streams/piping/abort.any.js.ini
  tests/wpt/meta/wasm/webapi/abort.any.js.ini
  tests/wpt/meta/webmessaging/message-channels/close-event/document-destroyed.tentative.window.js.ini
  tests/wpt/meta/websockets/back-forward-cache-with-closed-websocket-connection-ccns.tentative.window.js.ini
  tests/wpt/meta/websockets/back-forward-cache-with-closed-websocket-connection.window.js.ini
  tests/wpt/meta/websockets/back-forward-cache-with-open-websocket-connection-ccns.tentative.window.js.ini
  tests/wpt/meta/websockets/back-forward-cache-with-open-websocket-connection.window.js.ini
  tests/wpt/mozilla/meta/MANIFEST.json
  tests/wpt/mozilla/tests/mozilla/interfaces.https.html
  tests/wpt/mozilla/tests/mozilla/interfaces.worker.js
Labels: S-awaiting-merge

#39496 Establish baselines for testdriver.js infrastructure tests
  tests/wpt/meta/infrastructure/testdriver/actions/eventOrder.html.ini
  tests/wpt/meta/infrastructure/testdriver/actions/mouseClickCount.html.ini
  tests/wpt/meta/infrastructure/testdriver/actions/multiTouchPoints.html.ini
  tests/wpt/meta/infrastructure/testdriver/actions/multiTouchPointsReleaseFirstPoint.html.ini
  tests/wpt/meta/infrastructure/testdriver/actions/multiTouchPointsReleaseSecondPoint.html.ini
  tests/wpt/meta/infrastructure/testdriver/actions/multiTouchPointsSimultaneousMove.html.ini
  tests/wpt/meta/infrastructure/testdriver/actions/multiTouchPointsTwoTouchStarts.html.ini
  tests/wpt/meta/infrastructure/testdriver/actions/multiTouchPointsWithPause.html.ini
  tests/wpt/meta/infrastructure/testdriver/actions/penPointerEventProperties.html.ini
  tests/wpt/meta/infrastructure/testdriver/actions/penPointerEvents.html.ini
  tests/wpt/meta/infrastructure/testdriver/actions/touchPointerEventProperties.html.ini
  tests/wpt/meta/infrastructure/testdriver/bidi/bluetooth/handle_request_device_prompt.https.html.ini
  tests/wpt/meta/infrastructure/testdriver/bidi/bluetooth/simulate_adapter.https.html.ini
  tests/wpt/meta/infrastructure/testdriver/bidi/bluetooth/simulate_characteristic.https.html.ini
  tests/wpt/meta/infrastructure/testdriver/bidi/bluetooth/simulate_characteristic_response.https.html.ini
  tests/wpt/meta/infrastructure/testdriver/bidi/bluetooth/simulate_descriptor.https.html.ini
  tests/wpt/meta/infrastructure/testdriver/bidi/bluetooth/simulate_descriptor_response.https.html.ini
  tests/wpt/meta/infrastructure/testdriver/bidi/bluetooth/simulate_gatt_connection_response.https.html.ini
  tests/wpt/meta/infrastructure/testdriver/bidi/bluetooth/simulate_gatt_disconnection.https.html.ini
  tests/wpt/meta/infrastructure/testdriver/bidi/bluetooth/simulate_preconnected_peripheral.https.html.ini
  tests/wpt/meta/infrastructure/testdriver/bidi/bluetooth/simulate_service.https.html.ini
  tests/wpt/meta/infrastructure/testdriver/bidi/emulation/set_geolocation_override.https.html.ini
  tests/wpt/meta/infrastructure/testdriver/bidi/emulation/set_locale_override.https.html.ini
  tests/wpt/meta/infrastructure/testdriver/bidi/emulation/set_screen_orientation_override.https.html.ini
  tests/wpt/meta/infrastructure/testdriver/bidi/permissions/set_permission.https.html.ini
  tests/wpt/meta/infrastructure/testdriver/click_iframe.html.ini
  tests/wpt/meta/infrastructure/testdriver/click_nested.html.ini
  tests/wpt/meta/infrastructure/testdriver/click_window.html.ini
  tests/wpt/meta/infrastructure/testdriver/generate_test_report.html.ini
  tests/wpt/meta/infrastructure/testdriver/get_all_cookies.sub.html.ini
  tests/wpt/meta/infrastructure/testdriver/get_all_cookies.sub.https.html.ini
  tests/wpt/meta/infrastructure/testdriver/get_named_cookie.sub.html.ini
  tests/wpt/meta/infrastructure/testdriver/get_named_cookie.sub.https.html.ini
  tests/wpt/meta/infrastructure/testdriver/minimize_restore_popup.html.ini
  tests/wpt/meta/infrastructure/testdriver/set_permission.https.html.ini
  tests/wpt/meta/infrastructure/testdriver/virtual_authenticator.html.ini
Labels: S-awaiting-merge

#39504 Script: Remove last instances of Deref<str> and DerefMut<str> used for DOMString
  components/script/devtools.rs
  components/script/dom/console.rs
  components/script/dom/document.rs
  components/script/dom/domtokenlist.rs
  components/script/dom/element.rs
  components/script/dom/eventsource.rs
  components/script/dom/file.rs
  components/script/dom/fontface.rs
  components/script/dom/formdata.rs
  components/script/dom/globalscope.rs
  components/script/dom/keyboardevent.rs
  components/script/dom/medialist.rs
  components/script/dom/mediastream.rs
  components/script/dom/mouseevent.rs
  components/script/dom/mutationobserver.rs
  components/script/dom/navigator.rs
  components/script/dom/node.rs
  components/script/dom/performance.rs
  components/script/dom/performanceobserver.rs
  components/script/dom/range.rs
  components/script/dom/reportingendpoint.rs
  components/script/dom/stylepropertymapreadonly.rs
  components/script/dom/subtlecrypto.rs
  components/script/dom/webgl/webglprogram.rs
  components/script/script_runtime.rs
  components/script/textinput.rs
  components/script_bindings/str.rs
Labels: S-awaiting-review, S-awaiting-merge

#39514 Fully implement request constructor body handling
  components/script/body.rs
  components/script/dom/request.rs
  components/script/dom/response.rs
  components/script/script_runtime.rs
  tests/wpt/meta/fetch/api/abort/general.any.js.ini
  tests/wpt/meta/fetch/api/abort/request.any.js.ini
Labels: S-awaiting-review, S-awaiting-merge

#39499 webdriver: Elegantly handle "element screenshot" when bounding box has area zero
  components/servo/lib.rs
  components/shared/embedder/webdriver.rs
  components/webdriver_server/lib.rs
Labels: S-awaiting-merge

#39507 servoshell(egl): Adjust `WebViewRenderer` size when resizing surface size
  ports/servoshell/egl/app_state.rs
Labels: S-awaiting-merge

#39537 script: Rename `StylesheetLoader` to `ElementStylesheetLoader`
  components/script/dom/cssrulelist.rs
  components/script/dom/html/htmllinkelement.rs
  components/script/dom/html/htmlstyleelement.rs
  components/script/stylesheet_loader.rs
Labels: S-awaiting-merge

#39536 script: Make stylesheets loaded via `<link>` elements block the rendering
  components/script/dom/document.rs
  components/script/dom/window.rs
  components/script/stylesheet_loader.rs
  tests/wpt/meta/html/dom/render-blocking/parser-inserted-stylesheet-link.html.ini
  tests/wpt/meta/html/dom/render-blocking/remove-attr-stylesheet-link-keeps-blocking.html.ini
Labels: S-awaiting-merge

#39535 script: Add message to InvalidStateError
  components/script/dom/audio/audiobuffersourcenode.rs
  components/script/dom/audio/audiocontext.rs
  components/script/dom/audio/audionode.rs
  components/script/dom/audio/audioparam.rs
  components/script/dom/audio/audioscheduledsourcenode.rs
  components/script/dom/audio/baseaudiocontext.rs
  components/script/dom/audio/channelmergernode.rs
  components/script/dom/audio/channelsplitternode.rs
  components/script/dom/audio/iirfilternode.rs
  components/script/dom/audio/mediastreamaudiosourcenode.rs
  components/script/dom/audio/offlineaudiocontext.rs
  components/script/dom/audio/oscillatornode.rs
  components/script/dom/audio/pannernode.rs
  components/script/dom/bindings/constructor.rs
  components/script/dom/bindings/error.rs
  components/script/dom/bluetooth/bluetooth.rs
  components/script/dom/broadcastchannel.rs
  components/script/dom/canvas/2d/canvas_state.rs
  components/script/dom/canvas/imagebitmap.rs
  components/script/dom/canvas/imagebitmaprenderingcontext.rs
  components/script/dom/canvas/imagedata.rs
  components/script/dom/canvas/offscreencanvas.rs
  components/script/dom/cssrulelist.rs
  components/script/dom/datatransferitemlist.rs
  components/script/dom/document.rs
  components/script/dom/dommatrixreadonly.rs
  components/script/dom/eventtarget.rs
  components/script/dom/extendableevent.rs
  components/script/dom/filereader.rs
  components/script/dom/formdata.rs
  components/script/dom/gamepad/gamepadhapticactuator.rs
  components/script/dom/html/htmlcanvaselement.rs
  components/script/dom/html/htmlimageelement.rs
  components/script/dom/html/htmlinputelement.rs
  components/script/dom/idbdatabase.rs
  components/script/dom/idbobjectstore.rs
  components/script/dom/idbtransaction.rs
  components/script/dom/node.rs
  components/script/dom/nodeiterator.rs
  components/script/dom/range.rs
  components/script/dom/selection.rs
  components/script/dom/serviceworker.rs
  components/script/dom/textcontrol.rs
  components/script/dom/treewalker.rs
  components/script/dom/webgpu/gpucanvascontext.rs
  components/script/dom/webrtc/rtcdatachannel.rs
  components/script/dom/webrtc/rtcpeerconnection.rs
  components/script/dom/websocket.rs
  components/script/dom/webxr/xrframe.rs
  components/script/dom/webxr/xrmediabinding.rs
  components/script/dom/webxr/xrrigidtransform.rs
  components/script/dom/webxr/xrsession.rs
  components/script/dom/webxr/xrsystem.rs
  components/script/dom/webxr/xrwebglbinding.rs
  components/script/dom/webxr/xrwebgllayer.rs
  components/script/dom/xmlhttprequest.rs
  components/script/dom/xpathresult.rs
  components/script_bindings/error.rs
Labels: S-awaiting-merge

#39543 webdriver: Safely converting to OpenGL coordinates when taking (element) screenshot
  components/compositing/compositor.rs
Labels: S-awaiting-merge

#39418 storage: Move storage related backend threads to their own crate
  Cargo.lock
  Cargo.toml
  components/constellation/Cargo.toml
  components/constellation/constellation.rs
  components/constellation/pipeline.rs
  components/fonts/tests/font_context.rs
  components/net/Cargo.toml
  components/net/filemanager_thread.rs
  components/net/image_cache.rs
  components/net/lib.rs
  components/net/resource_thread.rs
  components/net/tests/fetch.rs
  components/net/tests/filemanager_thread.rs
  components/net/tests/main.rs
  components/script/Cargo.toml
  components/script/dom/debuggerglobalscope.rs
  components/script/dom/dedicatedworkerglobalscope.rs
  components/script/dom/dissimilaroriginwindow.rs
  components/script/dom/globalscope.rs
  components/script/dom/idbcursor.rs
  components/script/dom/idbcursorwithvalue.rs
  components/script/dom/idbdatabase.rs
  components/script/dom/idbkeyrange.rs
  components/script/dom/idbobjectstore.rs
  components/script/dom/idbopendbrequest.rs
  components/script/dom/idbrequest.rs
  components/script/dom/idbtransaction.rs
  components/script/dom/storage.rs
  components/script/dom/window.rs
  components/script/dom/windowproxy.rs
  components/script/dom/workerglobalscope.rs
  components/script/dom/workletglobalscope.rs
  components/script/indexed_db.rs
  components/script/script_thread.rs
  components/servo/Cargo.toml
  components/servo/lib.rs
  components/shared/constellation/Cargo.toml
  components/shared/constellation/from_script_message.rs
  components/shared/net/lib.rs
  components/shared/script/Cargo.toml
  components/shared/script/lib.rs
  components/shared/storage/Cargo.toml
  components/shared/storage/indexeddb_thread.rs
  components/shared/storage/lib.rs
  components/shared/storage/storage_thread.rs
  components/storage/Cargo.toml
  components/storage/indexeddb/engines/mod.rs
  components/storage/indexeddb/engines/sqlite.rs
  components/storage/indexeddb/engines/sqlite/create.rs
  components/storage/indexeddb/engines/sqlite/database_model.rs
  components/storage/indexeddb/engines/sqlite/object_data_model.rs
  components/storage/indexeddb/engines/sqlite/object_store_index_model.rs
  components/storage/indexeddb/engines/sqlite/object_store_model.rs
  components/storage/indexeddb/idb_thread.rs
  components/storage/indexeddb/mod.rs
  components/storage/lib.rs
  components/storage/storage_thread.rs
  components/storage/tests/main.rs
  components/storage/tests/sqlite.rs
  components/storage/webstorage_thread.rs
Labels: S-awaiting-merge, A-storage

#39534 crown: Check closure bodies for unrooted types and fix root TransmitBodyPromise*
  components/script/body.rs
  support/crown/src/unrooted_must_root.rs
  support/crown/tests/compile-fail/unrooted_must_root_body.rs
  support/crown/tests/compile-fail/unrooted_must_root_closure_body.rs
Labels: S-awaiting-merge

#39468 script: when fetching a worker script abort if response status is not ok
  components/script/dom/dedicatedworkerglobalscope.rs
  tests/wpt/meta/resource-timing/initiator-type/workers.html.ini
Labels: S-awaiting-merge

#39244 More changes to HashMap/HashSet to use fxhash
  components/compositing/compositor.rs
  components/net/protocols/mod.rs
  components/script/dom/html/htmlimageelement.rs
  components/shared/compositing/lib.rs
  components/shared/net/pub_domains.rs
  components/webgl/webxr.rs
Labels: S-awaiting-merge

#39564 script: Return cached object from `CryptoKey.usages` getter
  components/script/dom/cryptokey.rs
  tests/wpt/meta/WebCryptoAPI/crypto_key_cached_slots.https.any.js.ini
Labels: S-awaiting-merge

#39568 layout: Ensure that the `Epoch` stored in layout is accurate
  components/compositing/compositor.rs
  components/layout/layout_impl.rs
  components/script/dom/document.rs
  components/shared/base/lib.rs
  components/shared/compositing/lib.rs
Labels: S-awaiting-merge

#39585 script: move testbinding DOM interfaces to script/dom/test
  components/script/dom/mod.rs
  components/script/dom/testing/mod.rs
  components/script/dom/testing/testbinding.rs
  components/script/dom/testing/testbindingiterable.rs
  components/script/dom/testing/testbindingmaplikewithinterface.rs
  components/script/dom/testing/testbindingmaplikewithprimitive.rs
  components/script/dom/testing/testbindingpairiterable.rs
  components/script/dom/testing/testbindingproxy.rs
  components/script/dom/testing/testbindingsetlikewithinterface.rs
  components/script/dom/testing/testbindingsetlikewithprimitive.rs
  components/script/dom/testing/testns.rs
  components/script/dom/testing/testutils.rs
  components/script/dom/testing/testworklet.rs
  components/script/dom/testing/testworkletglobalscope.rs
Labels: S-awaiting-merge

#39583 libservo: Add a `WebView::take_screenshot()` API and use it for reftests
  Cargo.lock
  components/compositing/Cargo.toml
  components/compositing/compositor.rs
  components/compositing/lib.rs
  components/compositing/screenshot.rs
  components/compositing/tracing.rs
  components/compositing/webview_renderer.rs
  components/config/opts.rs
  components/constellation/constellation.rs
  components/constellation/pipeline.rs
  components/constellation/tracing.rs
  components/script/dom/window.rs
  components/script/messaging.rs
  components/script/script_thread.rs
  components/servo/Cargo.toml
  components/servo/lib.rs
  components/servo/webview.rs
  components/shared/compositing/lib.rs
  components/shared/constellation/from_script_message.rs
  components/shared/constellation/lib.rs
  components/shared/embedder/lib.rs
  components/shared/script/lib.rs
  ports/servoshell/desktop/app_state.rs
  ports/servoshell/egl/app_state.rs
  ports/servoshell/lib.rs
  ports/servoshell/output_image.rs
  ports/servoshell/prefs.rs
Labels: S-awaiting-review, S-awaiting-merge

#39546 Move XPath implementation into its own crate
  Cargo.lock
  Cargo.toml
  components/script/Cargo.toml
  components/script/dom/xpathevaluator.rs
  components/script/dom/xpathexpression.rs
  components/script/dom/xpathresult.rs
  components/script/lib.rs
  components/script/xpath.rs
  components/script/xpath/mod.rs
  components/xpath/Cargo.toml
  components/xpath/src/context.rs
  components/xpath/src/eval.rs
  components/xpath/src/eval_function.rs
  components/xpath/src/eval_value.rs
  components/xpath/src/lib.rs
  components/xpath/src/parser.rs
Labels: S-awaiting-review, S-awaiting-merge
